// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

#![allow(
    clippy::doc_markdown,
    reason = "prose with proper nouns (openEHR, EHRbase, CNF, cabolabs)"
)]
#![allow(
    clippy::panic,
    clippy::print_stdout,
    clippy::print_stderr,
    let_underscore_drop,
    reason = "test assertions/diagnostics/fixtures"
)]
//! C14N byte-parity gate for canonical XML.
//!
//! The other two XML gates (`xml_roundtrip`, `xml_ehrbase`) prove only internal
//! `ToXml`↔`FromXml` self-consistency. This gate proves that our `ToXml` output
//! is **byte-identical, after XML Canonicalization (C14N)**, to the vendored
//! openEHR **CNF** canonical-XML fixtures — i.e. real wire-parity, not just
//! round-trip stability.
//!
//! Oracle: the CNF Platform Conformance test data
//! `docs/specs/openehr/CNF/tests/platform/robot/_resources/test_data_sets/
//! compositions/CANONICAL_XML/*.xml` — canonical COMPOSITION documents with
//! `archetype_node_id` as an attribute, `xsi:type` dispatch, and canonical
//! element order. Method: parse the fixture via `FromXml`, re-serialize via
//! `to_canonical_xml`, canonicalize both the fixture and our output with
//! `xmllint --noblanks --c14n`, and byte-compare.
//!
//! ## The one documented convention difference: `xsi:type` verbosity
//!
//! These CNF fixtures are generated by the cabolabs OpenEHR toolkit, which emits
//! `xsi:type` **redundantly** — on the document root and on every element whose
//! declared slot type already fixes the concrete type (e.g. `<name
//! xsi:type="DV_TEXT">`, where `LOCATABLE.name` is declared `DV_TEXT`). Our
//! serializer (and stock archie/EHRbase, the Stage-1 parity target) follow the
//! **minimal** convention: `xsi:type` is emitted only when the concrete type
//! differs from the declared slot type (verified correct by the canonical-XML
//! audit and `emit_xml.rs`). Both are valid canonical XML for the same infoset.
//!
//! This gate therefore byte-compares **strictly** first; on the residual it
//! classifies a fixture as an `xsi:type`-convention divergence **only if**
//! stripping every `xsi:type` attribute from both sides makes them byte-
//! identical (so element order, values, `archetype_node_id` attributes,
//! namespaces, and text are all proven byte-perfect) **and** our `xsi:type` set
//! is a subset of the reference's (we emit no `xsi:type` the verbose reference
//! lacks). Any other difference is a hard failure — the comparison is not
//! loosened for arbitrary content; only this one cited serialization-convention
//! axis is normalized, and only when everything else already matches to the
//! byte. `xsi:type` *dispatch* correctness is independently covered by
//! `xml_ehrbase`/`xml_roundtrip`.

use openehr_its::xml::runtime::from_xml;
use openehr_its::xml::to_canonical_xml_ns;
use openehr_rm::prelude::Composition;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The CNF canonical-XML COMPOSITION fixture directory.
fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(
        "../../docs/specs/openehr/CNF/tests/platform/robot/_resources/\
         test_data_sets/compositions/CANONICAL_XML",
    )
}

/// Fixtures excluded from the gate entirely, each with a cited reason. A skip
/// removes the whole fixture rather than weakening the comparison.
const SKIP: &[(&str, &str)] = &[
    // The `__invalid_*` fixtures are deliberately malformed (wrong structure /
    // non-existent OPT) — validation-negative *inputs*, not canonical output,
    // so they are not a serialization-parity oracle.
    (
        "__invalid",
        "deliberately-invalid CNF fixture (validation-negative input, not canonical output)",
    ),
];

/// Canonicalize an XML string with `xmllint --noblanks --c14n`. `--noblanks`
/// drops formatting-only whitespace (fixtures are pretty-printed, our output is
/// compact); `--c14n` produces W3C Canonical XML (sorted attributes, normalized
/// namespaces). Element order and non-blank text are preserved by both.
fn c14n(xml: &str, label: &str) -> Result<String, String> {
    use std::io::Write;
    let mut tmp = std::env::temp_dir();
    tmp.push(format!(
        "c14n_{}_{}.xml",
        label.replace(['/', '.'], "_"),
        std::process::id()
    ));
    std::fs::File::create(&tmp)
        .and_then(|mut f| f.write_all(xml.as_bytes()))
        .map_err(|e| format!("write temp {}: {e}", tmp.display()))?;
    let out = Command::new("xmllint")
        .arg("--noblanks")
        .arg("--c14n")
        .arg(&tmp)
        .output()
        .map_err(|e| format!("run xmllint: {e}"))?;
    // Best-effort temp cleanup; a leftover file is harmless.
    drop(std::fs::remove_file(&tmp));
    if !out.status.success() {
        return Err(format!(
            "xmllint --noblanks --c14n failed ({label}): {}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("c14n not UTF-8 ({label}): {e}"))
}

/// Remove every ` xsi:type="…"` attribute from a C14N string.
fn strip_xsi_type(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some((head, after)) = rest.split_once(" xsi:type=\"") {
        out.push_str(head);
        // Skip to the closing quote of the attribute value.
        let Some((_, tail)) = after.split_once('"') else {
            rest = after;
            break;
        };
        rest = tail;
    }
    out.push_str(rest);
    out
}

/// The multiset of `xsi:type` values in a C14N string.
fn xsi_type_values(s: &str) -> Vec<&str> {
    let mut vals = Vec::new();
    let mut rest = s;
    while let Some((_, after)) = rest.split_once("xsi:type=\"") {
        match after.split_once('"') {
            Some((value, tail)) => {
                vals.push(value);
                rest = tail;
            }
            None => break,
        }
    }
    vals
}

/// `true` if every distinct value in `sub` also occurs in `sup` (subset by
/// value): our minimal `xsi:type` set must be contained in the verbose
/// reference's, i.e. we never emit an `xsi:type` the reference lacks.
fn is_value_subset(sub: &[&str], sup: &[&str]) -> bool {
    sub.iter().all(|v| sup.contains(v))
}

#[test]
fn composition_c14n_matches_cnf_canonical_fixtures() {
    let dir = fixtures_dir();
    assert!(
        dir.is_dir(),
        "CNF canonical-XML fixtures not found at {}",
        dir.display()
    );
    // xmllint is required; fail loudly rather than silently skipping the gate.
    assert!(
        Command::new("xmllint")
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success()),
        "xmllint not available; the C14N parity gate needs it (serialization.md)"
    );

    let (mut strict, mut convention, mut skipped) = (0usize, 0usize, 0usize);
    let mut failures = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("read fixtures dir") {
        let path = entry.unwrap().path();
        if path.extension().and_then(std::ffi::OsStr::to_str) != Some("xml") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
        if let Some((_, reason)) = SKIP.iter().find(|(m, _)| stem.contains(m)) {
            eprintln!("skip {stem}: {reason}");
            skipped += 1;
            continue;
        }
        let fixture = std::fs::read_to_string(&path).unwrap();
        let compo: Composition = match from_xml(&fixture) {
            Ok(c) => c,
            Err(e) => {
                failures.push(format!("{stem}: FromXml parse failed: {e}"));
                continue;
            }
        };
        // The CNF reference corpus is v1-era, so parity is judged in the
        // fixtures' own lineage (the crate default is v2, #2453).
        let ours = to_canonical_xml_ns(
            &compo,
            "composition",
            openehr_its::xml::runtime::Namespace::V1,
        )
        .expect("serialize");
        let ref_c14n = c14n(&fixture, &format!("{stem}_ref")).expect("c14n fixture");
        let our_c14n = c14n(&ours, &format!("{stem}_ours")).expect("c14n ours");

        if ref_c14n == our_c14n {
            strict += 1;
            continue;
        }
        // Not byte-identical: the only permitted residual is the cited
        // `xsi:type`-verbosity convention. Everything else must already match.
        let ref_no_xsi = strip_xsi_type(&ref_c14n);
        let our_no_xsi = strip_xsi_type(&our_c14n);
        if ref_no_xsi != our_no_xsi {
            let diff = ref_no_xsi
                .split_inclusive('>')
                .zip(our_no_xsi.split_inclusive('>'))
                .find(|(a, b)| a != b)
                .map_or_else(
                    || format!("len ref={} our={}", ref_no_xsi.len(), our_no_xsi.len()),
                    |(a, b)| format!("  ref: {a}\n  our: {b}"),
                );
            failures.push(format!(
                "{stem}: C14N mismatch beyond the xsi:type convention (real divergence):\n{diff}"
            ));
            continue;
        }
        // xsi:type-stripped forms are byte-identical → the residual is purely
        // the cabolabs verbose-xsi:type convention. Guard that ours is the
        // minimal subset (no xsi:type the verbose reference lacks).
        let our_vals = xsi_type_values(&our_c14n);
        let ref_vals = xsi_type_values(&ref_c14n);
        if !is_value_subset(&our_vals, &ref_vals) {
            failures.push(format!(
                "{stem}: our xsi:type set is not a subset of the reference's (ours={our_vals:?}, ref={ref_vals:?})"
            ));
            continue;
        }
        assert!(
            our_vals.len() <= ref_vals.len(),
            "{stem}: minimal convention must emit no more xsi:type than the verbose reference"
        );
        convention += 1;
    }
    eprintln!(
        "XML C14N parity: {strict} strict, {convention} xsi:type-convention, {skipped} skipped, {} failed",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "C14N parity failures:\n{}",
        failures.join("\n\n")
    );
    // The gate must actually compare something (guard against a broken path or
    // an all-skip no-op).
    assert!(
        strict + convention > 0,
        "no fixtures compared — check the fixtures path / skip-list"
    );
}
