// @generated by openehr-codegen from BMM (`EXPR_ARCHETYPE_REF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `EXPR_ARCHETYPE_REF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v2_4::aom2::constraint_model::archetype_constraint::ArchetypeConstraint;

/// Expression tree leaf item representing a reference to a value found in data at a location specified by a path in the archetype definition.
///
/// * A path referring to a value in the archetype (paths with a leading ‘/’ are in the definition section.
/// * Paths with no leading ‘/’ are in the outer part of the archetype, e.g. “archetype_id/value” refers to the String value of the archetype_id attribute of the enclosing archetype.
#[doc(alias = "EXPR_ARCHETYPE_REF")]
#[derive(Debug, Clone, PartialEq)]
pub struct ExprArchetypeRef {
    /// The `item` attribute of openEHR `EXPR_ARCHETYPE_REF` (the vendored BMM carries no documentation for it).
    pub item: ArchetypeConstraint,
    /// The path to the archetype node.
    pub path: String,
}
