// @generated by openehr-codegen from BMM (`CODE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `CODE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v3_1::terminology::terminology_status::TerminologyStatus;

/// A single code entity in a code set.
#[doc(alias = "CODE")]
#[derive(Debug, Clone, PartialEq)]
pub struct Code {
    /// The code string for this code entity, e.g. `"AF"`.
    pub value: String,
    /// Optional description of this code, e.g. `"AFGHANISTAN"`.
    ///
    /// This field may be used to hold translations of the description in a language-specific copy of the English language original code set.
    pub description: Option<String>,
    /// Status of this code within the code set.
    pub status: Option<TerminologyStatus>,
}
