// @generated by openehr-codegen from BMM (`DV_IDENTIFIER`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `DV_IDENTIFIER` spec class, generated from the vendored BMM
//! meta-model.

/// Type for representing identifiers of real-world entities. Typical identifiers include drivers licence number, social security number, veterans affairs number, prescription id, order id, and so on.
///
/// DV_IDENTIFIER is used to represent any identifier of a real thing, issued by some authority or agency.
///
/// Misuse: DV_IDENTIFIER is not used to express identifiers generated by the infrastructure to refer to information items; the types OBJECT_ID and OBJECT_REF and subtypes are defined for this purpose.
#[doc(alias = "DV_IDENTIFIER")]
#[derive(Debug, Clone, PartialEq)]
pub struct DvIdentifier {
    /// Optional authority which issues the kind of id used in the id field of this object.
    pub issuer: Option<String>,
    /// Optional organisation that assigned the id to the item being identified.
    pub assigner: Option<String>,
    /// The identifier value. Often structured, according to the definition of the issuing authority's rules.
    pub id: String,
    /// Optional identifier type, such as  prescription , or  Social Security Number . One day a controlled vocabulary might be possible for this.
    pub r#type: Option<String>,
}
