// @generated by openehr-codegen from BMM (`AOM_PROPERTY_MAPPING`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Data object expressing a mapping between two class properties.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "AOM_PROPERTY_MAPPING")]
pub struct AomPropertyMapping {
    /// Name of property in source class.
    pub source_property_name: String,
    /// Name of property in target class.
    pub target_property_name: String,
}
