// @generated by openehr-codegen from BMM (`LOCATABLE`) — DO NOT EDIT.

use crate::common::directory::folder::Folder;
use crate::composition::composition::Composition;
use crate::composition::content::entry::action::Action;
use crate::composition::content::entry::activity::Activity;
use crate::composition::content::entry::admin_entry::AdminEntry;
use crate::composition::content::entry::evaluation::Evaluation;
use crate::composition::content::entry::instruction::Instruction;
use crate::composition::content::entry::observation::Observation;
use crate::composition::content::navigation::section::Section;
use crate::data_structures::history::history::History;
use crate::data_structures::history::interval_event::IntervalEvent;
use crate::data_structures::history::point_event::PointEvent;
use crate::data_structures::item_structure::item_list::ItemList;
use crate::data_structures::item_structure::item_single::ItemSingle;
use crate::data_structures::item_structure::item_structure::ItemStructure;
use crate::data_structures::item_structure::item_table::ItemTable;
use crate::data_structures::item_structure::item_tree::ItemTree;
use crate::data_structures::representation::cluster::Cluster;
use crate::data_structures::representation::element::Element;
use crate::demographic::address::Address;
use crate::demographic::agent::Agent;
use crate::demographic::capability::Capability;
use crate::demographic::contact::Contact;
use crate::demographic::group::Group;
use crate::demographic::organisation::Organisation;
use crate::demographic::party_identity::PartyIdentity;
use crate::demographic::party_relationship::PartyRelationship;
use crate::demographic::person::Person;
use crate::demographic::role::Role;
use crate::ehr::ehr_access::EhrAccess;
use crate::ehr::ehr_status::EhrStatus;
use crate::ehr_extract::common::extract::Extract;
use crate::ehr_extract::common::extract_action_request::ExtractActionRequest;
use crate::ehr_extract::common::extract_chapter::ExtractChapter;
use crate::ehr_extract::common::extract_folder::ExtractFolder;
use crate::ehr_extract::common::extract_request::ExtractRequest;
use crate::ehr_extract::generic_extract::generic_content_item::GenericContentItem;
use crate::ehr_extract::openehr_extract::openehr_content_item::OpenehrContentItem;
use crate::integration::generic_entry::GenericEntry;

/// Root class of all information model classes that can be archetyped. Most classes in the openEHR reference model inherit from the `LOCATABLE` class, which defines the idea of  locatability in an archetyped structure. `LOCATABLE` defines a runtime name and an `_archetype_node_id_`.
/// Closed subtype set of `LOCATABLE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum Locatable {
    Action(Action),
    Activity(Activity),
    Address(Address),
    AdminEntry(AdminEntry),
    Agent(Agent),
    Capability(Capability),
    Cluster(Cluster),
    Composition(Composition),
    Contact(Contact),
    EhrAccess(EhrAccess),
    EhrStatus(EhrStatus),
    Element(Element),
    Evaluation(Evaluation),
    Extract(Extract),
    ExtractActionRequest(ExtractActionRequest),
    ExtractChapter(ExtractChapter),
    ExtractFolder(ExtractFolder),
    ExtractRequest(ExtractRequest),
    Folder(Folder),
    GenericContentItem(Box<GenericContentItem>),
    GenericEntry(GenericEntry),
    Group(Group),
    History(History<ItemStructure>),
    Instruction(Instruction),
    IntervalEvent(IntervalEvent<ItemStructure>),
    ItemList(ItemList),
    ItemSingle(ItemSingle),
    ItemTable(ItemTable),
    ItemTree(ItemTree),
    Observation(Observation),
    OpenehrContentItem(OpenehrContentItem),
    Organisation(Organisation),
    PartyIdentity(PartyIdentity),
    PartyRelationship(PartyRelationship),
    Person(Person),
    PointEvent(PointEvent<ItemStructure>),
    Role(Role),
    Section(Section),
}
