// @generated by openehr-codegen from BMM (`GENERIC_ID`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `GENERIC_ID` spec class, generated from the vendored BMM
//! meta-model.

/// Generic identifier type for identifiers whose format is otherwise unknown to openEHR. Includes an attribute for naming the identification scheme (which may well be local).
#[doc(alias = "GENERIC_ID")]
#[derive(Debug, Clone, PartialEq)]
pub struct GenericId {
    // inherited: OBJECT_ID
    /// The value of the id in the form defined below.
    pub value: String,
    /// Name of the scheme to which this identifier conforms. Ideally this name will be recognisable globally but realistically it may be a local ad hoc scheme whose name is not controlled or standardised in any way.
    pub scheme: String,
}
