// @generated by openehr-codegen from BMM (`INTERNET_ID`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

/// Model of a reverse internet domain, as used to uniquely identify an internet domain. In the form of a dot-separated string in the reverse order of a domain name, specified by https://www.rfc-editor.org/info/rfc1034[IETF RFC 1034^].
#[derive(Debug, Clone, PartialEq)]
pub struct InternetId {
    // inherited: UID
    /// The value of the id.
    pub value: String,
}
