// @generated by openehr-codegen from BMM (`ISO_OID`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Model of ISO's Object Identifier (oid) as defined by the standard ISO/IEC 8824. Oids are formed from integers separated by dots. Each non-leaf node in an Oid starting from the left corresponds to an assigning authority, and identifies that authority's namespace, inside which the remaining part of the identifier is locally unique.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "ISO_OID")]
pub struct IsoOid {
    // inherited: UID
    /// The value of the id.
    pub value: String,
}
