// @generated by openehr-codegen from BMM (`UID`) — DO NOT EDIT.

use crate::base_types::identification::internet_id::InternetId;
use crate::base_types::identification::iso_oid::IsoOid;
use crate::base_types::identification::uuid::Uuid;

/// Abstract parent of classes representing unique identifiers which identify information entities in a durable way. UIDs only ever identify one IE in time or space and are never re-used.
/// Closed subtype set of `UID`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum Uid {
    InternetId(InternetId),
    IsoOid(IsoOid),
    Uuid(Uuid),
}
