// @generated by openehr-codegen from BMM (`UID_BASED_ID`) — DO NOT EDIT.

use crate::base_types::identification::hier_object_id::HierObjectId;
use crate::base_types::identification::object_version_id::ObjectVersionId;
use serde::Serialize;

/// Abstract model of UID-based identifiers consisting of a root part and an optional extension; lexical form: `root '::' extension`.
/// Closed subtype set of `UID_BASED_ID`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum UidBasedId {
    HierObjectId(HierObjectId),
    ObjectVersionId(ObjectVersionId),
}

impl<'de> ::serde::Deserialize<'de> for UidBasedId {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("HIER_OBJECT_ID") => {
                ::core::result::Result::Ok(Self::HierObjectId(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("OBJECT_VERSION_ID") => {
                ::core::result::Result::Ok(Self::ObjectVersionId(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => {
                ::core::result::Result::Err(::serde::de::Error::custom(
                    "UID_BASED_ID: missing required `_type` on polymorphic slot (expected one of: HIER_OBJECT_ID, OBJECT_VERSION_ID)",
                ))
            }
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "UID_BASED_ID: unexpected `_type` {__other:?} (expected one of: HIER_OBJECT_ID, OBJECT_VERSION_ID)"
                )))
            }
        }
    }
}
