// @generated by openehr-codegen from BMM (`EXPR_VALUE_REF`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am24::aom2::rules::expr_archetype_ref::ExprArchetypeRef;
use openehr_derive::OpenEhrType;
use serde::Serialize;

/// Path-based reference to a value in a data structure.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "EXPR_VALUE_REF")]
pub struct ExprValueRefData {
    // inherited: EXPR_LEAF
    /// The reference item from which the value of this node can be computed.
    pub item: Option<serde_json::Value>,
}

/// Path-based reference to a value in a data structure.
/// Polymorphic slot of `EXPR_VALUE_REF`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ExprValueRef {
    ExprArchetypeRef(ExprArchetypeRef),
    ExprValueRef(ExprValueRefData),
}

impl<'de> ::serde::Deserialize<'de> for ExprValueRef {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("EXPR_ARCHETYPE_REF") => {
                ::core::result::Result::Ok(Self::ExprArchetypeRef(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("EXPR_VALUE_REF") => {
                ::core::result::Result::Ok(Self::ExprValueRef(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => ::core::result::Result::Ok(Self::ExprValueRef(
                ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
            )),
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "EXPR_VALUE_REF: unexpected `_type` {__other:?} (expected one of: EXPR_ARCHETYPE_REF, EXPR_VALUE_REF)"
                )))
            }
        }
    }
}
