// @generated by openehr-codegen from BMM (`EL_PROPERTY_REF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `EL_PROPERTY_REF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v2_4::bmm::core::bmm_property::BmmProperty;
use crate::v2_4::bmm3::expression::el_value_generator::ElValueGenerator;

/// Reference to a writable property.
#[doc(alias = "EL_PROPERTY_REF")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElPropertyRef {
    /// Defined to return True.
    pub is_writable: bool,

    // inherited: EL_VALUE_GENERATOR
    /// Name used to represent the reference or other entity.
    pub name: String,

    // inherited: EL_FEATURE_REF
    /// Scoping expression, which must be a `EL_VALUE_GENERATOR`.
    pub scoper: Option<Box<ElValueGenerator>>,
    /// Property definition (within class).
    pub definition: BmmProperty,
}
