// @generated by openehr-codegen from BMM (`EL_TYPE_REF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `EL_TYPE_REF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v2_4::bmm::core::bmm_type::BmmType;

/// Meta-type for reference to a non-abstract type as an object. Assumed to be accessible at run-time. Typically represented syntactically as `TypeName` or `{TypeName}`.
///
/// May be used as a value, or as the qualifier for a function or constant access.
#[doc(alias = "EL_TYPE_REF")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElTypeRef {
    // inherited: EL_VALUE_GENERATOR
    /// The `is_writable` attribute of openEHR `EL_VALUE_GENERATOR` (the vendored BMM carries no documentation for it).
    pub is_writable: bool,
    /// Name used to represent the reference or other entity.
    pub name: String,
    /// Type, directly from the name of the reference, e.g. `{SOME_TYPE}`.
    pub r#type: BmmType,
    /// The `is_mutable` attribute of openEHR `EL_TYPE_REF` (the vendored BMM carries no documentation for it).
    pub is_mutable: bool,
}
