// @generated by openehr-codegen from BMM (`EL_WRITABLE_VARIABLE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `EL_WRITABLE_VARIABLE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v2_4::bmm3::core::feature::bmm_writable_variable::BmmWritableVariable;

/// Meta-type of writable variables, including routine locals and the special variable 'Result'.
#[doc(alias = "EL_WRITABLE_VARIABLE")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElWritableVariable {
    /// Defined to return True in all cases.
    pub is_writable: bool,

    // inherited: EL_VALUE_GENERATOR
    /// Name used to represent the reference or other entity.
    pub name: String,
    /// Variable definition to which this reference refers.
    pub definition: BmmWritableVariable,
}
