// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR spec package `v1_4/aom14/archetype/ontology` — generated module tree.

pub mod archetype_ontology;
pub mod archetype_term;

// hand-written modules (spec behaviour), auto-declared:
pub mod archetype_ontology_impl;
pub mod archetype_term_impl;
