= RM Mappings

== COMPOSITION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_composition_class[COMPOSITION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/language|code": "en",
  "conformance-ehrbase.de.v0/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/territory|code": "US",
  "conformance-ehrbase.de.v0/territory|terminology": "ISO_3166-1",
  "conformance-ehrbase.de.v0/category|code": "433",
  "conformance-ehrbase.de.v0/category|value": "event",
  "conformance-ehrbase.de.v0/category|terminology": "openehr",
  "conformance-ehrbase.de.v0/context/start_time": "2021-12-21T14:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/setting|code": "238",
  "conformance-ehrbase.de.v0/context/setting|value": "other care",
  "conformance-ehrbase.de.v0/context/setting|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/time": "2021-12-21T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/_uid": "6e3a9506-b81c-4d74-a37f-1464fb7106b2::ehrbase.org::1",
  "conformance-ehrbase.de.v0/language|code": "en",
  "conformance-ehrbase.de.v0/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/territory|code": "US",
  "conformance-ehrbase.de.v0/territory|terminology": "ISO_3166-1",
  "conformance-ehrbase.de.v0/category|code": "433",
  "conformance-ehrbase.de.v0/category|value": "event",
  "conformance-ehrbase.de.v0/category|terminology": "openehr",
  "conformance-ehrbase.de.v0/context/_health_care_facility|id": "9091",
  "conformance-ehrbase.de.v0/context/_health_care_facility|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_health_care_facility|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_health_care_facility|name": "Hospital",
  "conformance-ehrbase.de.v0/context/_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/context/_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/context/_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/context/_participation:0|id": "199",
  "conformance-ehrbase.de.v0/context/_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/start_time": "2021-12-21T14:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/_end_time": "2021-12-21T15:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/_location": "microbiology lab 2",
  "conformance-ehrbase.de.v0/context/setting|code": "238",
  "conformance-ehrbase.de.v0/context/setting|value": "other care",
  "conformance-ehrbase.de.v0/context/setting|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/time": "2021-12-21T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/composer|id": "1234-5678",
  "conformance-ehrbase.de.v0/composer|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/composer|id_namespace": "EHR.NETWORK"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/category`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| category
| yes
|

| `/composer`
| <<PARTY_PROXY,PARTY_PROXY>>
| composer
| yes
| add ctx/composer_self:true to set composer to PARTY_SELF

| `/context`
| <<EVENT_CONTEXT,EVENT_CONTEXT>>
| context
| yes
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== ADMIN_ENTRY

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_admin_entry_class[ADMIN_ENTRY] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/dv_text": "DV_TEXT 56",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/encoding|terminology": "IANA_character-sets"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/dv_text": "DV_TEXT 56",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|id": "199",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|function": "performer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|mode": "not specified",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|name": "Lara Markham",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|id": "198",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_other_participation:1|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_work_flow_id|type": "WORKFLOW",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_work_flow_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_work_flow_id|id": "335645",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_work_flow_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_admin_entry/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| will be set to PARTY_SELF if not explicitly set

| `/_work_flow_id`
| <<OBJECT_REF,OBJECT_REF>>
| workflow_id
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== INSTRUCTION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_instruction_class[INSTRUCTION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/dv_text": "DV_TEXT 45",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing": "R4/2022-01-31T10:00:00+01:00/P3M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing|formalism": "timing",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/dv_text": "DV_TEXT 91",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/expiry_time": "2022-01-31T10:33:28.724259+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/narrative": "Human readable instruction narrative",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/encoding|terminology": "IANA_character-sets"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/dv_text": "DV_TEXT 45",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing": "R4/2022-01-31T10:00:00+01:00/P3M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing|formalism": "timing",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/action_archetype_id": "/openEHR-EHR-CLUSTER.conformance_action.v0/",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/dv_text": "DV_TEXT 91",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/expiry_time": "2022-01-31T10:33:28.724259+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/narrative": "Human readable instruction narrative",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_wf_definition|value": "wf_definition",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_wf_definition|formalism": "formalism",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|id": "199",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|function": "performer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|mode": "not specified",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|name": "Lara Markham",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|id": "198",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_other_participation:1|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|type": "GUIDELINE",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|id": "3445",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_work_flow_id|type": "WORKFLOW",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_work_flow_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_work_flow_id|id": "335645",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_work_flow_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/narrative`
| <<DV_TEXT,DV_TEXT>>
| narrative
| yes
|

| `/_expiry_time`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| expiry_time
| Yes
|

| `/_wf_definition`
| <<DV_PARSABLE,DV_PARSABLE>>
| wf_definition
| no
|

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| will be set to PARTY_SELF if not explicitly set

| `/_guideline_id`
| <<OBJECT_REF,OBJECT_REF>>
| guideline_id
| no
|

| `/_work_flow_id`
| <<OBJECT_REF,OBJECT_REF>>
| workflow_id
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== ACTION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_evaluation_class[EVALUATION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/dv_text": "dv_text in description",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/dv_text2": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|code": "532",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|value": "completed",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/time": "2022-01-31T10:33:28.72414+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/encoding|terminology": "IANA_character-sets"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/dv_text": "dv_text in description",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/dv_text2": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|code": "532",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|value": "completed",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|path": "/content[openEHR-EHR-SECTION.conformance_section.v0]/items[openEHR-EHR-INSTRUCTION.conformance_instruction.v0]",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|composition_uid": "4cdc3017-d8c5-4cd3-9900-f3bb7171d006",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|activity_id": "activities[at0001]",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/time": "2022-01-31T10:33:28.72414+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|id": "199",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|function": "performer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|mode": "not specified",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|name": "Lara Markham",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|id": "198",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_other_participation:1|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_guideline_id|type": "GUIDELINE",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_guideline_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_guideline_id|id": "3445",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_guideline_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_work_flow_id|type": "WORKFLOW",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_work_flow_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_work_flow_id|id": "335645",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_work_flow_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/time`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| time
| YES
|

| `/ism_transition`
| <<ISM_TRANSITION,ISM_TRANSITION>>
| ism_transition
| Yes
|

| `/_instruction_details`
| <<INSTRUCTION_DETAILS,INSTRUCTION_DETAILS>>
| instruction_details
| no
|

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| will be set to PARTY_SELF if not explicitly set

| `/_guideline_id`
| <<OBJECT_REF,OBJECT_REF>>
| guideline_id
| no
|

| `/_work_flow_id`
| <<OBJECT_REF,OBJECT_REF>>
| workflow_id
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== EVALUATION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_evaluation_class[EVALUATION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/dv_text": "dv_text in data",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/dv_text2": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/encoding|terminology": "IANA_character-sets"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/dv_text": "dv_text in data",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/dv_text2": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|id": "199",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|function": "performer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|mode": "not specified",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|name": "Lara Markham",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|id": "198",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_other_participation:1|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_guideline_id|type": "GUIDELINE",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_guideline_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_guideline_id|id": "3445",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_guideline_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_work_flow_id|type": "WORKFLOW",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_work_flow_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_work_flow_id|id": "335645",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_work_flow_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_evaluation/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| will be set to PARTY_SELF if not explicitly set

| `/_guideline_id`
| <<OBJECT_REF,OBJECT_REF>>
| guideline_id
| no
|

| `/_work_flow_id`
| <<OBJECT_REF,OBJECT_REF>>
| workflow_id
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== OBSERVATION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_composition_class[COMPOSITION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text_state": "DV_TEXT in State",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/dv_text": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/time": "2021-12-21T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|terminology": "IANA_character-sets"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text_state": "DV_TEXT in State",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/dv_text": "dv_text in protocol",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/time": "2021-12-21T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/history_origin": "2021-12-20T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject|id": "1234-5678",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject|id_namespace": "EHR.NETWORK",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/_identifier:0|id": "122",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/_identifier:0|issuer": "issuer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/_identifier:0|assigner": "assigner",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/_identifier:0|type": "type",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/relationship|code": "10",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/subject/relationship|value": "mother",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_provider|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|id": "199",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|function": "performer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|mode": "not specified",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|name": "Lara Markham",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|id": "198",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_other_participation:1|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_guideline_id|type": "GUIDELINE",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_guideline_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_guideline_id|id": "3445",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_guideline_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_work_flow_id|type": "WORKFLOW",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_work_flow_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_work_flow_id|id": "335645",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_work_flow_id|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/originating_system_audit|system_id": "orig",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/original_content": "Hello world!",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/original_content|formalism": "text/plain"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| Yes
|

| `/territory`
| <<CODE_PHRASE,CODE_PHRASE>>
| territory
| Yes
|

| `/history_origin`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| history.origin
| no
| will be set to the time of the earliest event if not explicitly set

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| will be set to PARTY_SELF if not explicitly set

| `/_guideline_id`
| <<OBJECT_REF,OBJECT_REF>>
| guideline_id
| no
|

| `/_work_flow_id`
| <<OBJECT_REF,OBJECT_REF>>
| workflow_id
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== ELEMENT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_structures.html#_element_class[ELEMENT] class.

[NOTE]
====
Using FLAT format there is no difference between an ELEMENT and its value.
====

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_null_flavour|code": "253",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_null_flavour|value": "unknown",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_null_flavour|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_null_reason": "sample reason"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/_null_flavour`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| null_flavour
| no
|

| `/_null_reason`
| <<DV_TEXT,DV_TEXT>>
| null_reason
| no
|

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

== CLUSTER

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_structures.html#_cluster_class[CLUSTER] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/labresult/text_value": "labresult 4"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/labresult/text_value": "labresult 4",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_feeder_audit/originating_system_audit|system_id": "orig",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_uid":"9fcc1c70-9349-444d-b9cb-8fa817697f5e",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/conformance_cluster/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/_link:i`
| <<LINK,LINK>>
| links
| no
|

| `/_feeder_audit`
| <<FEEDER_AUDIT,FEEDER_AUDIT>>
| feeder_audit
| no
|

| `/_uid`
| STRING
| uid.value
| no
|
|===

[[LINK]]
== LINK

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_link_class[LINK] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/_link:0|type": "problem",
  "conformance-ehrbase.de.v0/_link:0|meaning": "problem related note",
  "conformance-ehrbase.de.v0/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|type`
| STRING
| type.value
| yes
|

| `\|meaning`
| STRING
| meaning.value
| yes
|

| `\|target`
| STRING
| target.value
| yes
|
|===

[[FEEDER_AUDIT]]
== FEEDER_AUDIT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_feeder_audit_class[FEEDER_AUDIT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit|system_id": "orig"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit|system_id": "orig",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/location|id": "12342341",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/location|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/location|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/location|name": "Org 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/subject|id": "456",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/subject|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/subject|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/subject|name": "Per 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/provider|id": "456",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/provider|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/provider|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit/provider|name": "Per 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_audit|time": "2021-12-21T16:02:58.0094262+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:0|id": "id1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:0|issuer": "issuer1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:0|assigner": "assigner1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:0|type": "PERSON",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:1|id": "id2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:1|issuer": "issuer2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:1|assigner": "assigner2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/originating_system_item_id:1|type": "PERSON",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/original_content": "Hello world!",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/original_content|formalism": "text/plain",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:0|id": "id1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:0|issuer": "issuer1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:0|assigner": "assigner1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:0|type": "PERSON",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:1|id": "id2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:1|issuer": "issuer2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:1|assigner": "assigner2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_item_id:1|type": "PERSON",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit|system_id": "orig",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/location|id": "12342341",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/location|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/location|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/location|name": "Org 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/subject|id": "456",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/subject|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/subject|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/subject|name": "Per 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/provider|id": "456",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/provider|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/provider|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit/provider|name": "Per 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/_feeder_audit/feeder_system_audit|time": "2021-12-21T16:02:58.0094262+01:00"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/originating_system_item_id:i`
| <<DV_IDENTIFIER,DV_IDENTIFIER>>
| originating_system_item_ids
| no
|

| `/feeder_system_item_id:i`
| <<DV_IDENTIFIER,DV_IDENTIFIER>>
| feeder_system_item_ids
| no
|

| `/original_content`
| <<DV_PARSABLE,DV_PARSABLE>>
| original_content
| no
| one one of original_content and original_content_multimedia can be set

| `/original_content_multimedia`
| <<DV_MULTIMEDIA,DV_MULTIMEDIA>>
| original_content
| no
| one one of original_content and original_content_multimedia can be set

| `/originating_system_audit`
| <<PARTY_IDENTIFIED,PARTY_IDENTIFIED>>
| originating_system_audit
| yes
|

| `/feeder_system_audit`
| <<FEEDER_AUDIT_DETAILS,FEEDER_AUDIT_DETAILS>>
| feeder_system_audit
| no
|
|===

== FEEDER_AUDIT_DETAILS

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_feeder_audit_details_class[FEEDER_AUDIT_DETAILS] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit|system_id": "orig"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject|id": "1234-5678",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject|id_namespace": "EHR.NETWORK",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject/_identifier:0|id": "122",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject/_identifier:0|issuer": "issuer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject/_identifier:0|assigner": "assigner",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/subject/_identifier:0|type": "type",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider|id": "1234-5678",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider|id_namespace": "EHR.NETWORK",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider/_identifier:0|id": "122",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider/_identifier:0|issuer": "issuer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider/_identifier:0|assigner": "assigner",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/provider/_identifier:0|type": "type",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/location|id": "12342341",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/location|id_scheme": "NMC",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/location|id_namespace": "uk.org.nmc",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit/location|name": "Org 1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit|system_id": "orig",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit|version_id": "final",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/_feeder_audit/feeder_system_audit|time": "2021-12-21T16:02:58.0094262+01:00"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|system_id`
| String
| system_id
| yes
|

| `\|version_id`
| String
| version_id
| no
|

| `\|time`
| String
| time.value
| no
|

| `/subject`
| <<PARTY_PROXY,PARTY_PROXY>>
| subject
| no
| add /subject\|_type:"PARTY_SELF" to set this to PARTY_SELF

| `/provider`
| <<PARTY_IDENTIFIED,PARTY_IDENTIFIED>>
| provider
| no
|

| `/location`
| <<PARTY_IDENTIFIED,PARTY_IDENTIFIED>>
| location
| no
|
|===

== ACTIVITY

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_activity_class[ACTIVITY] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/dv_text": "DV_TEXT 45",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing": "R4/2022-01-31T10:00:00+01:00/P3M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing|formalism": "timing"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/dv_text": "DV_TEXT 45",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing": "R4/2022-01-31T10:00:00+01:00/P3M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/timing|formalism": "timing",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/current_activity/action_archetype_id": "/openEHR-EHR-CLUSTER.conformance_action.v0/"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/timing`
| <<DV_PARSABLE,DV_PARSABLE>>
| timing
| no
|

| `/action_archetype_id`
| STRING
| action_archetype_id
| no
| Will be set to /.*/ if not set explicit.
|===

[[ISM_TRANSITION]]
== ISM_TRANSITION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_activity_class[ACTIVITY] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|code": "532",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|value": "completed",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|terminology": "openehr"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|code": "532",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|value": "completed",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/current_state|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/transition|code": "548",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/transition|value": "finish",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/transition|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/careflow_step|code": "at0006",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/careflow_step|value": "transition",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/careflow_step|terminology": "local",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/ism_transition/_reason:0": "reason 1"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/current_state`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| current_state
| yes
|

| `/transition`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| transition
| no
|

| `/careflow_step`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| careflow_step
| no
|

| `/_reason:i`
| <<DV_TEXT,DV_TEXT>>
| reason
| no
|
|===

[[INSTRUCTION_DETAILS]]
== INSTRUCTION_DETAILS

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_instruction_details_class[INSTRUCTION_DETAILS] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|path": "/content[openEHR-EHR-SECTION.conformance_section.v0]/items[openEHR-EHR-INSTRUCTION.conformance_instruction.v0]",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|composition_uid": "4cdc3017-d8c5-4cd3-9900-f3bb7171d006",
  "conformance-ehrbase.de.v0/conformance_section/conformance_action/_instruction_details|activity_id": "activities[at0001]"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|path`
| STRING
| instruction_id.path
| yes
|

| `\|composition_uid`
| STRING
| instruction_id.id
| yes
|

| `\|activity_id`
| STRING
| activity_id
| yes
|
|===

[[EVENT_CONTEXT]]
== EVENT_CONTEXT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_event_context_class[EVENT_CONTEXT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/context/start_time": "2021-12-21T14:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/setting|code": "238",
  "conformance-ehrbase.de.v0/context/setting|value": "other care",
  "conformance-ehrbase.de.v0/context/setting|terminology": "openehr"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/context/_health_care_facility|id": "9091",
  "conformance-ehrbase.de.v0/context/_health_care_facility|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_health_care_facility|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_health_care_facility|name": "Hospital",
  "conformance-ehrbase.de.v0/context/_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/context/_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/context/_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/context/_participation:0|id": "199",
  "conformance-ehrbase.de.v0/context/_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/start_time": "2021-12-21T14:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/_end_time": "2021-12-21T15:19:31.649613+01:00",
  "conformance-ehrbase.de.v0/context/_location": "Ward A3, Room 12",
  "conformance-ehrbase.de.v0/context/setting|code": "238",
  "conformance-ehrbase.de.v0/context/setting|value": "other care",
  "conformance-ehrbase.de.v0/context/setting|terminology": "openehr"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/start_time`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| start_time
| yes
|

| `/setting`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| setting
| yes
| ValueSet (openEHR `setting` group)

| `/_end_time`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| end_time
| no
|

| `/_location`
| String
| location
| no
| Free-text label (e.g. "Ward A3"); not a date-time.

| `/_health_care_facility`
| <<PARTY_IDENTIFIED,PARTY_IDENTIFIED>>
| health_care_facility
| no
|

| `/_participation:i`
| <<PARTICIPATION,PARTICIPATION>>
| participations
| no
|
|===

NOTE: The `other_context` (RM `ITEM_STRUCTURE`) attribute is not represented as a leaf in this table; archetyped context content is flattened to sit directly under `/context/<node-name>/...`, where `<node-name>` is the identifier derived from the contained archetype (e.g. `/context/organisation/...` for an `openEHR-EHR-CLUSTER.organisation.v0` slot inside `other_context`). The underlying AQL path retains `/context/other_context[at0001]/items[...]`. The leading underscore on `_end_time`, `_location`, `_health_care_facility` and `_participation:i` marks them as optional RM-level attributes (see <<RM Attributes prefix>>).

[[PARTICIPATION]]
== PARTICIPATION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_participation_class[PARTICIPATION] class.

The `performer` (`PARTY_IDENTIFIED`) is inlined: its attributes are emitted at the same level as `function` and `mode`, rather than nested under `/performer`.

[source,json]
----
{
  "conformance-ehrbase.de.v0/context/_participation:0|function": "requester",
  "conformance-ehrbase.de.v0/context/_participation:0|mode": "face-to-face communication",
  "conformance-ehrbase.de.v0/context/_participation:0|name": "Dr. Marcus Johnson",
  "conformance-ehrbase.de.v0/context/_participation:0|id": "199",
  "conformance-ehrbase.de.v0/context/_participation:0|id_scheme": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_participation:0|id_namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/context/_participation:0|identifiers_id:0": "122",
  "conformance-ehrbase.de.v0/context/_participation:0|identifiers_issuer:0": "issuer",
  "conformance-ehrbase.de.v0/context/_participation:0|identifiers_assigner:0": "assigner",
  "conformance-ehrbase.de.v0/context/_participation:0|identifiers_type:0": "type"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|function`
| String
| function.value
| yes
|

| `\|mode`
| String
| mode.value
| no
| ValueSet (openEHR `participation mode` group)

| `\|name`
| String
| performer.name
| no
|

| `\|id`
| String
| performer.external_ref.id.value
| no
|

| `\|id_scheme`
| String
| performer.external_ref.id.scheme
| no
|

| `\|id_namespace`
| String
| performer.external_ref.namespace
| (yes)
| required if `\|id` is set. (RM `OBJECT_REF` has `namespace` directly on the reference, not nested under `id`.)

| `\|identifiers_id:i`
| String
| performer.identifiers[i].id
| no
|

| `\|identifiers_issuer:i`
| String
| performer.identifiers[i].issuer
| no
|

| `\|identifiers_assigner:i`
| String
| performer.identifiers[i].assigner
| no
|

| `\|identifiers_type:i`
| String
| performer.identifiers[i].type
| no
|
|===

NOTE: PARTICIPATION's `time` (RM `DV_INTERVAL<DV_DATE_TIME>`) is not currently emitted by FLAT mappings. Entries with a constrained participation `time` interval require the canonical RM JSON form.

[[participation_party_related]]
=== PARTY_RELATED performer

When the `performer` is a `PARTY_RELATED` (a sub-type of `PARTY_IDENTIFIED` that carries a `relationship: DV_CODED_TEXT`), the `relationship` attribute is emitted as a sub-path under the participation, with the standard <<DV_CODED_TEXT,DV_CODED_TEXT>> suffixes (`\|code`, `\|value`, `\|terminology`):

[source,json]
----
{
  "conformance-ehrbase.de.v0/context/_participation:0|function": "next of kin",
  "conformance-ehrbase.de.v0/context/_participation:0|name": "Susan Doe",
  "conformance-ehrbase.de.v0/context/_participation:0/relationship|code": "10",
  "conformance-ehrbase.de.v0/context/_participation:0/relationship|value": "mother",
  "conformance-ehrbase.de.v0/context/_participation:0/relationship|terminology": "openehr"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/relationship`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| relationship (when `performer` is `PARTY_RELATED`)
| (yes)
| Required when `performer` is a `PARTY_RELATED`; not present otherwise.
|===

NOTE: Implementation status — EHRbase reads and writes this path (`PartyRelatedStdConfig.addRelationship`); Better's `ParticipationToFlatMapper` currently treats the performer as `PARTY_IDENTIFIED` only and does not emit `relationship`. Producers that need cross-implementation portability for a `PARTY_RELATED` performer should either fall back to canonical RM JSON or limit usage to EHRbase-side flows until parity is established.

[[OBJECT_REF]]
== OBJECT_REF

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_event_context_class[EVENT_CONTEXT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|type": "GUIDELINE",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|namespace": "HOSPITAL-NS",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|id": "3445",
  "conformance-ehrbase.de.v0/conformance_section/conformance_instruction/_guideline_id|id_scheme": "HOSPITAL-NS"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|type`
| String
| type
| yes
|

| `\|id`
| String
| id.value
| yes
|

| `\|scheme`
| String
| id.scheme
| yes
|

| `\|namespace`
| String
| namespace
| yes
|
|===

== INTERVAL_EVENT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_structures.html#_interval_event_class[INTERVAL_EVENT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/width": "P30D",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|code": "146",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|value": "mean",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|terminology": "openehr"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0|sample_count": 5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/width": "P30D",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|code": "146",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|value": "mean",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/math_function|terminology": "openehr"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/width`
| <<DV_DURATION,DV_DURATION>>
| width
| yes
|

| `/math_function`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| math_function
| yes
|

| `\|sample_count`
| INTEGER
| sample_count
| no
|
|===

== POINT_EVENT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/ehr.html#_event_context_class[EVENT_CONTEXT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text": "DV_TEXT value",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/time": "2021-12-21T16:02:58.0094262+01:00"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/time`
| <<DV_DATE_TIME,DV_DATE_TIME>>
| time
| yes
|
|===

[[PARTY_PROXY]]
== PARTY_PROXY

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_party_proxy_class[PARTY_PROXY] class.

See <<PARTY_SELF,PARTY_SELF>>, <<PARTY_IDENTIFIED,PARTY_IDENTIFIED>> and <<PARTY_RELATED,PARTY_RELATED>>.

[[PARTY_SELF]]
== PARTY_SELF

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_party_self_class[PARTY_SELF] class.

[source,json]
----
{
  "ctx/composer_self": true,
  "conformance-ehrbase.de.v0/composer|id": "1234-5678",
  "conformance-ehrbase.de.v0/composer|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/composer|id_namespace": "EHR.NETWORK"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|id`
| String
| external_ref.id.value
| no
|

| `\|id_scheme`
| Integer
| external_ref.id.scheme
| no
|

| `\|id_namespace`
| String
| external_ref.namespace
| (yes)
| required if id is set
|===

[[PARTY_IDENTIFIED]]
== PARTY_IDENTIFIED

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_party_identified_class[PARTY_IDENTIFIED] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/composer|id": "1234-5678",
  "conformance-ehrbase.de.v0/composer|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/composer|id_namespace": "EHR.NETWORK",
  "conformance-ehrbase.de.v0/composer/_identifier:0|id": "122",
  "conformance-ehrbase.de.v0/composer/_identifier:0|issuer": "issuer",
  "conformance-ehrbase.de.v0/composer/_identifier:0|assigner": "assigner",
  "conformance-ehrbase.de.v0/composer/_identifier:0|type": "type"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|name`
| String
| name
| no
|

| `\|id`
| String
| external_ref.id.value
| no
|

| `\|id_scheme`
| Integer
| external_ref.id.scheme
| no
|

| `\|id_namespace`
| String
| external_ref.namespace
| (yes)
| required if id is set

| `/_identifier:i`
| <<DV_IDENTIFIER,DV_IDENTIFIER>>
| identifiers
| no
|
|===

[[PARTY_RELATED]]
== PARTY_RELATED

See RM specification of the https://specifications.openehr.org/releases/RM/latest/common.html#_party_related_class[PARTY_RELATED] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/composer/relationship|code": "10",
  "conformance-ehrbase.de.v0/composer/relationship|value": "mother",
  "conformance-ehrbase.de.v0/composer/relationship|terminology": "openehr"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/composer|name": "Silvia Blake",
  "conformance-ehrbase.de.v0/composer|id": "1234-5678",
  "conformance-ehrbase.de.v0/composer|id_scheme": "UUID",
  "conformance-ehrbase.de.v0/composer|id_namespace": "EHR.NETWORK",
  "conformance-ehrbase.de.v0/composer/relationship|code": "10",
  "conformance-ehrbase.de.v0/composer/relationship|value": "mother",
  "conformance-ehrbase.de.v0/composer/relationship|terminology": "openehr",
  "conformance-ehrbase.de.v0/composer/_identifier:0|id": "122",
  "conformance-ehrbase.de.v0/composer/_identifier:0|issuer": "issuer",
  "conformance-ehrbase.de.v0/composer/_identifier:0|assigner": "assigner",
  "conformance-ehrbase.de.v0/composer/_identifier:0|type": "type"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|name`
| String
| name
| no
|

| `\|id`
| String
| external_ref.id.value
| no
|

| `\|id_scheme`
| Integer
| external_ref.id.scheme
| no
|

| `\|id_namespace`
| String
| external_ref.namespace
| (yes)
| required if id is set

| `/_identifier:i`
| <<DV_IDENTIFIER,DV_IDENTIFIER>>
| identifiers
| no
|

| `/_relationship`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| relationship
| (yes)
|
|===

[[DV_TEXT]]
== DV_TEXT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text": "DV_TEXT value"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text": "DV_TEXT value",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text|formatting": "plain",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|preferred_term": "English",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0|match": "=",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|terminology": "SNOMED-CT",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|code": "21794005",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|code": "671",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|value": "research study"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|value`
| String
| value
| yes
|

| `\|formatting`
| String
| formatting
| no
|

| `/_language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| no
|

| `/_encoding`
| <<CODE_PHRASE,CODE_PHRASE>>
| encoding
| no
|

| `/_mapping:i`
| <<TERM_MAPPING,TERM_MAPPING>>
| mappings
| no
|
|===

[[CODE_PHRASE]]
== CODE_PHRASE

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_code_phrase_class[CODE_PHRASE] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|terminology": "ISO_639-1"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_language|preferred_term": "English"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|code`
| String
| code_string
| yes
|

| `\|terminology`
| String
| terminology_id.value
| yes
|

| `\|preferred_term`
| String
| preferred_term
| no
|
|===

[[TERM_MAPPING]]
== TERM_MAPPING

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_term_mapping_class[TERM_MAPPING] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0|match": "=",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|terminology": "SNOMED-CT",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|code": "21794005"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0|match": "=",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|terminology": "SNOMED-CT",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/target|code": "21794005",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|code": "671",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_text/_mapping:0/purpose|value": "research study"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|match`
| String
| match
| yes
|

| `/target`
| <<CODE_PHRASE,CODE_PHRASE>>
| target
| yes
|

| `/purpose`
| <<DV_CODED_TEXT,DV_CODED_TEXT>>
| purpose
| no
|
|===

[[DV_CODED_TEXT]]
== DV_CODED_TEXT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|value": "term1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|code": "at0006",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|terminology": "local"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|value": "term1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|code": "at0006",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|terminology": "local",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|preferred_term": "Term One",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|formatting": "plain",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_language|preferred_term": "English",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_encoding|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_encoding|terminology": "IANA_character-sets",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0|match": "=",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0/target|terminology": "SNOMED-CT",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0/target|code": "21794005",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0/purpose|terminology": "openehr",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0/purpose|code": "671",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text/_mapping:0/purpose|value": "research study"
}
----

Free-text value when the archetype constraint allows an open value-set (`listOpen: true` in the web template):

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_coded_text|other": "free-text value not in the coded list"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|code`
| String
| defining_code.code_string
| yes
|

| `\|value`
| String
| value
| (yes)
| only required for external terminologies

| `\|terminology`
| String
| defining_code.terminology_id.value
| (yes)
| only required for external terminologies

| `\|preferred_term`
| String
| defining_code.preferred_term
| no
| Optional preferred display rubric for the `defining_code`. See the `\|preferred_term` row of <<CODE_PHRASE,CODE_PHRASE>> for the analogous mapping on a bare `CODE_PHRASE`.

| `\|other`
| String
| _value_ (as `<<DV_TEXT,DV_TEXT>>`)
| no
| Free-text value used when the constraint allows an open value-set (`listOpen: true` in the web template). When `\|other` is set, `\|code`, `\|value`, `\|terminology` and `\|preferred_term` MUST NOT be set; the leaf is serialised in the canonical RM as a `DV_TEXT` rather than a `DV_CODED_TEXT`.

| `\|formatting`
| String
| formatting
| no
|

| `/_language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| no
|

| `/_encoding`
| <<CODE_PHRASE,CODE_PHRASE>>
| encoding
| no
|

| `/_mapping:i`
| <<TERM_MAPPING,TERM_MAPPING>>
| mappings
| no
|
|===

=== When a `DV_CODED_TEXT` becomes a `DV_TEXT`

Where the archetype constraint allows an open value-set (`listOpen: true` in the web template; non-`limit-to-list` in ADL), a leaf bound to `DV_CODED_TEXT` may be populated with a free-text value via the `\|other` suffix. In that case:

* the canonical RM serialisation of the leaf is a <<DV_TEXT,DV_TEXT>>, not a `DV_CODED_TEXT` with empty `defining_code`;
* `\|other` is mutually exclusive with `\|code`, `\|value`, `\|terminology` and `\|preferred_term` on the same leaf;
* on a closed list (`listOpen: false`), `\|other` MUST be rejected.

See <<open_value_sets>> for the cross-cutting rule and rationale.

[[DV_ORDINAL]]
== DV_ORDINAL

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_ordinal_class[DV_ORDINAL] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|code": "at0015",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|value": "value1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|ordinal": 1
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|code": "at0015",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|value": "value1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal|ordinal": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/lower|code": "at0015",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/lower|value": "value1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/lower|ordinal": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/upper|code": "at0015",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/upper|value": "value1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_normal_range/upper|ordinal": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0/lower|code": "at0016",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0/lower|value": "value2",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0/lower|ordinal": 2,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0|upper_unbounded": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0|upper_included": false,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ordinal/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|code`
| String
| symbol.defining_code.code_string
| Yes
|

| `\|value`
| String
| symbol.value
| (Yes)
| my be left out if symbol is defined in template

| `\|ordinal`
| Integer
| value
| (Yes)
| my be left out if symbol is defined in template

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_ORDINAL>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_ORDINAL>
| `_other_reference_ranges`
| no
|
|===

[[DV_BOOLEAN]]
== DV_BOOLEAN

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_boolean_class[DV_BOOLEAN] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_boolean": true
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| Boolean
| value
| Yes
|
|===

== DV_URI

See RM specification of the https://specifications.openehr.org/releases/RM/Release-1.0.4/data_types.html#_dv_uri_class[DV_URI] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_uri": "https://www.google.com/"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
|
|===

== DV_EHR_URI

See RM specification of the https://specifications.openehr.org/releases/RM/Release-1.0.4/data_types.html#_dv_ehr_uri_class[DV_EHR_URI] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_ehr_uri": "ehr://766b3873-0762-4921-91e2-838c8546d47f"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
|
|===

[[DV_IDENTIFIER]]
== DV_IDENTIFIER

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_quantity_class[DV_QUANTITY] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_identifier|id": "A123"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_identifier|id": "A123",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_identifier|issuer": "Issuer",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_identifier|assigner": "Assigner",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_identifier|type": "Prescription"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|id`
| String
| id
| Yes
| For the input \|id might be left out.

| `\|issuer`
| String
| issuer
| no
|

| `\|assigner`
| String
| assigner
| no
|

| `\|type`
| String
| type
| no
|
|===

== DV_QUANTITY

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_quantity_class[DV_QUANTITY] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude": 65.9,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|accuracy": 50.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|accuracy_is_percent": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|precision": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|units_system": "units_system",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity|units_display_name": "units_display_name",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_normal_range/lower|magnitude": 20.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_normal_range/lower|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_normal_range/upper|magnitude": 66.6,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_normal_range/upper|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|magnitude": 70.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/upper|magnitude": 77.6,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/upper|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|value": "very high",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|code": "260360000",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|terminology": "SNOMED-CT"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|magnitude`
| String
| magnitude
| yes
|

| `\|unit`
| Real
| unit
| yes
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `\|accuracy`
| Real
| accuracy
| no
|

| `\|accuracy_is_percent`
| Boolean
| accuracy_is_percent
| no
|

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_QUANTITY>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_QUANTITY>
| `_other_reference_ranges`
| no
|
|===

== DV_PROPORTION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_proportion_class[DV_PROPORTION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|numerator": 20.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|denominator": 12.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|type": 0
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|numerator": 20.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|denominator": 12.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|type": 0,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion": 1.6532258064516128,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|accuracy": 50.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|accuracy_is_percent": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion|precision": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/lower|numerator": 20.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/lower|denominator": 12.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/lower|type": 0,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/lower": 1.6532258064516128,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/upper|numerator": 25.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/upper|denominator": 12.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/upper|type": 0,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_normal_range/upper": 2.0564516129032255,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/lower|numerator": 20.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/lower|denominator": 18.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/lower|type": 0,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/lower": 1.1141304347826089,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/upper|numerator": 25.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/upper|denominator": 12.4,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/upper|type": 0,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/upper": 2.0564516129032255,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_proportion/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|numerator`
| Real
| numerator
| yes
|

| `\|denominator`
| Real
| denominator
| yes
|

| `\|type`
| Integer
| type
| yes
| ValueSet proportion_kind

| `\|precision`
| Integer
| precision
| no
| Number of decimal places to which `\|numerator` and `\|denominator` are expressed. Value `0` implies integral; `-1` implies no limit.

|
| Real
| magnitude
| no
| calculated on output

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|accuracy`
| Real
| accuracy
| no
| Half-range accuracy of measurement. Interpretation depends on `\|accuracy_is_percent`. A value of `0` means accuracy is 100% (no error).

| `\|accuracy_is_percent`
| Boolean
| accuracy_is_percent
| no
| When `true`, `\|accuracy` is a percentage (0–100); when `false` or absent, `\|accuracy` is an absolute quantity in the same units as the value.

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_PROPORTION>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_PROPORTION>
| `_other_reference_ranges`
| no
|
|===

== DV_COUNT

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_count_class[DV_COUNT] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count": 7
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count": 7,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count|accuracy": 50.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count|accuracy_is_percent": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count/_normal_range/lower": 1,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count/_normal_range/upper": 8,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count/_other_reference_ranges:0/lower": 8,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count/_other_reference_ranges:0/upper": 10,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_count/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| Integer
| magnitude
| Yes
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `\|accuracy`
| Real
| accuracy
| no
| Half-range accuracy of measurement. Interpretation depends on `\|accuracy_is_percent`. A value of `0` means accuracy is 100% (no error).

| `\|accuracy_is_percent`
| Boolean
| accuracy_is_percent
| no
| When `true`, `\|accuracy` is a percentage (0–100); when `false` or absent, `\|accuracy` is an absolute quantity in the same units as the value.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_COUNT>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_COUNT>
| `_other_reference_ranges`
| no
|
|===

== DV_DATE

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_date_class[DV_DATE] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date": "2022-01-12"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date": "2022-01-12",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_accuracy": "P2D",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_normal_range/lower": "2022-01-12",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_normal_range/upper": "2022-02-12",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_other_reference_ranges:0/lower": "2022-02-12",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_other_reference_ranges:0/upper": "2022-03-12",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
| ISO8601 date

| `/_accuracy`
| <<DV_DURATION,DV_DURATION>>
| accuracy
| no
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_DATE>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_DATE>
| `_other_reference_ranges`
| no
|
|===

[[DV_DATE_TIME]]
== DV_DATE_TIME

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_date_time_class[DV_DATE_TIME] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time": "2022-01-12T13:22:34.000868+01:00"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time": "2022-01-12T13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_accuracy": "P2DT9H52M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_normal_range/lower": "2022-01-12T13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_normal_range/upper": "2022-02-12T13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_other_reference_ranges:0/lower": "2022-02-12T13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_other_reference_ranges:0/upper": "2022-03-12T13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_date_time/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
| ISO8601 date-time

| `/_accuracy`
| <<DV_DURATION,DV_DURATION>>
| accuracy
| no
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_DATE_TIME>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_DATE_TIME>
| `_other_reference_ranges`
| no
|
|===

== DV_TIME

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_time_class[DV_TIME] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time": "13:22:34.000868+01:00"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time": "13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_accuracy": "PT9H52M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_normal_range/lower": "13:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_normal_range/upper": "14:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_other_reference_ranges:0/lower": "14:10:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_other_reference_ranges:0/upper": "15:22:34.000868+01:00",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_time/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
| ISO8601 time

| `/_accuracy`
| <<DV_DURATION,DV_DURATION>>
| accuracy
| no
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_TIME>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_TIME>
| `_other_reference_ranges`
| no
|
|===

[[DV_DURATION]]
== DV_DURATION

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_duration_class[DV_DURATION] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration": "P2DT11H33M"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration": "P2DT11H33M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration|magnitude_status": "~",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration|normal_status": "N",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration|accuracy": 50.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration|accuracy_is_percent": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration/_normal_range/lower": "P2DT11H33M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration/_normal_range/upper": "P2DT12H33M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration/_other_reference_ranges:0/lower": "P2DT11H33M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration/_other_reference_ranges:0/upper": "P2DT15H33M",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_duration/_other_reference_ranges:0/meaning": "high"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| value
| Yes
| ISO8601 duration

| `\|accuracy`
| Real
| accuracy
| no
|

| `\|accuracy_is_percent`
| Boolean
| accuracy_is_percent
| no
|

| `\|magnitude_status`
| String
| magnitude_status
| no
| ValueSet (=,>,>=,<,\<=,~)

| `\|normal_status`
| String
| normal_status.code_string
| no
| ValueSet `normal_statuses` (codes `HHH`, `HH`, `H`, `N`, `L`, `LL`, `LLL`). The FLAT carries only the `code_string`; the underlying `CODE_PHRASE` terminology is implicitly `openehr`.

| `/_normal_range`
| <<DV_INTERVAL,DV_INTERVAL>> <DV_DURATION>
| normal_range
| no
|

| `/_other_reference_ranges:i`
| <<REFERENCE_RANGE,REFERENCE_RANGE>> <DV_DURATION>
| `_other_reference_ranges`
| no
|
|===

[[REFERENCE_RANGE]]
== REFERENCE_RANGE

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_reference_range_class[REFERENCE_RANGE] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|magnitude": 70.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/upper|magnitude": 77.6,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/upper|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|value": "high"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|magnitude": 70.5,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/lower|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0|upper_unbounded": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0|upper_included": false,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|value": "very high",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|code": "260360000",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:0/meaning|terminology": "SNOMED-CT",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1|lower_unbounded": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1|lower_included": false,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1/upper|magnitude": 77.6,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1/upper|unit": "unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1/meaning|value": "very high",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1/meaning|code": "260360000",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_quantity/_other_reference_ranges:1/meaning|terminology": "SNOMED-CT"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/lower`
| T
| range.lower
| no
|

| `/upper`
| T
| range.upper
| no
|

| `\|lower_unbounded`
| Boolean
| range.lower_unbounded
| no
| defaults to false

| `\|upper_unbounded`
| Boolean
| range.upper_unbounded
| no
| defaults to false

| `\|lower_included`
| Boolean
| range.lower_included
| no
| defaults to true

| `\|upper_included`
| Boolean
| range.upper_included
| no
| defaults to true

| \meaning
| <<DV_TEXT,DV_TEXT>>
| meaning
| yes
|
|===

[[DV_PARSABLE]]
== DV_PARSABLE

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_parsable_class[DV_PARSABLE] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable": "Formal instructions on carrying out the procedure...",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable|formalism": "GLIF 1.0"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable": "Formal instructions on carrying out the procedure...",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable|formalism": "GLIF 1.0",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable/_language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable/_charset|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_parsable/_charset|terminology": "IANA_character-sets"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `\|value`
| String
| value
| Yes
|

| `\|formalism`
| String
| formalism
| Yes
|

| `/_charset`
| <<CODE_PHRASE,CODE_PHRASE>>
| charset
| no
|

| `/_language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| no
|
|===

[[DV_MULTIMEDIA]]
== DV_MULTIMEDIA

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class[DV_MULTIMEDIA] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia": "http://med.tube.com/sample",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|mediatype": "video/H261",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|size": 504903212
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia": "http://med.tube.com/sample",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|mediatype": "video/H261",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|size": 504903212,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|compression_algorithm": "zlib",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|alternatetext": "alternate text",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|integrity_check": "b90360558e5420cef47015b1afbd70a156f940afa470b0515f95eacc2edcef6a",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia|integrity_check_algorithm": "SHA-256",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_thumbnail|data": "Z2hnZ2pnamdnag==",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_thumbnail|mediatype": "image/png",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_thumbnail|size": 504,
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_language|code": "en",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_language|terminology": "ISO_639-1",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_charset|code": "UTF-8",
  "conformance-ehrbase.de.v0/conformance_section/conformance_observation/any_event:0/dv_multimedia/_charset|terminology": "IANA_character-sets"
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

|
| String
| uri.value
| no
|

| `\|mediatype`
| String
| media_type.code_string
| Yes
| ValueSet (IANA_media-types)

| `\|size`
| Integer
| size
| Yes
|

| `\|alternatetext`
| String
| alternate_text
| no
|

| `\|compression_algorithm`
| String
| compression_algorithm.code_string
| no
| ValueSet (openehr_compression_algorithms)

| `\|integrity_check_algorithm`
| String
| integrity_check_algorithm
| no
| ValueSet (openehr_integrity_check_algorithms)

| `\|integrity_check`
| String
| integrity_check
| no
|

| `\|data`
| String
| dta
| no
|

| `/_thumbnail`
| <<DV_MULTIMEDIA,DV_MULTIMEDIA>>
| thumbnail
| no
|

| `/_charset`
| <<CODE_PHRASE,CODE_PHRASE>>
| charset
| no
|

| `/_language`
| <<CODE_PHRASE,CODE_PHRASE>>
| language
| no
|
|===

[[DV_INTERVAL]]
== DV_INTERVAL

See RM specification of the https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_interval_class[DV_INTERVAL] class.

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/lower|magnitude": 72.83,
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/lower|unit": "Unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/upper|magnitude": 80.83,
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/upper|unit": "Unit"
}
----

[source,json]
----
{
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/lower|magnitude": 72.83,
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity/lower|unit": "Unit",
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity|lower_included": false,
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity|upper_unbounded": true,
  "conformance-ehrbase.de.v0/conformance_section/conformance_interval/any_event:0/interval_dv_quantity|upper_included": false
}
----

[cols="5*", options="header"]
|===
| Flat Path
| Flat type
| RM Path
| Required
| Note

| `/lower`
| T
| lower
| no
|

| `/upper`
| T
| upper
| no
|

| `\|lower_unbounded`
| BOOLEAN
| `\|lower_unbounded`
| no
| defaults to false. only in output if true

| `\|upper_unbounded`
| BOOLEAN
| upper_unbounded
| no
| defaults to false, only in output if true

| `\|lower_included`
| BOOLEAN
| lower_included
| no
| defaults to true. only in output if false

| `\|upper_included`
| BOOLEAN
| upper_included
| no
| defaults to true. only in output if false
|===