// @generated by openehr-codegen from BMM (`VERSIONED_COMPOSITION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `VERSIONED_COMPOSITION` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::data_types::quantity::date_time::dv_date_time::DvDateTime;
use openehr_base::v1_2::base_types::identification::hier_object_id::HierObjectId;
use openehr_base::v1_2::base_types::identification::object_ref::ObjectRef;

/// Version-controlled composition abstraction, defined by inheriting `VERSIONED_OBJECT<COMPOSITION>`.
#[doc(alias = "VERSIONED_COMPOSITION")]
#[derive(Debug, Clone, PartialEq)]
pub struct VersionedComposition {
    // inherited: VERSIONED_OBJECT
    /// Unique identifier of this version container in the form of a UID with no extension.
    ///
    /// This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
    pub uid: HierObjectId,
    /// Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
    pub owner_id: ObjectRef,
    /// Time of initial creation of this versioned object.
    pub time_created: DvDateTime,
}
