// @generated by openehr-codegen from BMM (`EXPR_CONSTRAINT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am24::aom2::constraint_model::c_primitive_object::CPrimitiveObject;
use crate::am24::aom2::rules::expr_archetype_id_constraint::ExprArchetypeIdConstraint;

/// Expression tree leaf item representing a constraint on a primitive type, expressed in the form of a concrete subtype of C_PRIMITIVE_OBJECT.
#[derive(Debug, Clone, PartialEq)]
pub struct ExprConstraintData {
    /// The constraint.
    pub item: CPrimitiveObject,
}

/// Expression tree leaf item representing a constraint on a primitive type, expressed in the form of a concrete subtype of C_PRIMITIVE_OBJECT.
/// Polymorphic slot of `EXPR_CONSTRAINT`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ExprConstraint {
    ExprArchetypeIdConstraint(ExprArchetypeIdConstraint),
    ExprConstraint(ExprConstraintData),
}
