// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR spec package `v1_2/data_structures/item_structure` — generated module tree.

pub mod item_list;
pub mod item_single;
pub mod item_structure;
pub mod item_table;
pub mod item_tree;

// hand-written modules (spec behaviour), auto-declared:
pub mod item_list_impl;
pub mod item_single_impl;
pub mod item_table_impl;
pub mod item_tree_impl;
