// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_2/ehr_extract` — generated module tree.

pub mod common;
pub mod generic_extract;
pub mod message;
pub mod openehr_extract;
pub mod sync_extract;
