// @generated by openehr-codegen from BMM (`EXTRACT_ITEM`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `EXTRACT_ITEM` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::ehr_extract::common::extract_folder::ExtractFolder;
use crate::v1_2::ehr_extract::generic_extract::generic_content_item::GenericContentItem;
use crate::v1_2::ehr_extract::openehr_extract::openehr_content_item::OpenehrContentItem;

/// Closed subtype set of `EXTRACT_ITEM`, dispatched on each payload's `_type`.
///
/// Abstract parent of Extract Folder and Content types.
#[doc(alias = "EXTRACT_ITEM")]
#[derive(Debug, Clone, PartialEq)]
pub enum ExtractItem {
    /// The `EXTRACT_FOLDER` subtype of `EXTRACT_ITEM`.
    ExtractFolder(ExtractFolder),
    /// The `GENERIC_CONTENT_ITEM` subtype of `EXTRACT_ITEM`.
    GenericContentItem(GenericContentItem),
    /// The `OPENEHR_CONTENT_ITEM` subtype of `EXTRACT_ITEM`.
    OpenehrContentItem(OpenehrContentItem),
}
