//! AQL execution + `RESULT_SET` assembly (our own engine, P16).
//!
//! [`execute`] plans-to-SQL ([`super::sql::build`]), runs the one statement on
//! the `sqlx` pool, and assembles a [`QueryResult`] (column metadata + canonical
//! JSON rows) the service renders as an ITS-REST 1.0.3 `RESULT_SET`. Scalar cells
//! are read directly as canonical JSON (`jsonb`); whole-object cells reassemble
//! their node subtree through the P10 codec ([`crate::storage::reassemble`]).

use serde_json::Value;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use super::error::{AqlError, ExecError};
use super::ir::{Params, QueryIr};
use super::sql::{CellKind, ColumnSpec, SqlCtx};

/// One `RESULT_SET` column's metadata (`schemas/query/ResultSetColumn`).
///
/// `RESULT_SET_COLUMN.archetype_id [0..1]` is deliberately absent: the SM
/// `result_set_column.adoc` marks it "check on whether needed or **inside the
/// path**", and the ITS-REST 1.0.3 `ResultSetColumn` examples carry the
/// archetype/node codes inline in `path` (never a separate `archetype_id`), so a
/// distinct field has no pinned semantics or golden to validate against.
// PORT NOTE: no `archetype_id` field is emitted (the decision is recorded in
// the register): SM `result_set_column.adoc` marks it "check on whether needed
// or inside the path", the ITS-REST 1.0.3 `ResultSetColumn` examples carry the
// archetype/node codes inline in `path`, and no golden pins a standalone field.
// Should a future CNF case pin one, derive it from the leaf's deepest archetype
// predicate (cheaply available on `ir::LeafPath`) and have `result_set.rs` emit
// it; today the archetype info lives inside `path`.
#[derive(Debug, Clone)]
pub struct ColumnMeta {
    /// The column name (`AS` alias or `#{index}`).
    pub name: String,
    /// The AQL path expression, if reconstructable.
    pub path: Option<String>,
}

/// The assembled result of an AQL query: the SELECT column metadata and the rows
/// (each a vector of canonical-JSON cells, aligned to `columns`).
#[derive(Debug, Clone)]
pub struct QueryResult {
    /// The SELECT columns, in order.
    pub columns: Vec<ColumnMeta>,
    /// The rows; each is one cell per column.
    pub rows: Vec<Vec<Value>>,
}

/// Plan, execute, and assemble an AQL query.
///
/// # Errors
///
/// [`AqlError::Sql`] if the IR cannot be lowered to SQL; [`AqlError::Exec`] if
/// the database rejects the query or a whole-object cell cannot be reassembled.
pub async fn execute(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
) -> Result<QueryResult, AqlError> {
    let prepared = super::sql::build(ir, params, ctx)?;
    // The SQL is generated by our own `sea-query` builder (never client text);
    // `AssertSqlSafe` acknowledges that to the sqlx injection guard.
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(prepared.sql), prepared.values)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;

    let columns = prepared
        .columns
        .iter()
        .map(|c| ColumnMeta {
            name: c.name.clone(),
            path: c.path.clone(),
        })
        .collect();

    let mut out_rows = Vec::with_capacity(rows.len());
    for row in &rows {
        let mut cells = Vec::with_capacity(prepared.columns.len());
        for spec in &prepared.columns {
            cells.push(read_cell(pool, row, spec).await?);
        }
        out_rows.push(cells);
    }

    Ok(QueryResult {
        columns,
        rows: out_rows,
    })
}

/// The distinct EHR ids and template ids an AQL query touches, collected for the
/// ABAC query post-check (`docs/enterprise/access-control.md` §6.4) —
/// independent of the query's projection (the v1 defect-#1 fix).
#[derive(Debug, Clone, Default)]
pub struct QueryScope {
    /// Distinct touched EHR ids (as strings).
    pub ehr_ids: Vec<String>,
    /// Distinct touched template ids.
    pub template_ids: Vec<String>,
}

/// Run the scope-collection query for `ir` and return the distinct EHR-id and
/// template-id sets it touches (§6.4). Empty when the query has no VO root.
///
/// # Errors
/// [`AqlError::Sql`] if the scope query cannot be lowered; [`AqlError::Exec`] if
/// the database rejects it.
pub async fn collect_scope(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
) -> Result<QueryScope, AqlError> {
    let Some(scope) = super::sql::build_scope(ir, params, ctx)? else {
        return Ok(QueryScope::default());
    };
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(scope.sql), scope.values)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;
    let mut ehr_ids = std::collections::BTreeSet::new();
    let mut template_ids = std::collections::BTreeSet::new();
    for row in &rows {
        // Every bound VO root contributes an (ehr_id, template_id) column pair.
        for (ehr_col, template_col) in &scope.columns {
            if let Ok(Some(e)) = row.try_get::<Option<Uuid>, _>(ehr_col.as_str()) {
                ehr_ids.insert(e.to_string());
            }
            if let Ok(Some(t)) = row.try_get::<Option<String>, _>(template_col.as_str()) {
                template_ids.insert(t);
            }
        }
    }
    Ok(QueryScope {
        ehr_ids: ehr_ids.into_iter().collect(),
        template_ids: template_ids.into_iter().collect(),
    })
}

/// Read one cell for `spec` from a result `row`.
async fn read_cell(
    pool: &PgPool,
    row: &sqlx::postgres::PgRow,
    spec: &ColumnSpec,
) -> Result<Value, AqlError> {
    match spec.kind {
        CellKind::Scalar => {
            let v: Option<Value> = row
                .try_get(spec.sql_cols[0].as_str())
                .map_err(ExecError::from)?;
            Ok(v.unwrap_or(Value::Null))
        }
        CellKind::WholeObject => {
            let vo_id: Option<Uuid> = row
                .try_get(spec.sql_cols[0].as_str())
                .map_err(ExecError::from)?;
            let Some(vo_id) = vo_id else {
                return Ok(Value::Null);
            };
            let sys_version: i32 = row
                .try_get(spec.sql_cols[1].as_str())
                .map_err(ExecError::from)?;
            let num: i32 = row
                .try_get(spec.sql_cols[2].as_str())
                .map_err(ExecError::from)?;
            let num_cap: i32 = row
                .try_get(spec.sql_cols[3].as_str())
                .map_err(ExecError::from)?;
            // PERF(port): one follow-up query per whole-object cell (correct
            // first); a single-query jsonb aggregation is a P20 optimization.
            // The subtree SELECT + path rebasing lives in the storage codec
            // (register 02); the engine supplies only the four locators.
            Ok(crate::storage::node_repo::read_subtree_canonical(
                pool,
                vo_id,
                sys_version,
                num,
                num_cap,
            )
            .await
            .map_err(ExecError::from)?)
        }
    }
}
