//! AQL execution + `RESULT_SET` assembly (our own engine, P16).
//!
//! [`execute`] plans-to-SQL ([`super::sql::build`]), runs the one statement on
//! the `sqlx` pool, and assembles a [`QueryResult`] (column metadata + canonical
//! JSON rows) the service renders as an ITS-REST 1.0.3 `RESULT_SET`. Scalar cells
//! are read directly as canonical JSON (`jsonb`); whole-object cells reassemble
//! their node subtree through the P10 codec ([`crate::storage::reassemble`]).

use serde_json::Value;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::storage::{NodeRow, reassemble};

use super::error::{AqlError, ExecError};
use super::ir::{Params, QueryIr};
use super::sql::{CellKind, ColumnSpec, SqlCtx};

/// One `RESULT_SET` column's metadata (`schemas/query/ResultSetColumn`).
#[derive(Debug, Clone)]
pub struct ColumnMeta {
    /// The column name (`AS` alias or `#{index}`).
    pub name: String,
    /// The AQL path expression, if reconstructable.
    pub path: Option<String>,
}

/// The assembled result of an AQL query: the SELECT column metadata and the rows
/// (each a vector of canonical-JSON cells, aligned to `columns`).
#[derive(Debug, Clone)]
pub struct QueryResult {
    /// The SELECT columns, in order.
    pub columns: Vec<ColumnMeta>,
    /// The rows; each is one cell per column.
    pub rows: Vec<Vec<Value>>,
}

/// Plan, execute, and assemble an AQL query.
///
/// # Errors
///
/// [`AqlError::Sql`] if the IR cannot be lowered to SQL; [`AqlError::Exec`] if
/// the database rejects the query or a whole-object cell cannot be reassembled.
pub async fn execute(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
) -> Result<QueryResult, AqlError> {
    let prepared = super::sql::build(ir, params, ctx)?;
    // The SQL is generated by our own `sea-query` builder (never client text);
    // `AssertSqlSafe` acknowledges that to the sqlx injection guard.
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(prepared.sql), prepared.values)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;

    let columns = prepared
        .columns
        .iter()
        .map(|c| ColumnMeta {
            name: c.name.clone(),
            path: c.path.clone(),
        })
        .collect();

    let mut out_rows = Vec::with_capacity(rows.len());
    for row in &rows {
        let mut cells = Vec::with_capacity(prepared.columns.len());
        for spec in &prepared.columns {
            cells.push(read_cell(pool, row, spec).await?);
        }
        out_rows.push(cells);
    }

    Ok(QueryResult {
        columns,
        rows: out_rows,
    })
}

/// The distinct EHR ids and template ids an AQL query touches, collected for the
/// ABAC query post-check (`docs/enterprise/access-control.md` §6.4) —
/// independent of the query's projection (the v1 defect-#1 fix).
#[derive(Debug, Clone, Default)]
pub struct QueryScope {
    /// Distinct touched EHR ids (as strings).
    pub ehr_ids: Vec<String>,
    /// Distinct touched template ids.
    pub template_ids: Vec<String>,
}

/// Run the scope-collection query for `ir` and return the distinct EHR-id and
/// template-id sets it touches (§6.4). Empty when the query has no VO root.
///
/// # Errors
/// [`AqlError::Sql`] if the scope query cannot be lowered; [`AqlError::Exec`] if
/// the database rejects it.
pub async fn collect_scope(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
) -> Result<QueryScope, AqlError> {
    let Some(scope) = super::sql::build_scope(ir, params, ctx)? else {
        return Ok(QueryScope::default());
    };
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(scope.sql), scope.values)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;
    let mut ehr_ids = std::collections::BTreeSet::new();
    let mut template_ids = std::collections::BTreeSet::new();
    for row in &rows {
        // Every bound VO root contributes an (ehr_id, template_id) column pair.
        for (ehr_col, template_col) in &scope.columns {
            if let Ok(Some(e)) = row.try_get::<Option<Uuid>, _>(ehr_col.as_str()) {
                ehr_ids.insert(e.to_string());
            }
            if let Ok(Some(t)) = row.try_get::<Option<String>, _>(template_col.as_str()) {
                template_ids.insert(t);
            }
        }
    }
    Ok(QueryScope {
        ehr_ids: ehr_ids.into_iter().collect(),
        template_ids: template_ids.into_iter().collect(),
    })
}

/// Read one cell for `spec` from a result `row`.
async fn read_cell(
    pool: &PgPool,
    row: &sqlx::postgres::PgRow,
    spec: &ColumnSpec,
) -> Result<Value, AqlError> {
    match spec.kind {
        CellKind::Scalar => {
            let v: Option<Value> = row
                .try_get(spec.sql_cols[0].as_str())
                .map_err(ExecError::from)?;
            Ok(v.unwrap_or(Value::Null))
        }
        CellKind::WholeObject => {
            let vo_id: Option<Uuid> = row
                .try_get(spec.sql_cols[0].as_str())
                .map_err(ExecError::from)?;
            let Some(vo_id) = vo_id else {
                return Ok(Value::Null);
            };
            let sys_version: i32 = row
                .try_get(spec.sql_cols[1].as_str())
                .map_err(ExecError::from)?;
            let num: i32 = row
                .try_get(spec.sql_cols[2].as_str())
                .map_err(ExecError::from)?;
            let num_cap: i32 = row
                .try_get(spec.sql_cols[3].as_str())
                .map_err(ExecError::from)?;
            // PERF(port): one follow-up query per whole-object cell (correct
            // first); a single-query jsonb aggregation is a P20 optimization.
            reassemble_subtree(pool, vo_id, sys_version, num, num_cap).await
        }
    }
}

/// Reassemble a whole structure object from its node subtree, re-based so the
/// anchor node (`num`) becomes the fragment root (the codec requires `num == 0`
/// and an empty path at the root).
async fn reassemble_subtree(
    pool: &PgPool,
    vo_id: Uuid,
    sys_version: i32,
    num: i32,
    num_cap: i32,
) -> Result<Value, AqlError> {
    let rows = sqlx::query(
        "SELECT num, num_cap, parent_num, citem_num, rm_type, archetype, name, path, data \
         FROM node WHERE vo_id = $1 AND sys_version = $2 AND num BETWEEN $3 AND $4 ORDER BY num",
    )
    .bind(vo_id)
    .bind(sys_version)
    .bind(num)
    .bind(num_cap)
    .fetch_all(pool)
    .await
    .map_err(ExecError::from)?;

    // The anchor is the lowest-num row (the queried `num`); its path is the
    // prefix to strip so descendants re-root at it.
    let base_path: String = rows
        .first()
        .and_then(|r| r.try_get::<String, _>("path").ok())
        .unwrap_or_default();

    let mut node_rows = Vec::with_capacity(rows.len());
    for r in &rows {
        let path: String = r.try_get("path").map_err(ExecError::from)?;
        let rebased = path.strip_prefix(&base_path).unwrap_or(&path).to_owned();
        node_rows.push(NodeRow {
            num: r.try_get::<i32, _>("num").map_err(ExecError::from)? - num,
            num_cap: r.try_get::<i32, _>("num_cap").map_err(ExecError::from)? - num,
            // parent_num / citem_num are not used by `reassemble`; re-root them.
            parent_num: 0,
            citem_num: None,
            rm_type: r.try_get("rm_type").map_err(ExecError::from)?,
            archetype: r.try_get("archetype").map_err(ExecError::from)?,
            name: r.try_get("name").map_err(ExecError::from)?,
            path: rebased,
            data: r.try_get("data").map_err(ExecError::from)?,
        });
    }
    Ok(reassemble(&node_rows).map_err(ExecError::from)?)
}
