// @generated by openehr-codegen from BMM (`BMM_GENERIC_TYPE`) — DO NOT EDIT.

//! The openEHR `BMM_GENERIC_TYPE` spec class, generated from the vendored BMM
//! meta-model.

use crate::bmm::core::bmm_generic_class::BmmGenericClass;
use crate::bmm::core::bmm_type::BmmType;

/// Type reference based on a generic class, e.g. 'HashTable \<List \<Packet\>, String\>'.
#[doc(alias = "BMM_GENERIC_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmGenericType {
    // inherited: BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,
    /// Generic parameters of the root_type in this type specifier. The order must match the order of the owning class's formal generic parameter declarations.
    pub generic_parameters: Vec<BmmType>,
    /// The base class of this type.
    pub base_class: BmmGenericClass,
}
