// @generated by openehr-codegen from BMM (`BMM_PACKAGE_CONTAINER`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use crate::bmm::core::bmm_package::BmmPackage;
use openehr_derive::OpenEhrType;

/// Abstraction of a BMM model component that contains packages and classes.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "BMM_PACKAGE_CONTAINER")]
pub struct BmmPackageContainer {
    // inherited: BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,
    /// Child packages; keys all in upper case for guaranteed matching.
    pub packages: Option<std::collections::BTreeMap<String, BmmPackage>>,
}
