// @generated by openehr-codegen from BMM (`ACTIVITY`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::common::archetyped::archetyped::Archetyped;
use crate::common::archetyped::feeder_audit::FeederAudit;
use crate::common::archetyped::link::Link;
use crate::data_structures::item_structure::item_structure::ItemStructure;
use crate::data_types::encapsulated::dv_parsable::DvParsable;
use crate::data_types::text::dv_text::DvText;
use openehr_base::prelude::UidBasedId;
use openehr_derive::OpenEhrType;

/// Defines a single activity within an Instruction, such as a medication administration.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "ACTIVITY")]
pub struct Activity {
    // inherited: LOCATABLE
    /// Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
    pub name: DvText,
    /// Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
    ///
    /// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
    pub archetype_node_id: String,
    /// Optional globally unique object identifier for root points of archetyped structures.
    pub uid: Option<UidBasedId>,
    /// Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
    pub links: Vec<Link>,
    /// Details of archetyping used on this node.
    pub archetype_details: Option<Archetyped>,
    /// Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
    pub feeder_audit: Option<FeederAudit>,
    /// Timing of the activity, in the form of a parsable string. If used, the preferred syntax is ISO8601 'R' format, but other formats may be used including HL7 GTS.
    ///
    /// May be omitted if:
    ///
    /// * timing is represented structurally in the `_description_` attribute (e.g. via archetyped elements), or
    /// * unavailable, e.g. imported legacy data; in such cases, the `INSTRUCTION._narrative_` should carry text that indicates the timing of its `_activities_`.
    pub timing: Option<DvParsable>,
    /// Perl-compliant regular expression pattern, enclosed in  '//' delimiters, indicating the valid identifiers of archetypes for Actions corresponding to this Activity specification.
    ///
    /// Defaults to  `/.*/`, meaning any archetype.
    pub action_archetype_id: String,
    /// Description of the activity, in the form of an archetyped structure.
    pub description: ItemStructure,
}
