// @generated by openehr-codegen from BMM (`CARE_ENTRY`) — DO NOT EDIT.

use crate::composition::content::entry::action::Action;
use crate::composition::content::entry::evaluation::Evaluation;
use crate::composition::content::entry::instruction::Instruction;
use crate::composition::content::entry::observation::Observation;
use serde::{Deserialize, Serialize};

/// The abstract parent of all clinical `ENTRY` subtypes. A `CARE_ENTRY` defines protocol and guideline attributes for all clinical Entry subtypes.
/// Closed subtype set of `CARE_ENTRY` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CareEntry {
    Action(Action),
    Evaluation(Evaluation),
    Instruction(Instruction),
    Observation(Observation),
}
