// @generated by openehr-codegen from BMM (`P_AUTHORED_RESOURCE`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::am24::aom2::persistence::archetype::p_authored_archetype::PAuthoredArchetype;
use crate::am24::aom2::persistence::archetype::p_operational_template::POperationalTemplate;
use crate::am24::aom2::persistence::archetype::p_template::PTemplate;

/// Abstract idea of an online resource created by a human author.
/// Closed subtype set of `P_AUTHORED_RESOURCE` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PAuthoredResource {
    PAuthoredArchetype(PAuthoredArchetype),
    POperationalTemplate(POperationalTemplate),
    PTemplate(PTemplate),
}
