// @generated by openehr-codegen from BMM (`BMM_PACKAGE_CONTAINER`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::bmm3::core::model::bmm_model::BmmModel;
use crate::bmm3::core::model::bmm_package::BmmPackage;

/// Abstraction of a BMM model component that contains packages and classes.
#[derive(Debug, Clone, PartialEq)]
pub struct BmmPackageContainerData {
    // inherited: BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,
    /// Child packages; keys all in upper case for guaranteed matching.
    pub packages: Option<std::collections::BTreeMap<String, BmmPackage>>,
}

/// Abstraction of a BMM model component that contains packages and classes.
/// Polymorphic slot of `BMM_PACKAGE_CONTAINER`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum BmmPackageContainer {
    BmmModel(BmmModel),
    BmmPackage(BmmPackage),
    BmmPackageContainer(BmmPackageContainerData),
}
