// @generated by openehr-codegen from BMM (`MEASUREMENT_SERVICE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `MEASUREMENT_SERVICE` spec class, generated from the vendored BMM
//! meta-model.

/// Defines an object providing proxy access to a measurement information service.
#[doc(alias = "MEASUREMENT_SERVICE")]
#[derive(Debug, Clone, PartialEq)]
pub struct MeasurementService {}
