// @generated by openehr-codegen from BMM (`EXPR_VARIABLE_REF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `EXPR_VARIABLE_REF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::beom::core::variable_declaration::VariableDeclaration;

/// Expression tree leaf item representing a reference to a declared variable.
#[doc(alias = "EXPR_VARIABLE_REF")]
#[derive(Debug, Clone, PartialEq)]
pub struct ExprVariableRef {
    /// The variable referred to.
    pub item: VariableDeclaration,
}
