// @generated by openehr-codegen from BMM (`ARCHETYPE_SLOT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am14::aom14::archetype::assertion::assertion::Assertion;
use openehr_base::prelude::Interval;

/// Constraint describing a  slot' where another archetype can occur.
#[derive(Debug, Clone, PartialEq)]
pub struct ArchetypeSlot {
    // inherited: C_OBJECT
    /// Reference model type that this node corresponds to.
    pub rm_type_name: String,
    /// Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1).
    pub occurrences: Interval<i32>,
    /// Semantic identifier of this node, used to distinguish sibling nodes. All nodes must have a node_id; for nodes under a container C_ATTRIBUTE, the id must be an id-code must be defined in the archetype terminology. For valid structures, all node ids are at-codes.
    /// For C_PRIMITIVE_OBJECTs, it will have the special value Primitive_node_id.
    pub node_id: String,
    /// List of constraints defining other archetypes that could be included at this point.
    pub includes: Vec<Assertion>,
    /// List of constraints defining other archetypes that cannot be included at this point.
    pub excludes: Vec<Assertion>,
}
