// @generated by openehr-codegen from BMM (`ARCHETYPE_CONSTRAINT`) — DO NOT EDIT.

//! The openEHR `ARCHETYPE_CONSTRAINT` spec class, generated from the vendored BMM
//! meta-model.

use crate::am14::aom14::archetype::constraint_model::archetype_internal_ref::ArchetypeInternalRef;
use crate::am14::aom14::archetype::constraint_model::archetype_slot::ArchetypeSlot;
use crate::am14::aom14::archetype::constraint_model::c_complex_object::CComplexObject;
use crate::am14::aom14::archetype::constraint_model::c_multiple_attribute::CMultipleAttribute;
use crate::am14::aom14::archetype::constraint_model::c_primitive_object::CPrimitiveObject;
use crate::am14::aom14::archetype::constraint_model::c_single_attribute::CSingleAttribute;
use crate::am14::aom14::archetype::constraint_model::constraint_ref::ConstraintRef;
use crate::am14::aom14::openehr_archetype_profile::c_coded_text::CCodedText;
use crate::am14::aom14::openehr_archetype_profile::c_ordinal::COrdinal;
use crate::am14::aom14::openehr_archetype_profile::c_quantity::CQuantity;

/// Closed subtype set of `ARCHETYPE_CONSTRAINT`, dispatched on each payload's `_type`.
///
/// Archetype equivalent to LOCATABLE class in openEHR Common reference model. Defines common constraints for any inheritor of LOCATABLE in any reference model.
#[doc(alias = "ARCHETYPE_CONSTRAINT")]
#[derive(Debug, Clone, PartialEq)]
pub enum ArchetypeConstraint {
    /// The `ARCHETYPE_INTERNAL_REF` subtype of `ARCHETYPE_CONSTRAINT`.
    ArchetypeInternalRef(ArchetypeInternalRef),
    /// The `ARCHETYPE_SLOT` subtype of `ARCHETYPE_CONSTRAINT`.
    ArchetypeSlot(ArchetypeSlot),
    /// The `CONSTRAINT_REF` subtype of `ARCHETYPE_CONSTRAINT`.
    ConstraintRef(ConstraintRef),
    /// The `C_CODED_TEXT` subtype of `ARCHETYPE_CONSTRAINT`.
    CCodedText(CCodedText),
    /// The `C_COMPLEX_OBJECT` subtype of `ARCHETYPE_CONSTRAINT`.
    CComplexObject(CComplexObject),
    /// The `C_MULTIPLE_ATTRIBUTE` subtype of `ARCHETYPE_CONSTRAINT`.
    CMultipleAttribute(CMultipleAttribute),
    /// The `C_ORDINAL` subtype of `ARCHETYPE_CONSTRAINT`.
    COrdinal(COrdinal),
    /// The `C_PRIMITIVE_OBJECT` subtype of `ARCHETYPE_CONSTRAINT`.
    CPrimitiveObject(CPrimitiveObject),
    /// The `C_QUANTITY` subtype of `ARCHETYPE_CONSTRAINT`.
    CQuantity(CQuantity),
    /// The `C_SINGLE_ATTRIBUTE` subtype of `ARCHETYPE_CONSTRAINT`.
    CSingleAttribute(CSingleAttribute),
}
