// @generated by openehr-codegen from BMM (`C_OBJECT`) — DO NOT EDIT.

use crate::am14::aom14::archetype::constraint_model::archetype_internal_ref::ArchetypeInternalRef;
use crate::am14::aom14::archetype::constraint_model::archetype_slot::ArchetypeSlot;
use crate::am14::aom14::archetype::constraint_model::c_complex_object::CComplexObject;
use crate::am14::aom14::archetype::constraint_model::c_primitive_object::CPrimitiveObject;
use crate::am14::aom14::archetype::constraint_model::constraint_ref::ConstraintRef;
use crate::am14::aom14::openehr_archetype_profile::c_coded_text::CCodedText;
use crate::am14::aom14::openehr_archetype_profile::c_ordinal::COrdinal;
use crate::am14::aom14::openehr_archetype_profile::c_quantity::CQuantity;

/// Abstract model of constraint on any kind of object node.
/// Closed subtype set of `C_OBJECT`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum CObject {
    ArchetypeInternalRef(ArchetypeInternalRef),
    ArchetypeSlot(ArchetypeSlot),
    ConstraintRef(ConstraintRef),
    CCodedText(CCodedText),
    CComplexObject(CComplexObject),
    COrdinal(COrdinal),
    CPrimitiveObject(CPrimitiveObject),
    CQuantity(CQuantity),
}
