// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `am14/aom14/archetype/constraint_model` — generated module tree.

pub mod archetype_constraint;
pub mod archetype_internal_ref;
pub mod archetype_slot;
pub mod c_attribute;
pub mod c_complex_object;
pub mod c_defined_object;
pub mod c_domain_type;
pub mod c_multiple_attribute;
pub mod c_object;
pub mod c_primitive_object;
pub mod c_reference_object;
pub mod c_single_attribute;
pub mod cardinality;
pub mod constraint_ref;
