// @generated by openehr-codegen from BMM (`BMM_SIMPLE_TYPE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `BMM_SIMPLE_TYPE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::entity::bmm_simple_class::BmmSimpleClass;
use crate::v1_0::bmm::core::entity::range_constrained::bmm_value_set_spec::BmmValueSetSpec;

/// Type reference to a single type i.e. not generic or container type.
#[doc(alias = "BMM_SIMPLE_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmSimpleType {
    // inherited: BMM_MODEL_TYPE
    /// The `value_constraint` attribute of openEHR `BMM_MODEL_TYPE` (the vendored BMM carries no documentation for it).
    pub value_constraint: Option<BmmValueSetSpec>,
    /// Defining class of this type.
    pub base_class: BmmSimpleClass,
}
