// @generated by openehr-codegen from BMM (`PROPORTION_KIND`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use crate::data_types::quantity::dv_proportion::DvProportion;
use openehr_derive::OpenEhrType;
use serde::{Deserialize, Serialize};

/// Class of enumeration constants defining types of proportion for the `DV_PROPORTION` class.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "PROPORTION_KIND")]
pub struct ProportionKindData {}

/// Class of enumeration constants defining types of proportion for the `DV_PROPORTION` class.
/// Polymorphic slot of `PROPORTION_KIND` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProportionKind {
    DvProportion(DvProportion),
    ProportionKind(ProportionKindData),
}
