// @generated by openehr-codegen from BMM (`REFERENCE_RANGE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `REFERENCE_RANGE` spec class, generated from the vendored BMM
//! meta-model.

use crate::data_types::quantity::dv_interval::DvInterval;
use crate::data_types::quantity::dv_ordered::DvOrdered;
use crate::data_types::text::dv_text::DvText;

/// Defines a named range to be associated with any `DV_ORDERED` datum.
///
/// Each such range is particular to the patient and context, e.g. sex, age, and any other factor which affects ranges. May be used to represent normal, therapeutic, dangerous, critical etc ranges.
#[doc(alias = "REFERENCE_RANGE")]
#[derive(Debug, Clone, PartialEq)]
pub struct ReferenceRange {
    /// Term whose value indicates the meaning of this range, e.g.  normal,  critical,  therapeutic  etc.
    pub meaning: DvText,
    /// The data range for this meaning, e.g. critical  etc.
    pub range: DvInterval<DvOrdered>,
}
