// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v1_1/bmm/rm_access` — generated module tree.

pub mod reference_model_access;
pub mod schema_descriptor;

// hand-written modules (spec behaviour), auto-declared:
pub mod error;
pub mod reference_model_access_impl;
pub mod schema_descriptor_impl;
