// @generated by openehr-codegen from BMM (`INTERVAL_EVENT`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `INTERVAL_EVENT` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::common::archetyped::archetyped::Archetyped;
use crate::v1_2::common::archetyped::feeder_audit::FeederAudit;
use crate::v1_2::common::archetyped::link::Link;
use crate::v1_2::data_structures::item_structure::item_structure::ItemStructure;
use crate::v1_2::data_types::quantity::date_time::dv_date_time::DvDateTime;
use crate::v1_2::data_types::quantity::date_time::dv_duration::DvDuration;
use crate::v1_2::data_types::text::dv_coded_text::DvCodedText;
use crate::v1_2::data_types::text::dv_text::DvText;
use openehr_base::v1_3::base_types::identification::uid_based_id::UidBasedId;

/// Defines a single interval event in a series.
#[doc(alias = "INTERVAL_EVENT")]
#[derive(Debug, Clone, PartialEq)]
pub struct IntervalEvent<T> {
    // inherited: LOCATABLE
    /// Runtime name of this fragment, used to build runtime paths.
    ///
    /// This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
    pub name: DvText,
    /// Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths.
    ///
    /// Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
    ///
    /// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
    pub archetype_node_id: String,
    /// Optional globally unique object identifier for root points of archetyped structures.
    pub uid: Option<UidBasedId>,
    /// Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
    pub links: Option<openehr_base::containers::NonEmptyVec<Link>>,
    /// Details of archetyping used on this node.
    pub archetype_details: Option<Archetyped>,
    /// Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
    pub feeder_audit: Option<FeederAudit>,

    // inherited: EVENT
    /// Time of this event. If the width is non-zero, it is the time point of the trailing edge of the event.
    pub time: DvDateTime,
    /// Optional state data for this event.
    pub state: Option<ItemStructure>,
    /// The data of this event.
    pub data: T,
    /// Duration of the time interval during which the values recorded under `data` are true and, if set, the values recorded under `state` are true. Void if an instantaneous event.
    pub width: DvDuration,
    /// Optional count of original samples to which this event corresponds.
    pub sample_count: Option<i32>,
    /// Mathematical function of the data of this event, e.g.  maximum, mean etc. Coded using <https://github.com/openEHR/terminology/blob/master/openEHR_RM/en/openehr_terminology.xml>\[openEHR vocabulary `event math function`\]. Default value `640|actual|`, meaning 'actual value'.
    pub math_function: DvCodedText,
}
