// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_2/data_structures/history` — generated module tree.

pub mod event;
pub mod history;
pub mod interval_event;
pub mod point_event;

// hand-written modules (spec behaviour), auto-declared:
pub mod event_impl;
pub mod history_impl;
pub mod interval_event_impl;
pub mod point_event_impl;
