= Types

== Overview

One of the foundational distinctions in the BMM is between _class_ and _type_, in common with the type systems of the modern forms of most object-oriented languages, but in contrast to the UML meta-model. This division is reflected in the two top-level meta-classes `BMM_CLASS` and `BMM_TYPE`, and their respective descendants, as shown in the following UML diagram.

[.text-center]
.`base.bmm.core.entity` Package - Types
image::{uml_diagrams_uri}/LANG-bmm3.core.entity.svg[id=core_entity, align="center"]

Classes are _definitional_ entities, while types are understood in BMM as the _formal generators_ of instances (where non-abstract). Types are the the basis of static typing in a formal model, and dynamic conformance at execution time, when polymorphic attachment is possible. Most types are specified via the definitions of classes and their constituent parts within a 'model'. Types are used for the following purposes in a BMM model:

* to define the _types of properties_;
* to defined the _types of routine parameters and return values_;
* to define _formal type parameters_ in a generic class;
* to define type(s) of _inheritance ancestors of class definitions_;
* to formalise concepts relating to functional programming, including _tuples_ and routine _signatures_;
* to determine _conformance_, which is a relation between types (not classes).

A simple example of typing of properties is shown in the instance diagram below.

[.text-center]
.BMM Typing
image::{diagrams_uri}/bmm_entities.svg[id=bmm_entities, align="center"]

Most types are based on one or more _defining_ class(es), which provide the formal definition for the type. The exceptions are formal generic parameters (e.g. the `T` in `List<T>`) and the special built-in types for tuples and routine signatures. The BMM meta-type `BMM_TYPE` and its descendants define the kinds of types available in a BMM model. The design of the types part of the BMM is based on a taxonomy that makes various distinctions convenient to a formalism intended for modelling rather than pure programming. This leads in particular to the top-level distinction between _unitary_ and _container_ meta-types. The taxonomy is illustrated below, including differentiae.

[.text-center]
.BMM meta-type taxonomy
image::{diagrams_uri}/bmm_metatype_taxonomy.svg[id=bmm_metatype_taxonomy, align="center"]

`BMM_TYPE` includes features common to all meta-types:

* `_is_abstract_`: indicates a type based on an abstract class - i.e. one that cannot be directly instantiated;
* `_is_primitive_`: indicates that a type is derived from a primitive class; primitive status has no effect on BMM model semantics, and is provided as a convenience for visualisation and type-system mapping;
* `_type_name_`: the effective type name of an entity; for simple classes, this will just be the class name (`BMM_CLASS._name_`); for generic and container classes it will be generic name such as `List<T>`, `Interval<T>` etc; for feature types it will be the declared type, i.e. a simple name, an open type name (e.g. `T`) or a generic type name (e.g. `Interval<Time>`);
* `_type_signature_`: a form of the type name that can be used as a fully-defined type signature, which for generic classes includes generic constrainer types, giving a signature such as `Interval<T:Ordered>`.

Below `BMM_TYPE` are the abstract meta-type `BMM_UNITARY_TYPE` and the concrete meta-type `BMM_CONTAINER_TYPE` and its specialisation `BMM_INDEXED_CONTAINER_TYPE`. `BMM_UNITARY_TYPE` is a meta-type for types whose _instances are unitary_ i.e. singular, while the container meta-types correspond to _collections of instances_. The latter are further described below. This distinction is made to enable BMM to directly represent the notion of collections in the type system rather than treating them in the same way as any other type, which would force modellers (i.e. authors of actual BMM models) to state concrete containment types such as `ArrayedList<Packet>`, where `ArrayedList` would have to be defined in the model as well as `Packet`. 

Unitary meta-types are further distinguished as formal generic parameters (`BMM_PARAMETER TYPE`) and _effective_ types, i.e. concrete unitary types. The former meta-type is used to represent replaceable formal generic parameters (typically 'T', 'U' within types such as `List<T>` etc) within generic type declarations.

Effective types have as their meta-type `BMM_EFFECTIVE_TYPE`. Its subtypes are `BMM_MODEL_TYPE`, a meta-type for types defined by classes in the model (thus characterised by the property `_base_class_: BMM_CLASS`), `BMM_TUPLE_TYPE`, a meta-type for tuples (a list of objects of varying types), and `BMM_SIGNATURE`, a meta-type representing signatures of routines and typed model elements (properties, variables etc).

`BMM_MODEL_TYPE` divides into `BMM_SIMPLE_TYPE` and `BMM_GENERIC_TYPE`, corresponding to the standard notions of types familiar in modern programming languages. The class definitions of instances (i.e. BMM model class definitions) of these meta-types are available via the property `_base_class_`, of meta-type `BMM_CLASS` for a BMM simple type, and `BMM_GENERIC_CLASS` for BMM generic type.

These various concrete meta-types are described in more detail below.

== Simple Type

A _simple type_ is a type based only on a _simple class_, which is a class with no formal generic parameters. An instance of a simple type is fully described by the class on which it is based, with the only difference being the usual object-oriented possibility of polymorphic attachments of sub-objects whose dynamic types conform to their static type counterparts in the original simple type. Thus, for example, a class `Organisation` may have a property `_manager_` of static type `Employee`. An instance of the simple type `Organisation` might have its `_manager_` property attached to an instance of `Manager`, which is legal as long as `Manager` conforms to `Employee`, which it will do if `Manager` is defined as a subtype of `Employee`.

=== Conformance

Conformance of Simple types follows the inheritance hierarchy via which they are defined, according to the rules:

* _meta-rule_: A Simple type can only conform to a Model type, i.e. either another Simple type or a Generic type;
* _concrete rule_: A Simple type A conforms to Simple type B iff for `_base_class_` of A, `_all_ancestors()_` contains B.

== Generic Type

A _generic type_ is a type based on a _generic class_, which has one or more formal type parameters that are substituted by actual types in its declaration. For example, the generic type `Interval<Quantity>` can be used in a model that contains the generic class `Interval<T:Ordered>` and `Quantity`. The general case is that the generic parameter substitution type (`BMM_GENERIC_TYPE._generic_parameters_`) for any formal parameter (`BMM_GENERIC_CLASS._generic_parameters_`) is of meta-type `BMM_UNITARY_TYPE`.

A typical programmatic usage of such a type, and its instantiated BMM model structure is shown below.

[.text-center]
.Generic type - closed simple
image::{diagrams_uri}/bmm_structure-generic_1.svg[id=bmm_structure_generic_1, align="center"]

The parameters of a generic type may be:

* a substitution of a formal parameter from the generic class with a concrete type, including other generic types and container types;
* an unsubstituted formal parameter, if used as the type of a feature, routine argument etc, whose context has an open generic type to which this parameter conforms.

Consequently, a generic type may be:

* _closed_: all formal parameters substituted e.g. `Interval<Quantity>`;
* _partially closed_: at least one formal parameter is substituted e.g. `Document<ClinicalContent, U>`;
* _open_: no formal parameters substituted, e.g. `Document<T, U>`.

The first case is detected via the function `_is_closed_` defined on `BMM_GENERIC_TYPE`, while the function `_is_partially_closed_` distinguishes the latter two cases. 

The following shows the BMM instance structure of a generic type that is open.

[.text-center]
.Generic type - open
image::{diagrams_uri}/bmm_structure-generic_3.svg[id=bmm_structure_generic_3, align="center"]

Since the meta-type of `BMM_GENERIC_TYPE._generic_parameters_` in the BMM is `BMM_UNITARY_TYPE`, constructions such as `MyGenericType<List<OtherType>>` are prevented, due to the concrete parameter type `List<OtherType>` being an instance of `BMM_CONTAINER_TYPE` rather than of `BMM_UNITARY_TYPE`. Such constructions are nearly always wrong, and not needed in a model expressed in BMM, because containment can be expressed _where the formal generic parameter is used_, not where the concrete parameter is declared. The following diagram shows the BMM concrete model structure created for a generic type whose formal parameter type is used in this way, i.e. within a container type.

[.text-center]
.Generic type - closed container
image::{diagrams_uri}/bmm_structure-generic_2.svg[id=bmm_structure_generic_2, align="center"]

=== Conformance

Conformance of Generic types is according to the rules:

* _meta-rule_: A Generic type can only conform to another Generic type;
* _concrete rules_: A Generic type `Ga<Ta~i~, ...>` conforms to Generic type `Gb<Tb~i~, ...>` iff:
** for `_base_class_` of `Ga`, `_all_ancestors()_` contains Gb; and
** the number of generic parameters is equal;
** for each `Ta~i~`, either
*** `Tb~i~` is an open formal parameter, and `Tai` conforms to any generic constraint type, or;
*** `Ta~i~` conforms to `Tb~i~`.

== Container Meta-types

In object-oriented type theory, 'container' types are generic types whose outer class happens to have the semantics of a container object, such as a list, set etc. Container types such as `List<T>`, `Set<T>` and `Hash<K,V>` are used ubiquitously in object models. In the BMM, containers and non-container generic types are distinguished via the meta-classes `BMM_CONTAINER_TYPE` and `BMM_GENERIC_TYPE` respectively. This allows the BMM to treat container types in a special way. A `BMM_CONTAINER_TYPE` can be thought of as a 1:N counterpart to a `BMM_UNITARY_TYPE`, such as the type `List<Paragraph>` with respect to `Paragraph`. `BMM_GENERIC_TYPE` is thus used for objects considered to be singular, but whose types are a product of the base class and one or more parameter types, e.g. `Interval<Quantity>`. 

The explicit provision of `BMM_CONTAINER_TYPE` enables BMM models to mention logical linear container types such as `List<T>` and `Set<T>`, on the assumption of their standard semantics in computer science , without worrying about providing concrete types which may be numerous and also variable across programming languages, e.g. `ArrayedList<T>`, `LinkedSet<T>`, `ArrayedStack<T>` and so on.

List and Set semantics are achieved via the `BMM_CONTAINER_TYPE` attributes `_is_ordered_` and `_is_unique_`, used in the standard combinations i.e.:

* `_is_ordered_ and not _is_unique_`: `List<T>`;
* `_is_unique_`: `Set<T>` (ordered or not);
* `not _is_ordered_ and not _is_unique_`: `Bag<T>`.

The following diagram shows how the container type `List<Paragraph>`, declared as the type of an attribute `_paragraphs_` in a class `Document`, is represented in a BMM model.

[.text-center]
.Container Type
image::{diagrams_uri}/bmm_structure-container.svg[id=bmm_structure_container, align="center"]

The semantics of indexed containers, commonly known under the type names `Hash<K,V>`, `HashMap<K,V>`, `HashTable<K,V>`, `Dictionary<K,V>` and so on, are represented by the meta-type `BMM_INDEXED_CONTAINER_TYPE`, which inherits from `BMM_CONTAINER_TYPE`, and adds the property `_index_type_`. The latter type represents the key type, which must be such that hash values can be generated, and may be any type, but practically speaking, is almost always a `String`, `Integer`, or a Date/Time type.

The following diagram shows how the container type `Hash<String, Person>` is represented in a BMM model.

[.text-center]
.Indexed Container Type
image::{diagrams_uri}/bmm_structure-indexed_container.svg[id=bmm_structure_indexed_container, align="center"]

=== Conformance

Conformance of Container types is according to the rules:

* _meta-rule_: A Container type can only conform to another Container type;
* _concrete rules_: 
** A Container type `C~a~<V~a~>` conforms to Container type `C~b~<V~b~>` conforms to iff:
*** for `_base_class_` of `C~a~`, `_all_ancestors()_` contains `C~b~`; and `V~a~` conforms to `V~b~`.
** An indexed Container type `C~a~<K~a~, V~a~>` conforms to indexed Container type `G~b~<K~b~, V~b~>` iff:
*** for `_base_class_` of `C~a~`, `_all_ancestors()_` contains `C~b~`; `K~b~` conforms to `K~b~` and `V~a~` conforms to `V~b~`.

== Bult-in Meta-types

BMM includes a small number of built-in meta-types that do not have corresponding model-source classes. These are shown in the following UML and described in the following sub-sections.

[.text-center]
.Built-in meta-types
image::{uml_diagrams_uri}/LANG-bmm3.core.entity-builtin.svg[id=core_entity_builtin, align="center"]

=== Tuple Meta-type

The meta-type `BMM_TUPLE_TYPE` enables the _type_ of a tuple i.e. an array of objects each of which may be of any type, to be stated in terms of other types. This is mostly used to state the type of a set of arguments in the `BMM_SIGNATURE` class, but standalone tuple types may also be used in a model, providing roughly the effect of an anonymous class (or a `struct` in C/C++).The notional type `Tuple` defined by `BMM_TUPLE_TYPE` is treadted as a BMM built-in, and is therefore not stated in any BMM model.

==== Conformance

Conformance of Tuple types is according to the rules:

* _meta-rule_: A Tuple type can only conform to another Tuple type;
* _concrete rules_: A Tuple type `Tuple[Ta~i~, ...]` conforms to Tuple type `Tuple[Tb~i~, ...]` iff:
** for each `Ta~i~`, `Ta~i~` conforms to `Tb~i~`.

The practical effect of this is that longer tuples may conform to shorter tuples. For example, the tuple type `[Document, String, Integer]` conforms to the tuple type `[Document]`.

=== Signature Meta-type

Within any typed formalism, any entity declared as having a type also has a _signature_. In BMM, this is is the case for any kind of feature of a class, including constants, properties, and routines. The signature of a feature is a formal construct capturing the type structure of the feature. The simplest type of signature is that of properties and constants, which may be expressed formally in a typical abstract syntax as follows:

----
    T_result
----

This indicates that both have a return type, being the type of the value they are attached to at execution time.

The general form of routine signatures is as follows:

----
    Function <[T_arg1, T_arg2, ...], T_result>    -- Function type
    Procedure <[T_arg1, T_arg2, ...]>             -- Procedure type
----

In the above, the construction `[Type, ...]` represents a type-tuple. Strictly speaking, the 'Function' and 'Procedure' are unnecessary, since they can be inferred from just the pure signature. However, for readability they are recommended.

Typical examples of function signatures are as follows:

----
    Function <[], Date>                          -- a 0-order function like current_date
    Function <[Real, Real], Real>                -- a 2nd-order function like '*' for the domain R
    Function <[Integer, Integer], Integer>       -- a 2nd-order function like 'add' for the domain I
----

Typical procedure signatures include the following:

----
    Procedure <[]>                               -- a 0-order (argumentless) procedure
    Procedure <[Real]>                           -- a 1st-order procedure for the domain R
    Procedure <[String, Integer]>                -- a procedure taking a String and an Integer argument
----

In order to support functional semantics such as function-as-object, the notion of signature is defined in BMM as a first order meta-type, `BMM_SIGNATURE` and descendants. Instances of `BMM_SIGNATURE` represent any kind of signature and reference the meta-type of the evaluated form via `_result_type_`, which may be of any BMM meta-type.

`BMM_ROUTINE_TYPE` is the meta-type of any kind of agent (i.e. lambda) and provides `_argument_types_`, whose meta-type is `BMM_TUPLE_TYPE` (See <<Tuple Type>>). The descendant `BMM_PROCEDURE_TYPE` specialises the return type to the built-in type `BMM_STATUS_TYPE` (see below), used to represent the status of a procedure call.

The following signatures state the types 'any function' and 'any procedure':

----
    Function <>                                  -- any function
    Procedure <>                                 -- any procedure
----

As for the Tuple meta-type, the notional `Signature` meta-type is a BMM built-in, and is not itself defined in any BMM model.

==== Conformance

Conformance of Signature types is as follows:

* _meta-rule_: A Signature type can only conform to another Signature type;
* _concrete rules_: 
** all specific Function signatures conform to the signature `Function`;
** all specific Procedure signatures conform to the signature `Procedure`;
** the conformance of specific Function or Procedure signatures to another Function or Procedure signature is such that:
*** the number of argument types accord and;
*** the type conformance of each corresponding argument and result type (for functions) follows the rules for conformance given by the meta-types of those types.

=== Status Meta-type

The meta-type `BMM_STATUS_TYPE` is provided to represent the return type of procedure calls, i.e. of which the pure formal type is often denoted `Void` or `None` in programming languages. Using a special return type simplifies the meta-model of routines, since without it, procedures create an anomaly within a system in which all other class features have a result type. Within BMM, procedures are considered to be _state-changing actions_, and the Status return type enables call and/or execution status information to be returned. Usually this can be ignored, and procedures can be called without assignment. This approach is similar to that of Haskell, in which procedure calls return the 'unit' type.

== Type Conformance

An algorithm to determine conformance of two type-names (e.g. to implement `BMM_MODEL._type_conforms_to()_`) is as follows:

[source,java]
--------
Boolean type_conforms_to (String a_type, anc_type)
{
    BMM_TYPE_NAME a_type_name, anc_type_name;

    if attached create_type_name_from_string (a_a_type) as a_type_name and
        attached create_type_name_from_string (anc_type) as anc_type_name
    {
        base_class = a_type_name.name;
        anc_base_class = anc_type_name.name;
        
        if (base_class.is_case_insensitive_equal (anc_base_class) or else 
            class_definition (base_class).has_ancestor_class (anc_base_class)) 
        {
            BMM_CLASS bmm_def_class = class_definition (base_class);
            
            // ---- Tuple types
            
            // ---- Signature types ----
            
            // ---- Generic types
            // handle case where formal generic names appear in type name
            if (valid_generic_type_name (a_type) and bmm_def_class instanceOf (BMM_GENERIC_CLASS) {

                // in the case of both being generic, we need to compare generics
                // to start with, the number of generics must match
                BMM_CLASS anc_bmm_def_class = class_definition (anc_base_class);
                if (valid_generic_type_name (anc_type) and anc_bmm_def_class instanceOf (BMM_GENERIC_CLASS)) {
                    ArrayedList<String> a_type_gen_params = a_type_name.generic_parameters_type_list;
                    ArrayedList<String> anc_type_gen_params = anc_type_name.generic_parameters_type_list;
                    
                    if (a_type_gen_params.count = anc_type_gen_params.count) {
                    
                        Iterator<String> this_gen_parms_it = a_type_gen_params.iterator();
                        Iterator<String> other_gen_parms_it = anc_type_gen_params.iterator();

                        Boolean result = True;
                        String a_type_gen_type, anc_type_gen_type;
                        
                        while (this_gen_parms_it.hasNext() && other_gen_parms_it.hasNext() || !result) {
                            // first we convert any open generic parameters to their conformance types
                            // We assume type names of 1 letter are open parameters
                            String this_gen_parm = this_gen_parms_it.next();
                            String other_gen_parm = other_gen_parms_it.next();
                            if (formal_generic_parameter_name (this_gen_parm))
                                a_type_gen_type = this_bmm_gen_class.generic_parameter_conformance_type (this_gen_parm);
                            else
                                a_type_gen_type = this_gen_parm;
    
                            if (formal_generic_parameter_name (other_gen_parm))
                                anc_type_gen_type = other_bmm_gen_class.generic_parameter_conformance_type (other_gen_parm);
                            else
                                anc_type_gen_type = other_gen_parm;

                            -- now do the test
                            result = type_conforms_to (a_type_gen_type, anc_type_gen_type);
                        }
                        
                        return result;
                    }

                }
                // Conforms - case where anc type is not provided in generic form, but desc is
                // e.g. Interval<Integer> conforms to Interval
                else
                    return True;
            }
            // in the following case, the descendant type is not generic, 
            // so the ancestor type cannot be either, for conformance
            else
                return not valid_generic_type_name (anc_type);
        }
    }
}

--------

== Model Theoretic Questions

The above model produces a number of outcomes that are not necessarily immediately obvious or expected, including:

* Inheritance is from classes to types rather than classes;
* A Generic type parameter can only be a unitary type, i.e. not a container type;
* Tuple and Signature types are pure types, i.e. not defined in generating model other than by implication due to use as routine argument lists;
* In theory, a Signature type could be a `BMM_GENERIC_TYPE` descendant but the specialisation restriction would make the meta-model more complex for no obvious benefit.

== Class Definitions

include::{uml_export_dir}/classes/{pkg}bmm_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_unitary_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_effective_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_parameter_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_model_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_simple_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_generic_type.adoc[]

include::{uml_export_dir}/classes/{pkg}bmm_builtin_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_tuple_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_signature.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_property_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_routine_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_function_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_procedure_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_status_type.adoc[]

include::{uml_export_dir}/classes/{pkg}bmm_container_type.adoc[]
include::{uml_export_dir}/classes/{pkg}bmm_indexed_container_type.adoc[]

