// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-License-Identifier: MIT

//! The `SAMPLE<T>` hierarchy (`sample.adoc`, `data_frame_sample.adoc`,
//! `openehr_sample.adoc`, `hl7v2_sample.adoc`, `hl7_fhir_sample.adoc`,
//! `variable_sample.adoc`).

#![expect(
    clippy::disallowed_types,
    reason = "owner-approved 2026-08-03 (#1694 family 6): FHIR resources are an external standard \
              with no RM type (typed-FHIR evaluation tracked separately)"
)]

use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::value::VariableValue;

/// `SAMPLE<T>` — "One retrieval (sample) of a data 'block', generated by
/// invocation of some retrieval method … encompasses retrieval (attempt)
/// time-stamp, availability status, and result, if available.
///
/// **Every retrieval attempt will generate a new Sample object, regardless of
/// whether data was actually available or not**" (`sample.adoc`).
///
/// Generic over the payload `T`, exactly as the spec's `SAMPLE<T>`:
/// [`DataFrameSample`] is `Sample<FramePayload>` and [`VariableSample`] is
/// `Sample<VariableValue>`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sample<T> {
    /// `retrieve_time [1]` — time the retrieve attempt was made (ISO-8601).
    pub retrieve_time: String,
    /// `effective_time [0..1]` — real-world time the data pertains to, if
    /// available; "comparable to `currency` in order to determine the
    /// freshness of the data" (master10 §Samples).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_time: Option<String>,
    /// `is_unavailable [1]` — true if no data was available for this attempt.
    pub is_unavailable: bool,
    /// `unavailable_reason [0..1]` — reason for absent data, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unavailable_reason: Option<String>,
    /// `result: T [0..1]` — result of the retrieve call, if available.
    #[serde(default = "Option::default", skip_serializing_if = "Option::is_none")]
    pub result: Option<T>,
}

impl<T> Sample<T> {
    /// An available sample carrying `result`, stamped `retrieve_time = now`.
    #[must_use]
    pub fn available(result: T) -> Self {
        Self {
            retrieve_time: now_iso(),
            effective_time: None,
            is_unavailable: false,
            unavailable_reason: None,
            result: Some(result),
        }
    }

    /// An unavailable sample (`is_unavailable = true`) with a reason.
    #[must_use]
    pub fn unavailable(reason: impl Into<String>) -> Self {
        Self {
            retrieve_time: now_iso(),
            effective_time: None,
            is_unavailable: true,
            unavailable_reason: Some(reason.into()),
            result: None,
        }
    }

    /// Set `effective_time` — the real-world time the data pertains to.
    #[must_use]
    pub fn with_effective_time(mut self, effective_time: impl Into<String>) -> Self {
        self.effective_time = Some(effective_time.into());
        self
    }
}

/// The payload of a [`DataFrameSample`]: the closed set of the three concrete
/// `DATA_FRAME_SAMPLE` descendants the spec defines (`openehr_sample.adoc` /
/// `hl7v2_sample.adoc` / `hl7_fhir_sample.adoc`).
///
/// Modelling the descendants as an enum variant on the payload is the
/// codegen's closed-subtype treatment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "_type")]
pub enum FramePayload {
    /// `OPENEHR_SAMPLE` — "openEHR sample whose result is in the form of a
    /// `RESULT_SET` structure" (`openehr_sample.adoc`). Carries the ITS-REST
    /// 1.0.3 `RESULT_SET` canonical JSON the Query service returned.
    #[serde(rename = "OPENEHR_SAMPLE")]
    Openehr {
        /// The `RESULT_SET` (canonical JSON).
        result_set: Value,
    },
    /// `HL7v2_SAMPLE` — "Container for `HL7v2` message based data frame results"
    /// (`hl7v2_sample.adoc`). A typed seam: no `HL7v2` transport exists, so this
    /// is never produced (see `DataBinding::get_frame`).
    #[serde(rename = "HL7v2_SAMPLE")]
    Hl7v2 {
        /// The raw `HL7v2` message text.
        message: String,
    },
    /// `HL7_FHIR_SAMPLE` — "Container for HL7 FHIR based data frame results"
    /// (`hl7_fhir_sample.adoc`). Carries the FHIR resource (or Bundle) JSON
    /// retrieved by the FHIR frame executor.
    #[serde(rename = "HL7_FHIR_SAMPLE")]
    Hl7Fhir {
        /// The FHIR resource (canonical JSON).
        resource: Value,
    },
}

/// `DATA_FRAME_SAMPLE<T>` — a `SAMPLE` carrying a back-end retrieval result.
///
/// "Abstract class with methods for extracting single variable values from data
/// frames" (`data_frame_sample.adoc`); the payload is the retrieval result
/// ([`FramePayload`]).
pub type DataFrameSample = Sample<FramePayload>;

/// `VARIABLE_SAMPLE` — "Sample whose result is in the form of a `VARIABLE_VALUE`
/// (descendant) structure" (`variable_sample.adoc`).
pub type VariableSample = Sample<VariableValue>;

/// The current time as an ISO-8601 string (`SAMPLE.retrieve_time`).
fn now_iso() -> String {
    jiff::Timestamp::now().to_string()
}
