// @generated by openehr-codegen from BMM (`BMM_MODEL_ELEMENT`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::bmm3::core::entity::bmm_class::BmmClass;
use crate::bmm3::core::entity::bmm_container_type::BmmContainerType;
use crate::bmm3::core::entity::bmm_function_type::BmmFunctionType;
use crate::bmm3::core::entity::bmm_generic_class::BmmGenericClass;
use crate::bmm3::core::entity::bmm_generic_type::BmmGenericType;
use crate::bmm3::core::entity::bmm_indexed_container_type::BmmIndexedContainerType;
use crate::bmm3::core::entity::bmm_parameter_type::BmmParameterType;
use crate::bmm3::core::entity::bmm_procedure_type::BmmProcedureType;
use crate::bmm3::core::entity::bmm_property_type::BmmPropertyType;
use crate::bmm3::core::entity::bmm_routine_type::BmmRoutineType;
use crate::bmm3::core::entity::bmm_signature::BmmSignature;
use crate::bmm3::core::entity::bmm_simple_class::BmmSimpleClass;
use crate::bmm3::core::entity::bmm_simple_type::BmmSimpleType;
use crate::bmm3::core::entity::bmm_status_type::BmmStatusType;
use crate::bmm3::core::entity::bmm_tuple_type::BmmTupleType;
use crate::bmm3::core::entity::bmm_type::BmmType;
use crate::bmm3::core::entity::range_constrained::bmm_enumeration::BmmEnumeration;
use crate::bmm3::core::entity::range_constrained::bmm_enumeration_integer::BmmEnumerationInteger;
use crate::bmm3::core::entity::range_constrained::bmm_enumeration_string::BmmEnumerationString;
use crate::bmm3::core::feature::bmm_constant::BmmConstant;
use crate::bmm3::core::feature::bmm_container_property::BmmContainerProperty;
use crate::bmm3::core::feature::bmm_function::BmmFunction;
use crate::bmm3::core::feature::bmm_indexed_container_property::BmmIndexedContainerProperty;
use crate::bmm3::core::feature::bmm_local::BmmLocal;
use crate::bmm3::core::feature::bmm_parameter::BmmParameter;
use crate::bmm3::core::feature::bmm_procedure::BmmProcedure;
use crate::bmm3::core::feature::bmm_property::BmmProperty;
use crate::bmm3::core::feature::bmm_result::BmmResult;
use crate::bmm3::core::feature::bmm_self::BmmSelf;
use crate::bmm3::core::feature::bmm_singleton::BmmSingleton;
use crate::bmm3::core::feature::bmm_unitary_property::BmmUnitaryProperty;
use crate::bmm3::core::model::bmm_model::BmmModel;
use crate::bmm3::core::model::bmm_package::BmmPackage;
use crate::bmm3::core::model::bmm_package_container::BmmPackageContainer;
use crate::bmm::core::bmm_generic_parameter::BmmGenericParameter;
use crate::bmm::core::bmm_open_type::BmmOpenType;

/// Ancestor class of most BMM model elements.
/// Closed subtype set of `BMM_MODEL_ELEMENT` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BmmModelElement {
    BmmClass(BmmClass),
    BmmConstant(BmmConstant),
    BmmContainerProperty(BmmContainerProperty),
    BmmContainerType(BmmContainerType),
    BmmEnumeration(BmmEnumeration),
    BmmEnumerationInteger(BmmEnumerationInteger),
    BmmEnumerationString(BmmEnumerationString),
    BmmFunction(BmmFunction),
    BmmFunctionType(BmmFunctionType),
    BmmGenericClass(BmmGenericClass),
    BmmGenericParameter(BmmGenericParameter),
    BmmGenericType(BmmGenericType),
    BmmIndexedContainerProperty(BmmIndexedContainerProperty),
    BmmIndexedContainerType(BmmIndexedContainerType),
    BmmLocal(BmmLocal),
    BmmModel(BmmModel),
    BmmOpenType(BmmOpenType),
    BmmPackage(BmmPackage),
    BmmPackageContainer(BmmPackageContainer),
    BmmParameter(BmmParameter),
    BmmParameterType(BmmParameterType),
    BmmProcedure(BmmProcedure),
    BmmProcedureType(BmmProcedureType),
    BmmProperty(BmmProperty<BmmType>),
    BmmPropertyType(BmmPropertyType),
    BmmResult(BmmResult),
    BmmRoutineType(BmmRoutineType),
    BmmSelf(BmmSelf),
    BmmSignature(BmmSignature),
    BmmSimpleClass(BmmSimpleClass),
    BmmSimpleType(BmmSimpleType),
    BmmSingleton(BmmSingleton),
    BmmStatusType(BmmStatusType),
    BmmTupleType(BmmTupleType),
    BmmUnitaryProperty(BmmUnitaryProperty),
}
