// @generated by openehr-codegen from BMM (`DV_TIME_SPECIFICATION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `DV_TIME_SPECIFICATION` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::data_types::time_specification::dv_general_time_specification::DvGeneralTimeSpecification;
use crate::v1_2::data_types::time_specification::dv_periodic_time_specification::DvPeriodicTimeSpecification;

/// Closed subtype set of `DV_TIME_SPECIFICATION`, dispatched on each payload's `_type`.
///
/// This is an abstract class of which all timing specifications are specialisations. Specifies points in time, possibly linked to the calendar, or a real world repeating event, such as  breakfast.
#[doc(alias = "DV_TIME_SPECIFICATION")]
#[derive(Debug, Clone, PartialEq)]
pub enum DvTimeSpecification {
    /// The `DV_GENERAL_TIME_SPECIFICATION` subtype of `DV_TIME_SPECIFICATION`.
    DvGeneralTimeSpecification(DvGeneralTimeSpecification),
    /// The `DV_PERIODIC_TIME_SPECIFICATION` subtype of `DV_TIME_SPECIFICATION`.
    DvPeriodicTimeSpecification(DvPeriodicTimeSpecification),
}
