// @generated by openehr-codegen from BMM (`SYNC_EXTRACT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `SYNC_EXTRACT` spec class, generated from the vendored BMM
//! meta-model.

use crate::ehr_extract::sync_extract::sync_extract_spec::SyncExtractSpec;
use crate::ehr_extract::sync_extract::x_contribution::XContribution;

/// The openEHR `SYNC_EXTRACT` class (the vendored BMM carries no documentation for it).
#[doc(alias = "SYNC_EXTRACT")]
#[derive(Debug, Clone, PartialEq)]
pub struct SyncExtract {
    /// Details of specification of this Extract.
    pub specification: SyncExtractSpec,
    /// Content, in the form of a serialised Contributions.
    pub items: Vec<XContribution>,
}
