// @generated by openehr-codegen from BMM (`X_CONTRIBUTION`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::common::change_control::version::Version;
use crate::common::generic::audit_details::AuditDetails;
use openehr_base::prelude::HierObjectId;

/// Serialised form of Contribution for an Extract.
#[derive(Debug, Clone, PartialEq)]
pub struct XContribution {
    /// Uid of Contribution in source system.
    pub uid: HierObjectId,
    /// Audit of Contribution in source system.
    pub audit: AuditDetails,
    /// Serialised Versions from Contribution in source system.
    pub versions: Vec<Version<XContribution>>,
}
