// @generated by openehr-codegen from BMM (`Iso8601_type`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `Iso8601_type` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::foundation_types::time::iso8601_date::Iso8601Date;
use crate::v1_1::foundation_types::time::iso8601_date_time::Iso8601DateTime;
use crate::v1_1::foundation_types::time::iso8601_duration::Iso8601Duration;
use crate::v1_1::foundation_types::time::iso8601_time::Iso8601Time;
use openehr_base::v1_2::foundation_types::time::iso8601_timezone::Iso8601Timezone;

/// Closed subtype set of `Iso8601_type`, dispatched on each payload's `_type`.
///
/// Abstract ancestor type of ISO 8601 types, defining interface for 'extended' and 'partial' concepts from ISO 8601.
#[doc(alias = "Iso8601_type")]
#[derive(Debug, Clone, PartialEq)]
pub enum Iso8601Type {
    /// The `Iso8601_date` subtype of `Iso8601_type`.
    Iso8601Date(Iso8601Date),
    /// The `Iso8601_date_time` subtype of `Iso8601_type`.
    Iso8601DateTime(Iso8601DateTime),
    /// The `Iso8601_duration` subtype of `Iso8601_type`.
    Iso8601Duration(Iso8601Duration),
    /// The `Iso8601_time` subtype of `Iso8601_type`.
    Iso8601Time(Iso8601Time),
    /// The `Iso8601_timezone` subtype of `Iso8601_type`.
    Iso8601Timezone(Iso8601Timezone),
}
