// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_1/foundation_types/time` — generated module tree.

pub mod iso8601_date;
pub mod iso8601_date_time;
pub mod iso8601_duration;
pub mod iso8601_time;
pub mod iso8601_type;
