// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v2_4/bmm3/model_access` — generated module tree.

pub mod bmm_model_access;
pub mod bmm_schema;
pub mod bmm_schema_descriptor;
