// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-License-Identifier: MIT

//! The import write path.
//!
//! Writes `vo_version` rows with an **explicit** `sys_period` — the EHR Extract
//! import (master06 §Copying) and the admin archive load — plus the lineage
//! close and container-state read the import policy needs.
//!
//! No openEHR spec governs the SQL — our own design. The import *policy* (period-chain synthesis, Case 2/3
//! classification) lives in the versioning layer.

#![expect(
    clippy::disallowed_types,
    reason = "owner-approved 2026-08-03 (#1694 family 1): stored canonical fragments — a typed \
              round-trip drops forward-compatible keys (the openEHR release strategy: minors are compatible supersets)"
)]

use serde_json::Value;
use sqlx::{PgConnection, Row};
use uuid::Uuid;

use crate::ids::{EhrId, VoId};
use crate::storage::error::StorageError;
use crate::storage::version_repo::optional_json_array;

/// One `vo_version` row to insert with an **explicit** `sys_period` (`[lower,
/// upper)`, `upper = None` ⇒ still-open) — the import analogue of the local
/// commit row, carrying no `template_id`.
///
/// The import path builds a synthetic strictly-increasing local period chain
/// per lineage (master06 §Copying).
///
/// The row is an `IMPORTED_VERSION`: `contribution_id` / `audit_id` /
/// `signature` are the **local** act of committal and
/// [`ImportedVersionRow::wrapped_original`] carries the wrapped
/// `ORIGINAL_VERSION`'s own provenance (master06 §Committal and Audits).
#[derive(Debug)]
pub struct ImportedVersionRow<'a> {
    /// The versioned object's id.
    pub vo_id: VoId,
    /// The `vo_version.kind` discriminator text.
    pub kind: &'a str,
    /// The owning EHR, or `None` for a demographic versioned object.
    pub ehr_id: Option<EhrId>,
    /// The per-object storage commit ordinal — NOT the wire version number.
    pub sys_version: i32,
    /// `VERSION_TREE_ID` first part.
    pub trunk_version: i32,
    /// `VERSION_TREE_ID` second part; `0` on a trunk row.
    pub branch_number: i32,
    /// `VERSION_TREE_ID` third part; `0` on a trunk row.
    pub branch_version: i32,
    /// The `version_lifecycle_state` numeric code.
    pub lifecycle_state: &'a str,
    /// The version's immutable `creating_system_id`.
    pub creating_system_id: &'a str,
    /// `ORIGINAL_VERSION.preceding_version_uid`; `None` for a first version.
    pub preceding_version_uid: Option<&'a str>,
    /// The merge provenance (`other_input_version_uids`).
    pub other_input_version_uids: &'a [String],
    /// The LOCAL import CONTRIBUTION this version was committed in.
    pub contribution_id: Uuid,
    /// The LOCAL import act's `AUDIT_DETAILS` row.
    pub audit_id: Uuid,
    /// The `IMPORTED_VERSION` wrapper's own `VERSION.signature` (0..1) —
    /// server-generated over the wrapper when signing is on, else `None`.
    pub signature: Option<&'a str>,
    /// The wrapped `ORIGINAL_VERSION`'s own `{contribution, commit_audit,
    /// signature?}` as verbatim canonical openEHR JSON.
    pub wrapped_original: &'a Value,
    /// Lower bound of the synthetic local `sys_period`.
    pub lower: jiff::Timestamp,
    /// Upper bound (`None` = the still-open tip of this lineage).
    pub upper: Option<jiff::Timestamp>,
    /// The assembled canonical body (`vo_version.body`) — the SAME value the
    /// node rows are decomposed from; `None` on a content-less version.
    pub body: Option<&'a Value>,
}

/// Insert one imported `vo_version` row with an explicit `sys_period`
/// (master06 §Copying). Stores `template_id = NULL`.
///
/// # Errors
/// Returns [`StorageError::Database`] on a driver/insert failure.
pub async fn insert_imported_vo_version(
    tx: &mut PgConnection,
    row: &ImportedVersionRow<'_>,
) -> Result<(), StorageError> {
    let other_input = optional_json_array(row.other_input_version_uids);
    // `signature_client_supplied = false`: the stored `signature` is the
    // WRAPPER's, generated by this server over the IMPORTED_VERSION it built
    // ("the IMPORTED_VERSION instance will carry its own signature which
    // signifies the act of importing" — master06 §Digital Signature), so it is
    // ours to re-verify at read. The wrapped original's foreign signature rides
    // `wrapped_original` and is never re-verified.
    sqlx::query(
        "INSERT INTO vo_version \
         (vo_id, kind, ehr_id, sys_version, trunk_version, branch_number, branch_version, \
          sys_period, lifecycle_state, creating_system_id, preceding_version_uid, \
          other_input_version_uids, contribution_id, audit_id, template_id, signature, \
          signature_client_supplied, wrapped_original, body) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, \
                 tstzrange($8::timestamptz, $9::timestamptz, '[)'), \
                 $10, $11, $12, $13, $14, $15, NULL, $16, false, $17, $18)",
    )
    .bind(row.vo_id)
    .bind(row.kind)
    .bind(row.ehr_id)
    .bind(row.sys_version)
    .bind(row.trunk_version)
    .bind(row.branch_number)
    .bind(row.branch_version)
    .bind(row.lower.to_string())
    .bind(row.upper.map(|t| t.to_string()))
    .bind(row.lifecycle_state)
    .bind(row.creating_system_id)
    .bind(row.preceding_version_uid)
    .bind(other_input)
    .bind(row.contribution_id)
    .bind(row.audit_id)
    .bind(row.signature)
    .bind(row.wrapped_original)
    .bind(
        row.body
            .map(serde_json::to_string)
            .transpose()
            .map_err(StorageError::BodyDecode)?,
    )
    .execute(&mut *tx)
    .await?;
    Ok(())
}

/// One `vo_version` row to re-persist **verbatim** during an archive load.
///
/// The stored columns (`sys_period` bounds as ISO strings, `template_id`,
/// `creating_system_id`) are preserved exactly as dumped (SM `I_ADMIN_DUMP_LOAD`
/// round-trip; no openEHR spec governs the archive). Unlike
/// [`ImportedVersionRow`] it keeps `template_id`, and unlike a local commit row
/// the `sys_period` is explicit.
#[derive(Debug)]
pub struct VerbatimVersionRow<'a> {
    /// The versioned object's id.
    pub vo_id: VoId,
    /// The `vo_version.kind` discriminator text.
    pub kind: &'a str,
    /// The owning EHR, or `None` for the archive's demographic wave (ehr-less
    /// party/relationship containers).
    pub ehr_id: Option<EhrId>,
    /// The per-object storage commit ordinal — NOT the wire version number.
    pub sys_version: i32,
    /// `VERSION_TREE_ID` first part.
    pub trunk_version: i32,
    /// `VERSION_TREE_ID` second part; `0` on a trunk row.
    pub branch_number: i32,
    /// `VERSION_TREE_ID` third part; `0` on a trunk row.
    pub branch_version: i32,
    /// `ORIGINAL_VERSION.preceding_version_uid`; `None` for a first version.
    pub preceding_version_uid: Option<&'a str>,
    /// The merge provenance (`other_input_version_uids`) as stored JSON.
    pub other_input_version_uids: Option<&'a Value>,
    /// Lower/upper `sys_period` bounds as ISO-8601 strings (`upper = None` ⇒
    /// still-open); bound with a `::timestamptz` cast.
    pub sys_period_lower: Option<&'a str>,
    /// Upper `sys_period` bound as an ISO-8601 string; `None` = still-open.
    pub sys_period_upper: Option<&'a str>,
    /// The `version_lifecycle_state` numeric code.
    pub lifecycle_state: &'a str,
    /// The CONTRIBUTION this version was committed in.
    pub contribution_id: Uuid,
    /// This version's own `AUDIT_DETAILS` row.
    pub audit_id: Uuid,
    /// The OPT `template_id` a COMPOSITION was committed against (else `None`).
    pub template_id: Option<&'a str>,
    /// `VERSION.signature` (0..1), opaque radix-64.
    pub signature: Option<&'a str>,
    /// Whether `signature` was client-supplied (foreign — never re-verified at
    /// read; master06 §Digital Signature); preserved verbatim across the
    /// dump/load round-trip.
    pub signature_client_supplied: bool,
    /// The version's immutable `creating_system_id`.
    pub creating_system_id: &'a str,
    /// The wrapped `ORIGINAL_VERSION`'s provenance fragment on an
    /// `IMPORTED_VERSION` row (`None` on a locally created one) — preserved
    /// verbatim across the dump/load round-trip.
    pub wrapped_original: Option<&'a Value>,
    /// The assembled canonical body (`vo_version.body`) — the SAME value the
    /// node rows are re-decomposed from; `None` on a content-less version.
    pub body: Option<&'a Value>,
}

/// Insert one `vo_version` row verbatim from an archive record (explicit
/// `sys_period` + preserved `template_id`) — the load side of the admin
/// dump/load round-trip.
///
/// The node rows are re-decomposed and written by the caller.
///
/// This is the ONE version writer that does not derive the version tree
/// position itself: the two live write paths compute the next
/// `VERSION_TREE_ID` from the container's own tip (a foreign tip forks a
/// branch — RM common `master06-change_control_package.adoc` §Copying
/// §Subsequent Local Modifications), so neither can produce a second TRUNK row
/// at an occupied position. A record replayed from an archive can, since the
/// file is arbitrary input, so the invariant is checked here before the insert
/// and reported as [`StorageError::TrunkPositionInUse`] — the trunk line is one
/// global sequence across creating systems (§Distributed Versioning's 3-part
/// identifier makes BRANCH ids system-local, not trunk positions). The
/// `uq_vo_version_trunk_position` partial unique index is the backstop; this
/// check exists so the failure names the container, the position and the
/// holder instead of surfacing as an opaque constraint violation.
///
/// # Errors
/// Returns [`StorageError::TrunkPositionInUse`] when another creating system
/// already holds this trunk position of the container, or
/// [`StorageError::Database`] on a driver/insert failure.
pub async fn insert_version_verbatim(
    tx: &mut PgConnection,
    row: &VerbatimVersionRow<'_>,
) -> Result<(), StorageError> {
    insert_versions_verbatim(tx, std::slice::from_ref(row)).await
}

/// Insert MANY verbatim `vo_version` rows in ONE statement.
///
/// The archive-load batch (a whole record's versions, never a round trip per
/// version), with the trunk-position invariant of
/// [`insert_version_verbatim`] checked for the whole batch in one probe
/// first.
///
/// The probe checks the batch against PRE-EXISTING rows; a corrupt record
/// that duplicates a trunk position within itself falls to the
/// `uq_vo_version_trunk_position` unique-index backstop instead of the named
/// error.
///
/// # Errors
/// Returns [`StorageError::TrunkPositionInUse`] when another creating system
/// already holds a batch member's trunk position, or
/// [`StorageError::Database`] on a driver/insert failure.
pub async fn insert_versions_verbatim(
    tx: &mut PgConnection,
    rows: &[VerbatimVersionRow<'_>],
) -> Result<(), StorageError> {
    if rows.is_empty() {
        return Ok(());
    }
    refuse_held_trunk_positions(tx, rows).await?;
    let n = rows.len();
    let mut vo_ids: Vec<Uuid> = Vec::with_capacity(n);
    let mut kinds: Vec<&str> = Vec::with_capacity(n);
    let mut ehr_ids: Vec<Option<Uuid>> = Vec::with_capacity(n);
    let mut sys_versions: Vec<i32> = Vec::with_capacity(n);
    let mut trunks: Vec<i32> = Vec::with_capacity(n);
    let mut branch_numbers: Vec<i32> = Vec::with_capacity(n);
    let mut branch_versions: Vec<i32> = Vec::with_capacity(n);
    let mut precedings: Vec<Option<&str>> = Vec::with_capacity(n);
    let mut other_inputs: Vec<Option<&Value>> = Vec::with_capacity(n);
    let mut lowers: Vec<Option<&str>> = Vec::with_capacity(n);
    let mut uppers: Vec<Option<&str>> = Vec::with_capacity(n);
    let mut lifecycles: Vec<&str> = Vec::with_capacity(n);
    let mut contribution_ids: Vec<Uuid> = Vec::with_capacity(n);
    let mut audit_ids: Vec<Uuid> = Vec::with_capacity(n);
    let mut template_ids: Vec<Option<&str>> = Vec::with_capacity(n);
    let mut signatures: Vec<Option<&str>> = Vec::with_capacity(n);
    let mut sig_client: Vec<bool> = Vec::with_capacity(n);
    let mut creating: Vec<&str> = Vec::with_capacity(n);
    let mut wrappeds: Vec<Option<&Value>> = Vec::with_capacity(n);
    let mut bodies: Vec<Option<String>> = Vec::with_capacity(n);
    for r in rows {
        vo_ids.push(r.vo_id.0);
        kinds.push(r.kind);
        ehr_ids.push(r.ehr_id.map(|e| e.0));
        sys_versions.push(r.sys_version);
        trunks.push(r.trunk_version);
        branch_numbers.push(r.branch_number);
        branch_versions.push(r.branch_version);
        precedings.push(r.preceding_version_uid);
        other_inputs.push(r.other_input_version_uids);
        lowers.push(r.sys_period_lower);
        uppers.push(r.sys_period_upper);
        lifecycles.push(r.lifecycle_state);
        contribution_ids.push(r.contribution_id);
        audit_ids.push(r.audit_id);
        template_ids.push(r.template_id);
        signatures.push(r.signature);
        sig_client.push(r.signature_client_supplied);
        creating.push(r.creating_system_id);
        wrappeds.push(r.wrapped_original);
        bodies.push(
            r.body
                .map(serde_json::to_string)
                .transpose()
                .map_err(StorageError::BodyDecode)?,
        );
    }
    sqlx::query(
        "INSERT INTO vo_version (vo_id, kind, ehr_id, sys_version, trunk_version, branch_number, \
         branch_version, preceding_version_uid, other_input_version_uids, sys_period, \
         lifecycle_state, contribution_id, audit_id, template_id, signature, \
         signature_client_supplied, creating_system_id, wrapped_original, body) \
         SELECT t.vo_id, t.kind, t.ehr_id, t.sys_version, t.trunk_version, t.branch_number, \
         t.branch_version, t.preceding_version_uid, t.other_input, \
         tstzrange(t.lower::timestamptz, t.upper::timestamptz, '[)'), t.lifecycle_state, \
         t.contribution_id, t.audit_id, t.template_id, t.signature, t.sig_client, \
         t.creating_system_id, t.wrapped_original, t.body \
         FROM unnest($1::uuid[], $2::text[], $3::uuid[], $4::int[], $5::int[], $6::int[], \
         $7::int[], $8::text[], $9::jsonb[], $10::text[], $11::text[], $12::text[], \
         $13::uuid[], $14::uuid[], $15::text[], $16::text[], $17::bool[], $18::text[], \
         $19::jsonb[], $20::text[]) \
         AS t(vo_id, kind, ehr_id, sys_version, trunk_version, branch_number, branch_version, \
         preceding_version_uid, other_input, lower, upper, lifecycle_state, contribution_id, \
         audit_id, template_id, signature, sig_client, creating_system_id, wrapped_original, \
         body)",
    )
    .bind(vo_ids)
    .bind(kinds)
    .bind(ehr_ids)
    .bind(sys_versions)
    .bind(trunks)
    .bind(branch_numbers)
    .bind(branch_versions)
    .bind(precedings)
    .bind(other_inputs)
    .bind(lowers)
    .bind(uppers)
    .bind(lifecycles)
    .bind(contribution_ids)
    .bind(audit_ids)
    .bind(template_ids)
    .bind(signatures)
    .bind(sig_client)
    .bind(creating)
    .bind(wrappeds)
    .bind(bodies)
    .execute(&mut *tx)
    .await?;
    Ok(())
}

/// Refuse a batch whose trunk rows would land on a trunk position another
/// creating system already holds — the named-error probe of
/// [`insert_versions_verbatim`], run against PRE-EXISTING rows in ONE
/// statement.
async fn refuse_held_trunk_positions(
    tx: &mut PgConnection,
    rows: &[VerbatimVersionRow<'_>],
) -> Result<(), StorageError> {
    let trunk_vos: Vec<Uuid> = rows
        .iter()
        .filter(|r| r.branch_number == 0)
        .map(|r| r.vo_id.0)
        .collect();
    if trunk_vos.is_empty() {
        return Ok(());
    }
    let trunk_positions: Vec<i32> = rows
        .iter()
        .filter(|r| r.branch_number == 0)
        .map(|r| r.trunk_version)
        .collect();
    let clash = sqlx::query(
        "SELECT v.vo_id, v.trunk_version, v.creating_system_id FROM vo_version v \
         JOIN unnest($1::uuid[], $2::int[]) AS q(vo_id, trunk_version) \
         ON q.vo_id = v.vo_id AND q.trunk_version = v.trunk_version \
         WHERE v.branch_number = 0 LIMIT 1",
    )
    .bind(&trunk_vos)
    .bind(&trunk_positions)
    .fetch_optional(&mut *tx)
    .await?;
    if let Some(hit) = clash {
        return Err(StorageError::TrunkPositionInUse {
            vo_id: hit.try_get::<Uuid, _>("vo_id")?,
            trunk_version: hit.try_get("trunk_version")?,
            held_by: hit.try_get("creating_system_id")?,
        });
    }
    Ok(())
}

/// Whether a specific version-tree position is already stored for `vo_id`.
///
/// `creating_system_id = None` matches any creating system — the trunk chain is
/// per versioned object. This is the receiver-side copy-closure probe (RM common
/// master06 §Copying: branch versions "cannot be copied without their
/// corresponding preceding versions on the same branch (if any) and trunk
/// versions also being copied"). Used by the import path to accept a Case-3
/// append whose ancestry arrived in an EARLIER import.
///
/// # Errors
/// The storage read error.
pub async fn has_version_tree(
    tx: &mut PgConnection,
    vo_id: VoId,
    creating_system_id: Option<&str>,
    trunk_version: i32,
    branch_number: i32,
    branch_version: i32,
) -> Result<bool, StorageError> {
    let exists: bool = sqlx::query_scalar(
        "SELECT EXISTS (SELECT 1 FROM vo_version WHERE vo_id = $1 \
         AND ($2::text IS NULL OR creating_system_id = $2) \
         AND trunk_version = $3 \
         AND branch_number = $4 AND branch_version = $5)",
    )
    .bind(vo_id)
    .bind(creating_system_id)
    .bind(trunk_version)
    .bind(branch_number)
    .bind(branch_version)
    .fetch_one(&mut *tx)
    .await?;
    Ok(exists)
}

/// Close the open (`upper_inf`) version of one LINEAGE of `vo_id` at an
/// explicit instant (the import base time).
///
/// The trunk lineage is `branch_number = 0`; a branch lineage is one
/// `(creating_system_id, trunk_version, branch_number)`. Used when importing
/// further versions into an existing container (master06 §Copying "previous
/// copies have been made for the item").
///
/// # Errors
/// Returns [`StorageError::Database`] on a driver/update failure.
pub async fn close_lineage_at(
    tx: &mut PgConnection,
    vo_id: VoId,
    lineage: &(String, i32, i32),
    at: jiff::Timestamp,
) -> Result<(), StorageError> {
    let (csid, trunk, branch) = lineage;
    if *branch == 0 {
        sqlx::query(
            "UPDATE vo_version SET sys_period = tstzrange(lower(sys_period), $2::timestamptz, '[)') \
             WHERE vo_id = $1 AND upper_inf(sys_period) AND branch_number = 0",
        )
        .bind(vo_id)
        .bind(at.to_string())
        .execute(&mut *tx)
        .await?;
    } else {
        sqlx::query(
            "UPDATE vo_version SET sys_period = tstzrange(lower(sys_period), $2::timestamptz, '[)') \
             WHERE vo_id = $1 AND upper_inf(sys_period) \
             AND creating_system_id = $3 AND trunk_version = $4 AND branch_number = $5",
        )
        .bind(vo_id)
        .bind(at.to_string())
        .bind(csid)
        .bind(trunk)
        .bind(branch)
        .execute(&mut *tx)
        .await?;
    }
    Ok(())
}

/// The stored state of one BRANCH lineage of a container — the highest
/// `branch_version` held on `(creating_system_id, trunk_version,
/// branch_number)` and whether that lineage's tip row is still open.
///
/// `(0, false)` when the store holds no version of the lineage.
///
/// # Errors
/// Returns [`StorageError::Database`] on a driver failure.
pub async fn branch_lineage_state(
    tx: &mut PgConnection,
    vo_id: VoId,
    lineage: &(String, i32, i32),
) -> Result<(i32, bool), StorageError> {
    let (csid, trunk, branch) = lineage;
    let row = sqlx::query(
        "SELECT max(branch_version) AS max_branch, \
                bool_or(upper_inf(sys_period)) AS open \
         FROM vo_version WHERE vo_id = $1 AND creating_system_id = $2 \
         AND trunk_version = $3 AND branch_number = $4",
    )
    .bind(vo_id)
    .bind(csid)
    .bind(trunk)
    .bind(branch)
    .fetch_one(&mut *tx)
    .await?;
    Ok((
        row.try_get::<Option<i32>, _>("max_branch")?.unwrap_or(0),
        row.try_get::<Option<bool>, _>("open")?.unwrap_or(false),
    ))
}

/// The current state of a to-be-imported container in the target store —
/// `kind: None` when the container is not present (first receipt — master06
/// §Copying Case 2).
///
/// Mapping the kind text to a versioned-object kind is the caller's.
#[derive(Debug, Clone, Default)]
pub struct ContainerStateRow {
    /// The stored kind text, if the `vo_id` already exists.
    pub kind: Option<String>,
    /// The owning EHR of the existing container.
    pub owner: Option<EhrId>,
    /// The highest trunk version currently held.
    pub max_trunk: i32,
    /// The highest storage ordinal currently held.
    pub max_ordinal: i32,
    /// Whether a still-open current TRUNK version exists.
    pub trunk_open: bool,
}

/// Read the [`ContainerStateRow`] of a to-be-imported container.
///
/// # Errors
/// Returns [`StorageError::Database`] on a driver failure.
pub async fn imported_container_state(
    tx: &mut PgConnection,
    vo_id: VoId,
) -> Result<ContainerStateRow, StorageError> {
    let row = sqlx::query(
        "SELECT max(trunk_version) FILTER (WHERE branch_number = 0) AS max_trunk, \
                max(sys_version) AS max_ordinal, \
                bool_or(upper_inf(sys_period) AND branch_number = 0) AS trunk_open, \
                (array_agg(kind))[1] AS kind, \
                (array_agg(ehr_id))[1] AS owner \
         FROM vo_version WHERE vo_id = $1",
    )
    .bind(vo_id)
    .fetch_one(&mut *tx)
    .await?;
    let max_ordinal: Option<i32> = row.try_get("max_ordinal")?;
    let Some(max_ordinal) = max_ordinal else {
        return Ok(ContainerStateRow::default());
    };
    Ok(ContainerStateRow {
        kind: row.try_get("kind")?,
        owner: row.try_get("owner")?,
        max_trunk: row.try_get::<Option<i32>, _>("max_trunk")?.unwrap_or(0),
        max_ordinal,
        trunk_open: row
            .try_get::<Option<bool>, _>("trunk_open")?
            .unwrap_or(false),
    })
}
