// @generated by openehr-codegen from BMM (`BMM_GENERIC_PARAMETER`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `BMM_GENERIC_PARAMETER` spec class, generated from the vendored BMM
//! meta-model.

#![expect(
    clippy::disallowed_types,
    reason = "adjudicated free-form JSON slots: serde_json::Value is workspace-banned (#1694); a generated carrier exists only where the spec leaves the slot open, and each adjudicated field's NOTE names its citation"
)]
use crate::v2_4::bmm::core::bmm_class::BmmClass;

/// Definition of a generic parameter in a class definition of a generic type.
#[doc(alias = "BMM_GENERIC_PARAMETER")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmGenericParameter {
    /// Name of the parameter, e.g. 'T' etc. The name is limited to 1 character and upper-case.
    pub name: String,

    // inherited: BMM_MODEL_ELEMENT
    /// Optional documentation of this element, as a keyed list.
    ///
    /// It is strongly recommended to use the following key /type combinations for the relevant purposes:
    ///
    /// * `"purpose": String`
    /// * `"keywords": List<String>`
    /// * `"use": String`
    /// * `"misuse": String`
    /// * `"references": String`
    ///
    /// Other keys and value types may be freely added.
    pub documentation: Option<std::collections::BTreeMap<String, serde_json::Value>>,
    // NOTE: `scope` (BMM-mandatory back-reference) omitted — LANG BMM3 bmm_model_element (scope: Model element within which an element is declared; Post_result of is_root_scope: Result = (scope = self)). A back-reference is not forward-owned data and never appears on the canonical wire; emitting it as an owning field would make this type non-constructible.
    /// Optional meta-data of this element, as a keyed list. May be used to extend the meta-model.
    pub extensions: Option<std::collections::BTreeMap<String, serde_json::Value>>,
    /// Optional conformance constraint that must be another valid class name.
    pub conforms_to_type: Option<BmmClass>,
    /// If set, is the corresponding generic parameter definition in an ancestor class.
    pub inheritance_precursor: Option<Box<BmmGenericParameter>>,
}
