// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_2/composition/content/navigation` — generated module tree.

pub mod section;

// hand-written modules (spec behaviour), auto-declared:
pub mod section_impl;
