// @generated by openehr-codegen from BMM (`VALUE_SET`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

/// Representation of a flat value set within the archetype terminology.
#[derive(Debug, Clone, PartialEq)]
pub struct ValueSet {
    // inherited: TERMINOLOGY_RELATION
    /// Code of source term of this relation.
    pub id: String,
    /// List of target terms in this relation.
    pub members: Vec<String>,
}
