// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR spec package `v2_4/aom2/profile` — generated module tree.

pub mod aom_profile;
pub mod aom_property_mapping;
pub mod aom_type_mapping;
