// @generated by openehr-codegen from BMM (`EL_TYPE_DEF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `EL_TYPE_DEF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::obsolete_elom::types::type_def_boolean::TypeDefBoolean;
use crate::v1_0::obsolete_elom::types::type_def_date::TypeDefDate;
use crate::v1_0::obsolete_elom::types::type_def_date_time::TypeDefDateTime;
use crate::v1_0::obsolete_elom::types::type_def_duration::TypeDefDuration;
use crate::v1_0::obsolete_elom::types::type_def_integer::TypeDefInteger;
use crate::v1_0::obsolete_elom::types::type_def_object_ref::TypeDefObjectRef;
use crate::v1_0::obsolete_elom::types::type_def_real::TypeDefReal;
use crate::v1_0::obsolete_elom::types::type_def_string::TypeDefString;
use crate::v1_0::obsolete_elom::types::type_def_terminology_code::TypeDefTerminologyCode;
use crate::v1_0::obsolete_elom::types::type_def_time::TypeDefTime;
use crate::v1_0::obsolete_elom::types::type_def_uri::TypeDefUri;

/// Closed subtype set of `EL_TYPE_DEF`, dispatched on each payload's `_type`.
///
/// Ancestor class for type definitions known in the openEHR Expression formalism.
#[doc(alias = "EL_TYPE_DEF")]
#[derive(Debug, Clone, PartialEq)]
pub enum ElTypeDef {
    /// The `TYPE_DEF_BOOLEAN` subtype of `EL_TYPE_DEF`.
    TypeDefBoolean(TypeDefBoolean),
    /// The `TYPE_DEF_DATE` subtype of `EL_TYPE_DEF`.
    TypeDefDate(TypeDefDate),
    /// The `TYPE_DEF_DATE_TIME` subtype of `EL_TYPE_DEF`.
    TypeDefDateTime(TypeDefDateTime),
    /// The `TYPE_DEF_DURATION` subtype of `EL_TYPE_DEF`.
    TypeDefDuration(TypeDefDuration),
    /// The `TYPE_DEF_INTEGER` subtype of `EL_TYPE_DEF`.
    TypeDefInteger(TypeDefInteger),
    /// The `TYPE_DEF_OBJECT_REF` subtype of `EL_TYPE_DEF`.
    TypeDefObjectRef(TypeDefObjectRef),
    /// The `TYPE_DEF_REAL` subtype of `EL_TYPE_DEF`.
    TypeDefReal(TypeDefReal),
    /// The `TYPE_DEF_STRING` subtype of `EL_TYPE_DEF`.
    TypeDefString(TypeDefString),
    /// The `TYPE_DEF_TERMINOLOGY_CODE` subtype of `EL_TYPE_DEF`.
    TypeDefTerminologyCode(TypeDefTerminologyCode),
    /// The `TYPE_DEF_TIME` subtype of `EL_TYPE_DEF`.
    TypeDefTime(TypeDefTime),
    /// The `TYPE_DEF_URI` subtype of `EL_TYPE_DEF`.
    TypeDefUri(TypeDefUri),
}
