// @generated by openehr-codegen from BMM (`TYPE_DEF_DURATION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `TYPE_DEF_DURATION` spec class, generated from the vendored BMM
//! meta-model.

#![expect(
    clippy::disallowed_types,
    reason = "adjudicated free-form JSON slots: serde_json::Value is workspace-banned (#1694); a generated carrier exists only where the spec leaves the slot open, and each adjudicated field's NOTE names its citation"
)]
/// Rules meta-type representing the primitive type Duration.
#[doc(alias = "TYPE_DEF_DURATION")]
#[derive(Debug, Clone, PartialEq)]
pub struct TypeDefDuration {
    /// The `type_name` attribute of openEHR `TYPE_DEF_DURATION` (the vendored BMM carries no documentation for it).
    pub type_name: String,
    /// The `type_anchor` attribute of openEHR `TYPE_DEF_DURATION` (the vendored BMM carries no documentation for it).
    pub type_anchor: serde_json::Value,
}
