// @generated by openehr-codegen from BMM (`EL_AGENT_CALL`) — DO NOT EDIT.

use crate::am24::bmm3::expression::el_function_call::ElFunctionCall;
use crate::am24::bmm3::statement::bmm_procedure_call::BmmProcedureCall;

/// A call made to a 'closed' agent, i.e. one with no remaining open arguments.
/// Closed subtype set of `EL_AGENT_CALL`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ElAgentCall {
    BmmProcedureCall(BmmProcedureCall),
    ElFunctionCall(ElFunctionCall),
}
