// @generated by openehr-codegen from BMM (`EL_CONSTRAINED`) — DO NOT EDIT.

use crate::am24::bmm3::expression::el_boolean_expression::ElBooleanExpression;

/// Abstract parent for second-order constrained forms of first-order expression meta-types.
/// Closed subtype set of `EL_CONSTRAINED`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ElConstrained {
    ElBooleanExpression(ElBooleanExpression),
}
