// @generated by openehr-codegen from BMM (`EL_EXPRESSION`) — DO NOT EDIT.

use crate::am24::bmm3::expression::el_attached::ElAttached;
use crate::am24::bmm3::expression::el_binary_operator::ElBinaryOperator;
use crate::am24::bmm3::expression::el_boolean_expression::ElBooleanExpression;
use crate::am24::bmm3::expression::el_case_table::ElCaseTable;
use crate::am24::bmm3::expression::el_condition_chain::ElConditionChain;
use crate::am24::bmm3::expression::el_defined::ElDefined;
use crate::am24::bmm3::expression::el_function_agent::ElFunctionAgent;
use crate::am24::bmm3::expression::el_function_call::ElFunctionCall;
use crate::am24::bmm3::expression::el_procedure_agent::ElProcedureAgent;
use crate::am24::bmm3::expression::el_property_ref::ElPropertyRef;
use crate::am24::bmm3::expression::el_readonly_variable::ElReadonlyVariable;
use crate::am24::bmm3::expression::el_static_ref::ElStaticRef;
use crate::am24::bmm3::expression::el_terminal::ElTerminal;
use crate::am24::bmm3::expression::el_tuple::ElTuple;
use crate::am24::bmm3::expression::el_unary_operator::ElUnaryOperator;
use crate::am24::bmm3::expression::el_writable_variable::ElWritableVariable;
use openehr_lang::prelude::ElLiteral;
use openehr_lang::prelude::ElTypeRef;

/// Abstract parent of all typed expression meta-types.
/// Closed subtype set of `EL_EXPRESSION`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ElExpression {
    ElAttached(ElAttached),
    ElBinaryOperator(Box<ElBinaryOperator>),
    ElBooleanExpression(Box<ElBooleanExpression>),
    ElCaseTable(ElCaseTable<ElTerminal>),
    ElConditionChain(ElConditionChain<ElTerminal>),
    ElDefined(ElDefined),
    ElFunctionAgent(ElFunctionAgent),
    ElFunctionCall(ElFunctionCall),
    ElLiteral(ElLiteral),
    ElProcedureAgent(ElProcedureAgent),
    ElPropertyRef(ElPropertyRef),
    ElReadonlyVariable(ElReadonlyVariable),
    ElStaticRef(ElStaticRef),
    ElTuple(ElTuple),
    ElTypeRef(ElTypeRef),
    ElUnaryOperator(Box<ElUnaryOperator>),
    ElWritableVariable(ElWritableVariable),
}
