// @generated by openehr-codegen from BMM (`EL_TUPLE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am24::bmm3::expression::el_tuple_item::ElTupleItem;
use openehr_lang::prelude::BmmTupleType;

/// Defines an array of optionally named items each of any type.
#[derive(Debug, Clone, PartialEq)]
pub struct ElTuple {
    /// Items in the tuple, potentially with names. Typical use is to represent an argument list to routine call.
    pub items: Vec<ElTupleItem>,
    /// Static type inferred from literal value.
    pub r#type: BmmTupleType,
}
