// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_2/ehr_extract/message` — generated module tree.

pub mod addressed_message;
pub mod message;
pub mod message_content;
