// @generated by openehr-codegen from BMM (`SERVICE_USE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `SERVICE_USE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::data_structures::item_structure::item_structure::ItemStructure;
use crate::v1_1::foundation_types::time::iso8601_date_time::Iso8601DateTime;
use crate::v1_1::foundation_types::time::iso8601_duration::Iso8601Duration;
use openehr_base::v1_2::base_types::identification::generic_id::GenericId;

/// The openEHR `SERVICE_USE` class (the vendored BMM carries no documentation for it).
#[doc(alias = "SERVICE_USE")]
#[derive(Debug, Clone, PartialEq)]
pub struct ServiceUse {
    // inherited: RESOURCE_USE
    /// The `cost_data` attribute of openEHR `RESOURCE_USE` (the vendored BMM carries no documentation for it).
    pub cost_data: Option<ItemStructure>,
    /// The `identifier` attribute of openEHR `SERVICE_USE` (the vendored BMM carries no documentation for it).
    pub identifier: Option<GenericId>,
    /// The `start_time` attribute of openEHR `SERVICE_USE` (the vendored BMM carries no documentation for it).
    pub start_time: Option<Iso8601DateTime>,
    /// The `duration` attribute of openEHR `SERVICE_USE` (the vendored BMM carries no documentation for it).
    pub duration: Option<Iso8601Duration>,
}
