//! JSON emitter: emits `impl ToJson` + `impl FromJson` for the generated spec
//! types (BASE / RM / AM / TERM / LANG), into
//! `openehr-its/src/json_codec/generated/`.
//!
//! Every fact comes from the BMM ([`Model::json_types`]): field idents, wire
//! names, omission kind, field defaults, enum variants + `_type` dispatch,
//! generics. There is no XSD input — the canonical-JSON wire shape is `_type`
//! first then BMM declaration order, with `None`/empty-`Vec` fields omitted. The
//! emitted impls are the byte-for-byte replacement for the
//! `#[derive(OpenEhrType)]` serde `Serialize`/`Deserialize` (`openehr-derive`);
//! the parity gate in `openehr-its/tests/json_codec_parity.rs` proves the
//! equivalence in both directions.
//!
//! The read side reproduces the retired derive's tolerance rules verbatim:
//! unknown wire keys ignored (a deliberate superset of the ITS-JSON schema's
//! `additionalProperties: false` — RM-version skew), out-of-order members,
//! present-but-wrong `_type` = error, absent `_type` accepted on a concrete slot,
//! `Option`/`Vec` defaulting, the `Interval` `*_included`/`*_unbounded` literal
//! defaults, and `_type`-keyed polymorphic-slot dispatch (abstract slots reject a
//! missing `_type`; concrete polymorphic slots default it to the base type).

use crate::analyze::Model;
use crate::load::bmm::BmmSchema;
use crate::plan::{JsonEnumDispatch, JsonField, JsonFieldKind, JsonType};
use std::fmt::Write as _;

/// One spec schema paired with the crate prelude its types are re-exported from.
#[derive(Clone, Copy)]
pub(crate) struct JsonSchema<'a> {
    pub model: &'a Model,
    pub schema: &'a BmmSchema,
    /// e.g. `openehr_rm::prelude` / `openehr_base::prelude`.
    pub prelude: &'a str,
    /// Module path (`openehr_lang::bmm::core::bmm_class`) for each spec class the
    /// crate prelude does NOT export, keyed by spec class name.
    ///
    /// A crate composed of several BMM generations exports one type per Rust NAME
    /// from its prelude, so for a class name both generations declare only one
    /// twin is reachable as `<crate>::prelude::<Ident>`; the other is named here
    /// by its full module path. Both twins are covered: they are distinct Rust
    /// types, so their `ToJson`/`FromJson` impls do not conflict, and the whole
    /// emitted model stays codec-complete.
    ///
    /// NOTE (adjudicated): the two twins share a canonical `_type` string (the
    /// BMM class name is the same in both generations), and that is not an
    /// ambiguity: `FromJson` is always invoked at a statically known Rust type,
    /// and `_type`-keyed dispatch only ever chooses among the variants of ONE
    /// enum — never across generations. No openEHR spec governs a BMM-model
    /// canonical-JSON wire at all (this codec is our own extension), so there is
    /// no cross-generation wire contract to break.
    pub unexported: &'a std::collections::BTreeMap<String, String>,
}

impl JsonSchema<'_> {
    /// The Rust path prefix a spec class's type is named by.
    fn path_of(&self, spec: &str) -> &str {
        self.unexported
            .get(spec)
            .map_or(self.prelude, String::as_str)
    }
}

/// The `ToJson` trait path in the target crate.
const TO_JSON: &str = "crate::json_codec::runtime::ToJson";
/// The `JsonWriter` path in the target crate.
const WRITER: &str = "crate::json_codec::runtime::JsonWriter";
/// The `FromJson` trait path in the target crate.
const FROM_JSON: &str = "crate::json_codec::runtime::FromJson";
/// The `JsonNode` trait path in the target crate.
const NODE: &str = "crate::json_codec::runtime::JsonNode";
/// The `JsonParseError` type path in the target crate.
const ERR: &str = "crate::json_codec::runtime::JsonParseError";

/// Emit the whole generated impl file: one `impl ToJson` + one `impl FromJson`
/// per instantiable type, in schema then class order.
pub(crate) fn emit_file(schemas: &[JsonSchema<'_>]) -> String {
    let mut b = String::new();
    // `unused_qualifications`: the emitted impls name every runtime item by its
    // full path so the emitter never has to reason about import scope — inherent
    // to text generation, not a defect in the output. `unused_imports` covers a
    // schema set that happens not to need every runtime item.
    // The whole set is ONE file-level `#![allow(…, reason = "…")]`: `reason` is
    // mandatory (`clippy::allow_attributes_without_reason` is deny workspace-
    // wide), an inner attribute is exempt from `clippy::allow_attributes`, and
    // `expect` is wrong for a blanket list because no single emission triggers
    // every listed lint.
    b.push_str(
        "// @generated by openehr-codegen (emit-json) — DO NOT EDIT.\n\
         // Canonical-JSON `ToJson`/`FromJson` impls for the RM/BASE/AM/TERM/LANG spec types.\n\n\
         #![allow(\n    \
         clippy::all,\n    \
         clippy::pedantic,\n    \
         clippy::nursery,\n    \
         unused_variables,\n    \
         unused_mut,\n    \
         unused_qualifications,\n    \
         unused_imports,\n    \
         reason = \"mechanically generated codec text: every runtime item is named \
         by its full path and every branch shape is emitted uniformly, so style \
         and unused-binding lints do not apply — the hand-written runtime carries \
         the lint bar\"\n\
         )]\n\
         use crate::json_codec::runtime::{self, FromJson, JsonNode, JsonParseError, JsonWriter, ToJson};\n\n",
    );
    for s in schemas {
        for ty in s.model.json_types(s.schema) {
            let prelude = s.path_of(json_type_spec(&ty));
            emit_to_json(&mut b, &ty, prelude);
            emit_from_json(&mut b, &ty, prelude);
        }
    }
    b
}

// ── Structural dispatch (`structural_check`) ─────────────────────────────────

/// The bound-fill type argument a generic class's structural decode is
/// monomorphized with.
///
/// A generic spec class (`DV_INTERVAL<T>`, `HISTORY<T>`, `ORIGINAL_VERSION<T>`,
/// `POINT_EVENT<T>`, …) has no single wire type argument: the canonical-JSON
/// `_type` names only the container class, and the element type is whatever the
/// declaring attribute said. The untyped fill decodes each element as an opaque
/// value, so the container's OWN shape (its mandatory attributes and their JSON
/// kinds) is checked while the elements are accepted verbatim — exactly the
/// monomorphization the hand-written typed dispatch uses for the same classes.
const GENERIC_FILL: &str = "::serde_json::Value";

/// Emit the generated `structural_check` dispatch file: `_type` → decode the
/// node into that class's generated Rust type and discard the value, so the
/// codec is the single structural-conformance authority for EVERY emitted class
/// rather than only the invariant-bearing ones.
///
/// Precedence when several schemas declare the same spec class name (110 names
/// in the current vendored set — `RESOURCE_DESCRIPTION`, `AUTHORED_RESOURCE`,
/// the whole `BMM_*` family, …): the FIRST schema in `schemas` wins, so the
/// caller passes them in dispatch priority. Every shadowed twin is listed in
/// the emitted header, never dropped silently.
pub(crate) fn emit_structural_file(schemas: &[JsonSchema<'_>]) -> String {
    let mut arms: std::collections::BTreeMap<String, String> = std::collections::BTreeMap::new();
    let mut shadowed: Vec<(String, String, String)> = Vec::new();
    let mut skipped: Vec<(String, &'static str)> = Vec::new();
    for s in schemas {
        for ty in s.model.json_types(s.schema) {
            // A newtype / literal-enum shape writes its BARE payload (no `_type`
            // member — see `emit_to_json`), and an untagged enum carries no
            // `_type` of its own either (the active variant's payload supplies
            // it, and every such payload is itself an emitted struct with its
            // own arm). Neither is reachable as a `_type` dispatch key, so
            // neither can have one — each is recorded, never silently dropped.
            let (spec, rust, generics) = match &ty {
                JsonType::Struct {
                    spec,
                    rust,
                    generics,
                    ..
                } => (spec, rust, generics),
                JsonType::Enum { rust, .. } => {
                    skipped.push((
                        rust.clone(),
                        "untagged enum: the wire `_type` is the active variant's, which has its own arm",
                    ));
                    continue;
                }
                JsonType::Newtype { rust } => {
                    skipped.push((
                        rust.clone(),
                        "transparent newtype: serializes as its bare primitive payload, never `_type`-tagged",
                    ));
                    continue;
                }
                JsonType::EnumLiterals { rust, .. } => {
                    skipped.push((
                        rust.clone(),
                        "BMM enumeration: a literal token/integer on the wire, never `_type`-tagged",
                    ));
                    continue;
                }
            };
            let path = s.path_of(spec);
            let fill = if generics.is_empty() {
                String::new()
            } else {
                let args = vec![GENERIC_FILL; generics.len()].join(", ");
                format!("<{args}>")
            };
            let expr = format!("{path}::{rust}{fill}");
            match arms.entry(spec.clone()) {
                std::collections::btree_map::Entry::Vacant(slot) => {
                    slot.insert(expr);
                }
                std::collections::btree_map::Entry::Occupied(held) => {
                    shadowed.push((spec.clone(), held.get().clone(), expr));
                }
            }
        }
    }

    let mut b = String::new();
    b.push_str(
        "// @generated by openehr-codegen (emit-json) — DO NOT EDIT.\n\
         //! Structural conformance dispatch: `_type` → the emitted `FromJson` decode\n\
         //! of that spec class.\n\
         //!\n\
         //! The canonical-JSON codec is the structural-conformance authority for a\n\
         //! wire node (mandatory attributes present, JSON kinds right, nested slot\n\
         //! `_type`s resolvable). This dispatch makes that authority reachable for\n\
         //! EVERY emitted class from a `_type` string alone, so a per-node validation\n\
         //! walk is not limited to the classes that happen to carry a class\n\
         //! invariant. The decoded value is discarded — only the `Result` matters.\n\
         //!\n\
         //! Coverage: one arm per class the generator emits as a STRUCT (every\n\
         //! concrete class, plus the few abstract classes emitted as structs because\n\
         //! their concrete descendants live in another schema). Deterministic\n\
         //! exclusions, by shape:\n\
         //!\n\
         //! - an untagged **enum** (abstract or polymorphic slot) carries no `_type`\n\
         //!   of its own — the active variant's payload does, and every payload is an\n\
         //!   emitted struct with its own arm;\n\
         //! - a transparent **newtype** and a BMM **enumeration** serialize as their\n\
         //!   bare primitive payload, so no `_type` member exists to dispatch on.\n\
         //!\n\
         //! Generic classes are monomorphized with an opaque element type, so the\n\
         //! container's own shape is checked and its elements are accepted verbatim\n\
         //! (each element is a `_type` node in its own right).\n\
         //!\n\
         //! NOTE: no openEHR spec governs a cross-component `_type` namespace (the\n\
         //! canonical-JSON `_type` is a class name, and several components' BMMs\n\
         //! declare the same name with different attributes) — our own design: the\n\
         //! emitter resolves a collision by schema priority, in the order the CLI\n\
         //! passes the schemas, and every shadowed twin is listed below.\n\n\
         #![allow(\n    \
         clippy::all,\n    \
         clippy::pedantic,\n    \
         clippy::nursery,\n    \
         unused_qualifications,\n    \
         reason = \"mechanically generated dispatch text: one uniform arm per emitted \
         class, every item named by its full path — length and style lints do not \
         apply, the hand-written runtime carries the lint bar\"\n\
         )]\n\n",
    );
    let _ = writeln!(b, "// Shadowed twins ({}):", shadowed.len());
    for (spec, winner, loser) in &shadowed {
        let _ = writeln!(b, "//   {spec}: {winner} wins over {loser}");
    }
    let _ = writeln!(b, "// Shapes with no `_type` key ({}):", skipped.len());
    for (rust, why) in &skipped {
        let _ = writeln!(b, "//   {rust}: {why}");
    }
    b.push('\n');
    let _ = write!(
        b,
        "/// Decode `node` as the emitted spec class named by `ty` and discard the\n\
         /// value: `Some(Ok(()))` when the node conforms structurally,\n\
         /// `Some(Err(_))` when it does not, `None` when `ty` names no emitted\n\
         /// class.\n\
         ///\n\
         /// # Errors\n\
         /// The inner `Err` is the codec's [`{ERR}`] for a node that does not\n\
         /// decode as `ty` (a missing mandatory attribute, a wrong JSON kind, an\n\
         /// unresolvable nested slot `_type`).\n\
         pub fn structural_check(\n    \
         ty: &str,\n    \
         node: &::serde_json::Value,\n\
         ) -> ::core::option::Option<::core::result::Result<(), {ERR}>> {{\n    \
         match ty {{\n"
    );
    for (spec, expr) in &arms {
        let _ = writeln!(
            b,
            "{spec:?} => ::core::option::Option::Some(\
             crate::json_codec::runtime::from_json_value::<{expr}>(node).map(|_| ())),"
        );
    }
    b.push_str("_ => ::core::option::Option::None,\n}\n}\n");
    b
}

/// The spec class a [`JsonType`] realizes — the key its Rust path is resolved by
/// ([`JsonSchema::path_of`]). A newtype/literal-enum carries only its Rust name,
/// which for those shapes is the `type_name` of the spec class itself.
fn json_type_spec(ty: &JsonType) -> &str {
    match ty {
        JsonType::Struct { spec, .. } | JsonType::Enum { spec, .. } => spec,
        JsonType::Newtype { rust } | JsonType::EnumLiterals { rust, .. } => rust,
    }
}

/// `(impl<…: Bound> , <…>)` — the impl-generics header and the type-args suffix.
fn generic_header(generics: &[String], bound: &str) -> (String, String) {
    if generics.is_empty() {
        (String::new(), String::new())
    } else {
        let bounded = generics
            .iter()
            .map(|g| format!("{g}: {bound}"))
            .collect::<Vec<_>>()
            .join(", ");
        (format!("<{bounded}>"), format!("<{}>", generics.join(", ")))
    }
}

// ── Serialize side (`ToJson`) ────────────────────────────────────────────────

/// Emit `impl ToJson` for one [`JsonType`].
fn emit_to_json(b: &mut String, ty: &JsonType, prelude: &str) {
    match ty {
        JsonType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics, TO_JSON);
            let _ = write!(
                b,
                "impl{hdr} {TO_JSON} for {prelude}::{rust}{args} {{\n\
                 fn json_type_name(&self) -> &'static str {{ \"{spec}\" }}\n\
                 fn write_json(&self, w: &mut {WRITER}) {{\n\
                 w.begin_object();\n\
                 w.field_str(\"_type\", \"{spec}\");\n"
            );
            for f in fields {
                emit_write_field(b, f);
            }
            b.push_str("w.end_object();\n}\n}\n\n");
        }
        JsonType::Enum {
            rust,
            generics,
            variant_idents,
            ..
        } => {
            let (hdr, args) = generic_header(generics, TO_JSON);
            let _ = write!(
                b,
                "impl{hdr} {TO_JSON} for {prelude}::{rust}{args} {{\n\
                 fn json_type_name(&self) -> &'static str {{ match self {{\n"
            );
            for ident in variant_idents {
                let _ = writeln!(b, "{prelude}::{rust}::{ident}(x) => x.json_type_name(),");
            }
            b.push_str("} }\n");
            let _ = writeln!(b, "fn write_json(&self, w: &mut {WRITER}) {{ match self {{");
            for ident in variant_idents {
                let _ = writeln!(b, "{prelude}::{rust}::{ident}(x) => x.write_json(w),");
            }
            b.push_str("} }\n}\n\n");
        }
        JsonType::Newtype { rust } => {
            let _ = write!(
                b,
                "impl {TO_JSON} for {prelude}::{rust} {{\n\
                 fn write_json(&self, w: &mut {WRITER}) {{ self.0.write_json(w) }}\n}}\n\n"
            );
        }
        JsonType::EnumLiterals {
            rust,
            string_backed,
        } => {
            // Byte-identical to the bare primitive it replaces: `as_str` = the
            // constant token (verbatim payload for `Other`), `value` = the
            // constant integer — matching the enum's hand-written serde.
            let body = if *string_backed {
                "w.write_str(self.as_str())"
            } else {
                "w.write_i32(self.value())"
            };
            let _ = write!(
                b,
                "impl {TO_JSON} for {prelude}::{rust} {{\n\
                 fn write_json(&self, w: &mut {WRITER}) {{ {body}; }}\n}}\n\n"
            );
        }
    }
}

/// Emit the write call for one struct field, per its omission kind (mirroring the
/// derive: `None`/empty-`Vec` omitted, everything else always written).
fn emit_write_field(b: &mut String, f: &JsonField) {
    let (wire, rust) = (&f.wire_name, &f.rust_name);
    match f.kind {
        JsonFieldKind::Plain => {
            let _ = writeln!(b, "w.field(\"{wire}\", &self.{rust});");
        }
        JsonFieldKind::Optional => {
            let _ = writeln!(
                b,
                "if let Some(v) = &self.{rust} {{ w.field(\"{wire}\", v); }}"
            );
        }
        JsonFieldKind::Container => {
            let _ = writeln!(
                b,
                "if !self.{rust}.is_empty() {{ w.field(\"{wire}\", &self.{rust}); }}"
            );
        }
        // An optional container omits BOTH states an empty array could carry —
        // `None` and `Some(vec![])` — because the released serialization rule is
        // about emptiness, not about optionality:
        // `docs/specs/openehr/ITS-REST/specifications/docs/overview/Resources.md`
        // §JSON Format, "The RM attributes (even required ones) that are `Null`
        // or an empty list (array) SHOULD be absent when serialized as JSON."
        // The present-but-empty state therefore lives in the typed model (where
        // the `x /= Void implies not x.is_empty` invariants judge it) and never
        // reaches the wire.
        JsonFieldKind::OptionalContainer => {
            let _ = writeln!(
                b,
                "if let Some(v) = &self.{rust} && !v.is_empty() {{ w.field(\"{wire}\", v); }}"
            );
        }
    }
}

// ── Deserialize side (`FromJson`) ────────────────────────────────────────────

/// Emit `impl FromJson` for one [`JsonType`].
fn emit_from_json(b: &mut String, ty: &JsonType, prelude: &str) {
    match ty {
        JsonType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => emit_struct_from_json(b, spec, rust, generics, fields, prelude),
        JsonType::Enum {
            spec: _,
            rust,
            generics,
            variant_idents,
            dispatch,
        } => emit_enum_from_json(b, rust, generics, variant_idents, dispatch, prelude),
        JsonType::Newtype { rust } => {
            let _ = write!(
                b,
                "impl {FROM_JSON} for {prelude}::{rust} {{\n\
                 fn from_json<__N: {NODE}>(node: &__N) -> ::core::result::Result<Self, {ERR}> {{\n\
                 ::core::result::Result::Ok({prelude}::{rust}({FROM_JSON}::from_json(node)?))\n}}\n}}\n\n"
            );
        }
        JsonType::EnumLiterals {
            rust,
            string_backed,
        } => {
            let body = if *string_backed {
                format!(
                    "let __s = node.as_str().ok_or_else(|| {ERR}::type_error(\"a string\", node.kind()))?;\n\
                     ::core::result::Result::Ok({prelude}::{rust}::from_wire(__s))"
                )
            } else {
                format!(
                    // The `TryFromIntError` cause is carried into the message
                    // rather than discarded (`clippy::map_err_ignore`), so the
                    // generated reader loses no diagnostic information.
                    "let __v = node.as_i64().ok_or_else(|| {ERR}::type_error(\"an integer\", node.kind()))?;\n\
                     let __v = i32::try_from(__v).map_err(|__e| {ERR}::custom(::std::format!(\"integer {{__v}} out of range for i32: {{__e}}\")))?;\n\
                     ::core::result::Result::Ok({prelude}::{rust}::from_value(__v))"
                )
            };
            let _ = write!(
                b,
                "impl {FROM_JSON} for {prelude}::{rust} {{\n\
                 fn from_json<__N: {NODE}>(node: &__N) -> ::core::result::Result<Self, {ERR}> {{\n\
                 {body}\n}}\n}}\n\n"
            );
        }
    }
}

/// Emit `impl FromJson` for a struct (a polymorphic-concrete `Data` struct, or a
/// plain struct). Object-required, `_type` validated, fields read by key per kind.
fn emit_struct_from_json(
    b: &mut String,
    spec: &str,
    rust: &str,
    generics: &[String],
    fields: &[JsonField],
    prelude: &str,
) {
    let (hdr, args) = generic_header(generics, FROM_JSON);
    let _ = write!(
        b,
        "impl{hdr} {FROM_JSON} for {prelude}::{rust}{args} {{\n\
         fn from_json<__N: {NODE}>(node: &__N) -> ::core::result::Result<Self, {ERR}> {{\n\
         runtime::expect_object(node, \"{spec}\")?;\n\
         runtime::check_type(node, \"{spec}\")?;\n\
         ::core::result::Result::Ok(Self {{\n"
    );
    for f in fields {
        let (wire, rust_name) = (&f.wire_name, &f.rust_name);
        let read = match (&f.kind, &f.default) {
            (JsonFieldKind::Plain, Some(default)) => {
                format!("runtime::defaulted_field(node, \"{wire}\", {default})?")
            }
            (JsonFieldKind::Plain, None) => {
                format!("runtime::required_field(node, \"{wire}\", \"{spec}\")?")
            }
            (JsonFieldKind::Optional, _) => format!("runtime::optional_field(node, \"{wire}\")?"),
            (JsonFieldKind::Container, _) => {
                format!("runtime::container_field(node, \"{wire}\")?")
            }
            (JsonFieldKind::OptionalContainer, _) => {
                format!("runtime::optional_container_field(node, \"{wire}\")?")
            }
        };
        let _ = writeln!(b, "{rust_name}: {read},");
    }
    b.push_str("})\n}\n}\n\n");
}

/// Emit `impl FromJson` for a closed-subtype-set / polymorphic enum, reproducing
/// the derive's `_type`-dispatch (or structural-untagged) reader.
fn emit_enum_from_json(
    b: &mut String,
    rust: &str,
    generics: &[String],
    variant_idents: &[String],
    dispatch: &JsonEnumDispatch,
    prelude: &str,
) {
    let (hdr, args) = generic_header(generics, FROM_JSON);
    let _ = write!(
        b,
        // `clippy::match_same_arms` is already covered by the file-level
        // `clippy::pedantic` allow, so the dispatch fn needs no attribute.
        "impl{hdr} {FROM_JSON} for {prelude}::{rust}{args} {{\n\
         fn from_json<__N: {NODE}>(node: &__N) -> ::core::result::Result<Self, {ERR}> {{\n"
    );
    match dispatch {
        JsonEnumDispatch::ByType {
            arms,
            self_ident,
            spec_name,
            expected,
        } => {
            b.push_str("match runtime::slot_type(node) {\n");
            for (spec, ident) in arms {
                let _ = writeln!(
                    b,
                    "::core::option::Option::Some({spec:?}) => ::core::result::Result::Ok(Self::{ident}({FROM_JSON}::from_json(node)?)),"
                );
            }
            if let Some(ident) = self_ident {
                let _ = writeln!(
                    b,
                    "::core::option::Option::None => ::core::result::Result::Ok(Self::{ident}({FROM_JSON}::from_json(node)?)),"
                );
            } else {
                let msg = format!(
                    "{spec_name}: missing required `_type` on polymorphic slot (expected one of: {expected})"
                );
                let _ = writeln!(
                    b,
                    "::core::option::Option::None => ::core::result::Result::Err({ERR}::custom({msg:?})),"
                );
            }
            // Inline the binding so the emitted `format!` is clippy-clean.
            let fmt = format!(
                "{spec_name}: unexpected `_type` {{__other:?}} (expected one of: {expected})"
            );
            let _ = writeln!(
                b,
                "::core::option::Option::Some(__other) => ::core::result::Result::Err({ERR}::custom(::std::format!({fmt:?}))),"
            );
            b.push_str("}\n");
        }
        JsonEnumDispatch::Structural { variant_idents: sv } => {
            // Structural `#[serde(untagged)]` fallback: try each variant in
            // declaration order, first success wins.
            let _ = writeln!(
                b,
                "// no `_type` on the targets — structural untagged: first matching variant wins."
            );
            let _ = variant_idents; // ToJson-order idents; `sv` is the same list
            for ident in sv {
                // `.map(Constructor)` pins the payload type, so the target
                // `FromJson` impl resolves without a turbofish.
                let _ = writeln!(
                    b,
                    "if let ::core::result::Result::Ok(__v) = {FROM_JSON}::from_json(node).map({prelude}::{rust}::{ident}) {{ return ::core::result::Result::Ok(__v); }}"
                );
            }
            let _ = writeln!(
                b,
                "::core::result::Result::Err({ERR}::custom(\"no variant of `{rust}` matched the JSON value\"))"
            );
        }
    }
    b.push_str("}\n}\n\n");
}
