//! XML emitter: emits `impl ToXml` + `impl FromXml` for the generated
//! RM/BASE spec types, into `openehr-its/src/xml/generated/`.
//!
//! The Rust facts (field idents, exact field types, enum variants, generics)
//! come from [`Model::xml_types`]; the wire shape (element order, attribute-vs-
//! element split for serialization, `xsi:type` slots) comes from the
//! [`XsdModel`]. Fields are matched to XSD elements/attributes by openEHR
//! property name; a struct absent from the XSD serializes in BMM field order
//! with no attributes. Deserialization dispatches child elements by name (order
//! -independent) and polymorphic slots by `xsi:type`.

use crate::analyze::Model;
use crate::load::bmm::BmmSchema;
use crate::load::xsd::XsdModel;
use crate::plan::construction;
use crate::plan::overrides::xml_bmm_only_allowed;
use crate::plan::{XmlField, XmlType};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// One spec GENERATION paired with the crate+generation root its types are
/// named from.
pub(crate) struct XmlSchema<'a> {
    pub model: &'a Model,
    pub schema: &'a BmmSchema,
    /// The generation root every type of this schema is named under — crate
    /// ident plus generation module, e.g. `openehr_rm::v1_2`. Impls name each
    /// type by its full defining-module path (never a prelude).
    pub root: &'a str,
    /// The generation's cross-crate index — resolves a `@SPEC` construction
    /// door parameter to the PAIRED dependency generation's defining module.
    pub external: &'a crate::analyze::External,
}

/// Resolves one construction-door parameter type for an [`XmlSchema`]: a
/// `@SPEC` marker becomes the generation-correct full type path (this
/// generation's own module when it declares the class, else the paired
/// dependency generation's); any other string passes through as a literal
/// Rust type.
///
/// # Panics
/// Panics when a marker names a class neither this generation nor its paired
/// dependencies emit — a construction-table bug.
fn door_param(s: &XmlSchema<'_>, ty: &str) -> String {
    let Some(spec) = ty.strip_prefix('@') else {
        return ty.to_owned();
    };
    let ident = crate::render::naming::type_name(spec);
    if s.schema.classes.contains_key(spec) {
        return format!(
            "{}::{}::{ident}",
            s.root,
            crate::render::emit::type_module_path(s.schema, spec)
        );
    }
    let module = s.external.module_of(spec).unwrap_or_else(|| {
        panic!(
            "construction door parameter @{spec}: neither the declaring generation nor its \
             paired dependency generations emit this class (a plan::construction table bug)"
        )
    });
    format!("{module}::{ident}")
}

/// The spec class an [`XmlType`] realizes — the key its Rust path is resolved
/// by.
fn xml_type_spec(ty: &XmlType) -> &str {
    match ty {
        XmlType::Struct { spec, .. }
        | XmlType::Enum { spec, .. }
        | XmlType::Newtype { spec, .. }
        | XmlType::EnumLiterals { spec, .. } => spec,
    }
}

/// Emit the whole generated impl file. `unmatched` receives `(type, element)`
/// pairs the XSD declared for serialization but BMM has no field for (skipped).
///
/// # Errors
/// Fails codegen (the LOCATABLE-attribute guard) if any emitted LOCATABLE subtype
/// would serialize `archetype_node_id` as a child element rather than the required
/// XML attribute (i.e. its XSD closure is missing, so it falls back to
/// attribute-less BMM order).
pub(crate) fn emit_file(
    schemas: &[XmlSchema<'_>],
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) -> Result<String, String> {
    let mut b = String::new();
    // `unused_qualifications`: the emitted impls name every runtime item by its
    // full path so the emitter never has to reason about import scope — inherent
    // to text generation, not a defect in the output.
    // The whole set is ONE file-level `#![allow(…, reason = "…")]`: `reason` is
    // mandatory (`clippy::allow_attributes_without_reason` is deny workspace-
    // wide), an inner attribute is exempt from `clippy::allow_attributes`, and
    // `expect` is wrong for a blanket list because no single emission triggers
    // every listed lint.
    b.push_str(
        "// @generated by openehr-codegen (emit-xml) — DO NOT EDIT.\n\
         // Canonical-XML `ToXml`/`FromXml` impls for the RM/BASE spec types.\n\n\
         #![allow(\n    \
         clippy::all,\n    \
         clippy::pedantic,\n    \
         clippy::nursery,\n    \
         unused_variables,\n    \
         unused_mut,\n    \
         unused_qualifications,\n    \
         unused_imports,\n    \
         reason = \"mechanically generated codec text: every runtime item is named \
         by its full path and every branch shape is emitted uniformly, so style \
         and unused-binding lints do not apply — the hand-written runtime carries \
         the lint bar\"\n\
         )]\n\
         use crate::xml::runtime::{ToXml, FromXml, XmlEvent, XmlError};\n\n",
    );
    let mut locatable_violations: Vec<String> = Vec::new();
    let mut bmm_only_violations: Vec<String> = Vec::new();
    let mut appended: Vec<String> = Vec::new();
    for s in schemas {
        for ty in s.model.xml_types(s.schema) {
            check_locatable_attr(&ty, xsd, &mut locatable_violations);
            check_bmm_field_coverage(&ty, xsd, &mut bmm_only_violations);
            if let XmlType::Struct { spec, fields, .. } = &ty {
                for f in bmm_only_fields(spec, fields, xsd) {
                    appended.push(format!("{spec}.{}", f.wire_name));
                }
            }
            let path = format!(
                "{}::{}",
                s.root,
                crate::render::emit::type_module_path(s.schema, xml_type_spec(&ty))
            );
            emit_to_xml(&mut b, &ty, &path, xsd, unmatched);
            emit_from_xml(&mut b, &ty, &path, xsd, Some(s));
        }
    }
    if !appended.is_empty() {
        eprintln!(
            "emit-xml: {} allowlisted BMM-only field(s) appended as trailing \
             canonical-XML elements (RM 1.2.0 / BASE 1.3.0 vs vendored ITS-XML skew): {}",
            appended.len(),
            appended.join(", ")
        );
    }
    if !locatable_violations.is_empty() {
        return Err(format!(
            "emit-xml LOCATABLE-attribute guard: {} LOCATABLE subtype(s) have no XSD closure, so \
             `archetype_node_id` would serialize as a child element instead of the required \
             XML attribute: {}. Extend the XSD input (tools/openehr-codegen/src/load/xsd.rs) so \
             these types reach `LOCATABLE`.",
            locatable_violations.len(),
            locatable_violations.join(", ")
        ));
    }
    if !bmm_only_violations.is_empty() {
        return Err(format!(
            "emit-xml BMM-field-coverage guard: {} BMM field(s) of XSD-covered type(s) have no \
             matching XSD element/attribute, so the XSD-driven `ToXml` would silently drop them \
             while the BMM-driven `FromXml` still reads them (an undetectable JSON/XML \
             divergence). Either extend the driving XSD input (tools/openehr-codegen/src/load/xsd.rs) \
             so the field gets a deterministic slot, or add it to `XML_BMM_ONLY_ALLOWLIST` in \
             plan/overrides.rs (with a spec-delta citation) to have it appended as a trailing \
             canonical-XML element. Fields: {}.",
            bmm_only_violations.len(),
            bmm_only_violations.join(", ")
        ));
    }
    Ok(b)
}

/// The LOCATABLE-attribute guard: any emitted struct carrying an
/// `archetype_node_id` field (per the BMM, a LOCATABLE subtype) must have that
/// field classified as an XML **attribute** by the driving XSD. `LOCATABLE`
/// declares `archetype_node_id`
/// `use="required"` (an attribute); a type whose XSD closure is missing falls
/// back to attribute-less BMM field order and would emit it as a child element —
/// invalid canonical XML. Record the violation so codegen fails loudly.
fn check_locatable_attr(ty: &XmlType, xsd: &XsdModel, violations: &mut Vec<String>) {
    if let XmlType::Struct { spec, fields, .. } = ty {
        let has_archetype_node_id = fields.iter().any(|f| f.wire_name == "archetype_node_id");
        if has_archetype_node_id && !attr_names(spec, xsd).contains("archetype_node_id") {
            violations.push(spec.clone());
        }
    }
}

/// `(impl<…: Bound> , <…>)` — the impl-generics header and the type-args suffix.
fn generic_header(generics: &[String], bound: &str) -> (String, String) {
    if generics.is_empty() {
        (String::new(), String::new())
    } else {
        let bounded = generics
            .iter()
            .map(|g| format!("{g}: {bound}"))
            .collect::<Vec<_>>()
            .join(", ");
        (format!("<{bounded}>"), format!("<{}>", generics.join(", ")))
    }
}

/// A local accumulator variable name for a field. Strips the `r#` raw-identifier
/// prefix (`r#type` → `__type`) since `__r#type` is not a valid identifier.
fn acc_var(rust_name: &str) -> String {
    format!("__{}", rust_name.trim_start_matches("r#"))
}

/// XSD attribute names for a type (empty if the type is not in the XSD).
fn attr_names(spec: &str, xsd: &XsdModel) -> BTreeSet<String> {
    if xsd.types.contains_key(spec) {
        xsd.flattened(spec)
            .0
            .iter()
            .map(|a| a.name.clone())
            .collect()
    } else {
        BTreeSet::new()
    }
}

/// The BMM-only fields of an XSD-covered struct: those whose `wire_name` matches
/// **no** XSD attribute or element, in BMM field order. These are the fields
/// `ToXml` (XSD-driven) would silently drop while `FromXml` (BMM-driven) still
/// reads. For a struct **not** in the XSD the emitter already walks the full BMM
/// field set (attribute-less BMM order), so nothing is dropped there and this
/// returns empty.
fn bmm_only_fields<'a>(spec: &str, fields: &'a [XmlField], xsd: &XsdModel) -> Vec<&'a XmlField> {
    if !xsd.types.contains_key(spec) {
        return Vec::new();
    }
    let (attrs, elems) = xsd.flattened(spec);
    let mut covered: BTreeSet<&str> = BTreeSet::new();
    for a in &attrs {
        covered.insert(a.name.as_str());
    }
    for e in &elems {
        covered.insert(e.name.as_str());
    }
    fields
        .iter()
        .filter(|f| !covered.contains(f.wire_name.as_str()))
        .collect()
}

/// The BMM-field-coverage guard: for every emitted XSD-covered struct, any BMM
/// field with no XSD slot must be on the
/// [`crate::plan::overrides::XML_BMM_ONLY_ALLOWLIST`]. An un-allowlisted field
/// would be dropped by the XSD-driven `ToXml` while still read by the BMM-driven
/// `FromXml` (a silent JSON/XML divergence no round-trip gate can see, because
/// both serializations omit it). Record every such field so codegen fails with
/// the complete reconciliation list — the mirror of [`check_locatable_attr`].
fn check_bmm_field_coverage(ty: &XmlType, xsd: &XsdModel, violations: &mut Vec<String>) {
    if let XmlType::Struct { spec, fields, .. } = ty {
        for f in bmm_only_fields(spec, fields, xsd) {
            if !xml_bmm_only_allowed(spec, &f.wire_name) {
                violations.push(format!("{spec}.{}", f.wire_name));
            }
        }
    }
}

// ── serialization ─────────────────────────────────────────────────────────────

/// Emit `impl ToXml` for one [`XmlType`]. Public so the OPT emitter
/// (`emit_opt`) can reuse it over XSD-derived [`XmlType`]s.
pub(crate) fn emit_to_xml(
    b: &mut String,
    ty: &XmlType,
    path: &str,
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) {
    match ty {
        XmlType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::ToXml");
            let by_wire: BTreeMap<&str, &XmlField> =
                fields.iter().map(|f| (f.wire_name.as_str(), f)).collect();
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {path}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ \"{spec}\" }}\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 let mut __attrs: Vec<(&str, String)> = Vec::new();\n\
                 if let Some(d) = declared {{ if d != \"{spec}\" {{ __attrs.push((\"xsi:type\", \"{spec}\".to_string())); }} }}\n"
            );
            // Wire order + attr/element split from the XSD; else BMM order, no attrs.
            let (attrs, mut elems): (Vec<String>, Vec<String>) = if xsd.types.contains_key(spec) {
                let (a, e) = xsd.flattened(spec);
                (
                    a.iter().map(|x| x.name.clone()).collect(),
                    e.iter().map(|x| x.name.clone()).collect(),
                )
            } else {
                (
                    Vec::new(),
                    fields.iter().map(|f| f.wire_name.clone()).collect(),
                )
            };
            // append any allowlisted BMM-only field (no XSD slot) as a
            // deterministic trailing element in BMM order, so it is not dropped.
            // (Non-allowlisted BMM-only fields already failed the guard above.)
            for f in bmm_only_fields(spec, fields, xsd) {
                elems.push(f.wire_name.clone());
            }
            // A validated class's fields are `pub(crate)` (the construction-door
            // scheme), so this codec — a different crate — reads them through the
            // emitted accessor.
            let validated = construction::is_validated(spec);
            let read = |f: &XmlField| {
                if validated {
                    format!("{}()", f.rust_name)
                } else {
                    f.rust_name.clone()
                }
            };
            for aname in &attrs {
                if let Some(f) = by_wire.get(aname.as_str()) {
                    if f.optional {
                        let _ = writeln!(
                            b,
                            "if let Some(v) = &self.{} {{ __attrs.push((\"{}\", v.to_string())); }}",
                            read(f),
                            f.wire_name
                        );
                    } else {
                        let _ = writeln!(
                            b,
                            "__attrs.push((\"{}\", self.{}.to_string()));",
                            f.wire_name,
                            read(f)
                        );
                    }
                } else {
                    unmatched.push((spec.clone(), aname.clone()));
                }
            }
            b.push_str("let mut __e = quick_xml::events::BytesStart::new(tag);\n");
            b.push_str("for (k, v) in &__attrs { __e.push_attribute((*k, v.as_str())); }\n");
            b.push_str("w.write_start(__e)?;\n");
            for ename in &elems {
                match by_wire.get(ename.as_str()) {
                    Some(f) => emit_write_field(b, f, validated),
                    None => unmatched.push((spec.clone(), ename.clone())),
                }
            }
            b.push_str("w.write_end(tag)?;\nOk(())\n}\n}\n\n");
        }
        XmlType::Enum {
            rust,
            generics,
            variants,
            ..
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::ToXml");
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {path}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ match self {{\n"
            );
            for v in variants {
                let _ = writeln!(b, "{path}::{rust}::{}(x) => x.xml_type_name(),", v.ident);
            }
            b.push_str("} }\n");
            b.push_str("fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> { match self {\n");
            for v in variants {
                let _ = writeln!(
                    b,
                    "{path}::{rust}::{}(x) => x.write_xml(w, tag, declared),",
                    v.ident
                );
            }
            b.push_str("} }\n}\n\n");
        }
        XmlType::Newtype { rust, .. } => {
            let _ = write!(
                b,
                "impl crate::xml::runtime::ToXml for {path}::{rust} {{\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, _declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 w.write_text_element(tag, &self.0.to_string())\n}}\n}}\n\n"
            );
        }
        XmlType::EnumLiterals {
            rust,
            string_backed,
            ..
        } => {
            // Write the enum's wire token/integer as element text — byte-identical
            // to the primitive it replaces (`as_str` = the constant token, `value`
            // = the constant integer; the verbatim payload for `Other`).
            let text = if *string_backed {
                "w.write_text_element(tag, self.as_str())"
            } else {
                "w.write_text_element(tag, &self.value().to_string())"
            };
            let _ = write!(
                b,
                "impl crate::xml::runtime::ToXml for {path}::{rust} {{\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, _declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 {text}\n}}\n}}\n\n"
            );
        }
    }
}

fn emit_write_field(b: &mut String, f: &XmlField, validated: bool) {
    // A validated class reads its `pub(crate)` fields through the emitted
    // accessor (see the construction-door scheme in `plan::construction`).
    let accessor = |name: &str| {
        if validated {
            format!("{name}()")
        } else {
            name.to_owned()
        }
    };
    // `Hash` (RM `Hash<String,String>`, → `BTreeMap`) and `OrderedDict` (the OPT
    // `StringDictionaryItem` group, → `IndexMap`) share the same
    // `<name id="key">value</name>` wire shape; only the map container differs,
    // and both iterate as `(k, v)` here.
    if f.target == "Hash" || f.target == "OrderedDict" {
        let rust = accessor(&f.rust_name);
        let (name, rust) = (&f.wire_name, &rust);
        if f.map_value.as_deref() == Some("String") {
            // `Hash<String, String>` → repeated `<name id="key">value</name>`
            // (the openEHR `StringDictionaryItem` shape).
            if f.optional {
                let _ = writeln!(
                    b,
                    "if let Some(m) = &self.{rust} {{ for (k, v) in m {{ w.write_kv_element(\"{name}\", k, v)?; }} }}"
                );
            } else {
                let _ = writeln!(
                    b,
                    "for (k, v) in &self.{rust} {{ w.write_kv_element(\"{name}\", k, v)?; }}"
                );
            }
        } else {
            // `Hash<String, ComplexType>` (translations, RESOURCE_ANNOTATIONS):
            // archetype-resource metadata serialized via ADL/AOM, off the RM
            // canonical-XML wire; its RM-XML shape is not spec-defined here.
            let _ = writeln!(
                b,
                "// NOTE: Hash<String, {}> field `{rust}` is off the RM canonical-XML wire (resource metadata); not serialized.",
                f.map_value.as_deref().unwrap_or("?")
            );
        }
        return;
    }
    let rust = accessor(&f.rust_name);
    let (name, rust, target) = (&f.wire_name, &rust, &f.target);
    if f.multiple && f.optional {
        // An optional container (`Option<Vec<T>>`). Canonical XML has no
        // representation for "the attribute is present but holds zero members"
        // — a repeated element with zero occurrences IS absence — so `None` and
        // `Some(vec![])` both write nothing, and the reader maps zero
        // occurrences back to `None` (`emit_from_xml` below). The
        // present-but-empty state is JSON-only by the wire's own shape.
        let _ = writeln!(
            b,
            "if let Some(vs) = &self.{rust} {{ for v in vs {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }} }}"
        );
    } else if f.multiple {
        let _ = writeln!(
            b,
            "for v in &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else if f.optional {
        let _ = writeln!(
            b,
            "if let Some(v) = &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else {
        let _ = writeln!(
            b,
            "self.{rust}.write_xml(w, \"{name}\", Some(\"{target}\"))?;"
        );
    }
}

// ── deserialization ─────────────────────────────────────────────────────────

/// Emit `impl FromXml` for one [`XmlType`]. Public so the OPT emitter
/// (`emit_opt`) can reuse it over XSD-derived [`XmlType`]s.
pub(crate) fn emit_from_xml(
    b: &mut String,
    ty: &XmlType,
    path: &str,
    xsd: &XsdModel,
    door_env: Option<&XmlSchema<'_>>,
) {
    match ty {
        XmlType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::FromXml");
            let attrs = attr_names(spec, xsd);
            let is_attr = |f: &XmlField| attrs.contains(&f.wire_name);
            // `Hash<String, String>` / `OrderedDict` are parsed inline
            // (StringDictionaryItem); `Hash<String, ComplexType>` is off-wire and
            // defaulted. `OrderedDict` (OPT `opt14`) accumulates into an
            // order-preserving `IndexMap`; `Hash` (RM) into a `BTreeMap`.
            let is_str_hash = |f: &XmlField| {
                (f.target == "Hash" || f.target == "OrderedDict")
                    && f.map_value.as_deref() == Some("String")
            };
            let is_cplx_hash =
                |f: &XmlField| f.target == "Hash" && f.map_value.as_deref() != Some("String");
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::FromXml for {path}::{rust}{args} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n"
            );
            // Accumulators for element fields. Types are intentionally left to
            // inference — each `__x` is pinned by its construction site below
            // (`field: __x…`), so boxing and type overrides resolve without
            // naming (and repeating the import of) the field type here.
            for f in fields.iter().filter(|f| !is_attr(f) && !is_cplx_hash(f)) {
                let var = acc_var(&f.rust_name);
                if is_str_hash(f) {
                    if f.target == "OrderedDict" {
                        let _ = writeln!(b, "let mut {var} = indexmap::IndexMap::new();");
                    } else {
                        let _ = writeln!(b, "let mut {var} = std::collections::BTreeMap::new();");
                    }
                } else if f.multiple {
                    let _ = writeln!(b, "let mut {var} = Vec::new();");
                } else {
                    let _ = writeln!(b, "let mut {var} = None;");
                }
            }
            b.push_str("loop { match reader.read()? {\n");
            b.push_str("crate::xml::runtime::XmlEvent::Start(__c) => match __c.name.as_str() {\n");
            for f in fields.iter().filter(|f| !is_attr(f) && !is_cplx_hash(f)) {
                let var = acc_var(&f.rust_name);
                if is_str_hash(f) {
                    // StringDictionaryItem: `<name id="key">value</name>`.
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ let __k = __c.attr(\"id\").unwrap_or(\"\").to_string(); let __v: String = crate::xml::runtime::FromXml::from_xml(reader, &__c)?; {var}.insert(__k, __v); }}",
                        f.wire_name
                    );
                } else if f.multiple {
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ {var}.push(crate::xml::runtime::FromXml::from_xml(reader, &__c)?); }}",
                        f.wire_name
                    );
                } else {
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ {var} = Some(crate::xml::runtime::FromXml::from_xml(reader, &__c)?); }}",
                        f.wire_name
                    );
                }
            }
            b.push_str("_ => reader.skip_element()?,\n},\n");
            b.push_str("crate::xml::runtime::XmlEvent::End => break,\n");
            b.push_str("crate::xml::runtime::XmlEvent::Text(_) => {}\n");
            b.push_str("crate::xml::runtime::XmlEvent::Eof => return Err(crate::xml::runtime::XmlError::Parse(\"unexpected EOF\".into())),\n");
            b.push_str("} }\n");
            // Construct. Each field's value expression is built first, so a
            // class with a validating construction door (`plan::construction`)
            // can hand the same expressions to its constructor instead of a
            // struct literal — one read path, one grammar.
            let mut values: Vec<(String, String)> = Vec::new();
            for f in fields {
                let fname = &f.rust_name;
                let expr = if is_attr(f) {
                    if f.optional {
                        format!("start.attr(\"{}\").map(|s| s.to_string())", f.wire_name)
                    } else {
                        format!(
                            "start.attr(\"{}\").ok_or_else(|| crate::xml::runtime::XmlError::Parse(\"missing attribute {}\".into()))?.to_string()",
                            f.wire_name, f.wire_name
                        )
                    }
                } else if is_cplx_hash(f) {
                    "Default::default()".to_owned()
                } else if is_str_hash(f) {
                    let var = acc_var(fname);
                    if f.optional {
                        format!("if {var}.is_empty() {{ None }} else {{ Some({var}) }}")
                    } else {
                        var
                    }
                } else if f.multiple && f.optional {
                    // Zero occurrences of a repeated element is indistinguishable
                    // from the attribute's absence in XML, so it reads back as
                    // `None` (see `emit_write_field`). A present-implies-non-empty
                    // field (`Option<NonEmptyVec<T>>`, #1730) builds through the
                    // fallible constructor — the branch guarantees non-emptiness,
                    // so the error arm is unreachable but honest.
                    let var = acc_var(fname);
                    if f.nonempty {
                        format!(
                            "if {var}.is_empty() {{ None }} else {{ Some(openehr_base::containers::NonEmptyVec::new({var}).map_err(|__e| crate::xml::runtime::XmlError::Parse(::std::format!(\"element {}: {{__e}}\", ).into()))?) }}",
                            f.wire_name
                        )
                    } else {
                        format!("if {var}.is_empty() {{ None }} else {{ Some({var}) }}")
                    }
                } else if f.nonempty {
                    // A `1..*` container goes through its own constructor, so a
                    // document with zero occurrences is refused at parse.
                    format!(
                        "openehr_base::containers::NonEmptyVec::new({}).map_err(|__e| crate::xml::runtime::XmlError::Parse(::std::format!(\"element {}: {{__e}}\", ).into()))?",
                        acc_var(fname),
                        f.wire_name
                    )
                } else if f.multiple || f.optional {
                    acc_var(fname)
                } else if let Some(default) = &f.default {
                    // Mandatory field archie omits at its default (Interval flags):
                    // use the default when the element is absent.
                    format!("{}.unwrap_or({default})", acc_var(fname))
                } else {
                    format!(
                        "{}.ok_or_else(|| crate::xml::runtime::XmlError::Parse(\"missing element {}\".into()))?",
                        acc_var(fname),
                        f.wire_name
                    )
                };
                values.push((fname.clone(), expr));
            }
            if let Some((params, fallible)) = construction::validated_ctor(spec) {
                {
                    assert_eq!(
                        params.len(),
                        values.len(),
                        "construction map declares {} constructor parameter(s) for {spec}, \
                         but the XML field view has {} field(s)",
                        params.len(),
                        values.len()
                    );
                    // Bind each read BY FIELD NAME to a local of the
                    // constructor's DECLARED parameter type (no inference
                    // ambiguity), calling in the table's declared order — one
                    // canonical door signature across generations whose BMMs
                    // declare the fields in different orders.
                    let mut names = Vec::new();
                    for (i, (param, ty)) in params.iter().enumerate() {
                        let Some((_, expr)) = values.iter().find(|(fname, _)| fname == param)
                        else {
                            panic!(
                                "construction map parameter {param:?} of {spec} names no \
                                 XML field (fields: {:?})",
                                values.iter().map(|(f, _)| f).collect::<Vec<_>>()
                            )
                        };
                        let ty = if let Some(env) = door_env {
                            door_param(env, ty)
                        } else {
                            assert!(
                                !ty.starts_with('@'),
                                "door class {spec} with a @-typed parameter emitted without \
                                 a door environment (an emit-opt closure generating a door \
                                 class is a table/closure bug)"
                            );
                            (*ty).to_owned()
                        };
                        let _ = writeln!(b, "let __a{i}: {ty} = {expr};");
                        names.push(format!("__a{i}"));
                    }
                    let args = names.join(", ");
                    if fallible {
                        let _ = writeln!(
                            b,
                            "{path}::{rust}::new({args}).map_err(|__e| crate::xml::runtime::XmlError::Parse(::std::format!(\"{spec}: {{__e}}\").into()))"
                        );
                    } else {
                        let _ = writeln!(b, "Ok({path}::{rust}::new({args}))");
                    }
                }
            } else {
                let _ = writeln!(b, "Ok({path}::{rust} {{");
                for (fname, expr) in &values {
                    let _ = writeln!(b, "{fname}: {expr},");
                }
                b.push_str("})\n");
            }
            b.push_str("}\n}\n\n");
        }
        XmlType::Enum {
            spec,
            rust,
            generics,
            dispatch,
            ..
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::FromXml");
            let self_ident = dispatch
                .iter()
                .find(|(x, _)| x == spec)
                .map(|(_, i)| i.clone());
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::FromXml for {path}::{rust}{args} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n\
                 match start.xsi_type() {{\n"
            );
            for (xsi, ident) in dispatch {
                let _ = writeln!(
                    b,
                    "Some(\"{xsi}\") => Ok({path}::{rust}::{ident}(crate::xml::runtime::FromXml::from_xml(reader, start)?)),"
                );
            }
            match self_ident {
                Some(ident) => {
                    let _ = writeln!(
                        b,
                        "None => Ok({path}::{rust}::{ident}(crate::xml::runtime::FromXml::from_xml(reader, start)?)),"
                    );
                }
                None => {
                    let _ = writeln!(
                        b,
                        "None => Err(crate::xml::runtime::XmlError::Parse(\"{rust}: missing xsi:type\".into())),"
                    );
                }
            }
            let _ = writeln!(
                b,
                "Some(other) => Err(crate::xml::runtime::XmlError::Parse(format!(\"{rust}: unknown xsi:type {{other}}\"))),"
            );
            b.push_str("}\n}\n}\n\n");
        }
        XmlType::Newtype { rust, .. } => {
            let _ = write!(
                b,
                "impl crate::xml::runtime::FromXml for {path}::{rust} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n\
                 Ok({path}::{rust}(crate::xml::runtime::FromXml::from_xml(reader, start)?))\n}}\n}}\n\n"
            );
        }
        XmlType::EnumLiterals {
            rust,
            string_backed,
            ..
        } => {
            // Read the bare primitive back, then map it through the total
            // `from_wire`/`from_value` (an unknown token/integer becomes `Other`).
            let body = if *string_backed {
                format!(
                    "let __s = <::std::string::String as crate::xml::runtime::FromXml>::from_xml(reader, start)?;\nOk({path}::{rust}::from_wire(&__s))"
                )
            } else {
                format!(
                    "let __v = <i32 as crate::xml::runtime::FromXml>::from_xml(reader, start)?;\nOk({path}::{rust}::from_value(__v))"
                )
            };
            let _ = write!(
                b,
                "impl crate::xml::runtime::FromXml for {path}::{rust} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n\
                 {body}\n}}\n}}\n\n"
            );
        }
    }
}
