//! REST emitter: OAS → the Rust *contract* for one API group, into
//! `openehr-its/src/rest/generated/`.
//!
//! Spec-first: the vendored `-codegen` OAS is the source of truth. For each API
//! group this emits the transport DTOs (the non-RM component schemas), a param
//! struct per operation, an `#[async_trait]` server trait (one typed method per
//! operation), and a route table `(method, path, operationId)`. RM payload
//! schemas resolve to the generated `openehr_rm`/`openehr_base` crates rather
//! than being re-emitted. `ehrbase-rest` implements the trait and wires axum
//! (the handler logic is the ported `EHRbase` behaviour — not generatable).

use crate::load::oas::{Oas, Operation};
use crate::render::naming;
use serde_json::Value;
use std::collections::BTreeSet;
use std::fmt::Write as _;

/// Map non-`[A-Za-z0-9_]` chars to `_` (a valid-ident base).
fn clean(raw: &str) -> String {
    raw.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// A proper `snake_case` Rust field ident for an OAS property/param name, then
/// keyword-escaped. Handles camelCase (`minOp` → `min_op`), acronym runs
/// (`SNOMED-CT` → `snomed_ct`), and separators (`Content-Type` → `content_type`,
/// `view:pass_through` → `view_pass_through`). A leading `_` (metadata keys like
/// `_type`) is preserved. Pair with a `#[serde(rename)]` to keep the wire name.
fn field_id(raw: &str) -> String {
    let leading_us = raw.starts_with('_');
    let mut out = String::new();
    let mut prev_alnum_lower = false;
    for c in raw.chars() {
        if c.is_ascii_uppercase() {
            if prev_alnum_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_alnum_lower = false;
        } else if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_alnum_lower = true;
        } else {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            prev_alnum_lower = false;
        }
    }
    let mut s = out.trim_matches('_').to_string();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    if leading_us {
        s.insert(0, '_');
    }
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    naming::field_ident(&s)
}

/// A Rust type ident for an OAS operation name (`operationId`s are snake, so
/// `type_name` gives `PascalCase`). Non-ident chars (`adl1.4`) map to `_` first.
fn type_id(raw: &str) -> String {
    naming::type_name(&clean(raw))
}

/// The Rust type name for an OAS DTO schema key. Keys are authored in
/// `PascalCase` (`ResultSet`, `OperationalTemplateV2`) and kept verbatim; an
/// all-uppercase acronym (`AQL`, `SNOMEDCT`) is title-cased (`Aql`, `Snomedct`)
/// so it is idiomatic Rust.
fn dto_type(raw: &str) -> String {
    let c = clean(raw);
    let alpha: String = c.chars().filter(char::is_ascii_alphabetic).collect();
    if !alpha.is_empty() && alpha.chars().all(|ch| ch.is_ascii_uppercase()) {
        naming::type_name(&c)
    } else {
        c
    }
}

/// Names emitted by the RM and BASE crates, to resolve OAS `$ref`s to preludes.
pub(crate) struct RmNames {
    pub rm: BTreeSet<String>,
    pub base: BTreeSet<String>,
}

/// Emit the generated module for one API group. `dtos` is the set of component
/// schema names this group defines that are *not* RM types (i.e. real DTOs).
#[must_use]
pub(crate) fn emit_group(oas: &Oas, group: &str, names: &RmNames) -> String {
    let trait_name = format!("{}Api", naming::type_name(group));
    // Component schemas split into RM-resolved vs local DTOs.
    let dtos: BTreeSet<String> = oas
        .schemas()
        .iter()
        .map(|(n, _)| n.clone())
        .filter(|n| !names.rm.contains(n) && !names.base.contains(n))
        .collect();
    let ctx = Ctx {
        oas,
        names,
        dtos: &dtos,
    };

    let mut b = String::new();
    let _ = write!(
        b,
        "// @generated by openehr-codegen (emit-rest) — DO NOT EDIT.\n\
         //! ITS-REST contract for the `{group}` API group: DTOs, per-operation\n\
         //! param structs, the `{trait_name}` server trait, and the route table.\n\n\
         #![allow(clippy::all, clippy::pedantic, clippy::nursery, dead_code, unused_variables)]\n\
         use serde::{{Deserialize, Serialize}};\n\n"
    );

    // ── DTOs ──
    for (name, schema) in oas.schemas() {
        if ctx.dtos.contains(&name) {
            emit_dto(&mut b, &name, schema, &ctx);
        }
    }

    // ── per-operation param structs ──
    let ops = oas.operations();
    for op in &ops {
        emit_params_struct(&mut b, op, &ctx);
    }

    // ── server trait ──
    let _ = write!(
        b,
        "/// Server contract for the `{group}` API group (ITS-REST). Every method\n\
         /// defaults to returning `ApiError::NotImplemented`, so an implementor\n\
         /// (the application service, or a test stub) overrides only the\n\
         /// operations it supports.\n\
         #[async_trait::async_trait]\n\
         pub trait {trait_name} {{\n"
    );
    for op in &ops {
        emit_trait_method(&mut b, op, &ctx);
    }
    b.push_str("}\n\n");

    // ── route table ──
    let _ = write!(
        b,
        "/// The operations of this group as `(method, path, operation_id)`, for\n\
         /// wiring an axum router in `ehrbase-rest`.\n\
         pub const ROUTES: &[(&str, &str, &str)] = &[\n"
    );
    for op in &ops {
        let _ = writeln!(
            b,
            "    (\"{}\", \"{}\", \"{}\"),",
            op.method.to_uppercase(),
            op.path,
            op.operation_id
        );
    }
    b.push_str("];\n");
    b
}

struct Ctx<'a> {
    oas: &'a Oas,
    names: &'a RmNames,
    dtos: &'a BTreeSet<String>,
}

impl Ctx<'_> {
    /// Map an OAS schema to a Rust type. RM `$ref`s resolve to the spec crate
    /// preludes; local DTO refs to the bare name; unknown/complex shapes degrade
    /// to `serde_json::Value` (the same honest fallback the BMM emitter uses).
    fn rust_type(&self, schema: &Value) -> String {
        // A `$ref` (possibly to a name we resolve without following it).
        if let Some(name) = Oas::ref_name(schema) {
            // RM/BASE spec types are opaque canonical-JSON payloads at the REST
            // boundary: the application exchanges `serde_json::Value` bodies and
            // validates them via the native codec + `openehr_its::rm_validate`.
            // The spec types carry no serde derive (the codec owns the wire), so
            // the contract DTOs carry any RM/BASE payload as an untyped `Value`
            // rather than the typed spec struct.
            if self.names.rm.contains(&name) || self.names.base.contains(&name) {
                return "serde_json::Value".to_string();
            }
            if self.dtos.contains(&name) {
                return dto_type(&name);
            }
            // A ref to something not emitted anywhere → resolve + map structurally.
            return self.rust_type(self.oas.resolve(schema));
        }
        match schema.get("type").and_then(Value::as_str) {
            Some("string") => "String".to_string(),
            Some("integer") => "i64".to_string(),
            Some("number") => "f64".to_string(),
            Some("boolean") => "bool".to_string(),
            Some("array") => {
                let item = schema.get("items").map_or_else(
                    || "serde_json::Value".to_string(),
                    |i| {
                        if i.as_object().is_some_and(serde_json::Map::is_empty) {
                            "serde_json::Value".to_string()
                        } else {
                            self.rust_type(self.oas.resolve(i))
                        }
                    },
                );
                format!("Vec<{item}>")
            }
            Some("object") => {
                if schema.get("properties").is_some() {
                    // An inline (anonymous) object — not named; carry as JSON.
                    "serde_json::Value".to_string()
                } else {
                    // A free map (`additionalProperties`).
                    "std::collections::BTreeMap<String, serde_json::Value>".to_string()
                }
            }
            // allOf/oneOf/anyOf and untyped → free-form JSON.
            _ => "serde_json::Value".to_string(),
        }
    }
}

fn emit_dto(b: &mut String, name: &str, schema: &Value, ctx: &Ctx) {
    let schema = ctx.oas.resolve(schema);
    // object with named properties → struct; everything else → an alias.
    if schema.get("type").and_then(Value::as_str) == Some("object")
        && let Some(props) = schema.get("properties").and_then(Value::as_object)
    {
        let ty_name = dto_type(name);
        // The vendored OAS `required` list, minus the docs-text-wins
        // corrections (`plan::overrides::REST_OPTIONAL_OVERRIDES` — the
        // ITS-REST docs text wins every conflict with the released OAS; where
        // it contradicts the OAS shape, the field is emitted optional).
        let required: BTreeSet<&str> = schema
            .get("required")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .filter(|f| crate::plan::overrides::rest_optional_override(&ty_name, f).is_none())
            .collect();
        let _ = write!(
            b,
            "/// The `{name}` transport DTO of this API group (an ITS-REST OAS\n\
             /// component schema).\n\
             #[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {ty_name} {{\n"
        );
        for (pname, pschema) in props {
            let ident = field_id(pname);
            let mut ty = ctx.rust_type(pschema);
            if !required.contains(pname.as_str()) {
                ty = format!("Option<{ty}>");
            }
            // A struct field is a public item `missing_docs` checks; the OAS
            // property name is the honest, deterministic summary.
            let _ = writeln!(b, "    /// The `{pname}` property of `{name}`.");
            // A docs-text-wins correction carries its citation into the
            // generated code (the OAS lists the field as required; the
            // ITS-REST docs text wins).
            if let Some(ov) = crate::plan::overrides::rest_optional_override(&ty_name, pname) {
                let _ = writeln!(b, "    /// OPTIONAL by the docs text — {}", ov.citation);
                let _ = writeln!(b, "    /// ({})", ov.reason);
            }
            if let Some(rename) = naming::serde_rename(pname, &ident) {
                let _ = writeln!(b, "    #[serde(rename = \"{rename}\")]");
            }
            let _ = writeln!(b, "    pub {ident}: {ty},");
        }
        b.push_str("}\n\n");
    } else {
        // string/array/map/ref alias.
        let _ = writeln!(
            b,
            "/// The `{name}` ITS-REST OAS component schema (a non-object shape, so\n\
             /// it is an alias rather than a struct).\n\
             pub type {} = {};\n",
            dto_type(name),
            ctx.rust_type(schema)
        );
    }
}

fn param_struct_name(op: &Operation) -> String {
    format!("{}Params", type_id(&op.operation_id))
}

fn emit_params_struct(b: &mut String, op: &Operation, ctx: &Ctx) {
    if op.parameters.is_empty() {
        return;
    }
    let sname = param_struct_name(op);
    let _ = write!(
        b,
        "/// Parameters for `{}` (path/query/header).\n\
         #[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {sname} {{\n",
        op.operation_id
    );
    for p in &op.parameters {
        let ident = field_id(&p.name);
        let mut ty = ctx.rust_type(&p.schema);
        if !p.required {
            ty = format!("Option<{ty}>");
        }
        if let Some(rename) = naming::serde_rename(&p.name, &ident) {
            let _ = writeln!(b, "    #[serde(rename = \"{rename}\")]");
        }
        let _ = writeln!(b, "    /// `{}` ({})", p.name, p.location);
        let _ = writeln!(b, "    pub {ident}: {ty},");
    }
    b.push_str("}\n\n");
}

fn emit_trait_method(b: &mut String, op: &Operation, ctx: &Ctx) {
    let method = field_id(&op.operation_id);
    let mut args = String::from("&self");
    if !op.parameters.is_empty() {
        let _ = write!(args, ", params: {}", param_struct_name(op));
    }
    if let Some((schema, required)) = &op.request_body {
        let ty = ctx.rust_type(schema);
        if *required {
            let _ = write!(args, ", body: {ty}");
        } else {
            let _ = write!(args, ", body: Option<{ty}>");
        }
    }
    let ret = op
        .success_body
        .as_ref()
        .map_or_else(|| "()".to_string(), |s| ctx.rust_type(s));
    // Emit a default body returning `NotImplemented` so an implementor overrides
    // only the operations it supports (no per-implementor stub boilerplate).
    let _ = writeln!(
        b,
        "    /// `{} {}`\n    async fn {method}({args}) -> Result<{ret}, crate::rest::runtime::ApiError> {{\n        Err(crate::rest::runtime::ApiError::NotImplemented)\n    }}",
        op.method.to_uppercase(),
        op.path
    );
}
