//! `emit-validate`: emit the **RM class-invariant cores** into `openehr-rm`
//! (`src/validate/generated.rs`), the single source both the typed `Validate`
//! impls (`*_impl.rs`) and the allocation-free fast path (`validate::fast`)
//! call for every mechanically-shaped RM class invariant.
//!
//! The cores' bodies are fixed spec logic (one `pub(crate) fn <name>_core` per
//! invariant group, each preserving the archie-style violation message verbatim
//! — see [`CORES`]); what the emitter derives from the vendored inputs is (a)
//! the `PROPORTION_KIND` codes, read from the RM BMM enumeration, and (b) the
//! **pending-adjudication register** — every RM class invariant the
//! assertion-dialect classifier ([`crate::analyze::invariants`]) marks
//! `runtime-hook-missing`, rendered as a doc note so the generated file honestly
//! accounts for the invariants no core yet realizes (nothing silently dropped).
//!
//! One generated file under `openehr-rm/src/validate/`; the hand-written
//! `validate.rs` declares `pub(crate) mod generated;` and keeps the runtime
//! helpers the cores call (`invariant_failed`, the ISO-8601 validators, the
//! dialect predicates).

use crate::analyze::Model;
use crate::analyze::invariants::{Bucket, classify};
use crate::load::bmm::{BmmEnumValue, BmmSchema};
use crate::render::emit::GenFile;

/// Emit the `validate/generated.rs` file for `openehr-rm` from the merged
/// BASE + RM model (for the `PROPORTION_KIND` codes) and the RM own schema (for
/// the class-invariant classification register).
#[must_use]
pub(crate) fn emit_files(model: &Model, own_schema: &BmmSchema) -> Vec<GenFile> {
    let mut body = String::new();
    body.push_str("// @generated by openehr-codegen (emit-validate) — DO NOT EDIT.\n");
    body.push_str(MODULE_DOC_INTRO);
    body.push_str(&pending_register(own_schema));
    body.push_str(MODULE_DOC_EXCLUDED);
    body.push('\n');
    body.push_str(IMPORTS);
    body.push('\n');
    body.push_str(&proportion_kind_consts(model));
    body.push('\n');
    body.push_str(CORES);
    vec![GenFile {
        path: "validate/generated.rs".to_string(),
        body,
    }]
}

/// The `PROPORTION_KIND` code constants, read from the RM BMM enumeration
/// (`pk_ratio = 0 … pk_integer_fraction = 4`). The `DV_PROPORTION` core compares
/// `kind` against the named codes rather than magic numbers.
fn proportion_kind_consts(model: &Model) -> String {
    let mut b = String::from(
        "// `PROPORTION_KIND` codes, generated from the RM BMM enumeration\n\
         // (`docs/specs/openehr/RM/docs/UML/classes/org.openehr.rm.data_types.proportion_kind.adoc`).\n",
    );
    let Some(class) = model.get("PROPORTION_KIND") else {
        return b;
    };
    let Some(e) = &class.enumeration else {
        return b;
    };
    for (i, name) in e.item_names.iter().enumerate() {
        let value = match e.item_values.as_ref().and_then(|v| v.get(i)) {
            Some(BmmEnumValue::Int(v)) => *v,
            _ => i64::try_from(i).unwrap_or_default(),
        };
        // `pk_ratio` (code 0) is the default kind with no dedicated invariant.
        if name == "pk_ratio" {
            b.push_str(
                "#[allow(dead_code)] // ratio (code 0) has no dedicated proportion invariant\n",
            );
        }
        b.push_str(&format!(
            "const {}: i32 = {value};\n",
            name.to_ascii_uppercase()
        ));
    }
    b
}

/// The pending-adjudication register: every RM class invariant the
/// assertion-dialect classifier marks `runtime-hook-missing`, one doc line each,
/// sorted `(class, name)`. Keeps the generated file honest — it names every
/// invariant no core realizes yet and why (the missing runtime hook).
fn pending_register(own_schema: &BmmSchema) -> String {
    let mut hooks: Vec<(String, String, &'static str)> = Vec::new();
    for (class, def) in &own_schema.classes {
        for (name, expr) in &def.invariants {
            if let Bucket::RuntimeHookMissing(reason) = classify(expr) {
                hooks.push((class.clone(), name.clone(), reason));
            }
        }
    }
    hooks.sort();
    let mut b = String::from(
        "//!\n\
         //! # Pending adjudication (runtime-hook-missing)\n\
         //!\n\
         //! These BMM class invariants are structurally within the dialect but each\n\
         //! needs a runtime hook the core layer cannot yet call (the openEHR\n\
         //! terminology service, a code-set, the demographic repository, or the\n\
         //! versioned-object aggregate model). No core realizes them here; they are\n\
         //! named so nothing is silently dropped:\n\
         //!\n",
    );
    for (class, name, reason) in &hooks {
        b.push_str(&format!("//! - `{class}.{name}` — {reason}.\n"));
    }
    b
}

/// The module-doc intro + the emitted-core inventory (the invariants the cores
/// below realize). Static text — the cores are fixed spec logic.
const MODULE_DOC_INTRO: &str = "\
//! RM class-invariant cores — the single source both the typed `Validate` impls
//! (`*_impl.rs`) and the allocation-free fast path (`validate::fast`) call. Each
//! core preserves the archie-style violation message (`Invariant <Name> failed
//! on type <RM_TYPE>`) so a failure is identifiable by its BMM invariant name.
//!
//! # Emitted cores
//!
//! - `code_phrase_core` — CODE_PHRASE `Code_string_valid`.
//! - `dv_text_core` — DV_TEXT / DV_CODED_TEXT `Valid_value`, `Formatting_valid`.
//! - `dv_uri_core` — DV_URI `Value_valid`.
//! - `dv_identifier_core` — DV_IDENTIFIER `Id_valid`.
//! - `term_mapping_core` — TERM_MAPPING `Match_valid`.
//! - `dv_parsable_core` — DV_PARSABLE `Formalism_valid`.
//! - `dv_amount_core` — DV_AMOUNT `Accuracy_is_percent_validity`,
//!   `Accuracy_validity` + DV_QUANTIFIED `Magnitude_status_valid`.
//! - `magnitude_status_core` — DV_QUANTIFIED `Magnitude_status_valid`.
//! - `temporal_value_core` — DV_DATE/DV_TIME/DV_DATE_TIME/DV_DURATION
//!   `Value_valid`.
//! - `dv_proportion_core` — DV_PROPORTION `Type_validity`, `Valid_denominator`,
//!   `Precision_validity`, `Fraction_validity`, `Unitary_validity`,
//!   `Percent_validity`.
//! - `archetype_node_id_core` — LOCATABLE `Archetype_node_id_valid`.
//! - `history_basic_core` — HISTORY `Events_valid` + inherited
//!   `Archetype_node_id_valid`.
//! - `composition_core` — COMPOSITION `Is_archetype_root` + inherited
//!   `Archetype_node_id_valid`.
//! - `entry_root_core` — ENTRY `Is_archetype_root` + inherited
//!   `Archetype_node_id_valid`.
//! - `activity_core` — ACTIVITY `Action_archetype_id_valid` + inherited
//!   `Archetype_node_id_valid`.
//! - `event_context_core` — EVENT_CONTEXT `location_valid`.
//! - `archetyped_core` — ARCHETYPED `Rm_version_valid`.
//! - `party_identified_core` — PARTY_IDENTIFIED / PARTY_RELATED `Basic_validity`,
//!   `Name_valid`.
//!
//! Complex invariants stay hand-written where the projection is non-trivial:
//! ELEMENT's null-flavour XOR (`element_impl`), DV_EHR_URI's `Scheme_valid`
//! extra (`dv_ehr_uri_impl`), HISTORY `Period_consistency` (typed-only, run
//! after `history_basic_core`), and DV_ORDERED
//! `Normal_range_and_status_consistency` (`dv_ordered_impl`).
";

/// The module-doc tail: the explicitly-excluded invariants (structural /
/// aggregate constraints realized outside the RM-crate core layer).
const MODULE_DOC_EXCLUDED: &str = "\
//!
//! # Explicitly excluded
//!
//! These RM invariants are not emitted even as pending-register entries: they
//! are aggregate/structural constraints realized outside the RM-crate invariant
//! core layer (the service/versioning layer, or structural typing):
//!
//! - `EHR.Ehr_status_valid`, `EHR.Ehr_access_valid`, `EHR.Directory_valid` —
//!   cross-object references resolved by the EHR service, not on the value.
//! - `VERSIONED_OBJECT.Uid_validity`, `VERSION.Preceding_version_uid_validity`,
//!   `REVISION_HISTORY_ITEM.Audit_valid` — the versioning aggregate model.
//! - `REFERENCE_RANGE.Range_is_simple` — a structural interval-shape constraint.
";

/// The imports the cores rely on, from the hand-written `validate.rs` parent.
const IMPORTS: &str = "\
use super::{
    InvariantViolation, invariant_failed, is_integral, valid_magnitude_status, valid_percentage,
    valid_proportion_kind,
};
";

/// The invariant cores — fixed spec logic, moved verbatim from the former
/// hand-written `push_*` siblings (same checks, same messages, `out` last).
const CORES: &str = r#"
/// CODE_PHRASE `Code_string_valid`: the code string must be non-empty.
pub(crate) fn code_phrase_core(code_string: &str, out: &mut Vec<InvariantViolation>) {
    if code_string.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Code_string_valid failed on type CODE_PHRASE",
        ));
    }
}

/// DV_TEXT / DV_CODED_TEXT `Valid_value` (non-empty rubric) and
/// `Formatting_valid` (present ⇒ non-empty). `ty` is `DV_TEXT` or
/// `DV_CODED_TEXT` (which inherits both).
pub(crate) fn dv_text_core(
    ty: &str,
    value: &str,
    formatting: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    if value.is_empty() {
        out.push(InvariantViolation::here(format!(
            "Invariant Valid_value failed on type {ty} (value must be non-empty)"
        )));
    }
    if formatting.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(format!(
            "Invariant Formatting_valid failed on type {ty}"
        )));
    }
}

/// DV_URI `Value_valid`: the URI value must be non-empty.
pub(crate) fn dv_uri_core(value: &str, out: &mut Vec<InvariantViolation>) {
    if value.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Value_valid failed on type DV_URI",
        ));
    }
}

/// DV_IDENTIFIER `Id_valid`: `id` must be non-empty.
pub(crate) fn dv_identifier_core(id: &str, out: &mut Vec<InvariantViolation>) {
    if id.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Id_valid failed on type DV_IDENTIFIER",
        ));
    }
}

/// TERM_MAPPING `Match_valid`: `match` must be one of `< = > ?`.
pub(crate) fn term_mapping_core(match_code: char, out: &mut Vec<InvariantViolation>) {
    if !crate::data_types::text::term_mapping::TermMapping::is_valid_match_code(match_code) {
        out.push(InvariantViolation::here(
            "Invariant Match_valid failed on type TERM_MAPPING",
        ));
    }
}

/// DV_PARSABLE `Formalism_valid`: `formalism` must be non-empty.
pub(crate) fn dv_parsable_core(formalism: &str, out: &mut Vec<InvariantViolation>) {
    if formalism.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Formalism_valid failed on type DV_PARSABLE",
        ));
    }
}

/// DV_QUANTIFIED `Magnitude_status_valid`: if present, `magnitude_status` must
/// be one of `= < > <= >= ~`.
pub(crate) fn magnitude_status_core(
    ty: &str,
    magnitude_status: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    if let Some(s) = magnitude_status
        && !valid_magnitude_status(s)
    {
        out.push(invariant_failed("Magnitude_status_valid", ty));
    }
}

/// The DV_AMOUNT invariants (`Accuracy_is_percent_validity`, `Accuracy_validity`)
/// plus the inherited DV_QUANTIFIED `Magnitude_status_valid`. Shared by every
/// concrete DV_AMOUNT descendant (DV_QUANTITY, DV_COUNT, DV_DURATION,
/// DV_PROPORTION).
#[allow(clippy::float_cmp)] // exact accuracy == 0 test, mirrors archie's `accuracy == 0.0`
pub(crate) fn dv_amount_core(
    ty: &str,
    accuracy: Option<f64>,
    accuracy_is_percent: Option<bool>,
    magnitude_status: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    // Accuracy_is_percent_validity: accuracy = 0 implies not recorded as percent.
    if accuracy == Some(0.0) && accuracy_is_percent == Some(true) {
        out.push(invariant_failed("Accuracy_is_percent_validity", ty));
    }
    // Accuracy_validity: recorded as percent implies 0 <= accuracy <= 100.
    if accuracy_is_percent == Some(true)
        && let Some(a) = accuracy
        && !valid_percentage(a)
    {
        out.push(invariant_failed("Accuracy_validity", ty));
    }
    magnitude_status_core(ty, magnitude_status, out);
}

/// The temporal `Value_valid` invariant: the string value must be a
/// well-formed ISO-8601 date/time/date-time/duration (caller supplies the
/// verdict via the ISO-8601 validators).
pub(crate) fn temporal_value_core(ty: &str, valid: bool, out: &mut Vec<InvariantViolation>) {
    if !valid {
        out.push(invariant_failed("Value_valid", ty));
    }
}

/// The DV_PROPORTION own invariants. The inherited DV_AMOUNT / DV_ORDERED
/// invariants are pushed by the callers.
// openEHR/archie compare denominator against 0/1/100 by exact value
// (`denominator.equals(0d)` etc.), so exact float comparison is intended.
#[allow(clippy::float_cmp)]
pub(crate) fn dv_proportion_core(
    numerator: f64,
    denominator: f64,
    kind: i32,
    precision: Option<i32>,
    out: &mut Vec<InvariantViolation>,
) {
    let integral = is_integral(numerator) && is_integral(denominator);

    // Type_validity: type in 0..=4.
    if !valid_proportion_kind(kind) {
        out.push(InvariantViolation::here(
            "Invariant Type_validity failed on type DV_PROPORTION",
        ));
    }
    // Valid_denominator: denominator != 0.
    if denominator == 0.0 {
        out.push(InvariantViolation::here(
            "Invariant Valid_denominator failed on type DV_PROPORTION",
        ));
    }
    // Precision_validity: precision 0 implies integral numerator & denominator.
    if precision == Some(0) && !integral {
        out.push(InvariantViolation::here(
            "Invariant Precision_validity failed on type DV_PROPORTION",
        ));
    }
    // Fraction_validity: fraction / integer_fraction kinds are integral.
    if (kind == PK_FRACTION || kind == PK_INTEGER_FRACTION) && !integral {
        out.push(InvariantViolation::here(
            "Invariant Fraction_validity failed on type DV_PROPORTION",
        ));
    }
    // Unitary_validity: unitary kind has denominator 1.
    if kind == PK_UNITARY && denominator != 1.0 {
        out.push(InvariantViolation::here(
            "Invariant Unitary_validity failed on type DV_PROPORTION",
        ));
    }
    // Percent_validity: percent kind has denominator 100.
    if kind == PK_PERCENT && denominator != 100.0 {
        out.push(InvariantViolation::here(
            "Invariant Percent_validity failed on type DV_PROPORTION",
        ));
    }
}

/// LOCATABLE `Archetype_node_id_valid`: `archetype_node_id` must be non-empty.
pub(crate) fn archetype_node_id_core(
    ty: &str,
    archetype_node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if archetype_node_id.is_empty() {
        out.push(invariant_failed("Archetype_node_id_valid", ty));
    }
}

/// The non-periodic HISTORY invariants: `Events_valid` (at least one event or a
/// summary) + inherited `Archetype_node_id_valid`. `Period_consistency` stays
/// typed-only (the fast path declines periodic histories).
pub(crate) fn history_basic_core(
    events_empty: bool,
    has_summary: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if events_empty && !has_summary {
        out.push(InvariantViolation::here(
            "Invariant Events_valid failed on type HISTORY",
        ));
    }
    archetype_node_id_core("HISTORY", node_id, out);
}

/// COMPOSITION `Is_archetype_root` (`archetype_details` present) + inherited
/// `Archetype_node_id_valid`.
pub(crate) fn composition_core(
    has_archetype_details: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if !has_archetype_details {
        out.push(InvariantViolation::here(
            "Invariant Is_archetype_root failed on type COMPOSITION",
        ));
    }
    archetype_node_id_core("COMPOSITION", node_id, out);
}

/// The shared ENTRY-root invariants: `Is_archetype_root` (an ENTRY is an
/// archetype root, so `archetype_details` must be present) + inherited
/// `Archetype_node_id_valid`. `ty` is the concrete ENTRY subtype.
pub(crate) fn entry_root_core(
    ty: &str,
    has_archetype_details: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if !has_archetype_details {
        out.push(invariant_failed("Is_archetype_root", ty));
    }
    archetype_node_id_core(ty, node_id, out);
}

/// ACTIVITY `Action_archetype_id_valid` (non-empty) + inherited
/// `Archetype_node_id_valid`.
pub(crate) fn activity_core(
    action_archetype_id: &str,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if action_archetype_id.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Action_archetype_id_valid failed on type ACTIVITY",
        ));
    }
    archetype_node_id_core("ACTIVITY", node_id, out);
}

/// EVENT_CONTEXT `location_valid`: if present, `location` must be non-empty.
pub(crate) fn event_context_core(location: Option<&str>, out: &mut Vec<InvariantViolation>) {
    if location.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(
            "Invariant location_valid failed on type EVENT_CONTEXT",
        ));
    }
}

/// ARCHETYPED `Rm_version_valid`: `rm_version` must be non-empty.
pub(crate) fn archetyped_core(rm_version: &str, out: &mut Vec<InvariantViolation>) {
    if rm_version.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Rm_version_valid failed on type ARCHETYPED",
        ));
    }
}

/// PARTY_IDENTIFIED / PARTY_RELATED `Basic_validity` (at least one of `name`,
/// `identifiers`, `external_ref`) and `Name_valid` (present ⇒ non-empty). `ty`
/// is `PARTY_IDENTIFIED` or `PARTY_RELATED` (which inherits both).
pub(crate) fn party_identified_core(
    ty: &str,
    name: Option<&str>,
    has_identifiers: bool,
    has_external_ref: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if name.is_none() && !has_identifiers && !has_external_ref {
        out.push(InvariantViolation::here(format!(
            "Invariant Basic_validity failed on type {ty}"
        )));
    }
    if name.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(format!(
            "Invariant Name_valid failed on type {ty}"
        )));
    }
}
"#;
