// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-License-Identifier: MIT

//! `emit-validate`: emit the **RM class-invariant cores** into `openehr-rm`
//! (`src/validate/generated.rs`), the single source both the typed `Validate`
//! impls (`*_impl.rs`) and the allocation-free fast path (`validate::fast`)
//! call for every mechanically-shaped RM class invariant.
//!
//! The cores' bodies are fixed spec logic (one `pub(crate) fn <name>_core` per
//! invariant group, each emitting the workspace's uniform violation message
//! shape verbatim — see [`CORES`]); what the emitter derives from the vendored
//! inputs is (a)
//! the `PROPORTION_KIND` codes, read from the RM BMM enumeration, (b) the
//! **emittable-invariant realization register** — every invariant the
//! assertion-dialect classifier ([`crate::analyze::invariants`]) marks
//! `emitted`, paired with the venue that realizes it (a core here, a hand-written
//! `*_impl.rs`, the `openehr-its` wire boundary, an adjudicated exclusion, or
//! nothing yet) — and (c) the **pending-adjudication register** — every
//! invariant the classifier marks `runtime-hook-missing`. Both registers render
//! as doc notes so the generated file honestly accounts for every classified
//! invariant, realized or not (nothing silently dropped).
//!
//! One generated file under `openehr-rm/src/validate/`; the hand-written
//! `validate.rs` declares `pub(crate) mod generated;` and keeps the runtime
//! helpers the cores call (`invariant_failed`, the ISO-8601 validators, the
//! dialect predicates).

use crate::analyze::Model;
use crate::analyze::invariants::{Bucket, classify};
use crate::load::bmm::{BmmEnumValue, BmmSchema};
use crate::plan::overrides::{InvariantVenue, RM_CLASS_DOCS, account_emitted};
use crate::render::emit::GenFile;

/// Emit the `validate/generated.rs` file for `openehr-rm` from the merged
/// BASE + RM model (for the `PROPORTION_KIND` codes) and the RM own schema (for
/// the class-invariant classification register).
#[must_use]
pub(crate) fn emit_files(model: &Model, own_schema: &BmmSchema) -> Vec<GenFile> {
    let mut body = String::new();
    body.push_str("// @generated by openehr-codegen (emit-validate) — DO NOT EDIT.\n");
    body.push_str(MODULE_DOC_INTRO);
    body.push_str(&realization_register(own_schema));
    body.push_str(&pending_register(own_schema));
    body.push('\n');
    body.push_str(IMPORTS);
    body.push('\n');
    body.push_str(&proportion_kind_consts(model));
    body.push('\n');
    body.push_str(&nonempty_list_rules(model));
    body.push('\n');
    body.push_str(CORES);
    vec![GenFile {
        path: "validate/generated.rs".to_string(),
        body,
    }]
}

/// The `PROPORTION_KIND` code constants, read from the RM BMM enumeration
/// (`pk_ratio = 0 … pk_integer_fraction = 4`). The `DV_PROPORTION` core compares
/// `kind` against the named codes rather than magic numbers.
fn proportion_kind_consts(model: &Model) -> String {
    let mut b = String::from(
        "// `PROPORTION_KIND` codes, generated from the RM BMM enumeration\n\
         // (`docs/specs/openehr/RM/docs/UML/classes/org.openehr.rm.data_types.proportion_kind.adoc`).\n",
    );
    let Some(class) = model.get("PROPORTION_KIND") else {
        return b;
    };
    let Some(e) = &class.enumeration else {
        return b;
    };
    for (i, name) in e.item_names.iter().enumerate() {
        let value = match e.item_values.as_ref().and_then(|v| v.get(i)) {
            Some(BmmEnumValue::Int(v)) => *v,
            _ => i64::try_from(i).unwrap_or_default(),
        };
        // `pk_ratio` (code 0) is the default kind with no dedicated invariant.
        if name == "pk_ratio" {
            b.push_str(
                "#[expect(dead_code, reason = \"ratio (code 0) has no dedicated proportion invariant\")]\n",
            );
        }
        b.push_str(&format!(
            "const {}: i32 = {value};\n",
            name.to_ascii_uppercase()
        ));
    }
    b
}

/// The **present-implies-non-empty rule table**, derived from the vendored BMM.
///
/// The `x /= Void implies not x.is_empty` invariant family has one uniform
/// assertion shape, so it is READ from the model rather than hand-listed: every
/// class invariant whose expression is exactly that shape, and whose named
/// attribute is a CONTAINER (a String-valued twin such as
/// `PARTY_IDENTIFIED.Name_valid` is a different rule, realized by its own core),
/// becomes a row `(class, attribute, invariant)`.
///
/// The evaluator (`openehr_rm::validate::nonempty_list_violations`) applies a
/// row to the class itself and to its transitive concrete descendants, so an
/// inherited rule (`LOCATABLE.Links_valid`, `DV_ORDERED.
/// Other_reference_ranges_validity`, `ENTRY.Other_participations_valid`) covers
/// every descendant without being restated — and a class the spec adds to the
/// hierarchy is covered the moment the model is regenerated.
fn nonempty_list_rules(model: &Model) -> String {
    let mut rows: Vec<(String, String, String)> = Vec::new();
    for (class_name, class) in &model.classes {
        for (invariant, expression) in &class.invariants {
            let Some(attribute) = crate::analyze::nonempty_list_attribute(expression) else {
                continue;
            };
            // Only a container attribute: the same assertion shape also guards
            // optional STRINGS, which are not this rule. An OPTIONAL container
            // carrying the invariant emits `Option<NonEmptyVec<T>>` (#1730 —
            // `analyze::nonempty_optional_lists`), so present-but-empty is
            // unrepresentable and the row would be dead: only a MANDATORY
            // container with the invariant (existence 1..1, cardinality lower
            // bound 0) still needs a runnable rule.
            if !class.properties.iter().any(|p| {
                p.name == attribute
                    && p.is_mandatory
                    && matches!(p.kind, crate::load::bmm::BmmPropKind::Container { .. })
            }) {
                continue;
            }
            rows.push((class_name.clone(), attribute, invariant.clone()));
        }
    }
    rows.sort();
    let mut b = String::from(
        "/// The `x /= Void implies not x.is_empty` rules, read from the vendored\n\
         /// BMM class invariants: `(class, attribute, invariant)`. Applied to the\n\
         /// class and its transitive concrete descendants by\n\
         /// [`super::nonempty_list_violations`].\n\
         pub(crate) const NONEMPTY_LIST_RULES: &[(&str, &str, &str)] = &[\n",
    );
    for (class, attribute, invariant) in rows {
        b.push_str(&format!(
            "    (\"{class}\", \"{attribute}\", \"{invariant}\"),\n"
        ));
    }
    b.push_str("];\n");
    b
}

/// The **emittable-invariant realization register**: every RM class invariant
/// the assertion-dialect classifier marks [`Bucket::Emitted`], paired with the
/// venue that realizes it (`plan::overrides::INVARIANT_REALIZATIONS`), grouped
/// by venue and sorted `(class, name)`.
///
/// The `Emitted` verdict says an expression *can* be evaluated mechanically —
/// not that anything evaluates it. Without this register an emittable invariant
/// realized nowhere reads exactly like one a core enforces, so it vanishes
/// silently (LOCATABLE `Links_valid` and `Archetyped_valid` did: both are
/// realized at the wire boundary, neither appears in any core). Rendering the
/// venue of every emittable invariant — including the two non-realizing
/// verdicts — makes the generated file account for the whole bucket, and an
/// invariant with no register row is rendered under an explicit
/// `UNACCOUNTED` heading (the emitter-invariant suite fails on a non-empty one).
fn realization_register(own_schema: &BmmSchema) -> String {
    let rows = account_emitted(own_schema.classes.iter().flat_map(|(class, def)| {
        def.invariants
            .iter()
            .map(move |(name, expr)| (class.as_str(), name.as_str(), expr.as_str()))
    }));

    let mut b = String::from(
        "//!\n\
         //! # Emittable-invariant realization register\n\
         //!\n\
         //! Every RM class invariant the assertion-dialect classifier judges\n\
         //! mechanically evaluable, with the venue that actually realizes it. A\n\
         //! `Core` row is realized by a core below; the other venues are realized\n\
         //! (or adjudicated) outside this file, and are listed so the emitted\n\
         //! bucket is accounted for in full rather than assumed.\n",
    );
    for venue in [
        InvariantVenue::Core,
        InvariantVenue::Impl,
        InvariantVenue::Wire,
        InvariantVenue::App,
        InvariantVenue::Excluded,
        InvariantVenue::Unrealized,
    ] {
        let group: Vec<_> = rows
            .iter()
            .filter_map(|r| r.realization.filter(|reg| reg.venue == venue))
            .collect();
        if group.is_empty() {
            continue;
        }
        b.push_str(&format!("//!\n//! ## {}\n//!\n", venue.heading()));
        for reg in group {
            let site = if reg.site.is_empty() {
                String::new()
            } else {
                format!(" — `{}`", reg.site)
            };
            b.push_str(&format!(
                "//! - `{}.{}`{site}: {} ({}/{} §Invariants).\n",
                reg.class, reg.name, reg.reason, RM_CLASS_DOCS, reg.spec_file,
            ));
        }
    }
    let unaccounted: Vec<_> = rows.iter().filter(|r| r.realization.is_none()).collect();
    if !unaccounted.is_empty() {
        b.push_str(
            "//!\n\
             //! ## UNACCOUNTED (classified emittable, no register row)\n\
             //!\n",
        );
        for r in unaccounted {
            b.push_str(&format!("//! - `{}.{}`.\n", r.class, r.name));
        }
    }
    b
}

/// The class-invariant runtime-hook register, split by adjudication verdict.
///
/// Every RM class invariant the assertion-dialect classifier marks
/// `runtime-hook-missing` needs a runtime lookup no generated core can express
/// mechanically. The terminology/code-set family is **enforced by the sibling
/// binding table** (`openehr-rm` `validate::terminology::validate_rm_terminology`,
/// over the openEHR terminology bundle, TERM 3.1.0), which the `openehr-its`
/// wire-boundary dispatcher runs as a post-core check — audited clean against
/// the whole corpus before enforcement. Only the versioned-object aggregate
/// invariants stay unrealized (they are a versioning/service-layer concern, not
/// a property of one node). Both groups are named here so nothing the classifier
/// flagged is silently dropped, sorted `(class, name)`.
fn pending_register(own_schema: &BmmSchema) -> String {
    let mut enforced: Vec<(String, String, &'static str)> = Vec::new();
    let mut aggregate: Vec<(String, String, &'static str)> = Vec::new();
    for (class, def) in &own_schema.classes {
        for (name, expr) in &def.invariants {
            if let Bucket::RuntimeHookMissing(reason) = classify(expr) {
                // The versioned-object aggregate invariants stay pending; the
                // terminology-service / code-set family is enforced by the
                // sibling `validate::terminology` binding table.
                if reason == "versioned-object aggregate model" {
                    aggregate.push((class.clone(), name.clone(), reason));
                } else {
                    enforced.push((class.clone(), name.clone(), reason));
                }
            }
        }
    }
    enforced.sort();
    aggregate.sort();

    let mut b = String::from(
        "//!\n\
         //! # Terminology-backed invariants (enforced in `validate::terminology`)\n\
         //!\n\
         //! These BMM class invariants bind a coded value to an openEHR terminology\n\
         //! group (`has_code_for_group_id`) or a code set (`code_set (id).has_code`),\n\
         //! so no generated core below can evaluate them mechanically. They are\n\
         //! realized instead by the sibling binding table —\n\
         //! `super::terminology::validate_rm_terminology`, over the openEHR\n\
         //! terminology bundle (TERM 3.1.0) — which the `openehr-its` wire-boundary\n\
         //! dispatcher runs as a post-core check. Enforcement was audited clean\n\
         //! against the whole corpus first, so none newly rejects previously-accepted\n\
         //! data:\n\
         //!\n",
    );
    for (class, name, reason) in &enforced {
        b.push_str(&format!(
            "//! - `{class}.{name}` — enforced in `validate::terminology` ({reason}).\n"
        ));
    }
    b.push_str(
        "//!\n\
         //! # Pending adjudication (runtime-hook-missing)\n\
         //!\n\
         //! The VERSIONED_OBJECT aggregate invariants quantify over the whole\n\
         //! version container (`all_versions`, `all_version_ids`, `version_count`,\n\
         //! `latest_version`) — a property of the versioning/service layer, not of\n\
         //! any single stored value node — so no per-node core can honestly\n\
         //! evaluate them (RM `common versioned_object.adoc` §Invariants). They stay\n\
         //! unrealized here:\n\
         //!\n",
    );
    for (class, name, reason) in &aggregate {
        b.push_str(&format!("//! - `{class}.{name}` — {reason}.\n"));
    }
    b
}

/// The module-doc intro + the emitted-core inventory (the invariants the cores
/// below realize). Static text — the cores are fixed spec logic.
const MODULE_DOC_INTRO: &str = "\
//! RM class-invariant cores — the single source both the typed `Validate` impls
//! (`*_impl.rs`) and the allocation-free fast path (`validate::fast`) call. Each
//! core emits this workspace's uniform violation message (`Invariant <Name>
//! failed on type <RM_TYPE>`) so a failure is identifiable by its BMM invariant
//! name.
//!
//! NOTE: no openEHR spec governs the wording of a violation message — the
//! shape below is our own convention, carrying the BMM invariant name so a
//! failure names the rule it violated.
//!
//! # Emitted cores
//!
//! - `code_phrase_core` — CODE_PHRASE `Code_string_valid`.
//! - `dv_text_core` — DV_TEXT / DV_CODED_TEXT `Valid_value`, `Formatting_valid`.
//! - `dv_uri_core` — DV_URI `Value_valid`.
//! - `dv_identifier_core` — DV_IDENTIFIER `Id_valid`.
//! - `term_mapping_core` — TERM_MAPPING `Match_valid`.
//! - `dv_parsable_core` — DV_PARSABLE `Formalism_valid`.
//! - `dv_amount_core` — DV_AMOUNT `Accuracy_is_percent_validity`,
//!   `Accuracy_validity` + DV_QUANTIFIED `Magnitude_status_valid`.
//! - `magnitude_status_core` — DV_QUANTIFIED `Magnitude_status_valid`.
//! - `temporal_value_core` — DV_DATE/DV_TIME/DV_DATE_TIME/DV_DURATION
//!   `Value_valid`.
//! - `dv_proportion_core` — DV_PROPORTION `Type_validity`, `Valid_denominator`,
//!   `Precision_validity`, `Fraction_validity`, `Unitary_validity`,
//!   `Percent_validity`.
//! - `archetype_node_id_core` — LOCATABLE `Archetype_node_id_valid`.
//! - `history_basic_core` — HISTORY `Events_valid` + inherited
//!   `Archetype_node_id_valid`.
//! - `composition_core` — COMPOSITION `Is_archetype_root` + inherited
//!   `Archetype_node_id_valid`.
//! - `entry_root_core` — ENTRY `Is_archetype_root` + inherited
//!   `Archetype_node_id_valid`.
//! - `activity_core` — ACTIVITY `Action_archetype_id_valid` + inherited
//!   `Archetype_node_id_valid`.
//! - `event_context_core` — EVENT_CONTEXT `location_valid`.
//! - `archetyped_core` — ARCHETYPED `Rm_version_valid`.
//! - `party_identified_core` — PARTY_IDENTIFIED / PARTY_RELATED `Basic_validity`,
//!   `Name_valid`.
//! - `nonempty_list_core` — the whole `x /= Void implies not x.is_empty`
//!   family, decidable on the typed model now that an optional container emits
//!   as `Option<Vec<T>>`.
//! - `resource_description_core` — RESOURCE_DESCRIPTION `Original_author_valid`,
//!   `Lifecycle_state_valid`, `Details_valid`.
//! - `resource_description_item_core` — RESOURCE_DESCRIPTION_ITEM
//!   `Purpose_valid`, `Use_valid`, `misuse_valid`, `copyright_valid`.
//! - `authored_resource_core` — AUTHORED_RESOURCE `Revision_history_valid`
//!   (evaluated only when `is_controlled` is present — the `xor` is not
//!   evaluable against a Void operand and the attribute is `0..1`).
//! - `extract_core` — EXTRACT `Sequence_nr_valid`.
//! - `extract_update_spec_core` — EXTRACT_UPDATE_SPEC `Overall_validity`.
//!
//! Complex invariants stay hand-written where the projection is non-trivial:
//! ELEMENT's null-flavour XOR (`element_impl`), DV_EHR_URI's `Scheme_valid`
//! extra (`dv_ehr_uri_impl`), HISTORY `Period_consistency` (typed-only, run
//! after `history_basic_core`), and DV_ORDERED
//! `Normal_range_and_status_consistency` (`dv_ordered_impl`).
";

const IMPORTS: &str = "\
use openehr_base::validate::InvariantViolation;
use super::{
    invariant_failed, is_integral, valid_magnitude_status, valid_percentage,
    valid_proportion_kind,
};
";

/// The invariant cores — fixed spec logic, moved verbatim from the former
/// hand-written `push_*` siblings (same checks, same messages, `out` last).
const CORES: &str = r#"
/// CODE_PHRASE `Code_string_valid`: the code string must be non-empty.
pub(crate) fn code_phrase_core(code_string: &str, out: &mut Vec<InvariantViolation>) {
    if code_string.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Code_string_valid failed on type CODE_PHRASE",
        ));
    }
}

/// DV_TEXT / DV_CODED_TEXT `Valid_value` (non-empty rubric) and
/// `Formatting_valid` (present ⇒ non-empty). `ty` is `DV_TEXT` or
/// `DV_CODED_TEXT` (which inherits both).
pub(crate) fn dv_text_core(
    ty: &str,
    value: &str,
    formatting: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    if value.is_empty() {
        out.push(InvariantViolation::here(format!(
            "Invariant Valid_value failed on type {ty} (value must be non-empty)"
        )));
    }
    if formatting.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(format!(
            "Invariant Formatting_valid failed on type {ty}"
        )));
    }
}

/// DV_URI `Value_valid`: the URI value must be non-empty.
pub(crate) fn dv_uri_core(value: &str, out: &mut Vec<InvariantViolation>) {
    if value.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Value_valid failed on type DV_URI",
        ));
    }
}

/// DV_IDENTIFIER `Id_valid`: `id` must be non-empty.
pub(crate) fn dv_identifier_core(id: &str, out: &mut Vec<InvariantViolation>) {
    if id.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Id_valid failed on type DV_IDENTIFIER",
        ));
    }
}

/// TERM_MAPPING `Match_valid`: `match` must be one of `< = > ?`.
pub(crate) fn term_mapping_core(match_code: char, out: &mut Vec<InvariantViolation>) {
    if !super::super::data_types::text::term_mapping::TermMapping::is_valid_match_code(match_code) {
        out.push(InvariantViolation::here(
            "Invariant Match_valid failed on type TERM_MAPPING",
        ));
    }
}

/// DV_PARSABLE `Formalism_valid`: `formalism` must be non-empty.
pub(crate) fn dv_parsable_core(formalism: &str, out: &mut Vec<InvariantViolation>) {
    if formalism.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Formalism_valid failed on type DV_PARSABLE",
        ));
    }
}

/// DV_QUANTIFIED `Magnitude_status_valid`: if present, `magnitude_status` must
/// be one of `= < > <= >= ~`.
pub(crate) fn magnitude_status_core(
    ty: &str,
    magnitude_status: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    if let Some(s) = magnitude_status
        && !valid_magnitude_status(s)
    {
        out.push(invariant_failed("Magnitude_status_valid", ty));
    }
}

/// The DV_AMOUNT invariants (`Accuracy_is_percent_validity`, `Accuracy_validity`)
/// plus the inherited DV_QUANTIFIED `Magnitude_status_valid`. Shared by every
/// concrete DV_AMOUNT descendant (DV_QUANTITY, DV_COUNT, DV_DURATION,
/// DV_PROPORTION).
pub(crate) fn dv_amount_core(
    ty: &str,
    accuracy: Option<f64>,
    accuracy_is_percent: Option<bool>,
    magnitude_status: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    // Accuracy_is_percent_validity: accuracy = 0 implies not recorded as percent.
    if accuracy == Some(0.0) && accuracy_is_percent == Some(true) {
        out.push(invariant_failed("Accuracy_is_percent_validity", ty));
    }
    // Accuracy_validity: recorded as percent implies 0 <= accuracy <= 100.
    if accuracy_is_percent == Some(true)
        && let Some(a) = accuracy
        && !valid_percentage(a)
    {
        out.push(invariant_failed("Accuracy_validity", ty));
    }
    magnitude_status_core(ty, magnitude_status, out);
}

/// The temporal `Value_valid` invariant: the string value must be a
/// well-formed ISO-8601 date/time/date-time/duration (caller supplies the
/// verdict via the ISO-8601 validators).
pub(crate) fn temporal_value_core(ty: &str, valid: bool, out: &mut Vec<InvariantViolation>) {
    if !valid {
        out.push(invariant_failed("Value_valid", ty));
    }
}

/// The DV_PROPORTION own invariants. The inherited DV_AMOUNT / DV_ORDERED
/// invariants are pushed by the callers.
// The released invariants compare the denominator against the exact values
// 0/1/100 (RM `dv_proportion.adoc` §Invariants: `Valid_denominator`,
// `Unitary_validity`, `Percent_validity` — `denominator = 1`, `= 100`,
// `<> 0`), so exact float comparison IS the spec semantics.
#[expect(
    clippy::float_cmp,
    reason = "the released invariants compare the denominator against exact 0/1/100 values"
)]
pub(crate) fn dv_proportion_core(
    numerator: f64,
    denominator: f64,
    kind: i32,
    precision: Option<i32>,
    out: &mut Vec<InvariantViolation>,
) {
    let integral = is_integral(numerator) && is_integral(denominator);

    // Type_validity: type in 0..=4.
    if !valid_proportion_kind(kind) {
        out.push(InvariantViolation::here(
            "Invariant Type_validity failed on type DV_PROPORTION",
        ));
    }
    // Valid_denominator: denominator != 0.
    if denominator == 0.0 {
        out.push(InvariantViolation::here(
            "Invariant Valid_denominator failed on type DV_PROPORTION",
        ));
    }
    // Precision_validity: precision 0 implies integral numerator & denominator.
    if precision == Some(0) && !integral {
        out.push(InvariantViolation::here(
            "Invariant Precision_validity failed on type DV_PROPORTION",
        ));
    }
    // Fraction_validity: `(type = pk_fraction or type = pk_integer_fraction)
    // implies is_integral`, where `is_integral()` is "True … if precision is 0"
    // (RM dv_proportion.adoc §Functions). A fraction / integer_fraction is
    // therefore invalid when its numerator/denominator are non-integral OR its
    // precision is a present, non-zero value. (Precision 0 or absent keeps a
    // whole-numerator/denominator fraction valid.)
    //
    // NOTE: `Is_integral_validity` (`is_integral implies …`) needs no separate
    // push — `is_integral()` IS "precision is 0" (§Functions), so the
    // invariant is extensionally the `Precision_validity` check above.
    if (kind == PK_FRACTION || kind == PK_INTEGER_FRACTION)
        && (!integral || precision.is_some_and(|p| p != 0))
    {
        out.push(InvariantViolation::here(
            "Invariant Fraction_validity failed on type DV_PROPORTION",
        ));
    }
    // Unitary_validity: unitary kind has denominator 1.
    if kind == PK_UNITARY && denominator != 1.0 {
        out.push(InvariantViolation::here(
            "Invariant Unitary_validity failed on type DV_PROPORTION",
        ));
    }
    // Percent_validity: percent kind has denominator 100.
    if kind == PK_PERCENT && denominator != 100.0 {
        out.push(InvariantViolation::here(
            "Invariant Percent_validity failed on type DV_PROPORTION",
        ));
    }
}

/// LOCATABLE `Archetype_node_id_valid`: `archetype_node_id` must be non-empty.
pub(crate) fn archetype_node_id_core(
    ty: &str,
    archetype_node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if archetype_node_id.is_empty() {
        out.push(invariant_failed("Archetype_node_id_valid", ty));
    }
}

/// The non-periodic HISTORY invariants: `Events_valid` (at least one event or a
/// summary) + inherited `Archetype_node_id_valid`. `Period_consistency` stays
/// typed-only (the fast path declines periodic histories).
pub(crate) fn history_basic_core(
    events_empty: bool,
    has_summary: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if events_empty && !has_summary {
        out.push(InvariantViolation::here(
            "Invariant Events_valid failed on type HISTORY",
        ));
    }
    archetype_node_id_core("HISTORY", node_id, out);
}

/// COMPOSITION `Is_archetype_root` (`archetype_details` present) + inherited
/// `Archetype_node_id_valid`.
pub(crate) fn composition_core(
    has_archetype_details: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if !has_archetype_details {
        out.push(InvariantViolation::here(
            "Invariant Is_archetype_root failed on type COMPOSITION",
        ));
    }
    archetype_node_id_core("COMPOSITION", node_id, out);
}

/// The shared ENTRY-root invariants: `Is_archetype_root` (an ENTRY is an
/// archetype root, so `archetype_details` must be present) + inherited
/// `Archetype_node_id_valid`. `ty` is the concrete ENTRY subtype.
pub(crate) fn entry_root_core(
    ty: &str,
    has_archetype_details: bool,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if !has_archetype_details {
        out.push(invariant_failed("Is_archetype_root", ty));
    }
    archetype_node_id_core(ty, node_id, out);
}

/// ACTIVITY `Action_archetype_id_valid` (non-empty) + inherited
/// `Archetype_node_id_valid`.
pub(crate) fn activity_core(
    action_archetype_id: &str,
    node_id: &str,
    out: &mut Vec<InvariantViolation>,
) {
    if action_archetype_id.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Action_archetype_id_valid failed on type ACTIVITY",
        ));
    }
    archetype_node_id_core("ACTIVITY", node_id, out);
}

/// EVENT_CONTEXT `location_valid`: if present, `location` must be non-empty.
pub(crate) fn event_context_core(location: Option<&str>, out: &mut Vec<InvariantViolation>) {
    if location.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(
            "Invariant location_valid failed on type EVENT_CONTEXT",
        ));
    }
}

/// ARCHETYPED `Rm_version_valid`: `rm_version` must be non-empty.
pub(crate) fn archetyped_core(rm_version: &str, out: &mut Vec<InvariantViolation>) {
    if rm_version.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Rm_version_valid failed on type ARCHETYPED",
        ));
    }
}

/// PARTY_IDENTIFIED / PARTY_RELATED `Basic_validity` (at least one of `name`,
/// `identifiers`, `external_ref`) and `Name_valid` (present ⇒ non-empty). `ty`
/// is `PARTY_IDENTIFIED` or `PARTY_RELATED` (which inherits both).
pub(crate) fn party_identified_core(
    ty: &str,
    name: Option<&str>,
    has_identifiers: bool,
    has_external_ref: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if name.is_none() && !has_identifiers && !has_external_ref {
        out.push(InvariantViolation::here(format!(
            "Invariant Basic_validity failed on type {ty}"
        )));
    }
    if name.is_some_and(str::is_empty) {
        out.push(InvariantViolation::here(format!(
            "Invariant Name_valid failed on type {ty}"
        )));
    }
}

/// The `x /= Void implies not x.is_empty` invariant family, shared by every RM
/// class that declares one (`LOCATABLE.Links_valid`, `COMPOSITION.Content_valid`,
/// `SECTION.Items_valid`, `ENTRY.Other_participations_valid`,
/// `INSTRUCTION.Activities_valid`, `EVENT_CONTEXT.Participations_validity`,
/// `DV_TEXT.Mappings_valid`, `DV_ORDERED.Other_reference_ranges_validity`,
/// `PARTY_IDENTIFIED.Identifiers_valid`, `ACTOR.Roles_valid`,
/// `ATTESTATION.Items_valid`, `ORIGINAL_VERSION.Attestations_valid` /
/// `Other_input_version_uids_valid`, … — each `docs/specs/openehr/RM/docs/UML/classes/org.openehr.rm.*`
/// §Invariants).
///
/// `present_and_empty` is the whole rule: the attribute is present on the
/// instance AND holds zero members. It is decidable on the typed model because
/// an optional container emits as `Option<Vec<T>>` — `Some(vec![])` is exactly
/// the forbidden state — so callers pass
/// `self.attr.as_ref().is_some_and(Vec::is_empty)`.
pub(crate) fn nonempty_list_core(
    ty: &str,
    attribute: &str,
    invariant: &str,
    present_and_empty: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if present_and_empty {
        out.push(InvariantViolation::here(format!(
            "{ty}.{attribute} is present but empty — a present list must be \
             non-empty ({ty}.{invariant})"
        )));
    }
}

/// RESOURCE_DESCRIPTION `Original_author_valid` / `Lifecycle_state_valid` /
/// `Details_valid`: the three own non-empty rules.
pub(crate) fn resource_description_core(
    original_author_empty: bool,
    lifecycle_state: &str,
    details_empty: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if original_author_empty {
        out.push(InvariantViolation::here(
            "Invariant Original_author_valid failed on type RESOURCE_DESCRIPTION",
        ));
    }
    if lifecycle_state.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Lifecycle_state_valid failed on type RESOURCE_DESCRIPTION",
        ));
    }
    if details_empty {
        out.push(InvariantViolation::here(
            "Invariant Details_valid failed on type RESOURCE_DESCRIPTION",
        ));
    }
}

/// RESOURCE_DESCRIPTION_ITEM `Purpose_valid` (`not purpose.is_empty`) plus the
/// three present-implies-non-empty string rules (`Use_valid`, `misuse_valid`,
/// `copyright_valid`).
pub(crate) fn resource_description_item_core(
    purpose: &str,
    use_: Option<&str>,
    misuse: Option<&str>,
    copyright: Option<&str>,
    out: &mut Vec<InvariantViolation>,
) {
    if purpose.is_empty() {
        out.push(InvariantViolation::here(
            "Invariant Purpose_valid failed on type RESOURCE_DESCRIPTION_ITEM",
        ));
    }
    for (value, invariant) in [
        (use_, "Use_valid"),
        (misuse, "misuse_valid"),
        (copyright, "copyright_valid"),
    ] {
        if value.is_some_and(str::is_empty) {
            out.push(invariant_failed(invariant, "RESOURCE_DESCRIPTION_ITEM"));
        }
    }
}

/// AUTHORED_RESOURCE `Revision_history_valid`
/// (`is_controlled xor revision_history = Void`): a controlled resource
/// carries a revision history and an uncontrolled one does not. Evaluated
/// only when `is_controlled` is PRESENT — the attribute is `0..1` and an
/// `xor` against a Void operand is not evaluable, so an absent flag asserts
/// nothing (never an invented prohibition).
pub(crate) fn authored_resource_core(
    is_controlled: Option<bool>,
    has_revision_history: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if let Some(controlled) = is_controlled
        && controlled != has_revision_history
    {
        out.push(InvariantViolation::here(
            "Invariant Revision_history_valid failed on type AUTHORED_RESOURCE",
        ));
    }
}

/// EXTRACT `Sequence_nr_valid`: `sequence_nr >= 1`.
pub(crate) fn extract_core(sequence_nr: i32, out: &mut Vec<InvariantViolation>) {
    if sequence_nr < 1 {
        out.push(InvariantViolation::here(
            "Invariant Sequence_nr_valid failed on type EXTRACT",
        ));
    }
}

/// EXTRACT_UPDATE_SPEC `Overall_validity`
/// (`repeat_period /= Void or trigger_events /= Void`): an update
/// specification names at least one update mode.
pub(crate) fn extract_update_spec_core(
    has_repeat_period: bool,
    has_trigger_events: bool,
    out: &mut Vec<InvariantViolation>,
) {
    if !has_repeat_period && !has_trigger_events {
        out.push(InvariantViolation::here(
            "Invariant Overall_validity failed on type EXTRACT_UPDATE_SPEC",
        ));
    }
}
"#;
