// @generated by openehr-codegen from BMM (`ASSERTION`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::beom::core::expression::Expression;
use openehr_derive::OpenEhrType;

/// Meta-type for a first order predicate logic expression with a Boolean result.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "ASSERTION")]
pub struct Assertion {
    /// Expression tag, used for differentiating multiple assertions.
    pub tag: Option<String>,
    /// String form of expression, in case an expression evaluator taking String expressions is used for evaluation.
    pub string_expression: Option<String>,
    /// Root of expression tree.
    pub expression: Box<Expression>,
}
