// @generated by openehr-codegen from BMM (`ASSIGNMENT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::beom::core::expr_value::ExprValue;
use crate::beom::core::variable_declaration::VariableDeclaration;

/// Meta-type representing the assignment statement, which associates a named variable with an expression, and produces no value.
#[derive(Debug, Clone, PartialEq)]
pub struct Assignment {
    /// The target variable on the notional left-hand side of this assignment.
    pub target: VariableDeclaration,
    /// Source right hand side) of the assignment.
    pub source: ExprValue,
}
