// @generated by openehr-codegen from BMM (`EXPR_VALUE`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::beom::core::expr_binary_operator::ExprBinaryOperator;
use crate::beom::core::expr_for_all::ExprForAll;
use crate::beom::core::expr_function_call::ExprFunctionCall;
use crate::beom::core::expr_literal::ExprLiteral;
use crate::beom::core::expr_unary_operator::ExprUnaryOperator;
use crate::beom::core::expr_value_ref::ExprValueRef;
use crate::beom::core::expr_variable_ref::ExprVariableRef;
use crate::beom::core::external_query::ExternalQuery;

/// Any kind of statement element that can be evaluated. The type will either be supplied in descendant types or else will be inferred by an assignment statement linked to a typed variable.
/// Closed subtype set of `EXPR_VALUE` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExprValue {
    ExprBinaryOperator(ExprBinaryOperator),
    ExprForAll(ExprForAll),
    ExprFunctionCall(ExprFunctionCall),
    ExprLiteral(ExprLiteral),
    ExprUnaryOperator(ExprUnaryOperator),
    ExprValueRef(ExprValueRef),
    ExprVariableRef(ExprVariableRef),
    ExternalQuery(ExternalQuery),
}
