// @generated by openehr-codegen from BMM (`EXPR_VALUE_REF`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Path-based reference to a value in a data structure.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "EXPR_VALUE_REF")]
pub struct ExprValueRef {
    // inherited: EXPR_LEAF
    /// The reference item from which the value of this node can be computed.
    pub item: Option<serde_json::Value>,
}
