// @generated by openehr-codegen from BMM (`STATEMENT_SET`) — DO NOT EDIT.

//! The openEHR `STATEMENT_SET` spec class, generated from the vendored BMM
//! meta-model.

use crate::beom::core::statement::Statement;

/// A container for a specific set of statements intended to be used together.
#[doc(alias = "STATEMENT_SET")]
#[derive(Debug, Clone, PartialEq)]
pub struct StatementSet {
    /// The member statements of this statement set.
    pub statement: Option<Vec<Statement>>,
    /// Optional name of this rule set.
    pub name: Option<String>,
}
