// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v1_3/base_types` — generated module tree.

pub mod definitions;
pub mod identification;
pub mod terminology;
