// @generated by openehr-codegen from BMM (`VERSIONED_OBJECT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::common::directory::versioned_folder::VersionedFolder;
use crate::data_types::quantity::date_time::dv_date_time::DvDateTime;
use crate::demographic::versioned_party::VersionedParty;
use crate::ehr::versioned_composition::VersionedComposition;
use crate::ehr::versioned_ehr_access::VersionedEhrAccess;
use crate::ehr::versioned_ehr_status::VersionedEhrStatus;
use openehr_base::prelude::HierObjectId;
use openehr_base::prelude::ObjectRef;
use openehr_derive::OpenEhrType;
use serde::Serialize;

/// Version control abstraction, defining semantics for versioning one complex object.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "VERSIONED_OBJECT")]
pub struct VersionedObjectData {
    /// Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
    pub uid: HierObjectId,
    /// Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
    pub owner_id: ObjectRef,
    /// Time of initial creation of this versioned object.
    pub time_created: DvDateTime,
}

/// Version control abstraction, defining semantics for versioning one complex object.
/// Polymorphic slot of `VERSIONED_OBJECT`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum VersionedObject {
    VersionedComposition(VersionedComposition),
    VersionedEhrAccess(VersionedEhrAccess),
    VersionedEhrStatus(VersionedEhrStatus),
    VersionedFolder(VersionedFolder),
    VersionedParty(VersionedParty),
    VersionedObject(VersionedObjectData),
}

impl<'de> ::serde::Deserialize<'de> for VersionedObject {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("VERSIONED_COMPOSITION") => {
                ::core::result::Result::Ok(Self::VersionedComposition(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("VERSIONED_EHR_ACCESS") => {
                ::core::result::Result::Ok(Self::VersionedEhrAccess(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("VERSIONED_EHR_STATUS") => {
                ::core::result::Result::Ok(Self::VersionedEhrStatus(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("VERSIONED_FOLDER") => {
                ::core::result::Result::Ok(Self::VersionedFolder(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("VERSIONED_OBJECT") => {
                ::core::result::Result::Ok(Self::VersionedObject(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("VERSIONED_PARTY") => {
                ::core::result::Result::Ok(Self::VersionedParty(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => ::core::result::Result::Ok(Self::VersionedObject(
                ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
            )),
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "VERSIONED_OBJECT: unexpected `_type` {__other:?} (expected one of: VERSIONED_COMPOSITION, VERSIONED_EHR_ACCESS, VERSIONED_EHR_STATUS, VERSIONED_FOLDER, VERSIONED_OBJECT, VERSIONED_PARTY)"
                )))
            }
        }
    }
}
