// @generated by openehr-codegen from BMM (`P_BMM_GENERIC_TYPE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `P_BMM_GENERIC_TYPE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::bmm::core::bmm_generic_type::BmmGenericType;
use crate::v1_1::bmm_persistence::p_bmm_type::PBmmType;

/// Persistent form of `BMM_GENERIC_TYPE`.
#[doc(alias = "P_BMM_GENERIC_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmGenericType {
    /// Result of `_create_bmm_type()_` call.
    pub bmm_type: Option<BmmGenericType>,

    // inherited: P_BMM_BASE_TYPE
    /// The `value_constraint` attribute of openEHR `P_BMM_BASE_TYPE` (the vendored BMM carries no documentation for it).
    pub value_constraint: Option<String>,
    /// Root type of this generic type, e.g. `Interval` in `Interval<Integer>`.
    pub root_type: String,
    /// Generic parameters of the root_type in this type specifier if non-simple types. The order must match the order of the owning class's formal generic parameter declarations. Persistent attribute.
    pub generic_parameter_defs: Vec<PBmmType>,
    /// Generic parameters of the `_root_type_` in this type specifier, if simple types. The order must match the order of the owning class's formal generic parameter declarations. Persistent attribute.
    pub generic_parameters: Option<Vec<String>>,
}
