// @generated by openehr-codegen from BMM (`P_BMM_CONSTANT`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `P_BMM_CONSTANT` spec class, generated from the vendored BMM
//! meta-model.

/// Persistent form of a BMM constant, i.e. a named, typed literal value defined on a class.
#[doc(alias = "P_BMM_CONSTANT")]
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmConstant {
    // inherited: P_BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,
    /// Name of this constant within its class. Persisted attribute.
    pub name: String,
    /// Type name of this constant, as a simple class name. Persisted attribute.
    pub r#type: String,
    /// The literal value of this constant, in its persisted (serialised) form. Persisted attribute.
    pub value: Option<String>,
}
