// @generated by openehr-codegen from BMM (`EL_FUNCTION_CALL`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `EL_FUNCTION_CALL` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::expression::el_function_agent::ElFunctionAgent;
use crate::v1_0::bmm::expression::el_instance_ref::ElInstanceRef;

/// A call made on a closed function agent, returning a result. Equivalent to an 'application' of a function in Lambda calculus.
#[doc(alias = "EL_FUNCTION_CALL")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElFunctionCall {
    // inherited: EL_SCOPED_REF
    /// Reference to an owning object for this terminal element, if it is not the current scope.
    pub scope: Option<Box<ElInstanceRef>>,
    /// The function agent being called.
    pub agent: Box<ElFunctionAgent>,
}
