// @generated by openehr-codegen from BMM (`P_BMM_SIMPLE_TYPE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::bmm3::core::entity::bmm_simple_type::BmmSimpleType;
use openehr_derive::OpenEhrType;

/// Persistent form of `BMM_SIMPLE_TYPE`.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "P_BMM_SIMPLE_TYPE")]
pub struct PBmmSimpleType {
    /// Result of `_create_bmm_type()_` call.
    pub bmm_type: Option<BmmSimpleType>,

    // inherited: P_BMM_BASE_TYPE
    pub value_constraint: Option<String>,
    /// Name of type - must be a simple class name.
    pub r#type: String,
}
