// @generated by openehr-codegen from BMM (`P_BMM_PROPERTY`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::bmm_persistence::p_bmm_container_property::PBmmContainerProperty;
use crate::bmm_persistence::p_bmm_generic_property::PBmmGenericProperty;
use crate::bmm_persistence::p_bmm_indexed_container_property::PBmmIndexedContainerProperty;
use crate::bmm_persistence::p_bmm_single_property::PBmmSingleProperty;
use crate::bmm_persistence::p_bmm_single_property_open::PBmmSinglePropertyOpen;

/// Persistent form of `BMM_PROPERTY`.
/// Closed subtype set of `P_BMM_PROPERTY` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PBmmProperty {
    PBmmContainerProperty(PBmmContainerProperty),
    PBmmGenericProperty(PBmmGenericProperty),
    PBmmIndexedContainerProperty(PBmmIndexedContainerProperty),
    PBmmSingleProperty(PBmmSingleProperty),
    PBmmSinglePropertyOpen(PBmmSinglePropertyOpen),
}
