// @generated by openehr-codegen from BMM (`P_BMM_OPEN_TYPE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::bmm::core::bmm_open_type::BmmOpenType;
use openehr_derive::OpenEhrType;

/// Persistent form of `BMM_GENERIC_PARAMETER` or `BMM_PARAMETER_TYPE` (in BMM v3).
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "P_BMM_OPEN_TYPE")]
pub struct PBmmOpenType {
    /// Result of `_create_bmm_type()_` call.
    pub bmm_type: Option<BmmOpenType>,

    // inherited: P_BMM_BASE_TYPE
    pub value_constraint: Option<String>,
    /// Simple type parameter as a single letter like 'T', 'G' etc.
    pub r#type: String,
}
