// @generated by openehr-codegen from BMM (`P_BMM_SINGLE_FUNCTION_PARAMETER_OPEN`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

/// Persistent form of a single-valued function parameter whose type is an open generic parameter, e.g. `T`.
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmSingleFunctionParameterOpen {
    // inherited: P_BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,

    // inherited: P_BMM_FUNCTION_PARAMETER
    /// Name of this parameter within its function signature. Persisted attribute.
    pub name: String,
    /// True if this parameter is allowed to be Void (null) in a call. Persisted attribute.
    pub is_nullable: Option<bool>,
    /// Open type parameter, i.e. a generic parameter name such as `T`, `G` etc. Persisted attribute.
    pub r#type: String,
}
