// @generated by openehr-codegen from BMM (`P_BMM_BASE_TYPE`) — DO NOT EDIT.

use crate::bmm_persistence::p_bmm_generic_type::PBmmGenericType;
use crate::bmm_persistence::p_bmm_open_type::PBmmOpenType;
use crate::bmm_persistence::p_bmm_simple_type::PBmmSimpleType;

/// Persistent form of a proper (non-container) BMM type.
/// Closed subtype set of `P_BMM_BASE_TYPE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum PBmmBaseType {
    PBmmGenericType(PBmmGenericType),
    PBmmOpenType(PBmmOpenType),
    PBmmSimpleType(PBmmSimpleType),
}
