// @generated by openehr-codegen from BMM (`P_BMM_CONTAINER_PROPERTY`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use crate::bmm::core::bmm_container_property::BmmContainerProperty;
use crate::bmm_persistence::p_bmm_container_type::PBmmContainerType;
use openehr_derive::OpenEhrType;

/// Persistent form of `BMM_CONTAINER_PROPERTY`.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "P_BMM_CONTAINER_PROPERTY")]
pub struct PBmmContainerProperty {
    // inherited: P_BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,

    // inherited: P_BMM_PROPERTY
    /// Name of this property within its class. Persisted attribute.
    pub name: String,
    /// True if this property is mandatory in its class. Persisted attribute.
    pub is_mandatory: Option<bool>,
    /// True if this property is computed rather than stored in objects of this class. Persisted Attribute.
    pub is_computed: Option<bool>,
    /// True if this property is info model 'infrastructure' rather than 'data'. Persisted attribute.
    pub is_im_infrastructure: Option<bool>,
    /// True if this property is info model 'runtime' settable property. Persisted attribute.
    pub is_im_runtime: Option<bool>,
    /// Type definition of this property, if not a simple String type reference. Persistent attribute.
    pub type_def: Option<PBmmContainerType>,
    /// `BMM_PROPERTY` created by `_create_bmm_property_`.
    pub bmm_property: Option<BmmContainerProperty>,
    /// Cardinality of this property in its class. Persistent attribute.
    pub cardinality: Option<serde_json::Value>,
}
