// @generated by openehr-codegen from BMM (`P_ARCHETYPE_SLOT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Constraint describing a  slot' where another archetype can occur.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "P_ARCHETYPE_SLOT")]
pub struct PArchetypeSlot {
    // inherited: P_C_OBJECT
    /// Reference model type that this node corresponds to.
    pub rm_type_name: String,
    /// Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1.
    pub occurrences: Option<String>,
    /// Semantic id of this node, used to differentiate sibling nodes of the same type. Each node_id must be defined in the archetype ontology as a term code.
    pub node_id: String,
    pub is_deprecated: Option<bool>,
    /// List of constraints defining other archetypes that could be included at this point.
    pub includes: Vec<serde_json::Value>,
    /// List of constraints defining other archetypes that cannot be included at this point.
    pub excludes: Vec<serde_json::Value>,
    pub is_closed: bool,
}
