// @generated by openehr-codegen from BMM (`P_C_PRIMITIVE_OBJECT`) — DO NOT EDIT.

use crate::am24::aom2::persistence::primitive::p_c_boolean::PCBoolean;
use crate::am24::aom2::persistence::primitive::p_c_string::PCString;
use crate::am24::aom2::persistence::primitive::p_c_terminology_code::PCTerminologyCode;

/// Parent of types representing constraints on primitive types.
/// Closed subtype set of `P_C_PRIMITIVE_OBJECT`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum PCPrimitiveObject {
    PCBoolean(PCBoolean),
    PCString(PCString),
    PCTerminologyCode(PCTerminologyCode),
}
