// @generated by openehr-codegen from BMM (`P_C_PRIMITIVE_OBJECT`) — DO NOT EDIT.

use crate::am24::aom2::persistence::primitive::p_c_boolean::PCBoolean;
use crate::am24::aom2::persistence::primitive::p_c_string::PCString;
use crate::am24::aom2::persistence::primitive::p_c_terminology_code::PCTerminologyCode;
use serde::Serialize;

/// Parent of types representing constraints on primitive types.
/// Closed subtype set of `P_C_PRIMITIVE_OBJECT` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum PCPrimitiveObject {
    PCBoolean(PCBoolean),
    PCString(PCString),
    PCTerminologyCode(PCTerminologyCode),
}

impl<'de> ::serde::Deserialize<'de> for PCPrimitiveObject {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("P_C_BOOLEAN") => {
                ::core::result::Result::Ok(Self::PCBoolean(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("P_C_STRING") => {
                ::core::result::Result::Ok(Self::PCString(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("P_C_TERMINOLOGY_CODE") => {
                ::core::result::Result::Ok(Self::PCTerminologyCode(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => {
                ::core::result::Result::Err(::serde::de::Error::custom(
                    "P_C_PRIMITIVE_OBJECT: missing required `_type` on polymorphic slot (expected one of: P_C_BOOLEAN, P_C_STRING, P_C_TERMINOLOGY_CODE)",
                ))
            }
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "P_C_PRIMITIVE_OBJECT: unexpected `_type` {__other:?} (expected one of: P_C_BOOLEAN, P_C_STRING, P_C_TERMINOLOGY_CODE)"
                )))
            }
        }
    }
}
