// @generated by openehr-codegen from BMM (`EL_AGENT`) — DO NOT EDIT.

use crate::bmm3::expression::el_function_agent::ElFunctionAgent;
use crate::bmm3::expression::el_procedure_agent::ElProcedureAgent;
use serde::Serialize;

/// A delayed routine call, whose arguments may be open, partially closed or closed. Generated by special reference to a routine, usually via a dedicated keyword, such as 'lambda' or 'agent', or other special syntax.
///
/// Instances may include closed delayed calls like `calculate_age (dob="1987-09-13", today="2019-06-03")` but also partially open calls such as `format_structure (struct=?, style=3)`, where `struct` is an open argument.
///
/// Evaluation type (i.e. type of runtime evaluated form) is `BMM_SIGNATURE`.
/// Closed subtype set of `EL_AGENT`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ElAgent {
    ElFunctionAgent(ElFunctionAgent),
    ElProcedureAgent(ElProcedureAgent),
}

impl<'de> ::serde::Deserialize<'de> for ElAgent {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("EL_FUNCTION_AGENT") => {
                ::core::result::Result::Ok(Self::ElFunctionAgent(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("EL_PROCEDURE_AGENT") => {
                ::core::result::Result::Ok(Self::ElProcedureAgent(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => {
                ::core::result::Result::Err(::serde::de::Error::custom(
                    "EL_AGENT: missing required `_type` on polymorphic slot (expected one of: EL_FUNCTION_AGENT, EL_PROCEDURE_AGENT)",
                ))
            }
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "EL_AGENT: unexpected `_type` {__other:?} (expected one of: EL_FUNCTION_AGENT, EL_PROCEDURE_AGENT)"
                )))
            }
        }
    }
}
