// @generated by openehr-codegen from BMM (`EL_CONSTRAINED`) — DO NOT EDIT.

use crate::bmm3::expression::el_boolean_expression::ElBooleanExpression;
use serde::{Deserialize, Serialize};

/// Abstract parent for second-order constrained forms of first-order expression meta-types.
/// Closed subtype set of `EL_CONSTRAINED` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ElConstrained {
    ElBooleanExpression(ElBooleanExpression),
}
