// @generated by openehr-codegen from BMM (`EL_PREDICATE`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::bmm3::expression::el_attached::ElAttached;
use crate::bmm3::expression::el_defined::ElDefined;

/// Parent type of predicate of any object reference.
/// Closed subtype set of `EL_PREDICATE` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ElPredicate {
    ElAttached(ElAttached),
    ElDefined(ElDefined),
}
