// @generated by openehr-codegen from BMM (`EL_VARIABLE`) — DO NOT EDIT.

use crate::bmm3::expression::el_readonly_variable::ElReadonlyVariable;
use crate::bmm3::expression::el_writable_variable::ElWritableVariable;
use serde::Serialize;

/// Abstract meta-type of any kind of symbolic variable.
/// Closed subtype set of `EL_VARIABLE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ElVariable {
    ElReadonlyVariable(ElReadonlyVariable),
    ElWritableVariable(ElWritableVariable),
}

impl<'de> ::serde::Deserialize<'de> for ElVariable {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("EL_READONLY_VARIABLE") => {
                ::core::result::Result::Ok(Self::ElReadonlyVariable(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("EL_WRITABLE_VARIABLE") => {
                ::core::result::Result::Ok(Self::ElWritableVariable(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => {
                ::core::result::Result::Err(::serde::de::Error::custom(
                    "EL_VARIABLE: missing required `_type` on polymorphic slot (expected one of: EL_READONLY_VARIABLE, EL_WRITABLE_VARIABLE)",
                ))
            }
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "EL_VARIABLE: unexpected `_type` {__other:?} (expected one of: EL_READONLY_VARIABLE, EL_WRITABLE_VARIABLE)"
                )))
            }
        }
    }
}
