//! The version-commit envelope (`master03-common_package.adoc` §Version
//! Update Semantics; `update_version.adoc`, `update_audit.adoc`).
//!
//! "Some of the interfaces defined in this specification cause creation or
//! update of a versioned 'top-level' openEHR object … Such calls implicitly
//! require the creation of a new `CONTRIBUTION` on the server side, as well
//! as one or more new `ORIGINAL_VERSION` objects, and in creation cases, new
//! `VERSIONED_OBJECTS`. … the `UPDATE_VERSION<T>` structure is provided in
//! order to enable the appropriate meta-data to be supplied by the caller,
//! leaving out parts that are generated by the service."

use serde::{Deserialize, Serialize};
use serde_json::Value;

use openehr_base::prelude::{ObjectVersionId, TerminologyCode};
use openehr_rm::common::generic::party_identified::{PartyIdentified, PartyIdentifiedData};
use openehr_rm::prelude::{DvEhrUri, DvMultimedia, DvText, PartyProxy};

/// `UPDATE_AUDIT` — "The set of attributes required to document the committal
/// of an information item to a repository. Used by the server to create an
/// `AUDIT_DETAILS` object" (`update_audit.adoc`).
///
/// Deliberately partial: "a partial version of `AUDIT_DETAILS` called
/// `UPDATE_AUDIT` is used, since the `time_committed` and `system_id`
/// attributes need to be generated on the server" (master03 §Version Update
/// Semantics). Invariant `Change_type_valid`: `change_type.defining_code`
/// must belong to the openEHR terminology *audit change type* group —
/// enforced at the service boundary via `openehr-term`, not in this type.
///
/// NOTE (wire): the two released sources spell this attribute differently.
/// ITS-REST `UpdateAudit.yaml` types `description` as `UDvText`, which is
/// `oneOf` [`DV_TEXT`, `DV_CODED_TEXT`] discriminated on `_type`
/// (`specifications/schemas/data_types/UDvText.yaml`) — an object, never a bare
/// JSON string; SM `UPDATE_AUDIT.description` is `String [0..1]`
/// (`SM/docs/UML/classes/update_audit.adoc` §Attributes). This native type keeps
/// the SM shape, and the only channel that fills it is the
/// `openehr-audit-details` header, whose grammar carries the attribute
/// pre-flattened as the `description.value` subkey — i.e. the `DV_TEXT.value`
/// string both `UDvText` branches share — which
/// [`crate::versioning::audit::AuditInput::from_update`] re-wraps as a plain
/// `DV_TEXT` fragment. A header therefore cannot express a coded description at
/// all: `DV_CODED_TEXT.defining_code` has no subkey to travel in. Where a coded
/// description IS expressible — the native CONTRIBUTION body — the commit does
/// NOT go through this struct and the whole canonical fragment is kept
/// (`crate::versioning::contribution`).
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UpdateAudit {
    /// Type of change; coded from the openEHR *audit change type* group.
    #[serde(with = "crate::codec_serde::spec")]
    pub change_type: TerminologyCode,
    /// Reason for committal.
    #[serde(default)]
    pub description: Option<String>,
    /// Identity (and optional identity-management reference) of the
    /// committing user.
    #[serde(with = "crate::codec_serde::spec")]
    pub committer: PartyProxy,
    /// System that committed the change. A client MAY supply this through the
    /// `openehr-audit-details` request header's `system_id` value (ITS-REST
    /// overview §"openehr-version and openehr-audit-details":
    /// "clients MAY supply values for the `AUDIT_DETAILS` attributes … and
    /// `system_id`"). When absent, "the server MUST set it to its own
    /// configured system identifier"; `time_committed` is always server-set.
    /// The server default is asserted at the versioning seam, not here — the
    /// header layer only carries a client-supplied value through
    /// (`Requests_and_responses.md` line 94).
    #[serde(default)]
    pub system_id: Option<String>,
}

/// `UPDATE_ATTESTATION` — the wire form of a client-supplied attestation
/// (ITS-REST `specifications/schemas/common/UpdateAttestation.yaml`; extends
/// `UpdateAudit`).
///
/// NOTE (wire): the SM says attestations are supplied "in their full
/// form" as RM `ATTESTATION` (master03 §Version Update Semantics), but the
/// ITS-REST wire carries this **partial** form — the server completes it into
/// a full RM `ATTESTATION` (adding `time_committed`/`system_id`, like
/// `UPDATE_AUDIT` → `AUDIT_DETAILS`). The wire wins at the boundary (the
/// wire-precedence rule); the native API therefore carries this type.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UpdateAttestation {
    /// Type of change; coded from the openEHR *audit change type* group
    /// (`666|attestation|` for attestations).
    #[serde(with = "crate::codec_serde::spec")]
    pub change_type: TerminologyCode,
    /// Reason for committal (inherited from the `UpdateAudit` base).
    #[serde(default)]
    pub description: Option<String>,
    /// The attesting party.
    #[serde(with = "crate::codec_serde::spec")]
    pub committer: PartyProxy,
    /// Optional visual representation of what was attested.
    #[serde(default, with = "crate::codec_serde::spec_opt")]
    pub attested_view: Option<DvMultimedia>,
    /// Proof of attestation.
    #[serde(default)]
    pub proof: Option<String>,
    /// Items attested, as EHR URIs.
    #[serde(default, with = "crate::codec_serde::spec_opt")]
    pub items: Option<Vec<DvEhrUri>>,
    /// Reason of this attestation.
    #[serde(with = "crate::codec_serde::spec")]
    pub reason: DvText,
    /// True if this attestation is outstanding.
    pub is_pending: bool,
}

/// `UPDATE_VERSION<T>` — "An object representing an update to an existing
/// `VERSION` within a `VERSIONED_OBJECT`, that can be provided by a client to
/// the platform. The back-end will construct a full `VERSION<T>` object from
/// this and server-side generated data items. If this represents the first
/// version, it will also construct a new `VERSIONED_OBJECT` first"
/// (`update_version.adoc`).
///
/// Rules (master03 §Version Update Semantics): "`preceding_version_uid` …
/// must be specified, except in the case where the version update is a first
/// version. The `lifecycle_state` must be supplied in all cases, which is a
/// value such as `532|complete|`, `553|incomplete|`, `523|deleted|`".
/// The spec's per-content derivations (`UV_COMPOSITION` etc.) are the
/// instantiations of the generic parameter `T`.
///
/// NOTEs (wire; oracle ITS-REST
/// `specifications/schemas/common/UpdateVersion.yaml`):
/// - the wire field for [`Self::audit`] is **`commit_audit`** (serde rename
///   below); the native name keeps the SM's `audit`;
/// - wire `attestations` items are the partial [`UpdateAttestation`], not
///   full RM `ATTESTATION` (see that type);
/// - the wire carries **`signature`**, absent from the SM class — kept here
///   and fed to the version signer.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UpdateVersion<T = Value> {
    /// Current version in the service for which this version is an update.
    /// `None` only for a first version.
    #[serde(default, with = "crate::codec_serde::spec_opt")]
    pub preceding_version_uid: Option<ObjectVersionId>,
    /// Lifecycle state of the content item in this version.
    #[serde(with = "crate::codec_serde::spec")]
    pub lifecycle_state: TerminologyCode,
    /// Attestations relating to this version (wire-partial form; see
    /// [`UpdateAttestation`]).
    #[serde(default)]
    pub attestations: Option<Vec<UpdateAttestation>>,
    /// The data item being provided in this version update.
    pub data: T,
    /// Audit details for this update (wire name `commit_audit`).
    #[serde(rename = "commit_audit")]
    pub audit: UpdateAudit,
    /// Version signature (wire-only field; not in the SM class).
    #[serde(default)]
    pub signature: Option<String>,
}

impl UpdateVersion {
    /// A plain server-side commit envelope around `data`: 532|complete|
    /// lifecycle, the server's own audit identity, no client signature, no
    /// attestations. The internal commit paths (FHIR ingest, TDD import) that
    /// synthesize compositions use this; wire commits carry the caller's
    /// merged envelope instead.
    #[must_use]
    pub fn direct(data: Value) -> Self {
        let code = |terminology: &str, code: &str| TerminologyCode {
            terminology_id: terminology.to_owned(),
            terminology_version: None,
            code_string: code.to_owned(),
            uri: None,
        };
        Self {
            preceding_version_uid: None,
            // 532|complete| (RM common master06 §Version Lifecycle).
            lifecycle_state: code("openehr", "532"),
            attestations: None,
            data,
            audit: UpdateAudit {
                // 249|creation| — a placeholder. A caller-supplied
                // `change_type` is honoured after group + operation
                // validation (`versioning::audit`, ITS-REST overview
                // §"openehr-version and openehr-audit-details" MUST-merge);
                // header-derived envelopes blank this first so only a
                // header-carried value reads as supplied
                // (`overview::committal::committal_audit`).
                change_type: code("openehr", "249"),
                description: None,
                // Built with the generated constructor rather than decoded
                // from a JSON literal: the value is a compile-time constant of
                // the RM model, so there is no fallible step to handle.
                committer: PartyProxy::PartyIdentified(PartyIdentified::PartyIdentified(
                    PartyIdentifiedData {
                        external_ref: None,
                        name: Some(crate::service::SYSTEM_COMMITTER_NAME.to_owned()),
                        identifiers: Vec::new(),
                    },
                )),
                system_id: None,
            },
            signature: None,
        }
    }
}

/// The client-supplied committal metadata of a **direct** commit whose
/// `UPDATE_VERSION` envelope never travels in the request body — the bare
/// `POST`/`PUT`/`DELETE` writes on a change-controlled resource, where the
/// only channel for it is the `openehr-version` / `openehr-audit-details`
/// request headers.
///
/// ITS-REST overview `Requests_and_responses.md` §"openehr-version and
/// openehr-audit-details": "services MUST accept `openehr-version` and
/// `openehr-audit-details` custom request headers", and "None of these headers
/// are mandatory, but whatever is provided it MUST be merged with the default
/// VERSION and `VERSION.audit_details` attributes on commit runtime." This type
/// carries the two halves of that merge — the `UPDATE_AUDIT` attributes and
/// the VERSION `lifecycle_state` — for the commit paths whose arguments are
/// the bare RM content (EHR creation) rather than a full envelope.
#[derive(Debug, Clone)]
pub struct Committal {
    /// The merged `UPDATE_AUDIT` attributes (`change_type`, `description`,
    /// `committer`, `system_id`), already seeded with the server defaults the
    /// client did not override.
    pub audit: UpdateAudit,
    /// `UPDATE_VERSION.lifecycle_state` as its numeric
    /// `version_lifecycle_state` code, when the client supplied one through
    /// `openehr-version`; `None` leaves the server default (`532|complete|`,
    /// RM common master06 §Version Lifecycle).
    pub lifecycle_state: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn update_version_deserializes_the_wire_shape() {
        // The ITS-REST `UpdateVersion.yaml` field names: `commit_audit`,
        // partial attestations, `signature`.
        let v: UpdateVersion = serde_json::from_value(json!({
            "preceding_version_uid": { "value": "8849182c-82ad-4088-a07f-48ead4180515::sys::1" },
            "lifecycle_state": { "terminology_id": "openehr", "code_string": "532" },
            "data": { "_type": "COMPOSITION" },
            "signature": "sig-bytes",
            "commit_audit": {
                "change_type": { "terminology_id": "openehr", "code_string": "251" },
                "committer": { "_type": "PARTY_IDENTIFIED", "name": "A user" }
            }
        }))
        .expect("wire-shaped UPDATE_VERSION deserializes");
        assert!(v.preceding_version_uid.is_some());
        assert_eq!(v.signature.as_deref(), Some("sig-bytes"));
        assert!(v.attestations.is_none());
    }
}
