// @generated by openehr-codegen from BMM (`C_ATTRIBUTE_TUPLE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `C_ATTRIBUTE_TUPLE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v2_4::aom2::constraint_model::c_attribute::CAttribute;
use crate::v2_4::aom2::constraint_model::c_primitive_tuple::CPrimitiveTuple;

/// Object representing a constraint on an attribute tuple, i.e. a group of attributes that are constrained together.
///
/// Typically used for representing co-varying constraints like `{units, range}` constraints.
#[doc(alias = "C_ATTRIBUTE_TUPLE")]
#[derive(Debug, Clone, PartialEq)]
pub struct CAttributeTuple {
    /// List of `C_ATTRIBUTEs` forming the definition of the tuple.
    pub members: Option<Vec<CAttribute>>,
    /// Tuple definitions.
    pub tuples: Option<Vec<CPrimitiveTuple>>,
}
