// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `v1_1/bmm3/core/model` — generated module tree.

pub mod bmm_model;
pub mod bmm_model_metadata;
pub mod bmm_package;
pub mod bmm_package_container;

// hand-written modules (spec behaviour), auto-declared:
pub mod bmm_model_impl;
