=== CODE_SET Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*CODE_SET*

h|*Description*
2+a|A code set.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of this code set.

h|*1..1*
|*openehr_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier used for code set in the openEHR Reference Model. The value is inferred from the `_name_` attribute.

Valid values take the form of an xs:NCName value, i.e. cannot contain:

* symbol characters `:, @, $, %, &, /, +, ,, ;`;
* whitespace characters or different parentheses. 

An NCName cannot begin with a number, dot or minus character although these can appear later in the value.

h|*1..1*
|*issuer*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of the issuing organisation.

h|*0..1*
|*codes*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_code_class,CODE>>>`
a|Codes in this code set.

h|*0..1*
|*external_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|An optional identifier assumed by openEHR to be the identifier of this code set, based on its published name, with spaces replaced by underscores.

Valid values take the form of an xs:NCName value, i.e. cannot contain:

* symbol characters `:, @, $, %, &, /, +, ,, ;`;
* whitespace characters or different parentheses. 

An NCName cannot begin with a number, dot or minus character although these can appear later in the value.

h|*0..1*
|*status*: `<<_terminology_status_enumeration,TERMINOLOGY_STATUS>> +
{default{nbsp}={nbsp}}`
a|Status of this code set.
|===
