// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `v1_1/common/directory` — generated module tree.

pub mod folder;
pub mod versioned_folder;

// hand-written modules (spec behaviour), auto-declared:
pub mod folder_impl;
