// @generated by openehr-codegen from BMM (`BMM_UNITARY_TYPE`) — DO NOT EDIT.

use crate::bmm3::core::entity::bmm_parameter_type::BmmParameterType;
use crate::bmm3::core::entity::bmm_signature::BmmSignature;
use crate::bmm3::core::entity::bmm_status_type::BmmStatusType;
use crate::bmm3::core::entity::bmm_tuple_type::BmmTupleType;

/// Parent of meta-types that may be used as the type of any instantiated object that is not a container object.
/// Closed subtype set of `BMM_UNITARY_TYPE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum BmmUnitaryType {
    BmmParameterType(BmmParameterType),
    BmmSignature(BmmSignature),
    BmmStatusType(BmmStatusType),
    BmmTupleType(BmmTupleType),
}
