// @generated by openehr-codegen from BMM (`BMM_STATUS_TYPE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `BMM_STATUS_TYPE` spec class, generated from the vendored BMM
//! meta-model.

/// Built-in meta-type representing action status, e.g. result of a call invocation.
#[doc(alias = "BMM_STATUS_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmStatusType {}

impl BmmStatusType {
    /// Base name (built-in).
    /// BMM constant `base_name`.
    pub const BASE_NAME: &'static str = "Status";
}
