// @generated by openehr-codegen from BMM (`VERSIONED_FOLDER`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `VERSIONED_FOLDER` spec class, generated from the vendored BMM
//! meta-model.

use crate::data_types::quantity::date_time::dv_date_time::DvDateTime;
use openehr_base::prelude::HierObjectId;
use openehr_base::prelude::ObjectRef;

/// A version-controlled hierarchy of `FOLDERs` giving the effect of a directory.
#[doc(alias = "VERSIONED_FOLDER")]
#[derive(Debug, Clone, PartialEq)]
pub struct VersionedFolder {
    // inherited: VERSIONED_OBJECT
    /// Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
    pub uid: HierObjectId,
    /// Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
    pub owner_id: ObjectRef,
    /// Time of initial creation of this versioned object.
    pub time_created: DvDateTime,
}
