name: Task
description: A general work item (maintenance, research, tooling, docs)
labels: ["chore"]
body:
  - type: textarea
    attributes:
      label: Contract
      description: The goal of this task and its impact once completed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exit criteria
      description: The checklist that defines "done".
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Further information
    validations:
      required: false
