# SPDX-FileCopyrightText: Ruben Talstra
# SPDX-License-Identifier: BUSL-1.1

name: Task
description: A general work item (maintenance, research, tooling, docs)
labels: ["chore"]
body:
  - type: textarea
    id: contract
    attributes:
      label: Contract
      description: The goal of this task and its impact once completed.
    validations:
      required: true
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: The checklist that defines "done".
      value: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further information
    validations:
      required: false
