// @generated by openehr-codegen from BMM (`C_DATE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `C_DATE` spec class, generated from the vendored BMM
//! meta-model.

use openehr_base::prelude::Interval;
use openehr_base::prelude::Iso8601Date;
use openehr_base::prelude::ValidityKind;

/// ISO 8601-compatible constraint on instances of Date in the form either of a set of validity values, or an actual date range. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date at all. Syntax expressions of instances of this class include “YYYY-??-??” (date with optional month and day).
#[doc(alias = "C_DATE")]
#[derive(Debug, Clone, PartialEq)]
pub struct CDate {
    /// The value to assume if this item is not included in data, due to being part of an optional structure.
    pub assumed_value: Option<Iso8601Date>,
    /// Validity of day in constrained date.
    pub day_validity: Option<ValidityKind>,
    /// Validity of month in constrained date.
    pub month_validity: Option<ValidityKind>,
    /// Interval of Dates specifying constraint.
    pub range: Option<Interval<Iso8601Date>>,
}
