// @generated by openehr-codegen from BMM (`C_DATE_TIME`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use openehr_derive::OpenEhrType;

/// ISO 8601-compatible constraint on instances of Date_Time. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date/time at all. Syntax expressions of instances of this class include “YYYY-MM-DDT??:??:??” (date/time with optional time) and “YYYY-MMDDTHH:MM:xx” (date/time, seconds not allowed).
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "C_DATE_TIME")]
pub struct CDateTime {
    /// The value to assume if this item is not included in data, due to being part of an optional structure.
    pub assumed_value: Option<serde_json::Value>,
    /// Validity of month in constrained date.
    pub month_validity: Option<serde_json::Value>,
    /// Validity of day in constrained date.
    pub day_validity: Option<serde_json::Value>,
    /// Validity of hour in constrained time.
    pub hour_validity: Option<serde_json::Value>,
    /// Validity of minute in constrained time.
    pub minute_validity: Option<serde_json::Value>,
    /// Validity of second in constrained time.
    pub second_validity: Option<serde_json::Value>,
    /// Validity of millisecond in constrained time.
    pub millisecond_validity: Option<serde_json::Value>,
    /// Validity of timezone in constrained date.
    pub timezone_validity: Option<serde_json::Value>,
    /// Range of Date_times specifying constraint.
    pub range: Option<serde_json::Value>,
}
