// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `am14/aom14/archetype/primitive` — generated module tree.

pub mod c_boolean;
pub mod c_date;
pub mod c_date_time;
pub mod c_duration;
pub mod c_integer;
pub mod c_primitive;
pub mod c_real;
pub mod c_string;
pub mod c_time;
