= Amendment Record

[cols="1,6,2,2", options="header"]
|===
|Issue|Details|Raiser|Completed

4+^h|*LANG Release 1.1.0 (unreleased)*

|[[latest_issue]]2.2.4
|{spec_tickets}/SPECLANG-14[SPECLANG-14^]. Formalise the BMM v2/v3 split: this specification is established as a separate, stable BMM document in the LANG component; the evolved meta-model is maintained in the separate BMM v3 specification.
|S Iancu
|[[latest_issue_date]]31 May 2026

4+^h|*LANG Release 1.0.0*

|2.2.3
|{spec_tickets}/SPECLANG-2[SPECLANG-2^]. Add Basic Meta-Model (BMM) spec to LANG component.
|openEHR SEC
|07 Nov 2017

|2.2.2
|Improve and update introductory text in the Overview section.
|E Sundvall, +
 T Beale
|03 Nov 2017

|2.2.1
|Rename `P_BMM_SIMPLE_TYPE_OPEN` to `P_BMM_OPEN_TYPE`; +
 Remove `BMM_CLASSIFIER._conformance_type_name_`; +
 Rename `P_BMM_GENERIC_PARAMETER._create_bmm_generic_parameter_definition_` to `_create_bmm_generic_parameter_`; +
 Remove inheritance from `P_BMM_PACKAGE_CONTAINER` to `P_BMM_MODEL_ELEMENT`; +
 Make `P_BMM_MODEL_ELEMENT` abstract; +
 Correct `P_BMM_ENUMERATION._items_names_` cardinality to multiple; +
 Constrain `BMM_GENERIC_PARAMETER._name_` and `P_BMM_GENERIC_PARAMETER._name_` to one character and upper case.
|C Nanjo, +
 T Beale
|02 Mar 2017

|2.2.0
|Rename `BMM_CLASSIFIER._as_type_string_` to `_type_name_` and `_as_conformance_type_string_` to `_conformance_type_name_`. +
 Move and rename `BMM_TYPE._as_display_type_string_` to `BMM_CLASSIFIER._type_signature_`. Add redefinitions in relevant descendant classes. +
 Rename `BMM_SIMPLE_TYPE_OPEN` to `BMM_OPEN_TYPE`. +
 Add new class `BMM_TYPE_ELEMENT` in preparation for BMM 3 refactoring. +
 Remove class `P_BMM_CLASSIFIER`. +
 Add missed inheritance from `P_BMM_PROPERTY` to `P_BMM_MODEL_ELEMENT`. +
 Rename `BMM_SCHEMA` to `BMM_MODEL`.
|T Beale
|20 Jun 2016

|
|Add missing inheritance from `P_BMM_SCHEMA` to `BMM_SCHEMA_CORE`. +
 Correct naming of `_bmm_xxx_definition_`, `_create_bmm_xxx_definition_` in `P_BMM_XXX` classes to `_bmm_xxx_`, `_create_bmm_xxx_` etc.
|T Beale
|18 Apr 2016

|2.1.0
|Initial writing based on ADL Workbench implementation.
|T Beale
|08 Feb 2016

|===
