// @generated by openehr-codegen from BMM (`Interval`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `Interval` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::foundation_types::interval::point_interval::PointInterval;
use crate::v1_2::foundation_types::interval::proper_interval::ProperInterval;

/// Closed subtype set of `Interval`, dispatched on each payload's `_type`.
///
/// Interval abstraction, featuring upper and lower limits that may be open or closed, included or not included.
#[derive(Debug, Clone, PartialEq)]
pub enum Interval<T> {
    /// The `Point_interval` subtype of `Interval`.
    PointInterval(PointInterval<T>),
    /// The `Proper_interval` subtype of `Interval`.
    ProperInterval(ProperInterval<T>),
}
