// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v1_2` — generated module tree.

pub mod base_types;
pub mod foundation_types;
pub mod prelude;
pub mod resource;
