// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0
//! Prelude: re-exports every generated spec type of ONE generation.
//!
//! Per-file imports are precise;
//! downstream crates and hand-written code may `use <path>::*`.
//!
//! The crate-level prelude re-exports the CURRENT generation only (the
//! composition table's `current` marker); every generation module also
//! carries its own `prelude`. An older generation's types are reached
//! through its generation module (its prelude or full module paths) —
//! no cross-generation collision resolution exists anywhere.

pub use crate::v1_2::base_types::definitions::validity_kind::ValidityKind;
pub use crate::v1_2::base_types::definitions::version_status::VersionStatus;
pub use crate::v1_2::base_types::identification::access_group_ref::AccessGroupRef;
pub use crate::v1_2::base_types::identification::archetype_id::ArchetypeId;
pub use crate::v1_2::base_types::identification::generic_id::GenericId;
pub use crate::v1_2::base_types::identification::hier_object_id::HierObjectId;
pub use crate::v1_2::base_types::identification::internet_id::InternetId;
pub use crate::v1_2::base_types::identification::iso_oid::IsoOid;
pub use crate::v1_2::base_types::identification::locatable_ref::LocatableRef;
pub use crate::v1_2::base_types::identification::object_id::ObjectId;
pub use crate::v1_2::base_types::identification::object_ref::ObjectRef;
pub use crate::v1_2::base_types::identification::object_ref::ObjectRefData;
pub use crate::v1_2::base_types::identification::object_version_id::ObjectVersionId;
pub use crate::v1_2::base_types::identification::party_ref::PartyRef;
pub use crate::v1_2::base_types::identification::template_id::TemplateId;
pub use crate::v1_2::base_types::identification::terminology_id::TerminologyId;
pub use crate::v1_2::base_types::identification::uid::Uid;
pub use crate::v1_2::base_types::identification::uid_based_id::UidBasedId;
pub use crate::v1_2::base_types::identification::uuid::Uuid;
pub use crate::v1_2::base_types::identification::version_tree_id::VersionTreeId;
pub use crate::v1_2::foundation_types::interval::cardinality::Cardinality;
pub use crate::v1_2::foundation_types::interval::interval::Interval;
pub use crate::v1_2::foundation_types::interval::multiplicity_interval::MultiplicityInterval;
pub use crate::v1_2::foundation_types::interval::point_interval::PointInterval;
pub use crate::v1_2::foundation_types::interval::proper_interval::ProperInterval;
pub use crate::v1_2::foundation_types::interval::proper_interval::ProperIntervalData;
pub use crate::v1_2::foundation_types::terminology::terminology_code::TerminologyCode;
pub use crate::v1_2::foundation_types::terminology::terminology_term::TerminologyTerm;
pub use crate::v1_2::foundation_types::time::iso8601_date::Iso8601Date;
pub use crate::v1_2::foundation_types::time::iso8601_date_time::Iso8601DateTime;
pub use crate::v1_2::foundation_types::time::iso8601_duration::Iso8601Duration;
pub use crate::v1_2::foundation_types::time::iso8601_time::Iso8601Time;
pub use crate::v1_2::foundation_types::time::iso8601_timezone::Iso8601Timezone;
pub use crate::v1_2::foundation_types::time::iso8601_type::Iso8601Type;
pub use crate::v1_2::resource::authored_resource::AuthoredResource;
pub use crate::v1_2::resource::resource_annotations::ResourceAnnotations;
pub use crate::v1_2::resource::resource_description::ResourceDescription;
pub use crate::v1_2::resource::resource_description_item::ResourceDescriptionItem;
pub use crate::v1_2::resource::translation_details::TranslationDetails;
