//! The SM Subject Proxy Service — `I_SUBJECT_PROXY_SERVICE` + the internal
//! `I_DATA_BINDING` interface and their information structures, transcribed
//! literally from the vendored spec.
//!
//! Spec sources
//! (`docs/specs/openehr/SM/docs/openehr_platform/master10-subject_proxy_service.adoc`
//! and the `UML/classes/*.adoc` it includes):
//! `i_subject_proxy_service.adoc`, `i_data_binding.adoc`, `subject_proxy.adoc`,
//! `subject_variable.adoc`, `subject_data_set.adoc`, `data_set_result.adoc`,
//! `sample.adoc`, `data_frame_sample.adoc`, `openehr_sample.adoc`,
//! `hl7v2_sample.adoc`, `hl7_fhir_sample.adoc`, `variable_sample.adoc`,
//! `variable_value.adoc` (+ `_single`/`_list`/`_time_series`), `env_binding.adoc`,
//! `data_frame.adoc`. Design digest:
//! `docs/design/sm-platform/04-message-subject-proxy-terminology-admin.md` §2 +
//! `docs/design/sm-platform/08-target-architecture.md` §4.4.
//!
//! The SPS "allows symbolic variables characterising the real world state of a
//! _subject_ … to be retrieved and tracked over time … The SPS avoids the
//! calling application having to know about the particular standard,
//! representational model, query language or API of the data source"
//! (master10 §Overview).
//!
//! PORT NOTE (no wire). ITS-REST vendors **no** Subject Proxy endpoints; the
//! design places the SPS behind the server's extension surface
//! (`docs/design/sm-platform/08-target-architecture.md` §5,
//! `/rest/subject_proxy`), which is out of CORE/STANDARD conformance scope.
//! Like [`EhrExtractService`](super::EhrExtractService) and
//! [`TddService`](super::TddService) this is therefore a **native-API-only**
//! capability and is deliberately **not** part of the [`Platform`](crate::Platform)
//! union; the concrete service implements it directly. Extension routes + the
//! JSON/YAML data-set/binding ingestion (master10 §Specifying a Data-set /
//! §Specifying a Binding) are a later wave (blueprint SM-6, roadmap doc 09).
//!
//! PORT NOTE (design-filled errors). The SM declares only pre-conditions
//! (`has_subject` / `has_application` / `has_binding` / `not has_*`) and no
//! error codes. Every unmet pre-condition surfaces as
//! [`SmError`]`(PreconditionViolation, …)` over `CALL_STATUS_TYPE` — the exact
//! shape the spec's `__Pre_…__` clauses describe.

use std::collections::BTreeMap;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::SmError;

// ─── VARIABLE_VALUE hierarchy (`variable_value*.adoc`) ────────────────────────

/// `VARIABLE_VALUE` — "Abstract parent of variable value structures"
/// (`variable_value.adoc`). Its three concrete descendants form a closed subtype
/// set, so this is an idiomatic Rust enum (the codegen closed-subtype rule) rather
/// than a trait; the payloads are `Any`, carried as canonical JSON [`Value`]s.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "_type")]
pub enum VariableValue {
    /// `VARIABLE_VALUE_SINGLE` — "Atomic Variable value" (`value: Any [0..1]`,
    /// `variable_value_single.adoc`).
    #[serde(rename = "VARIABLE_VALUE_SINGLE")]
    Single {
        /// The single value, from the source frame's latest sample.
        value: Option<Value>,
    },
    /// `VARIABLE_VALUE_LIST` — "Variable value in the form of a list"
    /// (`value: List<Any> [0..1]`, `variable_value_list.adoc`).
    #[serde(rename = "VARIABLE_VALUE_LIST")]
    List {
        /// The list of values, from the source frame's latest sample.
        value: Vec<Value>,
    },
    /// `VARIABLE_VALUE_TIME_SERIES` — "Variable value in the form of a
    /// time-series" (`value: Hash<Iso8601_date_time, Any> [0..1]`,
    /// `variable_value_time_series.adoc`).
    #[serde(rename = "VARIABLE_VALUE_TIME_SERIES")]
    TimeSeries {
        /// The time-keyed values (ISO-8601 date-time → `Any`).
        value: BTreeMap<String, Value>,
    },
}

// ─── SAMPLE hierarchy (`sample.adoc`, `data_frame_sample.adoc`, …) ────────────

/// `SAMPLE<T>` — "One retrieval (sample) of a data 'block', generated by
/// invocation of some retrieval method … encompasses retrieval (attempt)
/// time-stamp, availability status, and result, if available" (`sample.adoc`).
///
/// Generic over the payload `T`, exactly as the spec's `SAMPLE<T>`:
/// [`DataFrameSample`] is `Sample<FramePayload>` and [`VariableSample`] is
/// `Sample<VariableValue>`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sample<T> {
    /// `retrieve_time [1]` — time the retrieve attempt was made (ISO-8601).
    pub retrieve_time: String,
    /// `effective_time [0..1]` — real-world time the data pertains to, if
    /// available (compared against [`SubjectVariable::currency`] for freshness).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_time: Option<String>,
    /// `is_unavailable [1]` — true if no data was available for this attempt.
    pub is_unavailable: bool,
    /// `unavailable_reason [0..1]` — reason for absent data, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unavailable_reason: Option<String>,
    /// `result: T [0..1]` — result of the retrieve call, if available.
    #[serde(default = "Option::default", skip_serializing_if = "Option::is_none")]
    pub result: Option<T>,
}

impl<T> Sample<T> {
    /// An available sample carrying `result`, stamped `retrieve_time = now`.
    #[must_use]
    pub fn available(result: T) -> Self {
        Self {
            retrieve_time: now_iso(),
            effective_time: None,
            is_unavailable: false,
            unavailable_reason: None,
            result: Some(result),
        }
    }

    /// An unavailable sample (`is_unavailable = true`) with a reason.
    #[must_use]
    pub fn unavailable(reason: impl Into<String>) -> Self {
        Self {
            retrieve_time: now_iso(),
            effective_time: None,
            is_unavailable: true,
            unavailable_reason: Some(reason.into()),
            result: None,
        }
    }
}

/// The payload of a [`DataFrameSample`]: the closed set of the three concrete
/// `DATA_FRAME_SAMPLE` descendants the spec defines
/// (`openehr_sample.adoc` / `hl7v2_sample.adoc` / `hl7_fhir_sample.adoc`).
/// Modelling the descendants as an enum variant on the payload is the codegen's
/// closed-subtype treatment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "_type")]
pub enum FramePayload {
    /// `OPENEHR_SAMPLE` — "openEHR sample whose result is in the form of a
    /// `RESULT_SET` structure" (`openehr_sample.adoc`). Carries the ITS-REST
    /// 1.0.3 `RESULT_SET` canonical JSON the Query service returned.
    #[serde(rename = "OPENEHR_SAMPLE")]
    Openehr {
        /// The `RESULT_SET` (canonical JSON).
        result_set: Value,
    },
    /// `HL7v2_SAMPLE` — "Container for `HL7v2` message based data frame results"
    /// (`hl7v2_sample.adoc`). Stubbed seam (never produced yet — see
    /// [`DataBinding::get_frame`]).
    #[serde(rename = "HL7v2_SAMPLE")]
    Hl7v2 {
        /// The raw `HL7v2` message text.
        message: String,
    },
    /// `HL7_FHIR_SAMPLE` — "Container for HL7 FHIR based data frame results"
    /// (`hl7_fhir_sample.adoc`). Stubbed seam (never produced yet).
    #[serde(rename = "HL7_FHIR_SAMPLE")]
    Hl7Fhir {
        /// The FHIR resource (canonical JSON).
        resource: Value,
    },
}

/// `DATA_FRAME_SAMPLE<T>` — "Abstract class with methods for extracting single
/// variable values from data frames" (`data_frame_sample.adoc`); a `SAMPLE`
/// whose payload is a back-end retrieval result ([`FramePayload`]).
pub type DataFrameSample = Sample<FramePayload>;

/// `VARIABLE_SAMPLE` — "Sample whose result is in the form of a `VARIABLE_VALUE`
/// (descendant) structure" (`variable_sample.adoc`).
pub type VariableSample = Sample<VariableValue>;

// ─── SUBJECT_VARIABLE (`subject_variable.adoc`) ───────────────────────────────

/// `SUBJECT_VARIABLE` — "A single subject variable whose data may take various
/// forms, including atomic, list and time series" (`subject_variable.adoc`).
///
/// PORT NOTE (dropped runtime attributes). The spec's `history:
/// List<VARIABLE_SAMPLE> [0..1]` and `last_frame: DATA_FRAME_SAMPLE [0..1]` are
/// *runtime* sample state, not configuration; master10 §Persistence persists
/// only "the configuration contents (i.e. not data frame or variable results)".
/// This definition-time type therefore omits them — sample history / last-frame
/// caching (the `sp_sample` store + currency-based freshness of design 08 §4.4)
/// is deferred, and [`get_variable`](SubjectProxyService::get_variable)
/// re-executes the bound frame each call (always "most recent available", which
/// `currency = Void` explicitly allows).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubjectVariable {
    /// `namespace [0..1]` — optional namespace qualifying `name` (e.g.
    /// `cha2ds2vasc`); unset ⇒ the variable is in the 'global' namespace.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// `name [1]` — canonical name by which this item is known in the service
    /// (e.g. `date_of_birth`).
    pub name: String,
    /// `type_name [1]` — formal type name from the defining model.
    pub type_name: String,
    /// `currency: Iso8601_duration [0..1]` — required currency; unset ⇒ most
    /// recent available is valid.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// `ask_user: Boolean [0..1]` — if true, the service should attempt to
    /// obtain the item from a live user (unsupported here; see the type doc).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ask_user: Option<bool>,
    /// `is_manual: Boolean [1]` — true if obtained by manual notification.
    pub is_manual: bool,
    /// `frame_id [1]` — identifier of the retrieve frame from which to extract
    /// this variable.
    pub frame_id: String,
    /// `frame_path [1]` — path within the `last_frame` result at which the
    /// value sits (see [`SubjectProxyService::get_variable`] for the `RESULT_SET`
    /// selector semantics we adopt).
    pub frame_path: String,
}

impl SubjectVariable {
    /// `canonical_name (): String` — "Return canonical name, formed from
    /// `namespace` (if present) and `name` … `namespace::name` … or just
    /// `name`" (`subject_variable.adoc`).
    /// Subject-variable naming validity (SM master10 §Subject Variable
    /// Naming): a canonical name "may not include whitespace or any
    /// unprintable character". Checked over both `name` and `namespace`
    /// (the canonical name is formed from them); the name must be non-empty.
    #[must_use]
    pub fn name_valid(&self) -> bool {
        fn part_ok(s: &str) -> bool {
            !s.is_empty() && s.chars().all(|c| !c.is_whitespace() && !c.is_control())
        }
        part_ok(&self.name) && self.namespace.as_deref().is_none_or(part_ok)
    }

    #[must_use]
    pub fn canonical_name(&self) -> String {
        match &self.namespace {
            Some(ns) if !ns.is_empty() => format!("{ns}::{}", self.name),
            _ => self.name.clone(),
        }
    }

    /// `is_global (): Boolean` with `__Post_result__: Result = (namespace =
    /// Void)` — "True if `namespace` is set". PORT NOTE: the prose ("True if
    /// namespace is set") contradicts the post-condition; per the design digest
    /// (§2.2) the post-condition is the consistent reading — *global* means
    /// **no** namespace.
    #[must_use]
    pub fn is_global(&self) -> bool {
        self.namespace.as_ref().is_none_or(String::is_empty)
    }
}

// ─── SUBJECT_DATA_SET (`subject_data_set.adoc`) ───────────────────────────────

/// `SUBJECT_DATA_SET` — "Data set relating to a subject as used within an
/// application" (`subject_data_set.adoc`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubjectDataSet {
    /// `id [1]` — unique identifier of this data set for the subject (usually an
    /// application semantic label, e.g. a guideline id).
    pub id: String,
    /// `subject_id [1]` — identifier of the data subject.
    pub subject_id: String,
    /// `creating_app_id [0..1]` — identifier of the creating/registering
    /// application.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creating_app_id: Option<String>,
    /// `using_app_ids: List<String> [0..1]` — applications using this data set.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub using_app_ids: Vec<String>,
    /// `variables: Hash<String, SUBJECT_VARIABLE> [1]` — the variable set keyed
    /// by *local* name within the data set, which may differ from the variable's
    /// canonical `name` (e.g. `dob` → `date_of_birth`).
    pub variables: BTreeMap<String, SubjectVariable>,
}

/// `DATA_SET_RESULT` — "Data set result consisting of full set of variable
/// values extracted from data retrieve frame sources" (`data_set_result.adoc`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DataSetResult {
    /// `name [1]` — unique name of this data set.
    pub name: String,
    /// `subject_id [1]` — identifier of the data subject.
    pub subject_id: String,
    /// `variables: List<VARIABLE_SAMPLE> [0..1]` — samples of the variables in
    /// this data set.
    #[serde(default)]
    pub variables: Vec<VariableSample>,
}

// ─── bindings (`env_binding.adoc`, `data_frame.adoc`) ─────────────────────────

/// The retrieval method of a [`DataFrame`]. The SM types this
/// `SYSTEM_CALL [0..1]` (openEHR PROC `task_planning.html#_system_call_class`),
/// with the `QUERY_CALL` / `API_CALL` descendants shown in the master10 YAML
/// examples (§Specifying a Binding).
///
/// PORT NOTE: `SYSTEM_CALL` and its PROC descendants are **not** vendored or
/// generated in this workspace (the PROC/task-planning spec is out of scope), so
/// the method is modelled as the closed set the frame executors actually
/// dispatch on. Only [`FrameMethod::Aql`] is realized; the FHIR / `HL7v2` variants
/// are typed seams (`get_frame` rejects them `NotImplemented`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "_type")]
pub enum FrameMethod {
    /// openEHR `QUERY_CALL` (`call_name: aql_query`): AQL executed through the
    /// Query service, producing a `RESULT_SET` ([`FramePayload::Openehr`]).
    #[serde(rename = "QUERY_CALL")]
    Aql {
        /// The AQL query text (may reference `$subject_id`, bound by the
        /// executor to the `get_frame` subject).
        query_text: String,
    },
    /// HL7 FHIR `API_CALL` seam — carried verbatim, executed nowhere yet.
    #[serde(rename = "FHIR_API_CALL")]
    Fhir {
        /// Target system identifier.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        system_id: Option<String>,
        /// Named API call (e.g. `fhir_get`).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        call_name: Option<String>,
        /// Query/URL text for the FHIR request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        query_text: Option<String>,
    },
    /// `HL7v2` seam — carried verbatim, executed nowhere yet.
    #[serde(rename = "HL7v2_CALL")]
    Hl7v2 {
        /// Target system identifier.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        system_id: Option<String>,
        /// Named call.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        call_name: Option<String>,
    },
}

/// `DATA_FRAME` — "Data retrieval frame, consisting of primary and fallback
/// retrieval methods … and most recent result" (`data_frame.adoc`).
///
/// PORT NOTE: the runtime "most recent result" is not persisted (master10
/// §Persistence); this configuration type carries `id`, `model_type`, and the
/// primary/fallback methods only.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DataFrame {
    /// `id [1]` — the frame identifier (e.g. `openEHR::vital_signs`), referenced
    /// by [`SubjectVariable::frame_id`].
    pub id: String,
    /// `model_type [1]` — name of the underlying model/type system, e.g.
    /// `"openehr"`, `"hl7v2"`, `"hl7-fhir"` ("Currently not standardised").
    pub model_type: String,
    /// `primary_method: SYSTEM_CALL [0..1]` — the method used to perform the
    /// retrieval.
    pub primary_method: FrameMethod,
    /// `fallback_method: SYSTEM_CALL [0..1]` — alternative method if the primary
    /// retrieve fails.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fallback_method: Option<FrameMethod>,
}

/// `ENV_BINDING` — "Binding for an execution environment to a set of subject
/// variables" (`env_binding.adoc`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnvBinding {
    /// `env_id [1]` — identifier of the environment this binding is designed for.
    pub env_id: String,
    /// `description [0..1]` — informal description of the environment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// `data_frames: List<DATA_FRAME> [0..1]` — the frames of this binding.
    #[serde(default)]
    pub data_frames: Vec<DataFrame>,
}

// ─── the service interface (`i_subject_proxy_service.adoc`) ───────────────────

/// `I_SUBJECT_PROXY_SERVICE` — "Service that maintains subject 'proxies'
/// consisting of variables, and also enables applications to associate data-sets
/// with subject variables" (`i_subject_proxy_service.adoc`). One Rust method per
/// SM call, verbatim call names/parameters/pre-conditions.
///
/// No default method bodies (compile-time completeness by design): a backend that
/// does not implement a call is a build error, not a silent runtime stub.
#[async_trait]
pub trait SubjectProxyService: Send + Sync {
    /// `register_subject (subject_id: String, subject_category: String [0..1])`
    /// with `__Pre_subject_valid__: not has_subject(subject_id)`. "Register a
    /// new subject. The subject category may … be specified, otherwise it will
    /// be the default category."
    async fn register_subject(
        &self,
        subject_id: String,
        subject_category: Option<String>,
    ) -> Result<(), SmError>;

    /// `add_subject_variable (subject_id: String, var: SUBJECT_VARIABLE)` with
    /// `__Pre_subject_valid__: has_subject(subject_id)`. "Add a new subject
    /// variable definition to the proxy for `subject_id`."
    async fn add_subject_variable(
        &self,
        subject_id: String,
        var: SubjectVariable,
    ) -> Result<(), SmError>;

    /// `register_application_data_set (definition: SUBJECT_DATA_SET)` with
    /// `__Pre_subject_valid__: has_subject(subject_id)` — the `subject_id` is
    /// inside `definition` (spec imprecision, digest §2.2). "Register a data-set
    /// … This may have the effect of creating new subject variables, reducing
    /// the currency of existing subject variables …, or making no change …".
    async fn register_application_data_set(
        &self,
        definition: SubjectDataSet,
    ) -> Result<(), SmError>;

    /// `remove_application_data_set (subject_id: String, application_id: String)`
    /// with `__Pre_subject_valid__: has_subject` + `__Pre_application_valid__:
    /// has_application`. "Remove this data-set from the service."
    async fn remove_application_data_set(
        &self,
        subject_id: String,
        application_id: String,
    ) -> Result<(), SmError>;

    /// `remove_subject (subject_id: String)` with `__Pre_subject_valid__:
    /// has_subject`. "Remove proxy and any data-sets for an existing subject."
    async fn remove_subject(&self, subject_id: String) -> Result<(), SmError>;

    /// `remove_application (application_id: String)` with
    /// `__Pre_application_valid__: has_application`. "Remove all data-sets for
    /// `application_id`, across all subjects."
    async fn remove_application(&self, application_id: String) -> Result<(), SmError>;

    /// `get_variable (subject_id: String, var_name: String): VARIABLE_VALUE`
    /// with `__Pre_subject_valid__: has_subject`. "Get a single variable value
    /// from a data-set."
    async fn get_variable(
        &self,
        subject_id: String,
        var_name: String,
    ) -> Result<VariableValue, SmError>;

    /// `get_data_set (subject_id: String, data_set_id: String): DATA_SET_RESULT`
    /// with `__Pre_subject_valid__: has_subject`. "Get a full data set result."
    async fn get_data_set(
        &self,
        subject_id: String,
        data_set_id: String,
    ) -> Result<DataSetResult, SmError>;

    /// `has_subject (subject_id: String): Boolean`. "Return True if subject with
    /// id `subject_id` has been registered in the service."
    async fn has_subject(&self, subject_id: String) -> Result<bool, SmError>;

    /// `has_application (application_id: String): Boolean`. "Return True if
    /// application with id `application_id` has been registered in the service."
    async fn has_application(&self, application_id: String) -> Result<bool, SmError>;

    /// `get_variable_defs (subject_id: String): List<String>`. "Return a list of
    /// variable definitions each of the form 'name: Type', where 'name' is the
    /// canonical name, i.e. `SUBJECT_VARIABLE.name`."
    async fn get_variable_defs(&self, subject_id: String) -> Result<Vec<String>, SmError>;

    /// `register_binding (binding: ENV_BINDING)` with `__Pre_new_env__: not
    /// has_binding(binding.env_id)`. "Register a binding for an environment …".
    async fn register_binding(&self, binding: EnvBinding) -> Result<(), SmError>;

    /// `add_binding_frame (env_id: String, frame[1])` with `__Pre_valid_binding__:
    /// has_binding(env_id)`. "Add a retrieve frame definition to the binding
    /// container for an environment."
    ///
    /// PORT NOTE: the SM leaves the `frame` parameter **untyped**
    /// (`add_binding_frame (env_id, frame[1])`); we type it as [`DataFrame`], the
    /// element type of `ENV_BINDING.data_frames`.
    async fn add_binding_frame(&self, env_id: String, frame: DataFrame) -> Result<(), SmError>;

    /// `has_binding (env_id: String): Boolean`. "Return True if environment
    /// binding with id `env_id` has been registered in the service."
    async fn has_binding(&self, env_id: String) -> Result<bool, SmError>;

    /// `reset` — "Set back to virgin state, i.e. remove all subjects, variables
    /// and bindings" (master10 §Persistence).
    async fn reset(&self) -> Result<(), SmError>;
}

// ─── the internal binding interface (`i_data_binding.adoc`) ───────────────────

/// `I_DATA_BINDING` — "Internal interface via which Variable bindings are
/// invoked to obtain data" (`i_data_binding.adoc`).
///
/// PORT NOTE: the SM lists a `bindings: List<ENV_BINDING>` attribute here ("All
/// bindings registered in this service, one per environment"); it is realized by
/// the binding store and surfaced through
/// [`SubjectProxyService::has_binding`] / `register_binding`, not as a getter.
#[async_trait]
pub trait DataBinding: Send + Sync {
    /// `get_frame (subject_id: String, frame_id: String): DATA_FRAME_SAMPLE`.
    /// "Execute a retrieve on a data frame, for a specific subject."
    ///
    /// `subject_id`: "the identifier might not be the primary identifier for a
    /// person …, but instead an identifier of an information resource against
    /// which the query can be made, e.g. an EHR identifier" — the SM's own
    /// `TODO` about subject-id resolution. We bind it into the frame's AQL as the
    /// `$subject_id` parameter (PORT NOTE: no external identity-resolution step).
    ///
    /// Only the openEHR frame ([`FrameMethod::Aql`]) is executed (AQL through the
    /// Query service → [`FramePayload::Openehr`]); a FHIR / `HL7v2` frame is a
    /// typed rejection (`NotImplemented`).
    async fn get_frame(
        &self,
        subject_id: String,
        frame_id: String,
    ) -> Result<DataFrameSample, SmError>;
}

/// The current time as an ISO-8601 string (`SAMPLE.retrieve_time`).
fn now_iso() -> String {
    jiff::Timestamp::now().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn name_validity_rejects_whitespace_and_control() {
        // SM master10 §Subject Variable Naming.
        let mut v = SubjectVariable {
            namespace: None,
            name: "systolic_bp".to_owned(),
            type_name: "Quantity".to_owned(),
            currency: None,
            ask_user: None,
            is_manual: false,
            frame_id: "f".to_owned(),
            frame_path: "p".to_owned(),
        };
        assert!(v.name_valid());
        v.name = "systolic bp".to_owned();
        assert!(!v.name_valid(), "whitespace rejected");
        v.name = "sys\u{7}bp".to_owned();
        assert!(!v.name_valid(), "control character rejected");
        v.name = String::new();
        assert!(!v.name_valid(), "empty name rejected");
        v.name = "ok".to_owned();
        v.namespace = Some("my ns".to_owned());
        assert!(!v.name_valid(), "namespace whitespace rejected");
    }

    #[test]
    fn canonical_name_qualifies_with_namespace() {
        // master10 §Subject Variable Naming: `namespace::name`, or bare `name`.
        let global = SubjectVariable {
            namespace: None,
            name: "date_of_birth".to_owned(),
            type_name: "Date".to_owned(),
            currency: None,
            ask_user: None,
            is_manual: false,
            frame_id: "f".to_owned(),
            frame_path: "p".to_owned(),
        };
        assert_eq!(global.canonical_name(), "date_of_birth");
        assert!(global.is_global());

        let qualified = SubjectVariable {
            namespace: Some("cha2ds2vasc".to_owned()),
            ..global.clone()
        };
        assert_eq!(qualified.canonical_name(), "cha2ds2vasc::date_of_birth");
        // is_global follows the post-condition `Result = (namespace = Void)`.
        assert!(!qualified.is_global());
    }

    #[test]
    fn env_binding_round_trips_the_yaml_frame_shapes() {
        // master10 §Specifying a Binding: a mix of QUERY_CALL + API_CALL frames.
        let binding = EnvBinding {
            env_id: "prod".to_owned(),
            description: Some("deployment".to_owned()),
            data_frames: vec![
                DataFrame {
                    id: "openEHR::vital_signs".to_owned(),
                    model_type: "openEHR-EHR".to_owned(),
                    primary_method: FrameMethod::Aql {
                        query_text: "SELECT c FROM EHR e CONTAINS COMPOSITION c".to_owned(),
                    },
                    fallback_method: None,
                },
                DataFrame {
                    id: "OracleMPI::basic_demographics".to_owned(),
                    model_type: "HL7-FHIR_DSTU4_UK".to_owned(),
                    primary_method: FrameMethod::Fhir {
                        system_id: Some("ehr1.nhs.org.uk".to_owned()),
                        call_name: Some("fhir_get".to_owned()),
                        query_text: None,
                    },
                    fallback_method: None,
                },
            ],
        };
        let json = serde_json::to_value(&binding).expect("serialize");
        let back: EnvBinding = serde_json::from_value(json).expect("deserialize");
        assert_eq!(binding, back);
    }
}
