// @generated by openehr-codegen from BMM (`FUNCTION_DEF_EXAMPLE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `FUNCTION_DEF_EXAMPLE` spec class, generated from the vendored BMM
//! meta-model.

#![expect(
    clippy::disallowed_types,
    reason = "adjudicated free-form JSON slots: serde_json::Value is workspace-banned (#1694); a generated carrier exists only where the spec leaves the slot open, and each adjudicated field's NOTE names its citation"
)]
/// Example of an externally defined function of signature:
///
/// ```text
///     func (v: Numeric): Numeric
/// ```
#[doc(alias = "FUNCTION_DEF_EXAMPLE")]
#[derive(Debug, Clone, PartialEq)]
pub struct FunctionDefExample {
    /// The `evaluation_agent` attribute of openEHR `FUNCTION_DEF_EXAMPLE` (the vendored BMM carries no documentation for it).
    pub evaluation_agent: serde_json::Value,
    /// The `identifier` attribute of openEHR `FUNCTION_DEF_EXAMPLE` (the vendored BMM carries no documentation for it).
    pub identifier: String,
}
