// @generated by openehr-codegen from BMM (`OP_DEF_PLUS`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `OP_DEF_PLUS` spec class, generated from the vendored BMM
//! meta-model.

/// The openEHR `OP_DEF_PLUS` class (the vendored BMM carries no documentation for it).
#[doc(alias = "OP_DEF_PLUS")]
#[derive(Debug, Clone, PartialEq)]
pub struct OpDefPlus {
    /// The `name` attribute of openEHR `OP_DEF_PLUS` (the vendored BMM carries no documentation for it).
    pub name: String,
    /// The `symbols` attribute of openEHR `OP_DEF_PLUS` (the vendored BMM carries no documentation for it).
    pub symbols: Option<Vec<String>>,
}
