// @generated by openehr-codegen from BMM (`OP_DEF_AND`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `OP_DEF_AND` spec class, generated from the vendored BMM
//! meta-model.

#![expect(
    clippy::disallowed_types,
    reason = "adjudicated free-form JSON slots: serde_json::Value is workspace-banned (#1694); a generated carrier exists only where the spec leaves the slot open, and each adjudicated field's NOTE names its citation"
)]
/// Illustrative class showing what the normally built-in logical 'and' operator looks like as an external definition.
#[doc(alias = "OP_DEF_AND")]
#[derive(Debug, Clone, PartialEq)]
pub struct OpDefAnd {
    /// The `evaluation_agent` attribute of openEHR `OP_DEF_AND` (the vendored BMM carries no documentation for it).
    pub evaluation_agent: serde_json::Value,
    /// The `identifier` attribute of openEHR `OP_DEF_AND` (the vendored BMM carries no documentation for it).
    pub identifier: String,
    /// The `symbols` attribute of openEHR `OP_DEF_AND` (the vendored BMM carries no documentation for it).
    pub symbols: Option<Vec<String>>,
}
