// @generated by openehr-codegen from BMM (`OPERATOR_DEF_EXTERNAL`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `OPERATOR_DEF_EXTERNAL` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::obsolete_elom::extension::op_def_and::OpDefAnd;
use crate::v1_0::obsolete_elom::extension::op_def_example::OpDefExample;
use crate::v1_0::obsolete_elom::extension::op_def_exists::OpDefExists;

/// Closed subtype set of `OPERATOR_DEF_EXTERNAL`, dispatched on each payload's `_type`.
///
/// Ancestor of concrete operator definition types. Adds an optional execution agent, typically implemented by closures / lambdas/ agents in languages supporting functional programming.
#[doc(alias = "OPERATOR_DEF_EXTERNAL")]
#[derive(Debug, Clone, PartialEq)]
pub enum OperatorDefExternal {
    /// The `OP_DEF_AND` subtype of `OPERATOR_DEF_EXTERNAL`.
    OpDefAnd(OpDefAnd),
    /// The `OP_DEF_EXAMPLE` subtype of `OPERATOR_DEF_EXTERNAL`.
    OpDefExample(OpDefExample),
    /// The `OP_DEF_EXISTS` subtype of `OPERATOR_DEF_EXTERNAL`.
    OpDefExists(OpDefExists),
}
