// @generated by openehr-codegen from BMM (`BMM_ROUTINE_DEFINITION`) — DO NOT EDIT.

use crate::bmm3::core::feature::bmm_external_routine::BmmExternalRoutine;
use crate::bmm3::core::feature::bmm_local_routine::BmmLocalRoutine;

/// Abstract ancestor of routine body meta-types.
/// Closed subtype set of `BMM_ROUTINE_DEFINITION`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum BmmRoutineDefinition {
    BmmExternalRoutine(BmmExternalRoutine),
    BmmLocalRoutine(BmmLocalRoutine),
}
