// @generated by openehr-codegen from BMM (`BMM_CONSTANT`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::bmm3::core::entity::bmm_class::BmmClass;
use crate::bmm3::core::entity::bmm_type::BmmType;
use crate::bmm3::core::feature::bmm_feature_extension::BmmFeatureExtension;
use crate::bmm3::core::feature::bmm_feature_group::BmmFeatureGroup;
use crate::bmm3::core::literal_value::bmm_literal_value::BmmLiteralValue;

/// An immutable, static value-returning element scoped to a class. The `_value_` is the result of the evaluation of the `_generator_`, which may be as simple as a literal value, or may be any expression, including a function call.
#[derive(Debug, Clone, PartialEq)]
pub struct BmmConstant {
    // inherited: BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,

    // inherited: BMM_FORMAL_ELEMENT
    /// Declared or inferred static type of the entity.
    pub r#type: BmmType,
    /// True if this element can be null (Void) at execution time. May be interpreted as optionality in subtypes..
    pub is_nullable: Option<bool>,

    // inherited: BMM_FEATURE
    /// True if this feature was synthesised due to generic substitution in an inherited type, or further constraining of a formal generic parameter.
    pub is_synthesised_generic: Option<bool>,
    /// Extensions to feature-level meta-types.
    pub feature_extensions: Vec<BmmFeatureExtension>,
    /// Group containing this feature.
    pub group: BmmFeatureGroup,
    /// Model element within which an element is declared.
    pub scope: BmmClass,
    /// Literal value of the constant.
    pub generator: BmmLiteralValue,
}
