// @generated by openehr-codegen from BMM (`BMM_FEATURE_EXTENSION`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

/// Abstract parent of feature extensions.
#[derive(Debug, Clone, PartialEq)]
pub struct BmmFeatureExtension {}
