// @generated by openehr-codegen from BMM (`EL_AGENT_CALL`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `EL_AGENT_CALL` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::bmm3::expression::el_function_call::ElFunctionCall;
use crate::v1_1::bmm3::statement::bmm_procedure_call::BmmProcedureCall;

/// Closed subtype set of `EL_AGENT_CALL`, dispatched on each payload's `_type`.
///
/// A call made to a 'closed' agent, i.e. one with no remaining open arguments.
#[doc(alias = "EL_AGENT_CALL")]
#[derive(Debug, Clone, PartialEq)]
pub enum ElAgentCall {
    /// The `BMM_PROCEDURE_CALL` subtype of `EL_AGENT_CALL`.
    BmmProcedureCall(BmmProcedureCall),
    /// The `EL_FUNCTION_CALL` subtype of `EL_AGENT_CALL`.
    ElFunctionCall(ElFunctionCall),
}
