// @generated by openehr-codegen from BMM (`EL_ATTACHED`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `EL_ATTACHED` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::bmm3::expression::el_value_generator::ElValueGenerator;

/// A predicate on any object reference (including function call) that returns True if the reference is attached, i.e. non-Void.
#[doc(alias = "EL_ATTACHED")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElAttached {
    // inherited: EL_PREDICATE
    /// The target instance of this predicate.
    pub operand: ElValueGenerator,
}
