// @generated by openehr-codegen from BMM (`EL_BOOLEAN_EXPRESSION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `EL_BOOLEAN_EXPRESSION` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::bmm3::expression::el_expression::ElExpression;

/// Boolean-returning expression.
#[doc(alias = "EL_BOOLEAN_EXPRESSION")]
#[derive(Debug, Clone, PartialEq)]
pub struct ElBooleanExpression {
    // inherited: EL_CONSTRAINED
    /// The base expression of this constrained form.
    pub base_expression: Box<ElExpression>,
}
