// @generated by openehr-codegen from BMM (`BMM_INCLUDE_SPEC`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Schema inclusion structure.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "BMM_INCLUDE_SPEC")]
pub struct BmmIncludeSpec {
    /// Full identifier of the included schema, e.g. "openehr_primitive_types_1.0.2".
    pub id: String,
}
