// @generated by openehr-codegen from BMM (`TRANSLATION_DETAILS`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `TRANSLATION_DETAILS` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::data_types::text::code_phrase::CodePhrase;

/// Class providing details of a natural language translation.
#[doc(alias = "TRANSLATION_DETAILS")]
#[derive(Debug, Clone, PartialEq)]
pub struct TranslationDetails {
    /// Language of the translation.
    pub language: CodePhrase,
    /// Translator name and other demographic details.
    pub author: std::collections::BTreeMap<String, String>,
    /// Accreditation of translator, usually a national translator's registration or association membership id.
    pub accreditaton: Option<String>,
    /// Any other meta-data.
    pub other_details: Option<std::collections::BTreeMap<String, String>>,
}
