// @generated by openehr-codegen — DO NOT EDIT.

pub mod event;
pub mod history;
pub mod interval_event;
pub mod point_event;

// hand-written modules (ADR-003 spec behaviour), auto-declared:
pub mod event_impl;
pub mod history_impl;
pub mod interval_event_impl;
pub mod point_event_impl;
