// @generated by openehr-codegen from BMM (`BMM_FUNCTION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `BMM_FUNCTION` spec class, generated from the vendored BMM
//! meta-model.

#![expect(
    clippy::disallowed_types,
    reason = "adjudicated free-form JSON slots: serde_json::Value is workspace-banned (#1694); a generated carrier exists only where the spec leaves the slot open, and each adjudicated field's NOTE names its citation"
)]
use crate::v1_0::bmm::core::entity::bmm_class::BmmClass;
use crate::v1_0::bmm::core::entity::bmm_type::BmmType;
use crate::v1_0::bmm::core::feature::bmm_feature_extension::BmmFeatureExtension;
use crate::v1_0::bmm::core::feature::bmm_feature_group::BmmFeatureGroup;
use crate::v1_0::bmm::core::feature::bmm_local::BmmLocal;
use crate::v1_0::bmm::core::feature::bmm_operator::BmmOperator;
use crate::v1_0::bmm::core::feature::bmm_parameter::BmmParameter;
use crate::v1_0::bmm::core::feature::bmm_result::BmmResult;
use crate::v1_0::bmm::core::feature::bmm_routine_body::BmmRoutineBody;
use crate::v1_0::bmm::core::feature::bmm_visibility::BmmVisibility;
use crate::v1_0::bmm::statement::bmm_assertion::BmmAssertion;

/// A formal element with signature of the form: `name ({arg:TArg}*):TResult`. A function is a computed (rather than data) element, generally assumed to be non-state-changing.
#[doc(alias = "BMM_FUNCTION")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmFunction {
    // inherited: BMM_TYPED
    /// Declared or inferred static type of the entity.
    pub r#type: BmmType,

    // inherited: BMM_TYPED_FEATURE
    /// True if this element can be null (Void) at execution time. May be interpreted as optionality in subtypes..
    pub is_nullable: Option<bool>,

    // inherited: BMM_DECLARATION
    /// Name of this model element.
    pub name: String,
    /// Optional documentation of this element, as a keyed list.
    ///
    /// It is strongly recommended to use the following key /type combinations for the relevant purposes:
    ///
    /// * `"purpose": String`
    /// * `"keywords": List<String>`
    /// * `"use": String`
    /// * `"misuse": String`
    /// * `"references": String`
    ///
    /// Other keys and value types may be freely added.
    pub documentation: Option<std::collections::BTreeMap<String, serde_json::Value>>,

    // inherited: BMM_CLASS_FEATURE
    /// Class within which a referenceable element is known.
    pub scope: BmmClass,

    // inherited: BMM_DECLARATION
    /// Optional meta-data of this element, as a keyed list. May be used to extend the meta-model.
    pub extensions: Option<std::collections::BTreeMap<String, serde_json::Value>>,

    // inherited: BMM_CLASS_ENTITY
    /// True if this feature was synthesised due to generic substitution in an inherited type, or further constraining of a formal generic parameter.
    pub is_synthesised_generic: Option<bool>,

    // inherited: BMM_CLASS_FEATURE
    /// Visibility of this item to client entities.
    pub visibility: Option<BmmVisibility>,
    /// Extensions to feature-level meta-types.
    pub feature_extensions: Option<Vec<BmmFeatureExtension>>,
    /// Group containing this feature.
    pub group: BmmFeatureGroup,

    // inherited: BMM_ROUTINE
    /// Formal parameters of the routine.
    pub parameters: Option<Vec<BmmParameter>>,
    /// Local variables of the routine.
    pub locals: Option<Vec<BmmLocal>>,
    /// The `pre_conditions` attribute of openEHR `BMM_ROUTINE` (the vendored BMM carries no documentation for it).
    pub pre_conditions: Option<Vec<BmmAssertion>>,
    /// The `post_conditions` attribute of openEHR `BMM_ROUTINE` (the vendored BMM carries no documentation for it).
    pub post_conditions: Option<Vec<BmmAssertion>>,
    /// Body of a routine, i.e. executable program.
    pub body: Option<Box<BmmRoutineBody>>,
    /// Optional details enabling a function to be represented as an operator in a syntactic representation.
    pub operator_definition: Option<BmmOperator>,
    /// Automatically created Result variable, usable in body and post-condition.
    pub result: Box<BmmResult>,
}
