// @generated by openehr-codegen from BMM (`BMM_FEATURE_GROUP`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `BMM_FEATURE_GROUP` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::feature::bmm_class_feature::BmmClassFeature;
use crate::v1_0::bmm::core::feature::bmm_visibility::BmmVisibility;

/// A logical group of features, with a name and set of properties that applies to the group.
#[doc(alias = "BMM_FEATURE_GROUP")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmFeatureGroup {
    /// Name of this feature group; defaults to 'feature'.
    pub name: String,
    /// Set of properties of this group, represented as name/value pairs. These are understood to apply logically to all of the features contained within the group.
    pub properties: std::collections::BTreeMap<String, String>,
    /// Set of features in this group.
    pub features: Option<Vec<BmmClassFeature>>,
    /// Optional visibility to apply to all features in this group.
    pub visibility: Option<BmmVisibility>,
}
