// @generated by openehr-codegen from BMM (`BMM_FEATURE_EXTENSION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `BMM_FEATURE_EXTENSION` spec class, generated from the vendored BMM
//! meta-model.

/// Abstract parent of feature extensions.
#[doc(alias = "BMM_FEATURE_EXTENSION")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmFeatureExtension {}
