// @generated by openehr-codegen from BMM (`BMM_ASSERTION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `BMM_ASSERTION` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::bmm3::expression::el_boolean_expression::ElBooleanExpression;

/// A statement that asserts the truth of its expression. If the expression evaluates to False the execution generates an exception (depending on run-time settings).
///
/// May be rendered in syntax as `assert condition` or similar.
#[doc(alias = "BMM_ASSERTION")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmAssertion {
    /// Boolean-valued expression of the assertion.
    pub expression: ElBooleanExpression,
    /// Optional tag, typically used to designate design intention of the assertion, e.g. `"Inv_all_members_valid"`.
    pub tag: Option<String>,
}
