// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-License-Identifier: MIT

//! AQL execution + `RESULT_SET` assembly (our own engine).
//!
//! [`execute`] plans-to-SQL ([`super::sql::build`]), runs the one statement on
//! the `sqlx` pool, and assembles a [`QueryResult`] (column metadata + canonical
//! JSON rows) the service renders as an ITS-REST 1.1.0 `RESULT_SET`. Scalar cells
//! are read directly as canonical JSON (`jsonb`); whole-object cells reassemble
//! their node subtree through the codec ([`crate::storage::codec::reassemble`]).

#![expect(
    clippy::disallowed_types,
    reason = "owner-approved 2026-08-03 (#1694 family 5): AQL result rows are arbitrary \
              projections by specification (QUERY 1.1)"
)]

use serde_json::Value;
use sqlx::postgres::PgRow;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use super::error::{AqlError, ExecError};
use super::ir::{Params, QueryIr};
use super::sql::{CellKind, ColumnSpec, SqlCtx};
use crate::ids::VoId;
use crate::storage::node_repo::SubtreeAnchor;

/// One `RESULT_SET` column's metadata (`schemas/query/ResultSetColumn`).
///
/// `RESULT_SET_COLUMN.archetype_id [0..1]` is deliberately absent: the SM
/// `result_set_column.adoc` marks it "check on whether needed or **inside the
/// path**", and the ITS-REST 1.1.0 `ResultSetColumn` examples carry the
/// archetype/node codes inline in `path` (never a separate `archetype_id`), so a
/// distinct field has no pinned semantics or golden to validate against.
#[derive(Debug, Clone)]
pub struct ColumnMeta {
    /// The column name (`AS` alias or `#{index}`).
    pub name: String,
    /// The AQL path expression, if reconstructable.
    pub path: Option<String>,
}

/// The assembled result of an AQL query: the SELECT column metadata and the rows
/// (each a vector of canonical-JSON cells, aligned to `columns`).
#[derive(Debug, Clone)]
pub struct QueryResult {
    /// The SELECT columns, in order.
    pub columns: Vec<ColumnMeta>,
    /// The rows; each is one cell per column.
    pub rows: Vec<Vec<Value>>,
}

/// Plan, execute, and assemble an AQL query.
///
/// `profile` is the ACTIVE `spec_profile`: whole-object cells serve stored
/// version bodies, so they pass the same generation gate every other served
/// body passes (`crate::versioning::profile::gate_result_bodies`) before any
/// subtree is reassembled. Scalar cells serve values, not bodies, and are not
/// gated.
///
/// # Errors
///
/// [`AqlError::Sql`] if the IR cannot be lowered to SQL; [`AqlError::Exec`] if
/// the database rejects the query, a projected version body is outside the
/// active profile's generation set ([`ExecError::Profile`]), or a whole-object
/// cell cannot be reassembled.
pub async fn execute(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
    profile: crate::config::profile::SpecProfile,
) -> Result<QueryResult, AqlError> {
    let prepared = super::sql::build(ir, params, ctx)?;
    // The SQL is generated by our own `sea-query` builder (never client text);
    // `AssertSqlSafe` acknowledges that to the sqlx injection guard.
    // `persistent(false)`: AQL SQL is dynamically generated with unbounded
    // variety, so named prepared statements both pollute the per-connection
    // statement cache and hand PostgreSQL a GENERIC plan after five executions,
    // which collapses the streaming shape. An unnamed statement is
    // custom-planned with the real values on every execution (PostgreSQL docs:
    // PREPARE / plan caching).
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(prepared.sql), prepared.values)
        .persistent(false)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;

    let columns = prepared
        .columns
        .iter()
        .map(|c| ColumnMeta {
            name: c.name.clone(),
            path: c.path.clone(),
        })
        .collect();

    let Scan {
        mut out_rows,
        anchors,
        pending,
    } = scan_rows(&rows, &prepared.columns)?;

    if !anchors.is_empty() {
        crate::versioning::profile::gate_result_bodies(pool, profile, &anchors)
            .await
            .map_err(ExecError::Profile)?;
        let subtrees = crate::storage::node_repo::read_subtrees_canonical(pool, &anchors)
            .await
            .map_err(ExecError::from)?;
        fill_whole_object_cells(&mut out_rows, pending, subtrees);
    }

    Ok(QueryResult {
        columns,
        rows: out_rows,
    })
}

/// The result of scanning the SQL rows: the assembled cells, the subtree
/// anchors to batch-load, and the whole-object cells awaiting them.
struct Scan {
    out_rows: Vec<Vec<Value>>,
    anchors: Vec<SubtreeAnchor>,
    /// The whole-object cells to fill once the batch load resolves, by
    /// `(row, column)` position.
    pending: Vec<(usize, usize, SubtreeAnchor)>,
}

/// Assembles every cell of the result page.
///
/// Scalar cells read their JSON straight off the result row; whole-object
/// cells contribute a subtree anchor that is batch-loaded in ONE round trip
/// after the scan — never one follow-up SELECT per candidate row.
///
/// # Errors
/// [`AqlError::Exec`] if a projected column is missing from the result row.
fn scan_rows(rows: &[PgRow], columns: &[ColumnSpec]) -> Result<Scan, AqlError> {
    let mut out_rows: Vec<Vec<Value>> = Vec::with_capacity(rows.len());
    let mut anchors: Vec<SubtreeAnchor> = Vec::new();
    let mut pending: Vec<(usize, usize, SubtreeAnchor)> = Vec::new();
    for (ri, row) in rows.iter().enumerate() {
        let mut cells = Vec::with_capacity(columns.len());
        for (ci, spec) in columns.iter().enumerate() {
            match spec.kind {
                CellKind::Scalar => {
                    let v: Option<Value> =
                        row.try_get(sql_col(spec, 0)?).map_err(ExecError::from)?;
                    cells.push(v.unwrap_or(Value::Null));
                }
                CellKind::WholeObject => {
                    // A null vo-id locator (an outer-joined absent object) is a
                    // Null cell with nothing to load.
                    if let Some(anchor) = whole_object_anchor(row, spec)? {
                        anchors.push(anchor);
                        pending.push((ri, ci, anchor));
                    }
                    // Placeholder; a genuine value replaces it after the batch,
                    // and an empty subtree (logical delete) correctly stays Null.
                    cells.push(Value::Null);
                }
            }
        }
        out_rows.push(cells);
    }
    Ok(Scan {
        out_rows,
        anchors,
        pending,
    })
}

/// Moves each reassembled document into the cell that projected it.
///
/// A document MOVES into its last pending cell; only a repeated anchor (the
/// same version projected more than once on the page) pays a clone for the
/// earlier cells.
fn fill_whole_object_cells(
    out_rows: &mut [Vec<Value>],
    pending: Vec<(usize, usize, SubtreeAnchor)>,
    mut subtrees: std::collections::HashMap<SubtreeAnchor, Value>,
) {
    let mut remaining: std::collections::HashMap<SubtreeAnchor, usize> =
        std::collections::HashMap::new();
    for (_, _, anchor) in &pending {
        *remaining.entry(*anchor).or_insert(0) += 1;
    }
    for (ri, ci, anchor) in pending {
        let last_use = remaining.get_mut(&anchor).is_none_or(|n| {
            *n -= 1;
            *n == 0
        });
        let value = if last_use {
            subtrees.remove(&anchor)
        } else {
            subtrees.get(&anchor).cloned()
        };
        // `(ri, ci)` was recorded while building `out_rows`, so the cell
        // exists; fetched rather than indexed so a future refactor cannot turn
        // a bookkeeping slip into a panic on a request path.
        if let (Some(value), Some(cell)) =
            (value, out_rows.get_mut(ri).and_then(|row| row.get_mut(ci)))
        {
            *cell = value;
        }
    }
}

/// The distinct EHR ids and template ids an AQL query touches.
///
/// Collected for the ABAC query post-check (no openEHR spec governs ABAC — our
/// own access-control extension), independent of the query's projection.
#[derive(Debug, Clone, Default)]
pub struct QueryScope {
    /// Distinct touched EHR ids (as strings).
    pub ehr_ids: Vec<String>,
    /// Distinct touched template ids.
    pub template_ids: Vec<String>,
}

/// Run the scope-collection query for `ir` and return the distinct EHR-id and
/// template-id sets it touches. Empty when the query has no VO root.
///
/// # Errors
/// [`AqlError::Sql`] if the scope query cannot be lowered; [`AqlError::Exec`] if
/// the database rejects it.
pub async fn collect_scope(
    pool: &PgPool,
    ir: &QueryIr,
    params: &Params,
    ctx: &SqlCtx,
) -> Result<QueryScope, AqlError> {
    let Some(scope) = super::sql::build_scope(ir, params, ctx)? else {
        return Ok(QueryScope::default());
    };
    // `persistent(false)` for the same reason as `execute` above: dynamic
    // SQL, unnamed statement, custom plan per execution.
    let rows = sqlx::query_with(sqlx::AssertSqlSafe(scope.sql), scope.values)
        .persistent(false)
        .fetch_all(pool)
        .await
        .map_err(ExecError::from)?;
    let mut ehr_ids = std::collections::BTreeSet::new();
    let mut template_ids = std::collections::BTreeSet::new();
    for row in &rows {
        // Every bound VO root contributes an (ehr_id, template_id) column pair.
        for (ehr_col, template_col) in &scope.columns {
            if let Ok(Some(e)) = row.try_get::<Option<Uuid>, _>(ehr_col.as_str()) {
                ehr_ids.insert(e.to_string());
            }
            if let Ok(Some(t)) = row.try_get::<Option<String>, _>(template_col.as_str()) {
                template_ids.insert(t);
            }
        }
    }
    Ok(QueryScope {
        ehr_ids: ehr_ids.into_iter().collect(),
        template_ids: template_ids.into_iter().collect(),
    })
}

/// The `index`-th generated SQL alias of a `RESULT_SET` column, as a typed
/// reject rather than a panic when the lowering did not emit it.
///
/// # Errors
/// [`ExecError::MissingColumnAlias`] when `spec.sql_cols` is shorter than the
/// column's [`CellKind`] declares.
fn sql_col(spec: &ColumnSpec, index: usize) -> Result<&str, AqlError> {
    spec.sql_cols.get(index).map(String::as_str).ok_or_else(|| {
        ExecError::MissingColumnAlias {
            column: spec.name.clone(),
            index,
        }
        .into()
    })
}

/// Extract the [`SubtreeAnchor`] for a [`CellKind::WholeObject`] cell from its
/// four locator columns (`vo_id`, `sys_version`, `num`, `num_cap`). Returns
/// `None` when the `vo_id` locator is SQL NULL (an outer-joined absent object) —
/// the cell is then a JSON `null` with no subtree to load.
fn whole_object_anchor(
    row: &PgRow,
    spec: &ColumnSpec,
) -> Result<Option<SubtreeAnchor>, AqlError> {
    let vo_id: Option<VoId> = row.try_get(sql_col(spec, 0)?).map_err(ExecError::from)?;
    let Some(vo_id) = vo_id else {
        return Ok(None);
    };
    let sys_version: i32 = row.try_get(sql_col(spec, 1)?).map_err(ExecError::from)?;
    let num: i32 = row.try_get(sql_col(spec, 2)?).map_err(ExecError::from)?;
    let num_cap: i32 = row.try_get(sql_col(spec, 3)?).map_err(ExecError::from)?;
    Ok(Some(SubtreeAnchor {
        vo_id,
        sys_version,
        num,
        num_cap,
    }))
}
