// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `am24/aom2/rm_overlay` — generated module tree.

pub mod rm_attribute_visibility;
pub mod rm_overlay;
pub mod visibility_type;
