// @generated by openehr-codegen from BMM (`RM_ATTRIBUTE_VISIBILITY`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am24::aom2::rm_overlay::visibility_type::VisibilityType;
use openehr_base::prelude::TerminologyCode;

/// Definition of visibility of an RM attribute within a larger archetype structure.
#[derive(Debug, Clone, PartialEq)]
pub struct RmAttributeVisibility {
    /// Visibility setting of a non-archetyped RM attribute (RM attributes that are constrained or within the archetyped structure are visible by default).
    pub visibility: Option<VisibilityType>,
    /// Optional alias for the attribute referenced by the path.
    pub alias: Option<TerminologyCode>,
}
