// @generated by openehr-codegen from BMM (`LOCATABLE_REF`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `LOCATABLE_REF` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_3::base_types::identification::uid_based_id::UidBasedId;

/// Reference to a `LOCATABLE` instance inside the top-level content structure inside a `VERSION<T>` identified by the `_id_` attribute.
///
/// The `_path_` attribute is applied to the object that `VERSION._data_` points to.
#[doc(alias = "LOCATABLE_REF")]
#[derive(Debug, Clone, PartialEq)]
pub struct LocatableRef {
    // inherited: OBJECT_REF
    /// Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic .
    ///
    /// These names are not yet standardised. Legal values for `_namespace_` are:
    ///
    /// * `"local"`
    /// * `"unknown"`
    /// * a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.
    ///
    /// Note that the first two are just special values of the regex, and will be matched by it.
    pub namespace: String,
    /// Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model.
    ///
    /// The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).
    pub r#type: String,
    /// Globally unique id of an object, regardless of where it is stored.
    pub id: UidBasedId,
    /// The path to an instance, as an absolute path with respect to the object found at `VERSION._data_`. An empty path means that the object referred to by `_id_` is being specified.
    pub path: Option<String>,
}
