// @generated by openehr-codegen from BMM (`TEMPLATE_ID`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `TEMPLATE_ID` spec class, generated from the vendored BMM
//! meta-model.

/// Identifier for templates. Lexical form to be determined.
#[doc(alias = "TEMPLATE_ID")]
// NOTE: the fields stay public deliberately: the release states no constraint over this class's field values, so a validating construction door would check nothing — docs/specs/openehr/BASE/docs/UML/classes/org.openehr.base.base_types.template_id.adoc: “Identifier for templates. Lexical form to be determined.” — the release states no grammar, and §Syntaxes has no `template_id` production, so there is nothing a construction door could check.
#[derive(Debug, Clone, PartialEq)]
pub struct TemplateId {
    // inherited: OBJECT_ID
    /// The value of the id in the form defined below.
    pub value: String,
}
