// @generated by openehr-codegen from BMM (`AUTHORED_RESOURCE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use openehr_derive::OpenEhrType;
use crate::foundation_types::terminology::code_phrase::CodePhrase;
use crate::resource::resource_description::ResourceDescription;
use crate::resource::translation_details::TranslationDetails;

/// Abstract idea of an online resource created by a human author.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "AUTHORED_RESOURCE")]
pub struct AuthoredResource {
    /// Language in which this resource was initially authored. Although there is no language primacy of resources overall, the language of original authoring is required to ensure natural language translations can preserve quality. Language is relevant in both the description and ontology sections.
    pub original_language: CodePhrase,
    /// True if this resource is under any kind of change control (even file copying), in which case revision history is created.
    pub is_controlled: Option<bool>,
    /// List of details for each natural-language translation made of this resource, keyed by language. For each translation listed here, there must be corresponding sections in all language-dependent parts of the resource. The `_original_language_` does not appear in this list.
    pub translations: Option<std::collections::BTreeMap<String, TranslationDetails>>,
    /// Description and lifecycle information of the resource.
    pub description: Option<Box<ResourceDescription>>,
    /// The revision history of the resource. Only required if `_is_controlled_ = True` (avoids large revision histories for informal or private editing situations).
    pub revision_history: Option<serde_json::Value>,
}
