#!/usr/bin/env bash
# SPDX-FileCopyrightText: FerroEHR contributors
# SPDX-License-Identifier: MIT
# Render the public comparison page's content (tracker issue #147) from the
# COMMITTED runner artifacts — the same no-hand-typed-numbers discipline as
# scripts/render/conformance-stats.sh (CI: scripts/checks/conformance-numbers.sh).
#
# Inputs (all committed, regenerated by the CNF runner):
#   docs/conformance/{ferroehr,ehrbase}/{results.json,verdicts.json}
#   docs/conformance/{ferroehr,ehrbase}/stress.json  (when measured)
# Outputs:
#   website/book/generated/comparison-conformance.md
#   website/book/generated/comparison-bench.md
#   website/book/src/perf-assets/perf-stress-compare.svg  (committed,
#     rendered by `cnf-runner stress-compare` when BOTH sides carry a
#     committed stress report; the perf-assets CI drift gate covers it)
set -euo pipefail
cd "$(dirname "$0")/../.."

RS="docs/conformance/ferroehr"
EB="docs/conformance/ehrbase"
OUT="website/book/generated"

command -v jq >/dev/null 2>&1 || { echo "render-comparison: jq is required" >&2; exit 1; }
for f in "$RS/results.json" "$EB/results.json"; do
  [ -f "$f" ] || { echo "render-comparison: missing artifact $f" >&2; exit 1; }
done
mkdir -p "$OUT" website/book/src/comparison-assets

# Unified CNF schema on BOTH sides since the #232 re-base: `outcomes` records
# keyed by case id + optional format.
count() { jq "[(.cases // .outcomes)[] | select(.status == \"$2\")] | length" "$1/results.json"; }

# ── conformance side ─────────────────────────────────────────────────────────
# The CNF results artifacts are clock-free; date = the artifact's commit date
# (falling back to mtime for a not-yet-committed regeneration).
# --follow --diff-filter=AM: a rename of the artifact directory (a lane rename)
# must not restamp a measured run with the rename's date — only a commit that
# ADDED or MODIFIED the record is a run.
run_date() {
  local d
  d=$(git log --follow --diff-filter=AM -1 --format=%cs -- "$1/results.json" 2>/dev/null || true)
  [ -n "$d" ] || d=$(date -r "$1/results.json" +%Y-%m-%d)
  echo "$d"
}
rs_date=$(run_date "$RS")
eb_date=$(run_date "$EB")
eb_version=$(jq -r '.sut.version // .sut.name' "$EB/results.json")
rs_total=$(jq '(.cases // .outcomes) | length' "$RS/results.json")
eb_total=$(jq '(.cases // .outcomes) | length' "$EB/results.json")

# The shared per-case join: both runs execute the SAME committed catalogue,
# keyed by case id + format. (A case one run records N/A — an unclaimed
# option branch or an unrealizable ground on that party's topology — still
# joins; its status shows as not_applicable.)
shared=$(jq -n --slurpfile a "$RS/results.json" --slurpfile b "$EB/results.json" '
  (INDEX($a[0].outcomes[]; "\(.case)|\(.format // "-")")) as $rs
  | [$b[0].outcomes[] | . as $o | ($rs["\(.case)|\(.format // "-")"]) as $mine
     | select($mine != null)
     | {key: "\(.case)|\(.format // "-")", theirs: .status, rs: $mine.status}]')
shared_n=$(echo "$shared" | jq 'length')
srow() { echo "$shared" | jq "[.[] | select(.$1 == \"$2\")] | length"; }

# EHRbase failures grouped by schedule chapter (the case-id prefix), and the
# full per-case list with our outcome on the identical case.
fail_by_cap=$(jq -n --slurpfile b "$EB/results.json" '
  [$b[0].outcomes[] | select(.status=="failed")]
  | group_by(.case | split(".")[0] | split("-")[0])
  | map({cap: (.[0].case | split(".")[0] | split("-")[0]), n: length}) | sort_by(-.n)')
fail_rows=$(jq -rn --slurpfile a "$RS/results.json" --slurpfile b "$EB/results.json" '
  (INDEX($a[0].outcomes[]; "\(.case)|\(.format // "-")")) as $rs
  | [$b[0].outcomes[] | select(.status=="failed")]
  | sort_by(.case)[]
  | "| \(.case) | \(.format // "—") | \((.reason // "") | .[0:90] | gsub("\\|"; "\\\\|")) | \($rs["\(.case)|\(.format // "-")"].status // "—") |"')

# Profile verdict tokens from verdicts.json (pass/fail/not_claimed).
# The verdict pipeline's own in-scope tallies (verdicts.json .coverage) —
# the ONLY numbers the presentation rule lets the comparison headline.
scope() { jq -r ".coverage.${2} // 0" "$1/verdicts.json"; }

pverdict() { jq -r --arg t "$2" '.profiles[] | select(.[0]==$t) | .[1] // "—"' "$1/verdicts.json" | sed -e 's/^$/—/' -e 's/_/ /g'; }
sverdict() { jq -r '.security // "not claimed"' "$1/verdicts.json"; }

{
  cat <<EOF
## Systems under test

| | ferroehr | EHRbase |
|---|---|---|
| Product | $(jq -r '.sut.name' "$RS/results.json") $(jq -r '.sut.version' "$RS/results.json") | $(jq -r '.sut.name' "$EB/results.json") $(jq -r '.sut.version' "$EB/results.json") |
| Run date | ${rs_date} | ${eb_date} |
| Party statement | committed with the runner (declares ITS-REST pin, signing, terminology posture) | committed with the runner |
| Stack | the project's own compose stack, built from the current sources | a dedicated compose stack of the official EHRbase images |

## Methodology

Both systems execute the **same committed CNF 2.0 catalogue** ($(jq '(.cases // .outcomes) | length' "$RS/results.json") case-by-format
executions) through the same reference runner (\`tools/cnf-runner\`), each on
fresh volumes with its own committed party set: the ixit names the reachable
instances (EHRbase declares no readonly principal), and the statement (the
ICS) declares the claimed capabilities, spec versions, and ambiguity-register
options — ISO/IEC 9646-style test selection excuses undeclared option
branches, unclaimed capabilities, and release-dated behaviour outside the
declared versions as N/A with a citation, never as silent skips. Verdicts are
pure functions of (statement, results, catalogue, capability matrix).

**The declared-version delta matters and is stated, not hidden:** ferroehr
declares ITS-REST **$(jq -r '.spec_versions.its_rest // "—"' tools/cnf-runner/party/ferroehr/statement.json)**
while EHRbase declares ITS-REST
**$(jq -r '.spec_versions.its_rest // "—"' tools/cnf-runner/party/ehrbase/statement.json)** —
the catalogue realizes 1.1.0, so every Release-1.1.0-dated behaviour (the
Demographic API, ITEM_TAGs, Simplified Formats on the wire, the admin EHR
delete, the weak-\`ETag\`/\`Location\` header forms, …) is cited N/A for the
1.0.3 declaration rather than driven against a release EHRbase never
claimed. The verdict-bearing comparison below is therefore each party's
**in-scope subset**, never the raw record.

## Profile verdicts

| Profile | ferroehr | EHRbase |
|---|---|---|
| CORE | $(pverdict "$RS" CORE) | $(pverdict "$EB" CORE) |
| STANDARD | $(pverdict "$RS" STANDARD) | $(pverdict "$EB" STANDARD) |
| OPTIONS | $(pverdict "$RS" OPTIONS) | $(pverdict "$EB" OPTIONS) |
| SEC-BASIC | $(sverdict "$RS") | $(sverdict "$EB") |

## In-scope outcomes

Runs compared: **ferroehr** (run of ${rs_date}) vs **EHRbase
${eb_version}** (run of ${eb_date}) — the SAME catalogue through the same
runner, each with its own committed party statement. Per the presentation
rule, the headline is each party's VERDICT SCOPE (the cases its own
declarations select), never the raw record: a raw count would book
release-dated and unclaimed surfaces against a party that never claimed
them.

| | verdict scope (selected) | driven | in-scope passed | in-scope failed | in-scope inconclusive |
|---|---|---|---|---|---|
| **ferroehr** | $(scope "$RS" selected) | $(scope "$RS" driven) | $(scope "$RS" passed) | $(scope "$RS" failed) | $(scope "$RS" inconclusive) |
| **EHRbase** | $(scope "$EB" selected) | $(scope "$EB" driven) | $(scope "$EB" passed) | $(scope "$EB" failed) | $(scope "$EB" inconclusive) |

An **inconclusive** row's wire answered outside the operation's bound outcome
map, or its required ground could not be established (e.g. a refused
provisioning exchange) — never counted as a failure of the behaviour under
test. Every not-run row in the full committed record
(\`docs/conformance/<sut>/results.json\`) carries a machine-readable
citation: an undeclared option branch, an unclaimed capability, a
release-dated behaviour outside the declared spec versions, or a ground the
party's topology cannot establish.

## Capability-by-capability

Evidence tokens from each party's computed verdicts: **passed** (every
gating case green), **failed** (at least one gating case red),
**inconclusive** (a gating case neither passed nor failed cleanly),
**not_evidenced** (claimed, but no gating case produced a verdict — there
is no excused state: a required capability without passing evidence fails
its tier, whichever party claims it), or **not claimed** (absent from that
party's ICS).

| Capability | ferroehr | EHRbase |
|---|---|---|
$(jq -rn --slurpfile a "$RS/verdicts.json" --slurpfile b "$EB/verdicts.json" '
  (INDEX($a[0].capabilities[]; .[0])) as $rs
  | (INDEX($b[0].capabilities[]; .[0])) as $eb
  | ([$a[0].capabilities[][0], $b[0].capabilities[][0]] | unique)[]
  | "| \(.) | \($rs[.][1] // "not claimed") | \($eb[.][1] // "not claimed") |"')

## Failures — both directions

### ferroehr failures (with the EHRbase outcome on the identical case)

| Case | Format | Failure | EHRbase outcome |
|---|---|---|---|
$(jq -rn --slurpfile a "$RS/results.json" --slurpfile b "$EB/results.json" '
  (INDEX($b[0].outcomes[]; "\(.case)|\(.format // "-")")) as $eb
  | [$a[0].outcomes[] | select(.status=="failed")]
  | sort_by(.case)[]
  | "| \(.case) | \(.format // "—") | \((.reason // "") | .[0:90] | gsub("\\|"; "\\\\|")) | \($eb["\(.case)|\(.format // "-")"].status // "—") |"' ; [ "$(count "$RS" failed)" = "0" ] && echo '| — | — | *none — zero failing cases* | — |' )

### EHRbase failures by schedule chapter

| Chapter | failed cases |
|---|---|
$(echo "$fail_by_cap" | jq -r '.[] | "| \(.cap) | \(.n) |"')

<details><summary>Every EHRbase-failed case, with the ferroehr outcome on the identical case</summary>

| Case | Format | EHRbase failure | ferroehr outcome |
|---|---|---|---|
${fail_rows}

</details>
EOF
} > "$OUT/comparison-conformance.md"

# The repo-committed comparison record: the same derivation, with the honesty
# preamble, at docs/conformance/COMPARISON.md (regenerated per run -- #232).
{
  cat <<'PREAMBLE'
# openEHR CDR conformance comparison (generated)

> **Measured, not asserted.** Every cell below is derived from the two
> committed `results.json`/`verdicts.json` sets produced by the CNF 2.0
> reference runner (`tools/cnf-runner`) executing the SAME committed
> catalogue against each system, each with its own committed party statement
> (`tools/cnf-runner/party/<sut>/`). Nothing here is hand-entered
> (`scripts/render/comparison.sh`; CI: `scripts/checks/conformance-numbers.sh`).
>
> - A capability a party's statement does not claim reads **not claimed** and
>   never gates its verdicts; a ground unrealizable on a party's topology or
>   technology profile reads **N/A with a machine citation**, never fail.
> - This comparison makes **no certification claim on behalf of any other
>   vendor** -- each column is computed from that SUT's own run.
> - Where the comparison SUT out-performs ferroehr, its cell reads pass
>   while ours reads fail -- stated plainly, not hidden.

PREAMBLE
  cat "$OUT/comparison-conformance.md"

  # EHRbase measured-window error-class adjudication: the table derives from
  # the committed EHRbase measured record; the verdicts are the recorded
  # three-way adjudication (spec-required vs driver-sent vs EHRbase-observed,
  # .claude/rules/cnf-triage.md), live-reproduced against a composed EHRbase
  # on 2026-07-24 (tracker record: issue #266).
  if jq -e '.measurements[0].operations[]? | select(.errors > 0)' "$EB/results.json" >/dev/null 2>&1; then
    cat <<'ADJHEAD'

## EHRbase measured-window error classes (adjudicated)

The EHRbase measured record is honest as measured — errors are observations.
Every class below was reproduced against a freshly composed EHRbase and
adjudicated three-way against the RELEASED ITS-REST docs text before any
narrative: the driver payloads are spec-correct (the identical exchanges
succeed 0-error against ferroehr in the committed record), and each class
attributes to the EHRbase implementation. No expectation was bent either way.

| Operation | errors/requests (measured window) |
|---|---|
ADJHEAD
    jq -r '.measurements[0].operations[] | select(.errors > 0) | "| `\(.operation)` | \(.errors)/\(.requests) |"' "$EB/results.json"
    cat <<'ADJ'

- **`composition_update` + `ehr_status_update` (wire 400, deterministic)** —
  one shared root cause: EHRbase rejects the RFC-9110-quoted `If-Match`
  entity-tag form with `400 "UUID string too large"`. The released docs text
  itself mandates the quoted form (ITS-REST overview `Requests_and_responses.md`
  §"If-Match and accidental overwrites": `If-Match: "8849182c-…::openEHRSys.example.com::2"`),
  and EHRbase 400s even its own returned `ETag` echoed back verbatim; it
  succeeds only on the non-standard unquoted form. EHRbase non-conformance;
  the record stands.
- **`tags_put` + `tags_read` (wire 404, deterministic)** — the item-tag paths
  (`/ehr/{ehr_id}/tags`, `/ehr/{ehr_id}/composition/{uid}/tags`, …) are members
  of the STABLE EHR API in released ITS-REST 1.1.0 (RM grounding:
  `RM/docs/common/master07-tags.adoc`); EHRbase serves no such routes
  ("No resource found at path"). A released-STABLE surface absent from EHRbase is
  non-conformance, not a citable N/A; the record stands.
- **`template_get` (partial)** — the endpoint is fully functional when
  reproduced (200 for JSON and XML); the small error share sits in a load
  window whose `ward_query` p99 was ~10.9 s. Load-window transient, no defect
  on either side; honest error observation.
ADJ
  fi
} > docs/conformance/COMPARISON.md

# ── stress side (the CNF step-load instrument) ──
RS_STRESS="$RS/stress.json"
EB_STRESS="$EB/stress.json"

# Derivations from a committed stress report. The knee step is the stable
# step at the maximum sustainable rate; its worst per-operation p99 and its
# sampled resource peaks summarize the knee honestly.
mst() { jq -r '.max_sustainable_throughput_per_s | round' "$1"; }
# Every knee-step derivation tolerates a ZERO knee (no stable step — the
# measured "cannot sustain the workload" case renders as an em dash).
knee_p99() { jq -r '.max_sustainable_throughput_per_s as $m | [.steps[] | select(.rate == $m and .stable) | .operations[].latency_ms_p99] | if length == 0 then "—" else (max | round | tostring) end' "$1"; }
knee_res() { # $1 file, $2 role, $3 field-expression over samples
  jq -r --arg role "$2" '.max_sustainable_throughput_per_s as $m
    | [.steps[] | select(.rate == $m and .stable) | .resources.containers[]? | select(.role == $role) | .samples[]'"$3"'] 
    | if length == 0 then "—" else (max | round | tostring) end' "$1"
}
corpus_of() { jq -r '.corpus' "$1"; }

{
  if [ -f "$RS_STRESS" ] && [ -f "$EB_STRESS" ]; then
    cargo run -q -p cnf-runner -- stress-compare \
      --left "$RS_STRESS" --left-label "ferroehr" \
      --right "$EB_STRESS" --right-label "EHRbase" \
      --out website/book/src/perf-assets/perf-stress-compare.svg >&2
    cat <<EOF
Both systems run the **same committed step-load stress instrument**
(\`cnf-runner stress\`) on their own freshly seeded **$(corpus_of "$RS_STRESS")**
corpus: the geometric ladder climbs until the system leaves the envelope
(p99 over the budget or errors past tolerance), then bisects to the
**maximum sustainable throughput**. Every number derives from the two
committed \`stress.json\` reports; each load step embeds re-checkable
histograms and, where sampled, per-container resource telemetry.

| | max sustainable throughput | worst p99 at the knee | DB peak CPU at the knee | SUT peak RSS at the knee |
|---|---|---|---|---|
| **ferroehr** | $(mst "$RS_STRESS") req/s | $(knee_p99 "$RS_STRESS") ms | $(knee_res "$RS_STRESS" db ".cpu_pct") % | $(knee_res "$RS_STRESS" sut ".rss_bytes / 1000000") MB |
| **EHRbase** | $(mst "$EB_STRESS") req/s | $(knee_p99 "$EB_STRESS") ms | $(knee_res "$EB_STRESS" db ".cpu_pct") % | $(knee_res "$EB_STRESS" sut ".rss_bytes / 1000000") MB |

![Both systems' latency-throughput curves](perf-assets/perf-stress-compare.svg)

A stress report is exploration evidence: it earns no conformance class
(classes are earned exclusively by the hour-long measured class runs) and
carries no class vocabulary — the chart shows where each system breaks.
EOF
  elif [ -f "$RS_STRESS" ]; then
    cat <<EOF
The step-load stress instrument (\`cnf-runner stress\`) has a committed
report for **ferroehr** — the maximum sustainable throughput of
$(mst "$RS_STRESS") req/s on the $(corpus_of "$RS_STRESS") corpus, with the
latency-throughput curve below. **EHRbase is not measured**:
the first attempt was refused at workload provisioning (the stored-query
registration rejects a spec-valid qualified name — a conformance finding
recorded on the project tracker); the instrument is never adjusted to
accommodate, and this page publishes both directions the moment EHRbase
can host the workload — never a one-sided claim.

![The ferroehr latency-throughput curve](perf-assets/perf-stress-curve.svg)
EOF
  else
    cat <<'EOF'
No committed stress report exists yet for either system; the comparison
publishes only measured evidence.
EOF
  fi
} > "$OUT/comparison-bench.md"

echo "render-comparison: wrote $OUT/comparison-{conformance,bench}.md"
