#!/usr/bin/env bash
# SPDX-FileCopyrightText: Ruben Talstra
# SPDX-License-Identifier: BUSL-1.1
# Render the two EHDS pages FROM website/book/ehds.yaml.
#
# A readiness page typed by hand is wrong the first time a requirement's
# status changes, and wrong in the direction that matters: a stale "shipped"
# beside a requirement nothing implements is a false compliance claim on a
# public site. So the status lives in one committed file, both pages are a
# pure function of it, and the `ehds-pages` CI job re-renders and diffs.
#
# DETERMINISM. No clock, no HEAD commit, no network: two runs over an
# unchanged YAML produce identical bytes. The date a reader sees is the
# `regulation.read_on` field, which is when a human last read the regulation
# — a fact about the reading, not about the run.
#
# The legal text is NEVER restated as if it were binding. The YAML's
# `summary` fields are this project's paraphrase, the pages say so, and every
# page links the published regulation as the authority.
#
# Usage:
#   scripts/render/ehds-pages.sh            write both pages
#   scripts/render/ehds-pages.sh --check    fail when a committed page is stale
set -euo pipefail
cd "$(dirname "$0")/../.."

SRC="website/book/ehds.yaml"
READINESS="website/book/src/compliance/ehds-readiness.md"
TECHDOC="website/book/src/compliance/technical-documentation.md"
# The coverage matrix is injected into a HAND-WRITTEN page between markers,
# rather than owning a page of its own: the FHIR chapter is the place a reader
# already asks this question, and only the table is generated.
FHIR_PAGE="website/book/src/beyond-core/fhir.md"
FHIR_BEGIN="<!-- BEGIN generated: ehds-priority-categories -->"
FHIR_END="<!-- END generated: ehds-priority-categories -->"
SCRIPT="scripts/render/ehds-pages.sh"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

die() { printf 'ehds-pages: %s\n' "$1" >&2; exit 1; }

command -v yq >/dev/null || die "yq is not on PATH (mikefarah/yq v4)"
command -v jq >/dev/null || die "jq is not on PATH"
[[ -f "$SRC" ]] || die "$SRC does not exist"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

yq -o=json '.' "$SRC" > "$WORK/ehds.json" || die "$SRC is not valid YAML"

# Every status in the file must be one the vocabulary defines, or a typo
# becomes a silent blank cell on a compliance page.
bad="$(jq -r '
  [ (.requirements[].items[] | .status),
    (.components[] | .status) ]
  | map(select(. as $s | ["shipped","partial","planned","open"] | index($s) | not))
  | unique | join(", ")' "$WORK/ehds.json")"
[[ -z "$bad" ]] || die "unknown status value(s): $bad (expected shipped, partial, planned or open)"
bad="$(jq -r '
  [ .technical_documentation[].points[].source ]
  | map(select(. as $s | ["shipped","partial","open"] | index($s) | not))
  | unique | join(", ")' "$WORK/ehds.json")"
[[ -z "$bad" ]] || die "unknown source value(s): $bad (expected shipped, partial or open)"

reg_title="$(jq -r '.regulation.title' "$WORK/ehds.json")"
reg_url="$(jq -r '.regulation.url' "$WORK/ehds.json")"
reg_journal="$(jq -r '.regulation.journal' "$WORK/ehds.json")"
read_on="$(jq -r '.regulation.read_on' "$WORK/ehds.json")"

render_readiness() {
  cat <<HEADER
<!-- Generated by $SCRIPT from website/book/ehds.yaml. Do not edit by hand:
     the CI job re-renders and diffs, so an edit here is reverted with a red
     build. Change the YAML. -->

# EHDS readiness

The European Health Data Space regulation puts obligations on EHR systems in
its Chapter III: an EHR system must include two harmonised software
components, meet the essential requirements of Annex II, and carry technical
documentation and an EU declaration of conformity before it is placed on the
market or put into service.

This page states, requirement by requirement, what FerroEHR provides today.
It exists so an evaluator can see the real position rather than infer one,
and so the project has a checklist rather than an intention.

> [!WARNING]
> **No conformity assessment has been carried out.** No technical
> documentation has been drawn up under Article 37, no EU declaration of
> conformity exists under Article 39, and FerroEHR is not registered under
> Article 49. A status of "Shipped" below means the software provides the
> capability — it is not a claim of conformity, and nothing on this page is
> one.

## The regulation, and how to check this page against it

[$reg_title]($reg_url) — $reg_journal.

Every requirement identifier, heading and date on this page was read from
that published text on **$read_on**. The wording in the "Requirement" column
is this project's own paraphrase for navigation; the regulation is the
authority and its text governs. Where the two differ, the regulation is
right and this page is a defect worth reporting.

## When it applies

HEADER

  jq -r '.dates[] | "- **\(.when)** — \(.what)"' "$WORK/ehds.json"

  cat <<'COMPONENTS'

The last of those matters most here: a deployment that a health institution
runs for itself, or that is offered as a service, is *put into service* under
Article 26(2) rather than placed on the market.

## The two harmonised software components

Article 25(1) requires an EHR system to include both.

| Component | Status | Where it stands |
|---|---|---|
COMPONENTS

  jq -r '
    def badge: {shipped:"Shipped", partial:"Partial", planned:"Planned", open:"Open question"}[.];
    def issue_links: if (.issues // []) | length == 0 then "" else
      (" (" + ([.issues[] | "[#\(.)](https://github.com/rubentalstra/FerroEHR/issues/\(.))"] | join(", ")) + ")") end;
    .components[]
    | "| \(.name) | \(.status | badge)\(. | issue_links) | \(.note | gsub("\n"; " ")) |"
  ' "$WORK/ehds.json"

  cat <<'ANNEX2'

## Annex II — the essential requirements

The identifiers are the Annex's own. "Evidence" links what a reader can check
for themselves; "Gap" says what is missing when a row is not complete.

ANNEX2

  jq -r '
    def badge: {shipped:"Shipped", partial:"Partial", planned:"Planned", open:"Open question"}[.];
    def issue_links: if (.issues // []) | length == 0 then "" else
      ([.issues[] | "[#\(.)](https://github.com/rubentalstra/FerroEHR/issues/\(.))"] | join(", ")) end;
    def evidence: if (.evidence // []) | length == 0 then "—" else
      ([.evidence[] | "[\(.text)](\(.href))"] | join("; ")) end;
    def detail:
      [ (if .gap then "**Gap:** " + (.gap | gsub("\n"; " ")) else empty end),
        (if .question then "**Question:** " + (.question | gsub("\n"; " ")) else empty end),
        (if ((.issues // []) | length) > 0 then "Tracked in " + (. | issue_links) else empty end) ]
      | if length == 0 then "—" else join(" ") end;
    .requirements[]
    | ("### \(.group). \(.heading)\n",
       "| # | Requirement (our paraphrase) | Status | Evidence | Notes |",
       "|---|---|---|---|---|",
       (.items[] | "| \(.id) | \(.summary | gsub("\n"; " ")) | \(.status | badge) | \(. | evidence) | \(. | detail) |"),
       "")
  ' "$WORK/ehds.json"

  cat <<'QUESTIONS'
## Open questions

These decide whether Chapter III applies to a given deployment at all, and to
whom. They are questions this project has not answered, stated as questions.

QUESTIONS

  jq -r '
    def issue_links: if (.issues // []) | length == 0 then "" else
      (" Tracked in " + ([.issues[] | "[#\(.)](https://github.com/rubentalstra/FerroEHR/issues/\(.))"] | join(", ")) + ".") end;
    .open_questions[] | "- \(.question | gsub("\n"; " "))\(. | issue_links)"
  ' "$WORK/ehds.json"

  cat <<'FOOTER'

## Related

- [Technical documentation readiness](technical-documentation.md) — the Annex
  III elements, and what exists for each.
- [Shared responsibility](shared-responsibility.md) — which duties the
  software can carry and which belong to the deployment.
- [Control matrix](control-matrix.md) — the legal controls the tracker
  declares, generated from the tracker.
FOOTER
}

render_techdoc() {
  cat <<HEADER
<!-- Generated by $SCRIPT from website/book/ehds.yaml. Do not edit by hand:
     the CI job re-renders and diffs, so an edit here is reverted with a red
     build. Change the YAML. -->

# Technical documentation readiness

Article 37 of the EHDS regulation requires a manufacturer to draw up technical
documentation before an EHR system is placed on the market or put into
service, and to keep it up to date. Article 37(2) says it must contain at
least the elements of Annex III.

**This page is not that documentation.** It is a map of what FerroEHR can
already supply for each element and what does not exist, so the gap is
visible rather than discovered when someone needs the file.

> [!WARNING]
> No technical documentation has been drawn up, and no EU declaration of
> conformity exists. A "Shipped" row below means the material an element asks
> for is published and can be cited — not that the element has been written.

[$reg_title]($reg_url) — $reg_journal. Read on **$read_on**; the regulation
governs and the summaries here are this project's paraphrase.

## Annex III, element by element

HEADER

  jq -r '
    def badge: {shipped:"Available", partial:"Partial", open:"Missing"}[.];
    def link: if .href then "[what exists](\(.href))" else "—" end;
    def note: if .note then (.note | gsub("\n"; " ")) else "—" end;
    .technical_documentation[]
    | ("### \(.id). \(.heading)\n",
       "| # | Element | State | Material | Notes |",
       "|---|---|---|---|---|",
       (.points[] | "| \(.id) | \(.summary | gsub("\n"; " ")) | \(.source | badge) | \(. | link) | \(. | note) |"),
       "")
  ' "$WORK/ehds.json"

  cat <<'REST'
## Test evidence

Element 4 asks for the results of the verification and validation tests. What
exists is the openEHR conformance record: an independent instrument's runs
against a composed deployment, with the results, verdicts and the statement
committed under `docs/conformance/` and published on the
[conformance pages](../conformance.md).

Read what that record does and does not say. It demonstrates conformity to
the **openEHR** specifications. Conformity to Annex II is a different claim
against a different yardstick, and the European digital testing environment
of Article 40 — whose results Article 37(2) also requires a reference to —
does not exist yet.

## Risk analysis

Annex III does not name a risk analysis as a separate element, but element 1
asks for a description of the system architecture and element 2 for the
system in place to evaluate performance. The material FerroEHR publishes for
both is the [architecture](../concepts/architecture.md) chapter and the
[security](../security.md) chapter, with the pseudonymisation boundary
and its data flows documented as they land.

## Declaration of conformity

Article 39 requires an EU declaration of conformity stating that the
essential requirements of Annex II are met, and Annex IV sets out what it
contains. **No declaration exists**, and none can be drawn up yet: the common
specifications of Article 36 have not been adopted, so there is nothing to
declare conformity against, and the manufacturer of a given deployment has
not been identified — see the open questions on the
[readiness page](ehds-readiness.md).

When those two are settled, the declaration is drawn up by the manufacturer
of the deployment, not by this project on their behalf.

## Related

- [EHDS readiness](ehds-readiness.md) — status per Annex II requirement.
- [Shared responsibility](shared-responsibility.md) — which duties belong to
  the deployment.
REST
}

render_categories() {
  cat <<'INTRO'
The six priority categories of personal electronic health data are Annex I of
the EHDS regulation, and Annex II 2.1 to 2.3 require an EHR system to provide
and receive them in the European electronic health record exchange format.
That format is set by implementing acts under Article 36 which have not been
adopted, so this table is not a conformance claim against it. What it says is
narrower and checkable: which category has a committed template whose example
composition round-trips through this façade today.

| Annex I | Category | Committed template | A profile mapping would target | Transform proven |
|---|---|---|---|---|
INTRO

  jq -r '
    def state: {template:"Yes", "no-template":"**No committed template**"}[.];
    .priority_categories[]
    | "| \(.id) | \(.name) | \(if .template == "" then "—" else "`corpus/templates/ckm/\(.template).opt`" end) | \(.fhir) | \(.state | state) |"
  ' "$WORK/ehds.json"

  cat <<'OUTRO'

"Transform proven" means exactly what the test asserts, and no more
(`app/ferroehr/tests/it/fhir_priority_categories.rs`): the category's
committed operational template builds a Web Template, its committed example
composition flattens against that template to a non-empty map, and a mapping
entry over a leaf taken from that map drives the reverse transform to a FHIR
resource carrying the composition's own value. The leaf is derived from the
map rather than written into the test, so a corpus refresh moves it and the
case still holds.

Three things it deliberately does **not** establish, each of which a reader
could otherwise assume:

- **No profile mapping ships.** The rightmost column says what a mapping for
  that category *would* target, not what exists. The test maps its leaf onto
  `Observation.note.text`, a free-text element: it proves the machinery
  carries real clinical content, not that an IPS-shaped `Bundle` or a
  `MedicationRequest` has been authored and reviewed. Mappings are data a
  deployment registers, as the section above describes.
- **It exercises the transform, not the endpoint.** The test calls the
  reverse transform directly, so routing, authorization and the stored-mapping
  lookup are covered by other tests rather than by this table.
- **It is not conformance to the exchange format**, which does not exist yet.

The connector this table measures is planned to leave: FerroBRIDGE
(<https://github.com/rubentalstra/FerroBRIDGE>) is the FHIRconnect and OMOP
bridge, and [#3080](https://github.com/rubentalstra/FerroEHR/issues/3080)
retires the in-tree connector once it ships. The EHDS readiness question does
NOT leave with it — it is asked of the EHR system — so this table moves to the
compliance chapter at that point rather than being deleted with the page it
currently sits on.

Two of the example compositions this rests on — the patient summary and the
imaging report — were patched by hand rather than regenerated against a
running server, which their pack's provenance records and
[#1724](https://github.com/rubentalstra/FerroEHR/issues/1724) tracks. They are
real CKM templates either way; the caveat belongs beside a claim that leans on
them.
OUTRO
}

emit() {
  local target="$1" body="$2"
  if [[ "$CHECK" -eq 1 ]]; then
    [[ -f "$target" ]] || die "$target does not exist — run $SCRIPT"
    if ! diff -u "$target" "$body" > "$WORK/diff"; then
      cat "$WORK/diff" >&2
      die "$target is stale against $SRC — run $SCRIPT and commit the result"
    fi
  else
    mkdir -p "$(dirname "$target")"
    cp "$body" "$target"
  fi
}

render_readiness > "$WORK/readiness.md"
render_techdoc  > "$WORK/techdoc.md"
emit "$READINESS" "$WORK/readiness.md"
emit "$TECHDOC"   "$WORK/techdoc.md"

# The FHIR chapter keeps its hand-written prose; only the region between the
# markers is ours. A missing marker is an error rather than a silent skip.
grep -qF "$FHIR_BEGIN" "$FHIR_PAGE" || die "$FHIR_PAGE has no $FHIR_BEGIN marker"
grep -qF "$FHIR_END" "$FHIR_PAGE" || die "$FHIR_PAGE has no $FHIR_END marker"
{
  sed -n "1,/$(printf '%s' "$FHIR_BEGIN" | sed 's/[][\/.*^$]/\\&/g')/p" "$FHIR_PAGE"
  echo
  render_categories
  echo
  sed -n "/$(printf '%s' "$FHIR_END" | sed 's/[][\/.*^$]/\\&/g')/,\$p" "$FHIR_PAGE"
} > "$WORK/fhir.md"
emit "$FHIR_PAGE" "$WORK/fhir.md"

count="$(jq '[.requirements[].items[]] | length' "$WORK/ehds.json")"
if [[ "$CHECK" -eq 1 ]]; then
  echo "ehds-pages: both pages match $SRC ($count Annex II requirements)"
else
  echo "ehds-pages: wrote $READINESS and $TECHDOC ($count Annex II requirements)"
fi
