// @generated by openehr-codegen from BMM (`AUTHORED_RESOURCE`) — DO NOT EDIT.

//! The openEHR `AUTHORED_RESOURCE` spec class, generated from the vendored BMM
//! meta-model.

use crate::am14::aom14::archetype::archetype::Archetype;

/// Closed subtype set of `AUTHORED_RESOURCE`, dispatched on each payload's `_type`.
///
/// Abstract idea of an online resource created by a human author.
#[doc(alias = "AUTHORED_RESOURCE")]
#[derive(Debug, Clone, PartialEq)]
pub enum AuthoredResource {
    /// The `ARCHETYPE` subtype of `AUTHORED_RESOURCE`.
    Archetype(Box<Archetype>),
}
