// @generated by openehr-codegen from BMM (`C_ORDERED`) — DO NOT EDIT.

use crate::am24::aom2::constraint_model::primitive::c_date::CDate;
use crate::am24::aom2::constraint_model::primitive::c_date_time::CDateTime;
use crate::am24::aom2::constraint_model::primitive::c_duration::CDuration;
use crate::am24::aom2::constraint_model::primitive::c_integer::CInteger;
use crate::am24::aom2::constraint_model::primitive::c_real::CReal;
use crate::am24::aom2::constraint_model::primitive::c_time::CTime;

/// Abstract parent of primitive constrainer classes based on `Ordered` base types, i.e. types like `Integer`, `Real`, and the Date/Time types. The model constraint is a List of Intervals, which may include point Intervals, and acts as a efficient and formally tractable representation of any number of point values and/or contiguous intervals of an ordered value domain.
///
/// In its simplest form, the constraint accessor returns just a single point `Interval<T>` object, representing a single value.
///
/// The next simplest form is a single proper `Interval <T>` (i.e. normal two-sided or half-open interval). The most complex form is a list of any combination of point and proper intervals.
/// Closed subtype set of `C_ORDERED`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum COrdered {
    CDate(CDate),
    CDateTime(CDateTime),
    CDuration(CDuration),
    CInteger(CInteger),
    CReal(CReal),
    CTime(CTime),
}
