// @generated by openehr-codegen from BMM (`BMM_INCLUDE_SPEC`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `BMM_INCLUDE_SPEC` spec class, generated from the vendored BMM
//! meta-model.

/// Schema inclusion structure.
#[doc(alias = "BMM_INCLUDE_SPEC")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmIncludeSpec {
    /// Full identifier of the included schema, e.g. `"openehr_primitive_types_1.0.2"`.
    pub id: String,
}
