// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `terminology` — generated module tree.

pub mod code;
pub mod code_set;
pub mod terminology;
pub mod terminology_concept;
pub mod terminology_group;
pub mod terminology_status;
