// @generated by openehr-codegen from BMM (`Iso8601_date_time`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `Iso8601_date_time` spec class, generated from the vendored BMM
//! meta-model.

/// Represents an ISO 8601 date/time, including partial and extended forms. Value may be:
///
/// * `YYYY-MM-DDThh:mm:ss[(,|.)sss][Z | ±hh[:mm]]` (extended, preferred) or
/// * `YYYYMMDDThhmmss[(,|.)sss][Z | ±hh[mm]]` (compact)
/// * or a partial variant.
///
/// See `_valid_iso8601_date_time()_` for validity.
///
/// Note that this class includes 2 deviations from ISO 8601:2004:
///
/// * for partial date/times, any part of the date/time up to the month may be missing, not just seconds and minutes as in the standard;
/// * the time `24:00:00` is not allowed, since it would mean the date was really on the next day.
#[doc(alias = "Iso8601_date_time")]
#[derive(Debug, Clone, PartialEq)]
pub struct Iso8601DateTime {
    // inherited: Iso8601_type
    /// Representation of all descendants is a single String.
    pub value: String,
}
