// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v1_3/foundation_types/time` — generated module tree.

pub mod iso8601_date;
pub mod iso8601_date_time;
pub mod iso8601_duration;
pub mod iso8601_time;
pub mod iso8601_timezone;
pub mod iso8601_type;

// hand-written modules (spec behaviour), auto-declared:
pub mod iso8601_date_impl;
pub mod iso8601_date_time_impl;
pub mod iso8601_duration_impl;
pub mod iso8601_parse;
pub mod iso8601_time_impl;
pub mod iso8601_timezone_impl;
pub mod iso8601_type_impl;
pub mod time_definitions;
