// @generated by openehr-codegen from BMM (`DV_TEMPORAL`) — DO NOT EDIT.

use crate::data_types::quantity::date_time::dv_date::DvDate;
use crate::data_types::quantity::date_time::dv_date_time::DvDateTime;
use crate::data_types::quantity::date_time::dv_time::DvTime;

/// Specialised temporal variant of `DV_ABSOLUTE_QUANTITY` whose diff type is `DV_DURATION`.
/// Closed subtype set of `DV_TEMPORAL`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum DvTemporal {
    DvDate(DvDate),
    DvDateTime(DvDateTime),
    DvTime(DvTime),
}
