// @generated by openehr-codegen from BMM (`CODE_SET_ACCESS`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `CODE_SET_ACCESS` spec class, generated from the vendored BMM
//! meta-model.

/// Defines an object providing proxy access to a code_set.
#[doc(alias = "CODE_SET_ACCESS")]
#[derive(Debug, Clone, PartialEq)]
pub struct CodeSetAccess {}
