//! XML emitter (ADR-005): emits `impl crate::xml::runtime::ToXml` for the
//! generated RM/BASE spec types, into `openehr-its/src/xml/generated/`.
//!
//! The Rust facts (field idents, `Option`/`Vec`, enum variants, generics) come
//! from [`Model::xml_types`]; the wire shape (element order, attribute-vs-element
//! split, `xsi:type` slots) comes from the [`XsdModel`]. Fields are matched to
//! XSD elements/attributes by openEHR property name. A struct absent from the
//! XSD falls back to BMM field order with no attributes.

use crate::bmm::BmmSchema;
use crate::emit::{Model, XmlType};
use crate::xsd::XsdModel;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// One spec schema paired with the crate prelude its types are re-exported from.
pub struct XmlSchema<'a> {
    pub model: &'a Model,
    pub schema: &'a BmmSchema,
    /// e.g. `openehr_rm::prelude` / `openehr_base::prelude`.
    pub prelude: &'a str,
}

/// Emit the whole generated impl file for one namespace lineage. `unmatched`
/// receives `(type, xsd-element)` pairs the XSD declared but BMM has no field
/// for (diagnostics; those elements are skipped).
#[must_use]
pub fn emit_file(
    schemas: &[XmlSchema<'_>],
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) -> String {
    let mut b = String::new();
    b.push_str(
        "// @generated by openehr-codegen (emit-xml, ADR-005) — DO NOT EDIT.\n\
         // Canonical-XML `ToXml` impls for the RM/BASE spec types.\n\n\
         #![allow(clippy::all)]\n\
         #[allow(unused_imports)]\n\
         use crate::xml::runtime::ToXml;\n\n",
    );
    for s in schemas {
        for ty in s.model.xml_types(s.schema) {
            emit_type(&mut b, &ty, s.prelude, xsd, unmatched);
        }
    }
    b
}

fn generic_header(generics: &[String]) -> (String, String) {
    if generics.is_empty() {
        (String::new(), String::new())
    } else {
        let bounded = generics
            .iter()
            .map(|g| format!("{g}: crate::xml::runtime::ToXml"))
            .collect::<Vec<_>>()
            .join(", ");
        let bare = generics.join(", ");
        (format!("<{bounded}>"), format!("<{bare}>"))
    }
}

fn emit_type(
    b: &mut String,
    ty: &XmlType,
    prelude: &str,
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) {
    match ty {
        XmlType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics);
            let by_wire: BTreeMap<&str, &crate::emit::XmlField> =
                fields.iter().map(|f| (f.wire_name.as_str(), f)).collect();
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {prelude}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ \"{spec}\" }}\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n"
            );
            // Attributes gathered first (kept alive across write_start).
            b.push_str("let mut __attrs: Vec<(&str, String)> = Vec::new();\n");
            b.push_str(&format!(
                "if let Some(d) = declared {{ if d != \"{spec}\" {{ __attrs.push((\"xsi:type\", \"{spec}\".to_string())); }} }}\n"
            ));

            // Wire order + attr/element split from the XSD; fall back to BMM order.
            let (attrs, elems): (Vec<(String, bool)>, Vec<String>) = if xsd.types.contains_key(spec)
            {
                let (a, e) = xsd.flattened(spec);
                (
                    a.iter().map(|x| (x.name.clone(), x.required)).collect(),
                    e.iter().map(|x| x.name.clone()).collect(),
                )
            } else {
                (
                    Vec::new(),
                    fields.iter().map(|f| f.wire_name.clone()).collect(),
                )
            };

            for (aname, _req) in &attrs {
                if let Some(f) = by_wire.get(aname.as_str()) {
                    if f.optional {
                        let _ = writeln!(
                            b,
                            "if let Some(v) = &self.{} {{ __attrs.push((\"{}\", v.to_string())); }}",
                            f.rust_name, f.wire_name
                        );
                    } else {
                        let _ = writeln!(
                            b,
                            "__attrs.push((\"{}\", self.{}.to_string()));",
                            f.wire_name, f.rust_name
                        );
                    }
                } else {
                    unmatched.push((spec.clone(), aname.clone()));
                }
            }
            b.push_str("let mut __e = crate::xml::runtime::XmlStart::new(tag);\n");
            b.push_str("for (k, v) in &__attrs { __e.push_attribute((*k, v.as_str())); }\n");
            b.push_str("w.write_start(__e)?;\n");

            for ename in &elems {
                if let Some(f) = by_wire.get(ename.as_str()) {
                    emit_field_element(b, f);
                } else {
                    unmatched.push((spec.clone(), ename.clone()));
                }
            }
            b.push_str("w.write_end(tag)?;\nOk(())\n}\n}\n\n");
        }

        XmlType::Enum {
            spec: _,
            rust,
            generics,
            variants,
        } => {
            let (hdr, args) = generic_header(generics);
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {prelude}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ match self {{\n"
            );
            for v in variants {
                let _ = writeln!(b, "{prelude}::{rust}::{}(x) => x.xml_type_name(),", v.ident);
            }
            b.push_str("} }\n");
            b.push_str(
                "fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> { match self {\n",
            );
            for v in variants {
                let _ = writeln!(
                    b,
                    "{prelude}::{rust}::{}(x) => x.write_xml(w, tag, declared),",
                    v.ident
                );
            }
            b.push_str("} }\n}\n\n");
        }

        XmlType::Newtype { spec: _, rust } => {
            let _ = write!(
                b,
                "impl crate::xml::runtime::ToXml for {prelude}::{rust} {{\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, _declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 w.write_text_element(tag, &self.0.to_string())\n}}\n}}\n\n"
            );
        }
    }
}

fn emit_field_element(b: &mut String, f: &crate::emit::XmlField) {
    let (name, rust, target) = (&f.wire_name, &f.rust_name, &f.target);
    if target == "Hash" {
        // `Hash<K,V>` → `BTreeMap`: the openEHR canonical-XML shape for a hash is
        // vendor-specific and only appears on resource/AM-metadata types, off the
        // RM composition parity path. Skip for now.
        let _ = writeln!(b, "// TODO(port): skipped map field `{rust}` (Hash)");
        return;
    }
    if f.multiple {
        let _ = writeln!(
            b,
            "for v in &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else if f.optional {
        let _ = writeln!(
            b,
            "if let Some(v) = &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else {
        let _ = writeln!(
            b,
            "self.{rust}.write_xml(w, \"{name}\", Some(\"{target}\"))?;"
        );
    }
}
