//! XML emitter (ADR-005): emits `impl ToXml` + `impl FromXml` for the generated
//! RM/BASE spec types, into `openehr-its/src/xml/generated/`.
//!
//! The Rust facts (field idents, exact field types, enum variants, generics)
//! come from [`Model::xml_types`]; the wire shape (element order, attribute-vs-
//! element split for serialization, `xsi:type` slots) comes from the
//! [`XsdModel`]. Fields are matched to XSD elements/attributes by openEHR
//! property name; a struct absent from the XSD serializes in BMM field order
//! with no attributes. Deserialization dispatches child elements by name (order
//! -independent) and polymorphic slots by `xsi:type`.

use crate::bmm::BmmSchema;
use crate::emit::{Model, XmlField, XmlType};
use crate::xsd::XsdModel;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// One spec schema paired with the crate prelude its types are re-exported from.
pub struct XmlSchema<'a> {
    pub model: &'a Model,
    pub schema: &'a BmmSchema,
    /// e.g. `openehr_rm::prelude` / `openehr_base::prelude`.
    pub prelude: &'a str,
}

/// Emit the whole generated impl file. `unmatched` receives `(type, element)`
/// pairs the XSD declared for serialization but BMM has no field for (skipped).
///
/// # Errors
/// Fails codegen (F-05-01 guard) if any emitted LOCATABLE subtype would serialize
/// `archetype_node_id` as a child element rather than the required XML attribute
/// (i.e. its XSD closure is missing, so it falls back to attribute-less BMM order).
pub fn emit_file(
    schemas: &[XmlSchema<'_>],
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) -> Result<String, String> {
    let mut b = String::new();
    b.push_str(
        "// @generated by openehr-codegen (emit-xml, ADR-005) — DO NOT EDIT.\n\
         // Canonical-XML `ToXml`/`FromXml` impls for the RM/BASE spec types.\n\n\
         #![allow(clippy::all, clippy::pedantic, clippy::nursery, unused_variables, unused_mut)]\n\
         #[allow(unused_imports)]\n\
         use crate::xml::runtime::{ToXml, FromXml, XmlEvent, XmlError};\n\n",
    );
    let mut locatable_violations: Vec<String> = Vec::new();
    for s in schemas {
        for ty in s.model.xml_types(s.schema) {
            check_locatable_attr(&ty, xsd, &mut locatable_violations);
            emit_to_xml(&mut b, &ty, s.prelude, xsd, unmatched);
            emit_from_xml(&mut b, &ty, s.prelude, xsd);
        }
    }
    if !locatable_violations.is_empty() {
        return Err(format!(
            "emit-xml guard (F-05-01): {} LOCATABLE subtype(s) have no XSD closure, so \
             `archetype_node_id` would serialize as a child element instead of the required \
             XML attribute: {}. Extend the XSD input (crates/openehr-codegen/src/xsd.rs) so \
             these types reach `LOCATABLE`.",
            locatable_violations.len(),
            locatable_violations.join(", ")
        ));
    }
    Ok(b)
}

/// F-05-01 guard: any emitted struct carrying an `archetype_node_id` field (per
/// the BMM, a LOCATABLE subtype) must have that field classified as an XML
/// **attribute** by the driving XSD. `LOCATABLE` declares `archetype_node_id`
/// `use="required"` (an attribute); a type whose XSD closure is missing falls
/// back to attribute-less BMM field order and would emit it as a child element —
/// invalid canonical XML. Record the violation so codegen fails loudly.
fn check_locatable_attr(ty: &XmlType, xsd: &XsdModel, violations: &mut Vec<String>) {
    if let XmlType::Struct { spec, fields, .. } = ty {
        let has_archetype_node_id = fields.iter().any(|f| f.wire_name == "archetype_node_id");
        if has_archetype_node_id && !attr_names(spec, xsd).contains("archetype_node_id") {
            violations.push(spec.clone());
        }
    }
}

/// `(impl<…: Bound> , <…>)` — the impl-generics header and the type-args suffix.
fn generic_header(generics: &[String], bound: &str) -> (String, String) {
    if generics.is_empty() {
        (String::new(), String::new())
    } else {
        let bounded = generics
            .iter()
            .map(|g| format!("{g}: {bound}"))
            .collect::<Vec<_>>()
            .join(", ");
        (format!("<{bounded}>"), format!("<{}>", generics.join(", ")))
    }
}

/// A local accumulator variable name for a field. Strips the `r#` raw-identifier
/// prefix (`r#type` → `__type`) since `__r#type` is not a valid identifier.
fn acc_var(rust_name: &str) -> String {
    format!("__{}", rust_name.trim_start_matches("r#"))
}

/// XSD attribute names for a type (empty if the type is not in the XSD).
fn attr_names(spec: &str, xsd: &XsdModel) -> BTreeSet<String> {
    if xsd.types.contains_key(spec) {
        xsd.flattened(spec)
            .0
            .iter()
            .map(|a| a.name.clone())
            .collect()
    } else {
        BTreeSet::new()
    }
}

// ── serialization ─────────────────────────────────────────────────────────────

/// Emit `impl ToXml` for one [`XmlType`]. Public so the OPT emitter
/// (`emit_opt`) can reuse it over XSD-derived [`XmlType`]s (ADR-005).
pub fn emit_to_xml(
    b: &mut String,
    ty: &XmlType,
    prelude: &str,
    xsd: &XsdModel,
    unmatched: &mut Vec<(String, String)>,
) {
    match ty {
        XmlType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::ToXml");
            let by_wire: BTreeMap<&str, &XmlField> =
                fields.iter().map(|f| (f.wire_name.as_str(), f)).collect();
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {prelude}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ \"{spec}\" }}\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 let mut __attrs: Vec<(&str, String)> = Vec::new();\n\
                 if let Some(d) = declared {{ if d != \"{spec}\" {{ __attrs.push((\"xsi:type\", \"{spec}\".to_string())); }} }}\n"
            );
            // Wire order + attr/element split from the XSD; else BMM order, no attrs.
            let (attrs, elems): (Vec<String>, Vec<String>) = if xsd.types.contains_key(spec) {
                let (a, e) = xsd.flattened(spec);
                (
                    a.iter().map(|x| x.name.clone()).collect(),
                    e.iter().map(|x| x.name.clone()).collect(),
                )
            } else {
                (
                    Vec::new(),
                    fields.iter().map(|f| f.wire_name.clone()).collect(),
                )
            };
            for aname in &attrs {
                if let Some(f) = by_wire.get(aname.as_str()) {
                    if f.optional {
                        let _ = writeln!(
                            b,
                            "if let Some(v) = &self.{} {{ __attrs.push((\"{}\", v.to_string())); }}",
                            f.rust_name, f.wire_name
                        );
                    } else {
                        let _ = writeln!(
                            b,
                            "__attrs.push((\"{}\", self.{}.to_string()));",
                            f.wire_name, f.rust_name
                        );
                    }
                } else {
                    unmatched.push((spec.clone(), aname.clone()));
                }
            }
            b.push_str("let mut __e = crate::xml::runtime::XmlStart::new(tag);\n");
            b.push_str("for (k, v) in &__attrs { __e.push_attribute((*k, v.as_str())); }\n");
            b.push_str("w.write_start(__e)?;\n");
            for ename in &elems {
                match by_wire.get(ename.as_str()) {
                    Some(f) => emit_write_field(b, f),
                    None => unmatched.push((spec.clone(), ename.clone())),
                }
            }
            b.push_str("w.write_end(tag)?;\nOk(())\n}\n}\n\n");
        }
        XmlType::Enum {
            rust,
            generics,
            variants,
            ..
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::ToXml");
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::ToXml for {prelude}::{rust}{args} {{\n\
                 fn xml_type_name(&self) -> &'static str {{ match self {{\n"
            );
            for v in variants {
                let _ = writeln!(b, "{prelude}::{rust}::{}(x) => x.xml_type_name(),", v.ident);
            }
            b.push_str("} }\n");
            b.push_str("fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> { match self {\n");
            for v in variants {
                let _ = writeln!(
                    b,
                    "{prelude}::{rust}::{}(x) => x.write_xml(w, tag, declared),",
                    v.ident
                );
            }
            b.push_str("} }\n}\n\n");
        }
        XmlType::Newtype { rust, .. } => {
            let _ = write!(
                b,
                "impl crate::xml::runtime::ToXml for {prelude}::{rust} {{\n\
                 fn write_xml(&self, w: &mut crate::xml::runtime::XmlWriter, tag: &str, _declared: Option<&str>) -> Result<(), crate::xml::runtime::XmlError> {{\n\
                 w.write_text_element(tag, &self.0.to_string())\n}}\n}}\n\n"
            );
        }
    }
}

fn emit_write_field(b: &mut String, f: &XmlField) {
    if f.target == "Hash" {
        let (name, rust) = (&f.wire_name, &f.rust_name);
        if f.map_value.as_deref() == Some("String") {
            // `Hash<String, String>` → repeated `<name id="key">value</name>`
            // (the openEHR `StringDictionaryItem` shape).
            if f.optional {
                let _ = writeln!(
                    b,
                    "if let Some(m) = &self.{rust} {{ for (k, v) in m {{ w.write_kv_element(\"{name}\", k, v)?; }} }}"
                );
            } else {
                let _ = writeln!(
                    b,
                    "for (k, v) in &self.{rust} {{ w.write_kv_element(\"{name}\", k, v)?; }}"
                );
            }
        } else {
            // `Hash<String, ComplexType>` (translations, RESOURCE_ANNOTATIONS):
            // archetype-resource metadata serialized via ADL/AOM, off the RM
            // canonical-XML wire; its RM-XML shape is not spec-defined here.
            let _ = writeln!(
                b,
                "// PORT NOTE: Hash<String, {}> field `{rust}` is off the RM canonical-XML wire (resource metadata); not serialized.",
                f.map_value.as_deref().unwrap_or("?")
            );
        }
        return;
    }
    let (name, rust, target) = (&f.wire_name, &f.rust_name, &f.target);
    if f.multiple {
        let _ = writeln!(
            b,
            "for v in &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else if f.optional {
        let _ = writeln!(
            b,
            "if let Some(v) = &self.{rust} {{ v.write_xml(w, \"{name}\", Some(\"{target}\"))?; }}"
        );
    } else {
        let _ = writeln!(
            b,
            "self.{rust}.write_xml(w, \"{name}\", Some(\"{target}\"))?;"
        );
    }
}

// ── deserialization ─────────────────────────────────────────────────────────

/// Emit `impl FromXml` for one [`XmlType`]. Public so the OPT emitter
/// (`emit_opt`) can reuse it over XSD-derived [`XmlType`]s (ADR-005).
pub fn emit_from_xml(b: &mut String, ty: &XmlType, prelude: &str, xsd: &XsdModel) {
    match ty {
        XmlType::Struct {
            spec,
            rust,
            generics,
            fields,
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::FromXml");
            let attrs = attr_names(spec, xsd);
            let is_attr = |f: &XmlField| attrs.contains(&f.wire_name);
            // `Hash<String, String>` is parsed inline (StringDictionaryItem);
            // `Hash<String, ComplexType>` is off-wire and defaulted.
            let is_str_hash =
                |f: &XmlField| f.target == "Hash" && f.map_value.as_deref() == Some("String");
            let is_cplx_hash =
                |f: &XmlField| f.target == "Hash" && f.map_value.as_deref() != Some("String");
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::FromXml for {prelude}::{rust}{args} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n"
            );
            // Accumulators for element fields. Types are intentionally left to
            // inference — each `__x` is pinned by its construction site below
            // (`field: __x…`), so boxing and type overrides resolve without
            // naming (and repeating the import of) the field type here.
            for f in fields.iter().filter(|f| !is_attr(f) && !is_cplx_hash(f)) {
                let var = acc_var(&f.rust_name);
                if is_str_hash(f) {
                    let _ = writeln!(b, "let mut {var} = std::collections::BTreeMap::new();");
                } else if f.multiple {
                    let _ = writeln!(b, "let mut {var} = Vec::new();");
                } else {
                    let _ = writeln!(b, "let mut {var} = None;");
                }
            }
            b.push_str("loop { match reader.read()? {\n");
            b.push_str("crate::xml::runtime::XmlEvent::Start(__c) => match __c.name.as_str() {\n");
            for f in fields.iter().filter(|f| !is_attr(f) && !is_cplx_hash(f)) {
                let var = acc_var(&f.rust_name);
                if is_str_hash(f) {
                    // StringDictionaryItem: `<name id="key">value</name>`.
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ let __k = __c.attr(\"id\").unwrap_or(\"\").to_string(); let __v: String = crate::xml::runtime::FromXml::from_xml(reader, &__c)?; {var}.insert(__k, __v); }}",
                        f.wire_name
                    );
                } else if f.multiple {
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ {var}.push(crate::xml::runtime::FromXml::from_xml(reader, &__c)?); }}",
                        f.wire_name
                    );
                } else {
                    let _ = writeln!(
                        b,
                        "\"{}\" => {{ {var} = Some(crate::xml::runtime::FromXml::from_xml(reader, &__c)?); }}",
                        f.wire_name
                    );
                }
            }
            b.push_str("_ => reader.skip_element()?,\n},\n");
            b.push_str("crate::xml::runtime::XmlEvent::End => break,\n");
            b.push_str("crate::xml::runtime::XmlEvent::Text(_) => {}\n");
            b.push_str("crate::xml::runtime::XmlEvent::Eof => return Err(crate::xml::runtime::XmlError::Parse(\"unexpected EOF\".into())),\n");
            b.push_str("} }\n");
            // Construct.
            let _ = writeln!(b, "Ok({prelude}::{rust} {{");
            for f in fields {
                let fname = &f.rust_name;
                if is_attr(f) {
                    if f.optional {
                        let _ = writeln!(
                            b,
                            "{fname}: start.attr(\"{}\").map(|s| s.to_string()),",
                            f.wire_name
                        );
                    } else {
                        let _ = writeln!(
                            b,
                            "{fname}: start.attr(\"{}\").ok_or_else(|| crate::xml::runtime::XmlError::Parse(\"missing attribute {}\".into()))?.to_string(),",
                            f.wire_name, f.wire_name
                        );
                    }
                } else if is_cplx_hash(f) {
                    let _ = writeln!(b, "{fname}: Default::default(),");
                } else if is_str_hash(f) {
                    let var = acc_var(fname);
                    if f.optional {
                        let _ = writeln!(
                            b,
                            "{fname}: if {var}.is_empty() {{ None }} else {{ Some({var}) }},"
                        );
                    } else {
                        let _ = writeln!(b, "{fname}: {var},");
                    }
                } else if f.multiple || f.optional {
                    let _ = writeln!(b, "{fname}: {},", acc_var(fname));
                } else if let Some(default) = &f.default {
                    // Mandatory field archie omits at its default (Interval flags):
                    // use the default when the element is absent.
                    let _ = writeln!(b, "{fname}: {}.unwrap_or({default}),", acc_var(fname));
                } else {
                    let _ = writeln!(
                        b,
                        "{fname}: {}.ok_or_else(|| crate::xml::runtime::XmlError::Parse(\"missing element {}\".into()))?,",
                        acc_var(fname),
                        f.wire_name
                    );
                }
            }
            b.push_str("})\n}\n}\n\n");
        }
        XmlType::Enum {
            spec,
            rust,
            generics,
            dispatch,
            ..
        } => {
            let (hdr, args) = generic_header(generics, "crate::xml::runtime::FromXml");
            let self_ident = dispatch
                .iter()
                .find(|(x, _)| x == spec)
                .map(|(_, i)| i.clone());
            let _ = write!(
                b,
                "impl{hdr} crate::xml::runtime::FromXml for {prelude}::{rust}{args} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n\
                 match start.xsi_type() {{\n"
            );
            for (xsi, ident) in dispatch {
                let _ = writeln!(
                    b,
                    "Some(\"{xsi}\") => Ok({prelude}::{rust}::{ident}(crate::xml::runtime::FromXml::from_xml(reader, start)?)),"
                );
            }
            match self_ident {
                Some(ident) => {
                    let _ = writeln!(
                        b,
                        "None => Ok({prelude}::{rust}::{ident}(crate::xml::runtime::FromXml::from_xml(reader, start)?)),"
                    );
                }
                None => {
                    let _ = writeln!(
                        b,
                        "None => Err(crate::xml::runtime::XmlError::Parse(\"{rust}: missing xsi:type\".into())),"
                    );
                }
            }
            let _ = writeln!(
                b,
                "Some(other) => Err(crate::xml::runtime::XmlError::Parse(format!(\"{rust}: unknown xsi:type {{other}}\"))),"
            );
            b.push_str("}\n}\n}\n\n");
        }
        XmlType::Newtype { rust, .. } => {
            let _ = write!(
                b,
                "impl crate::xml::runtime::FromXml for {prelude}::{rust} {{\n\
                 fn from_xml(reader: &mut crate::xml::runtime::XmlReader, start: &crate::xml::runtime::StartTag) -> Result<Self, crate::xml::runtime::XmlError> {{\n\
                 Ok({prelude}::{rust}(crate::xml::runtime::FromXml::from_xml(reader, start)?))\n}}\n}}\n\n"
            );
        }
    }
}
