[package]
name = "openehr-lang"
version = "0.1.0"
description = "openEHR LANG 1.0.0: ODIN + BMM (P_BMM) + EL"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
serde_json.workspace = true

[lints]
workspace = true
