// @generated by openehr-codegen from BMM (`EXPR_TYPE_DEF`) — DO NOT EDIT.

use crate::beom::types::type_def_boolean::TypeDefBoolean;
use crate::beom::types::type_def_date::TypeDefDate;
use crate::beom::types::type_def_date_time::TypeDefDateTime;
use crate::beom::types::type_def_duration::TypeDefDuration;
use crate::beom::types::type_def_integer::TypeDefInteger;
use crate::beom::types::type_def_object_ref::TypeDefObjectRef;
use crate::beom::types::type_def_real::TypeDefReal;
use crate::beom::types::type_def_string::TypeDefString;
use crate::beom::types::type_def_terminology_code::TypeDefTerminologyCode;
use crate::beom::types::type_def_time::TypeDefTime;
use crate::beom::types::type_def_uri::TypeDefUri;

/// Ancestor class for type definitions known in the openEHR Expression formalism.
/// Closed subtype set of `EXPR_TYPE_DEF`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ExprTypeDef {
    TypeDefBoolean(TypeDefBoolean),
    TypeDefDate(TypeDefDate),
    TypeDefDateTime(TypeDefDateTime),
    TypeDefDuration(TypeDefDuration),
    TypeDefInteger(TypeDefInteger),
    TypeDefObjectRef(TypeDefObjectRef),
    TypeDefReal(TypeDefReal),
    TypeDefString(TypeDefString),
    TypeDefTerminologyCode(TypeDefTerminologyCode),
    TypeDefTime(TypeDefTime),
    TypeDefUri(TypeDefUri),
}
