// @generated by openehr-codegen from BMM (`TYPE_DEF_URI`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

/// Rules meta-type representing the primitive type Uri.
#[derive(Debug, Clone, PartialEq)]
pub struct TypeDefUri {
    pub type_name: String,
    pub type_anchor: String,
}
