// @generated by openehr-codegen — DO NOT EDIT.

pub mod access_control_settings;
pub mod ehr;
pub mod ehr_access;
pub mod ehr_status;
pub mod versioned_composition;
pub mod versioned_ehr_access;
pub mod versioned_ehr_status;
