// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR spec package `v1_2/data_structures` — generated module tree.

pub mod data_structure;
pub mod history;
pub mod item_structure;
pub mod representation;

// hand-written modules (spec behaviour), auto-declared:
pub mod data_structure_impl;
