// @generated by openehr-codegen from BMM (`DV_ABSOLUTE_QUANTITY`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `DV_ABSOLUTE_QUANTITY` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::data_types::quantity::date_time::dv_date::DvDate;
use crate::v1_2::data_types::quantity::date_time::dv_date_time::DvDateTime;
use crate::v1_2::data_types::quantity::date_time::dv_time::DvTime;

/// Closed subtype set of `DV_ABSOLUTE_QUANTITY`, dispatched on each payload's `_type`.
///
/// Abstract class defining the concept of quantified entities whose values are absolute with respect to an origin. Dates and Times are the main example.
#[doc(alias = "DV_ABSOLUTE_QUANTITY")]
#[derive(Debug, Clone, PartialEq)]
pub enum DvAbsoluteQuantity {
    /// The `DV_DATE` subtype of `DV_ABSOLUTE_QUANTITY`.
    DvDate(DvDate),
    /// The `DV_DATE_TIME` subtype of `DV_ABSOLUTE_QUANTITY`.
    DvDateTime(DvDateTime),
    /// The `DV_TIME` subtype of `DV_ABSOLUTE_QUANTITY`.
    DvTime(DvTime),
}
