// @generated by openehr-codegen from BMM (`DV_SCALE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `DV_SCALE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_2::data_types::quantity::dv_interval::DvInterval;
use crate::v1_2::data_types::quantity::dv_ordered::DvOrdered;
use crate::v1_2::data_types::quantity::reference_range::ReferenceRange;
use crate::v1_2::data_types::text::code_phrase::CodePhrase;
use crate::v1_2::data_types::text::dv_coded_text::DvCodedText;

/// A data type that represents scale values, where there is:
///
/// a) implied ordering,
/// b) no implication that the distance between each value is constant, and
/// c) the total number of values is finite;
/// d) non-integer values are allowed.
///
/// Example:
///
/// ----
/// Borg CR 10 Scale
///
/// 0    No Breathlessness at all
/// 0.5  Very Very Slight (Just Noticeable)
/// 1    Very Slight
/// 2    Slight Breathlessness
/// 3    Moderate
/// ... etc
/// ----
///
/// For scores that include only Integers, `DV_SCALE` may also be used, but `DV_ORDINAL` should be supported to accommodate existing data instances of that type.
#[doc(alias = "DV_SCALE")]
#[derive(Debug, Clone, PartialEq)]
pub struct DvScale {
    // inherited: DV_ORDERED
    /// Optional normal status indicator of value with respect to normal range for this value.
    ///
    /// Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
    pub normal_status: Option<CodePhrase>,
    /// Optional normal range.
    pub normal_range: Option<Box<DvInterval<DvOrdered>>>,
    /// Optional tagged other reference ranges for this value in its particular measurement context.
    pub other_reference_ranges: Option<openehr_base::containers::NonEmptyVec<ReferenceRange>>,
    /// Coded textual representation of this value in the scale range, which may be strings made from symbols or other enumerations of terms such as  `no breathlessness`, `very very slight`, `slight breathlessness`. Codes come from archetypes.
    ///
    /// In some cases, a scale may include values that have no code/symbol. In this case, the symbol will be a `DV-CODED_TEXT` including the `_terminology_id_` and a blank String value for `_code_string_`.
    pub symbol: DvCodedText,
    /// Real number value of Scale item.
    pub value: f64,
}
