// @generated by openehr-codegen from BMM (`C_OBJECT`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::am24::aom2::constraint_model::archetype_slot::ArchetypeSlot;
use crate::am24::aom2::constraint_model::c_archetype_root::CArchetypeRoot;
use crate::am24::aom2::constraint_model::c_complex_object::CComplexObject;
use crate::am24::aom2::constraint_model::c_complex_object_proxy::CComplexObjectProxy;
use crate::am24::aom2::constraint_model::primitive::c_boolean::CBoolean;
use crate::am24::aom2::constraint_model::primitive::c_date::CDate;
use crate::am24::aom2::constraint_model::primitive::c_date_time::CDateTime;
use crate::am24::aom2::constraint_model::primitive::c_duration::CDuration;
use crate::am24::aom2::constraint_model::primitive::c_integer::CInteger;
use crate::am24::aom2::constraint_model::primitive::c_real::CReal;
use crate::am24::aom2::constraint_model::primitive::c_string::CString;
use crate::am24::aom2::constraint_model::primitive::c_terminology_code::CTerminologyCode;
use crate::am24::aom2::constraint_model::primitive::c_time::CTime;

/// Abstract model of constraint on any kind of object node.
/// Closed subtype set of `C_OBJECT` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CObject {
    ArchetypeSlot(ArchetypeSlot),
    CArchetypeRoot(CArchetypeRoot),
    CBoolean(CBoolean),
    CComplexObject(CComplexObject),
    CComplexObjectProxy(CComplexObjectProxy),
    CDate(CDate),
    CDateTime(CDateTime),
    CDuration(CDuration),
    CInteger(CInteger),
    CReal(CReal),
    CString(CString),
    CTerminologyCode(CTerminologyCode),
    CTime(CTime),
}
