// @generated by openehr-codegen from BMM (`Iso8601_date`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_derive::OpenEhrType;

/// Represents an ISO 8601 date, including partial and extended forms. Value may be:
///
/// * `YYYY-MM-DD` (extended, preferred)
/// * `YYYYMMDD` (compact)
/// * a partial invariant.
///
/// See `Time_definitions._valid_iso8601_date()_` for validity.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "Iso8601_date")]
pub struct Iso8601Date {
    // inherited: Iso8601_type
    /// Representation of all descendants is a single String.
    pub value: String,
}
