// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v1_0/bmm_persistence` — generated module tree.

pub mod bmm_include_spec;
pub mod p_bmm_base_type;
pub mod p_bmm_class;
pub mod p_bmm_container_property;
pub mod p_bmm_container_type;
pub mod p_bmm_enumeration;
pub mod p_bmm_enumeration_integer;
pub mod p_bmm_enumeration_string;
pub mod p_bmm_generic_parameter;
pub mod p_bmm_generic_property;
pub mod p_bmm_generic_type;
pub mod p_bmm_indexed_container_property;
pub mod p_bmm_indexed_container_type;
pub mod p_bmm_model_element;
pub mod p_bmm_open_type;
pub mod p_bmm_package;
pub mod p_bmm_package_container;
pub mod p_bmm_property;
pub mod p_bmm_schema;
pub mod p_bmm_schema_descriptor;
pub mod p_bmm_simple_type;
pub mod p_bmm_single_property;
pub mod p_bmm_single_property_open;
pub mod p_bmm_type;
