// @generated by openehr-codegen from BMM (`P_BMM_SIMPLE_TYPE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `P_BMM_SIMPLE_TYPE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::entity::bmm_simple_type::BmmSimpleType;

/// Persistent form of `BMM_SIMPLE_TYPE`.
#[doc(alias = "P_BMM_SIMPLE_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmSimpleType {
    /// Result of `_create_bmm_type()_` call.
    pub bmm_type: Option<BmmSimpleType>,

    // inherited: P_BMM_BASE_TYPE
    /// The `value_constraint` attribute of openEHR `P_BMM_BASE_TYPE` (the vendored BMM carries no documentation for it).
    pub value_constraint: Option<String>,
    /// Name of type - must be a simple class name.
    pub r#type: String,
}
