// @generated by openehr-codegen from BMM (`P_BMM_GENERIC_PARAMETER`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `P_BMM_GENERIC_PARAMETER` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::entity::bmm_parameter_type::BmmParameterType;

/// Persistent form of `BMM_GENERIC_PARAMETER`.
#[doc(alias = "P_BMM_GENERIC_PARAMETER")]
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmGenericParameter {
    // inherited: P_BMM_MODEL_ELEMENT
    /// Optional documentation of this element.
    pub documentation: Option<String>,
    /// Name of the parameter, e.g. 'T' etc. Persisted attribute. Name is limited to 1 character, upper case.
    pub name: String,
    /// Optional conformance constraint - the name of a type to which a concrete substitution of this generic parameter must conform. Persisted attribute.
    pub conforms_to_type: Option<String>,
    /// `BMM_GENERIC_PARAMETER` created by `_create_bmm_generic_parameter_`.
    pub bmm_generic_parameter: Option<BmmParameterType>,
}
