// @generated by openehr-codegen from BMM (`P_BMM_CONTAINER_TYPE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `P_BMM_CONTAINER_TYPE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::entity::bmm_container_type::BmmContainerType;
use crate::v1_0::bmm_persistence::p_bmm_base_type::PBmmBaseType;
use crate::v1_0::bmm_persistence::p_bmm_indexed_container_type::PBmmIndexedContainerType;

/// Persistent form of `BMM_CONTAINER_TYPE`.
#[doc(alias = "P_BMM_CONTAINER_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub struct PBmmContainerTypeData {
    /// Result of `_create_bmm_type()_` call.
    pub bmm_type: Option<BmmContainerType>,
    /// The type of the container. This converts to the `_root_type_` in `BMM_GENERIC_TYPE`. Persisted attribute.
    pub container_type: String,
    /// Type definition of `_type_`, if not a simple String type reference. Persisted attribute.
    pub type_def: Option<PBmmBaseType>,
    /// The target type; this converts to the first parameter in `_generic_parameters_` in `BMM_GENERIC_TYPE`. Persisted attribute.
    pub r#type: Option<String>,
}

/// Polymorphic slot of `P_BMM_CONTAINER_TYPE`, dispatched on each payload's `_type`.
///
/// Persistent form of `BMM_CONTAINER_TYPE`.
#[doc(alias = "P_BMM_CONTAINER_TYPE")]
#[derive(Debug, Clone, PartialEq)]
pub enum PBmmContainerType {
    /// The `P_BMM_INDEXED_CONTAINER_TYPE` subtype of `P_BMM_CONTAINER_TYPE`.
    PBmmIndexedContainerType(PBmmIndexedContainerType),
    /// An instance of `P_BMM_CONTAINER_TYPE` itself (its own, least-rich form).
    PBmmContainerType(PBmmContainerTypeData),
}
