// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR spec package `v1_1/composition/content` — generated module tree.

pub mod content_item;
pub mod entry;
pub mod navigation;
