// @generated by openehr-codegen from BMM (`ORIGINAL_VERSION`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `ORIGINAL_VERSION` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::common::generic::attestation::Attestation;
use crate::v1_1::common::generic::audit_details::AuditDetails;
use crate::v1_1::data_types::text::dv_coded_text::DvCodedText;
use openehr_base::v1_2::base_types::identification::object_ref::ObjectRef;
use openehr_base::v1_2::base_types::identification::object_version_id::ObjectVersionId;

/// A Version containing locally created content and optional attestations.
#[doc(alias = "ORIGINAL_VERSION")]
#[derive(Debug, Clone, PartialEq)]
pub struct OriginalVersion<T> {
    // inherited: VERSION
    /// Contribution in which this version was added.
    pub contribution: ObjectRef,
    /// OpenPGP digital signature or digest of content committed in this Version.
    pub signature: Option<String>,
    /// Audit trail corresponding to the committal of this version to the `VERSIONED_OBJECT`.
    pub commit_audit: AuditDetails,
    /// Stored version of inheritance precursor.
    pub uid: ObjectVersionId,
    /// Stored version of inheritance precursor.
    pub preceding_version_uid: Option<ObjectVersionId>,
    /// Identifiers of other versions whose content was merged into this version, if any.
    pub other_input_version_uids: Option<openehr_base::containers::NonEmptyVec<ObjectVersionId>>,
    /// Lifecycle state of the content item in this version; coded by openEHR vocabulary `version lifecycle state`.
    pub lifecycle_state: DvCodedText,
    /// Set of attestations relating to this version.
    pub attestations: Option<openehr_base::containers::NonEmptyVec<Attestation>>,
    /// Data content of this Version.
    pub data: Option<T>,
}
