// @generated by openehr-codegen from BMM (`DATA_STRUCTURE`) — DO NOT EDIT.

use crate::data_structures::history::history::History;
use crate::data_structures::item_structure::item_list::ItemList;
use crate::data_structures::item_structure::item_single::ItemSingle;
use crate::data_structures::item_structure::item_structure::ItemStructure;
use crate::data_structures::item_structure::item_table::ItemTable;
use crate::data_structures::item_structure::item_tree::ItemTree;

/// Abstract parent class of all data structure types. Includes the `_as_hierarchy_` function which can generate the equivalent CEN EN13606 single hierarchy for each subtype's physical representation. For example, the physical representation of an `ITEM_LIST` is `List<ELEMENT>`; its implementation of `_as_hierarchy_` will generate a `CLUSTER` containing the set of `ELEMENT` nodes from the list.
/// Closed subtype set of `DATA_STRUCTURE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum DataStructure {
    History(History<ItemStructure>),
    ItemList(ItemList),
    ItemSingle(ItemSingle),
    ItemTable(ItemTable),
    ItemTree(ItemTree),
}
