#!/usr/bin/env bash
# Render the public comparison page's content (tracker issue #147) from the
# COMMITTED runner artifacts — the same no-hand-typed-numbers discipline as
# scripts/render-conformance-stats.sh (CI: scripts/check-conformance-numbers.sh).
#
# Inputs (all committed, regenerated by the CNF runner):
#   docs/conformance/{ehrbase-rs,ehrbase-java}/{results.json,verdicts.json}
#   docs/conformance/{ehrbase-rs,ehrbase-java}/stress.json  (when measured)
# Outputs:
#   website/book/generated/comparison-conformance.md
#   website/book/generated/comparison-bench.md
#   website/book/src/perf-assets/perf-stress-compare.svg  (committed,
#     rendered by `cnf-runner stress-compare` when BOTH sides carry a
#     committed stress report; the perf-assets CI drift gate covers it)
set -euo pipefail
cd "$(dirname "$0")/.."

RS="docs/conformance/ehrbase-rs"
JV="docs/conformance/ehrbase-java"
OUT="website/book/generated"

command -v jq >/dev/null 2>&1 || { echo "render-comparison: jq is required" >&2; exit 1; }
for f in "$RS/results.json" "$JV/results.json"; do
  [ -f "$f" ] || { echo "render-comparison: missing artifact $f" >&2; exit 1; }
done
mkdir -p "$OUT" website/book/src/comparison-assets

# Unified CNF schema on BOTH sides since the #232 re-base: `outcomes` records
# keyed by case id + optional format.
count() { jq "[(.cases // .outcomes)[] | select(.status == \"$2\")] | length" "$1/results.json"; }

# ── conformance side ─────────────────────────────────────────────────────────
# The CNF results artifacts are clock-free; date = the artifact's commit date
# (falling back to mtime for a not-yet-committed regeneration).
run_date() {
  local d
  d=$(git log -1 --format=%cs -- "$1/results.json" 2>/dev/null || true)
  [ -n "$d" ] || d=$(date -r "$1/results.json" +%Y-%m-%d)
  echo "$d"
}
rs_date=$(run_date "$RS")
jv_date=$(run_date "$JV")
jv_version=$(jq -r '.sut.version // .sut.name' "$JV/results.json")
rs_total=$(jq '(.cases // .outcomes) | length' "$RS/results.json")
jv_total=$(jq '(.cases // .outcomes) | length' "$JV/results.json")

# The shared per-case join: both runs execute the SAME committed catalogue,
# keyed by case id + format. (A case one run records N/A — an unclaimed
# option branch or an unrealizable ground on that party's topology — still
# joins; its status shows as not_applicable.)
shared=$(jq -n --slurpfile a "$RS/results.json" --slurpfile b "$JV/results.json" '
  (INDEX($a[0].outcomes[]; "\(.case)|\(.format // "-")")) as $rs
  | [$b[0].outcomes[] | . as $o | ($rs["\(.case)|\(.format // "-")"]) as $mine
     | select($mine != null)
     | {key: "\(.case)|\(.format // "-")", java: .status, rs: $mine.status}]')
shared_n=$(echo "$shared" | jq 'length')
srow() { echo "$shared" | jq "[.[] | select(.$1 == \"$2\")] | length"; }

# Upstream failures grouped by schedule chapter (the case-id prefix), and the
# full per-case list with our outcome on the identical case.
fail_by_cap=$(jq -n --slurpfile b "$JV/results.json" '
  [$b[0].outcomes[] | select(.status=="failed")]
  | group_by(.case | split(".")[0] | split("-")[0])
  | map({cap: (.[0].case | split(".")[0] | split("-")[0]), n: length}) | sort_by(-.n)')
fail_rows=$(jq -rn --slurpfile a "$RS/results.json" --slurpfile b "$JV/results.json" '
  (INDEX($a[0].outcomes[]; "\(.case)|\(.format // "-")")) as $rs
  | [$b[0].outcomes[] | select(.status=="failed")]
  | sort_by(.case)[]
  | "| \(.case) | \(.format // "—") | \((.reason // "") | .[0:90] | gsub("\\|"; "\\\\|")) | \($rs["\(.case)|\(.format // "-")"].status // "—") |"')

# Profile verdict tokens from verdicts.json (pass/fail/not_claimed).
pverdict() { jq -r --arg t "$2" '.profiles[] | select(.[0]==$t) | .[1] // "—"' "$1/verdicts.json" | sed -e 's/^$/—/' -e 's/_/ /g'; }
sverdict() { jq -r '.security // "not claimed"' "$1/verdicts.json"; }

{
  cat <<EOF
## Systems under test

| | ehrbase-rs | upstream (Java) |
|---|---|---|
| Product | $(jq -r '.sut.name' "$RS/results.json") $(jq -r '.sut.version' "$RS/results.json") | $(jq -r '.sut.name' "$JV/results.json") $(jq -r '.sut.version' "$JV/results.json") |
| Run date | ${rs_date} | ${jv_date} |
| Party statement | \`tools/cnf-runner/party/ehrbase-rs/\` | \`tools/cnf-runner/party/ehrbase-java/\` |
| Stack | root compose, built from the current sources | \`docker/sut-ehrbase-java.yml\` (official images) |

## Methodology

Both systems execute the **same committed CNF 2.0 catalogue** ($(jq '(.cases // .outcomes) | length' "$RS/results.json") case-by-format
executions) through the same reference runner (\`tools/cnf-runner\`), each on
fresh volumes with its own committed party set: the ixit names the reachable
instances (upstream declares no readonly principal), and the statement (the
ICS) declares the claimed capabilities and ambiguity-register options —
ISO/IEC 9646-style test selection excuses undeclared option branches as N/A
with a citation, never as silent skips. Verdicts are pure functions of
(statement, results, catalogue, capability matrix).

## Profile verdicts

| Profile | ehrbase-rs | upstream (Java) |
|---|---|---|
| CORE | $(pverdict "$RS" CORE) | $(pverdict "$JV" CORE) |
| STANDARD | $(pverdict "$RS" STANDARD) | $(pverdict "$JV" STANDARD) |
| OPTIONS | $(pverdict "$RS" OPTIONS) | $(pverdict "$JV" OPTIONS) |
| SEC-BASIC | $(sverdict "$RS") | $(sverdict "$JV") |

## Outcome totals

Runs compared: **ehrbase-rs** (run of ${rs_date}) vs **upstream EHRbase
${jv_version}** (run of ${jv_date}) — the SAME catalogue through the same
runner, each with its own committed party statement.

| | executed | passed | failed | errored | skipped | N/A |
|---|---|---|---|---|---|---|
| **ehrbase-rs** | ${rs_total} | $(count "$RS" passed) | $(count "$RS" failed) | $(count "$RS" errored) | $(count "$RS" skipped) | $(count "$RS" not_applicable) |
| **upstream (Java)** | ${jv_total} | $(count "$JV" passed) | $(count "$JV" failed) | $(count "$JV" errored) | $(count "$JV" skipped) | $(count "$JV" not_applicable) |

An **errored** row is inconclusive (the wire answered outside the operation's
bound outcome map), never counted as a failure. An **N/A** row carries a
machine-readable citation (an undeclared option branch, an unrealizable wire
on the technology profile, or a ground the party's topology cannot
establish).

## Capability-by-capability

Evidence tokens from each party's computed verdicts: **passed** (every
gating case green), **failed** (at least one gating case red), **unrealized**
(every case excused by a register citation — e.g. AMB-41: ADL 1.4 archetype
provisioning has no ITS-REST wire), **not_evidenced** (claimed, no gating
case ran), **no_cases**, or **not claimed** (absent from that party's ICS).

| Capability | ehrbase-rs | upstream (Java) |
|---|---|---|
$(jq -rn --slurpfile a "$RS/verdicts.json" --slurpfile b "$JV/verdicts.json" '
  (INDEX($a[0].capabilities[]; .[0])) as $rs
  | (INDEX($b[0].capabilities[]; .[0])) as $jv
  | ([$a[0].capabilities[][0], $b[0].capabilities[][0]] | unique)[]
  | "| \(.) | \($rs[.][1] // "not claimed") | \($jv[.][1] // "not claimed") |"')

## Failures — both directions

### ehrbase-rs failures (with the upstream outcome on the identical case)

| Case | Format | Failure | upstream outcome |
|---|---|---|---|
$(jq -rn --slurpfile a "$RS/results.json" --slurpfile b "$JV/results.json" '
  (INDEX($b[0].outcomes[]; "\(.case)|\(.format // "-")")) as $jv
  | [$a[0].outcomes[] | select(.status=="failed")]
  | sort_by(.case)[]
  | "| \(.case) | \(.format // "—") | \((.reason // "") | .[0:90] | gsub("\\|"; "\\\\|")) | \($jv["\(.case)|\(.format // "-")"].status // "—") |"' ; [ "$(count "$RS" failed)" = "0" ] && echo '| — | — | *none — zero failing cases* | — |' )

### Upstream failures by schedule chapter

| Chapter | failed cases |
|---|---|
$(echo "$fail_by_cap" | jq -r '.[] | "| \(.cap) | \(.n) |"')

<details><summary>Every upstream-failed case, with the ehrbase-rs outcome on the identical case</summary>

| Case | Format | Upstream failure | ehrbase-rs outcome |
|---|---|---|---|
${fail_rows}

</details>
EOF
} > "$OUT/comparison-conformance.md"

# The repo-committed comparison record: the same derivation, with the honesty
# preamble, at docs/conformance/COMPARISON.md (regenerated per run -- #232).
{
  cat <<'PREAMBLE'
# openEHR CDR conformance comparison (generated)

> **Measured, not asserted.** Every cell below is derived from the two
> committed `results.json`/`verdicts.json` sets produced by the CNF 2.0
> reference runner (`tools/cnf-runner`) executing the SAME committed
> catalogue against each system, each with its own committed party statement
> (`tools/cnf-runner/party/<sut>/`). Nothing here is hand-entered
> (`scripts/render-comparison.sh`; CI: `scripts/check-conformance-numbers.sh`).
>
> - A capability a party's statement does not claim reads **not claimed** and
>   never gates its verdicts; a ground unrealizable on a party's topology or
>   technology profile reads **N/A with a machine citation**, never fail.
> - This comparison makes **no certification claim on behalf of any other
>   vendor** -- each column is computed from that SUT's own run.
> - Where the comparison SUT out-performs ehrbase-rs, its cell reads pass
>   while ours reads fail -- stated plainly, not hidden.

PREAMBLE
  cat "$OUT/comparison-conformance.md"
} > docs/conformance/COMPARISON.md

# ── stress side (the CNF step-load instrument; the retired lab's overlays are gone) ──
RS_STRESS="$RS/stress.json"
JV_STRESS="$JV/stress.json"

# Derivations from a committed stress report. The knee step is the stable
# step at the maximum sustainable rate; its worst per-operation p99 and its
# sampled resource peaks summarize the knee honestly.
mst() { jq -r '.max_sustainable_throughput_per_s | round' "$1"; }
knee_p99() { jq -r '.max_sustainable_throughput_per_s as $m | [.steps[] | select(.rate == $m and .stable) | .operations[].latency_ms_p99] | max | round' "$1"; }
knee_res() { # $1 file, $2 role, $3 field-expression over samples
  jq -r --arg role "$2" '.max_sustainable_throughput_per_s as $m
    | [.steps[] | select(.rate == $m and .stable) | .resources.containers[]? | select(.role == $role) | .samples[]'"$3"'] 
    | if length == 0 then "—" else (max | round | tostring) end' "$1"
}
corpus_of() { jq -r '.corpus' "$1"; }

{
  if [ -f "$RS_STRESS" ] && [ -f "$JV_STRESS" ]; then
    cargo run -q -p cnf-runner -- stress-compare \
      --left "$RS_STRESS" --left-label "ehrbase-rs" \
      --right "$JV_STRESS" --right-label "upstream (Java)" \
      --out website/book/src/perf-assets/perf-stress-compare.svg >&2
    cat <<EOF
Both systems run the **same committed step-load stress instrument**
(\`cnf-runner stress\`) on their own freshly seeded **$(corpus_of "$RS_STRESS")**
corpus: the geometric ladder climbs until the system leaves the envelope
(p99 over the budget or errors past tolerance), then bisects to the
**maximum sustainable throughput**. Every number derives from the two
committed \`stress.json\` reports; each load step embeds re-checkable
histograms and, where sampled, per-container resource telemetry.

| | max sustainable throughput | worst p99 at the knee | DB peak CPU at the knee | SUT peak RSS at the knee |
|---|---|---|---|---|
| **ehrbase-rs** | $(mst "$RS_STRESS") req/s | $(knee_p99 "$RS_STRESS") ms | $(knee_res "$RS_STRESS" db ".cpu_pct") % | $(knee_res "$RS_STRESS" sut ".rss_bytes / 1000000") MB |
| **upstream (Java)** | $(mst "$JV_STRESS") req/s | $(knee_p99 "$JV_STRESS") ms | $(knee_res "$JV_STRESS" db ".cpu_pct") % | $(knee_res "$JV_STRESS" sut ".rss_bytes / 1000000") MB |

![Both systems' latency-throughput curves](perf-assets/perf-stress-compare.svg)

A stress report is exploration evidence: it earns no conformance class
(classes are earned exclusively by the hour-long measured class runs) and
carries no class vocabulary — the chart shows where each system breaks.
EOF
  elif [ -f "$RS_STRESS" ]; then
    cat <<EOF
The step-load stress instrument (\`cnf-runner stress\`) has a committed
report for **ehrbase-rs** — the maximum sustainable throughput of
$(mst "$RS_STRESS") req/s on the $(corpus_of "$RS_STRESS") corpus, with the
latency-throughput curve below. **Upstream EHRbase (Java) is not measured**:
the first attempt was refused at workload provisioning (the stored-query
registration rejects a spec-valid qualified name — a conformance finding
recorded on the project tracker); the instrument is never adjusted to
accommodate, and this page publishes both directions the moment upstream
can host the workload — never a one-sided claim.

![The ehrbase-rs latency-throughput curve](perf-assets/perf-stress-curve.svg)
EOF
  else
    cat <<'EOF'
No committed stress report exists yet for either system; the comparison
publishes only measured evidence.
EOF
  fi
} > "$OUT/comparison-bench.md"

echo "render-comparison: wrote $OUT/comparison-{conformance,bench}.md"
