// @generated by openehr-codegen from BMM (`BMM_PROCEDURE_CALL`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `BMM_PROCEDURE_CALL` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::expression::el_procedure_agent::ElProcedureAgent;

/// A call made on a closed procedure agent.
#[doc(alias = "BMM_PROCEDURE_CALL")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmProcedureCall {
    /// The procedure agent being called.
    pub agent: Box<ElProcedureAgent>,
}
