// @generated by openehr-codegen from BMM (`BMM_INSTANTIABLE_FEATURE`) — DO NOT EDIT.

use crate::am24::bmm3::core::feature::bmm_constant::BmmConstant;
use crate::am24::bmm3::core::feature::bmm_singleton::BmmSingleton;

/// Meta-type representing instantiable features, i.e. features that are created as value objects.
/// Closed subtype set of `BMM_INSTANTIABLE_FEATURE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum BmmInstantiableFeature {
    BmmConstant(BmmConstant),
    BmmSingleton(BmmSingleton),
}
