// @generated by openehr-codegen from BMM (`BMM_VARIABLE`) — DO NOT EDIT.

use crate::am24::bmm3::core::feature::bmm_local::BmmLocal;
use crate::am24::bmm3::core::feature::bmm_parameter::BmmParameter;
use crate::am24::bmm3::core::feature::bmm_result::BmmResult;
use crate::am24::bmm3::core::feature::bmm_self::BmmSelf;

/// A routine-scoped formal element.
/// Closed subtype set of `BMM_VARIABLE`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum BmmVariable {
    BmmLocal(BmmLocal),
    BmmParameter(BmmParameter),
    BmmResult(BmmResult),
    BmmSelf(BmmSelf),
}
