// @generated by openehr-codegen from BMM (`BMM_STATIC`) — DO NOT EDIT.

//! The openEHR `BMM_STATIC` spec class, generated from the vendored BMM
//! meta-model.

use crate::am24::bmm3::core::feature::bmm_constant::BmmConstant;
use crate::am24::bmm3::core::feature::bmm_singleton::BmmSingleton;

/// Closed subtype set of `BMM_STATIC`, dispatched on each payload's `_type`.
///
/// Meta-type for static (i.e. read-only) properties.
#[doc(alias = "BMM_STATIC")]
#[derive(Debug, Clone, PartialEq)]
pub enum BmmStatic {
    /// The `BMM_CONSTANT` subtype of `BMM_STATIC`.
    BmmConstant(BmmConstant),
    /// The `BMM_SINGLETON` subtype of `BMM_STATIC`.
    BmmSingleton(BmmSingleton),
}
