// @generated by openehr-codegen from BMM (`ASSERTION_VARIABLE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

//! The openEHR `ASSERTION_VARIABLE` spec class, generated from the vendored BMM
//! meta-model.

/// Definition of a named variable used in an assertion expression.
#[doc(alias = "ASSERTION_VARIABLE")]
#[derive(Debug, Clone, PartialEq)]
pub struct AssertionVariable {
    /// Name of variable.
    pub name: String,
    /// Formal definition of the variable.
    pub definition: String,
}
