// @generated by openehr-codegen from BMM (`ASSERTION`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use crate::am14::aom14::archetype::assertion::assertion_variable::AssertionVariable;
use crate::am14::aom14::archetype::assertion::expr_item::ExprItem;

/// Structural model of a typed first order predicate logic assertion, in the form of an expression tree, including optional variable definitions.
#[derive(Debug, Clone, PartialEq)]
pub struct Assertion {
    /// Expression tag, used for differentiating multiple assertions.
    pub tag: Option<String>,
    /// String form of expression, in case an expression evaluator taking String expressions is used for evaluation.
    pub string_expression: Option<String>,
    /// Root of expression tree.
    pub expression: ExprItem,
    /// Definitions of variables used in the assertion expression.
    pub variables: Vec<AssertionVariable>,
}
