// @generated by openehr-codegen from BMM (`HIER_OBJECT_ID`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `HIER_OBJECT_ID` spec class, generated from the vendored BMM
//! meta-model.

/// Concrete type corresponding to hierarchical identifiers of the form defined by `UID_BASED_ID`.
#[doc(alias = "HIER_OBJECT_ID")]
#[derive(Debug, Clone, PartialEq)]
pub struct HierObjectId {
    // inherited: OBJECT_ID
    /// The value of the id in the form defined below.
    pub(crate) value: String,
}

/// Read access to the `pub(crate)` fields of [`HierObjectId`].
///
/// The fields are not `pub`: the release states a **constraint over this
/// class's own field values** (a lexical form, or a class invariant), so
/// construction checks it and is the only door — docs/specs/openehr/BASE/docs/base_types/master05-identification_package.adoc §Syntaxes: `hier_object_id = uid_based_id`, `uid_based_id = root, [ '::', extension ]`, `root = uid`.
///
/// The validating constructor lives in the hand-written `*_impl.rs` sibling
/// (the generator never writes into it); every generated codec builds this
/// type through that constructor.
impl HierObjectId {
    /// The `value` this instance was constructed with, checked at the door.
    #[must_use]
    pub fn value(&self) -> &str {
        &self.value
    }
}
