// @generated by openehr-codegen from BMM (`INTERNET_ID`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `INTERNET_ID` spec class, generated from the vendored BMM
//! meta-model.

/// Model of a reverse internet domain, as used to uniquely identify an internet domain.
///
/// In the form of a dot-separated string in the reverse order of a domain name, specified by [IETF RFC 1034^](https://www.rfc-editor.org/info/rfc1034).
#[doc(alias = "INTERNET_ID")]
#[derive(Debug, Clone, PartialEq)]
pub struct InternetId {
    // inherited: UID
    /// The value of the id.
    pub(crate) value: String,
}

/// Read access to the `pub(crate)` fields of [`InternetId`].
///
/// The fields are not `pub`: the release states a **constraint over this
/// class's own field values** (a lexical form, or a class invariant), so
/// construction checks it and is the only door — docs/specs/openehr/BASE/docs/base_types/master05-identification_package.adoc §Syntaxes: `internet_id = subdomain`, `subdomain = label | subdomain, '.', label`.
///
/// The validating constructor lives in the hand-written `*_impl.rs` sibling
/// (the generator never writes into it); every generated codec builds this
/// type through that constructor.
impl InternetId {
    /// The `value` this instance was constructed with, checked at the door.
    #[must_use]
    pub fn value(&self) -> &str {
        &self.value
    }
}
