// @generated by openehr-codegen from BMM (`BMM_MODEL_ELEMENT`) — DO NOT EDIT.

//! The openEHR `BMM_MODEL_ELEMENT` spec class, generated from the vendored BMM
//! meta-model.

use crate::am24::bmm3::core::feature::bmm_constant::BmmConstant;
use crate::am24::bmm3::core::feature::bmm_function::BmmFunction;
use crate::am24::bmm3::core::feature::bmm_local::BmmLocal;
use crate::am24::bmm3::core::feature::bmm_parameter::BmmParameter;
use crate::am24::bmm3::core::feature::bmm_procedure::BmmProcedure;
use crate::am24::bmm3::core::feature::bmm_result::BmmResult;
use crate::am24::bmm3::core::feature::bmm_self::BmmSelf;
use crate::am24::bmm3::core::feature::bmm_singleton::BmmSingleton;
use openehr_lang::prelude::BmmClass;
use openehr_lang::prelude::BmmContainerType;
use openehr_lang::prelude::BmmGenericParameter;
use openehr_lang::prelude::BmmGenericType;
use openehr_lang::prelude::BmmOpenType;
use openehr_lang::prelude::BmmPackageContainer;
use openehr_lang::prelude::BmmParameterType;
use openehr_lang::prelude::BmmProperty;
use openehr_lang::prelude::BmmSignature;
use openehr_lang::prelude::BmmSimpleType;
use openehr_lang::prelude::BmmStatusType;
use openehr_lang::prelude::BmmTupleType;
use openehr_lang::prelude::BmmType;

/// Closed subtype set of `BMM_MODEL_ELEMENT`, dispatched on each payload's `_type`.
///
/// Ancestor class of most BMM model elements.
#[doc(alias = "BMM_MODEL_ELEMENT")]
#[derive(Debug, Clone, PartialEq)]
pub enum BmmModelElement {
    /// The `BMM_CLASS` subtype of `BMM_MODEL_ELEMENT`.
    BmmClass(BmmClass),
    /// The `BMM_CONSTANT` subtype of `BMM_MODEL_ELEMENT`.
    BmmConstant(BmmConstant),
    /// The `BMM_CONTAINER_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmContainerType(BmmContainerType),
    /// The `BMM_FUNCTION` subtype of `BMM_MODEL_ELEMENT`.
    BmmFunction(BmmFunction),
    /// The `BMM_GENERIC_PARAMETER` subtype of `BMM_MODEL_ELEMENT`.
    BmmGenericParameter(BmmGenericParameter),
    /// The `BMM_GENERIC_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmGenericType(BmmGenericType),
    /// The `BMM_LOCAL` subtype of `BMM_MODEL_ELEMENT`.
    BmmLocal(BmmLocal),
    /// The `BMM_OPEN_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmOpenType(BmmOpenType),
    /// The `BMM_PACKAGE_CONTAINER` subtype of `BMM_MODEL_ELEMENT`.
    BmmPackageContainer(BmmPackageContainer),
    /// The `BMM_PARAMETER` subtype of `BMM_MODEL_ELEMENT`.
    BmmParameter(BmmParameter),
    /// The `BMM_PARAMETER_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmParameterType(BmmParameterType),
    /// The `BMM_PROCEDURE` subtype of `BMM_MODEL_ELEMENT`.
    BmmProcedure(BmmProcedure),
    /// The `BMM_PROPERTY` subtype of `BMM_MODEL_ELEMENT`.
    BmmProperty(BmmProperty<BmmType>),
    /// The `BMM_RESULT` subtype of `BMM_MODEL_ELEMENT`.
    BmmResult(BmmResult),
    /// The `BMM_SELF` subtype of `BMM_MODEL_ELEMENT`.
    BmmSelf(BmmSelf),
    /// The `BMM_SIGNATURE` subtype of `BMM_MODEL_ELEMENT`.
    BmmSignature(BmmSignature),
    /// The `BMM_SIMPLE_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmSimpleType(BmmSimpleType),
    /// The `BMM_SINGLETON` subtype of `BMM_MODEL_ELEMENT`.
    BmmSingleton(BmmSingleton),
    /// The `BMM_STATUS_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmStatusType(BmmStatusType),
    /// The `BMM_TUPLE_TYPE` subtype of `BMM_MODEL_ELEMENT`.
    BmmTupleType(BmmTupleType),
}
