// @generated by openehr-codegen from BMM (`ARCHETYPE_TERM`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR `ARCHETYPE_TERM` spec class, generated from the vendored BMM
//! meta-model.

/// Representation of any coded entity (term or constraint) in the archetype ontology.
#[doc(alias = "ARCHETYPE_TERM")]
#[derive(Debug, Clone, PartialEq)]
pub struct ArchetypeTerm {
    /// Code of this term.
    pub code: String,
    /// Short term text, typically for display.
    pub text: String,
    /// Full description text.
    pub description: String,
    /// Hash of keys and corresponding values for other items in a term, e.g. provenance.
    pub other_items: Option<std::collections::BTreeMap<String, String>>,
}
