// @generated by openehr-codegen from BMM (`DV_ENCAPSULATED`) — DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::data_types::encapsulated::dv_multimedia::DvMultimedia;
use crate::data_types::encapsulated::dv_parsable::DvParsable;

/// Abstract class defining the common meta-data of all types of encapsulated data.
/// Closed subtype set of `DV_ENCAPSULATED` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DvEncapsulated {
    DvMultimedia(DvMultimedia),
    DvParsable(DvParsable),
}
