// @generated by openehr-codegen — DO NOT EDIT.

//! The openEHR spec package `data_types/encapsulated` — generated module tree.

pub mod dv_encapsulated;
pub mod dv_multimedia;
pub mod dv_parsable;

// hand-written modules (spec behaviour), auto-declared:
pub mod dv_multimedia_impl;
pub mod dv_parsable_impl;
