// @generated by openehr-codegen from BMM (`BMM_STRING_VALUE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `BMM_STRING_VALUE` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_0::bmm::core::entity::bmm_simple_type::BmmSimpleType;

/// Meta-type for a literal String value, for which `_type_` is fixed to the `BMM_TYPE` representing `String` and `_value_` is of type `String`.
#[doc(alias = "BMM_STRING_VALUE")]
#[derive(Debug, Clone, PartialEq)]
pub struct BmmStringValue {
    // inherited: BMM_PRIMITIVE_VALUE
    /// Declared or inferred static type of the entity.
    pub r#type: BmmSimpleType,

    // inherited: BMM_LITERAL_VALUE
    /// A serial representation of the value.
    pub value_literal: String,
    /// Native String value.
    pub value: String,

    // inherited: BMM_LITERAL_VALUE
    /// Optional specification of formalism of the `_value_literal_` attribute for complex values.
    ///
    /// Value may be any of `json | yawl | xml | odin | rdf` or another value agreed by the user community. If not set, `json` is assumed.
    pub syntax: Option<String>,
}
