// @generated by openehr-codegen from BMM (`BMM_PROCEDURE_CALL`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs` (ADR-004).

use openehr_derive::OpenEhrType;
use crate::bmm3::expression::el_procedure_agent::ElProcedureAgent;

/// A call made on a closed procedure agent. The method in BMM via which external actions are achieved from within a program.
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "BMM_PROCEDURE_CALL")]
pub struct BmmProcedureCall {
    /// The procedure agent being called.
    pub agent: ElProcedureAgent,
}
