// @generated by openehr-codegen from BMM (`DV_QUANTIFIED`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `DV_QUANTIFIED` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::data_types::quantity::date_time::dv_date::DvDate;
use crate::v1_1::data_types::quantity::date_time::dv_date_time::DvDateTime;
use crate::v1_1::data_types::quantity::date_time::dv_duration::DvDuration;
use crate::v1_1::data_types::quantity::date_time::dv_time::DvTime;
use crate::v1_1::data_types::quantity::dv_count::DvCount;
use crate::v1_1::data_types::quantity::dv_proportion::DvProportion;
use crate::v1_1::data_types::quantity::dv_quantity::DvQuantity;

/// Closed subtype set of `DV_QUANTIFIED`, dispatched on each payload's `_type`.
///
/// Abstract class defining the concept of true quantified values, i.e. values which are not only ordered, but which have a precise magnitude.
#[doc(alias = "DV_QUANTIFIED")]
#[derive(Debug, Clone, PartialEq)]
pub enum DvQuantified {
    /// The `DV_COUNT` subtype of `DV_QUANTIFIED`.
    DvCount(DvCount),
    /// The `DV_DATE` subtype of `DV_QUANTIFIED`.
    DvDate(DvDate),
    /// The `DV_DATE_TIME` subtype of `DV_QUANTIFIED`.
    DvDateTime(DvDateTime),
    /// The `DV_DURATION` subtype of `DV_QUANTIFIED`.
    DvDuration(DvDuration),
    /// The `DV_PROPORTION` subtype of `DV_QUANTIFIED`.
    DvProportion(DvProportion),
    /// The `DV_QUANTITY` subtype of `DV_QUANTIFIED`.
    DvQuantity(DvQuantity),
    /// The `DV_TIME` subtype of `DV_QUANTIFIED`.
    DvTime(DvTime),
}
