apiVersion: v1
kind: Service
metadata:
  name: {{ include "ehrbase-rs.fullname" . }}
  labels:
    {{- include "ehrbase-rs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if and .Values.management.enabled .Values.management.port }}
    - name: management
      port: {{ .Values.management.port }}
      targetPort: management
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ehrbase-rs.selectorLabels" . | nindent 4 }}
