// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: BUSL-1.1 AND Apache-2.0

//! The openEHR spec package `v2_4/bmm3/core/literal_value` — generated module tree.

pub mod bmm_boolean_value;
pub mod bmm_integer_value;
pub mod bmm_literal_value;
pub mod bmm_primitive_value;
pub mod bmm_string_value;
pub mod bmm_unitary_value;
