// @generated by openehr-codegen from BMM (`VIEW_ENTRY`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `VIEW_ENTRY` spec class, generated from the vendored BMM
//! meta-model.

use crate::v1_1::common::archetyped::locatable::Locatable;
use crate::v1_1::composition::view::citation::Citation;

/// Closed subtype set of `VIEW_ENTRY`, dispatched on each payload's `_type`.
#[doc(alias = "VIEW_ENTRY")]
#[derive(Debug, Clone, PartialEq)]
pub enum ViewEntry {
    /// The `CITATION` subtype of `VIEW_ENTRY`.
    Citation(Citation<Locatable>),
}
