// @generated by openehr-codegen from BMM (`CODE_PHRASE`) — DO NOT EDIT.
// Hand-written spec functions/invariants live in the sibling `*_impl.rs`.

use openehr_base::prelude::TerminologyId;
use openehr_derive::OpenEhrType;

/// A fully coordinated (i.e. all coordination has been performed) term from a terminology service (as distinct from a particular terminology).
#[derive(Debug, Clone, PartialEq, OpenEhrType)]
#[openehr(type_name = "CODE_PHRASE")]
pub struct CodePhrase {
    /// Identifier of the distinct terminology from which the code_string (or its elements) was extracted.
    pub terminology_id: TerminologyId,
    /// The key used by the terminology service to identify a concept or coordination of concepts. This string is most likely parsable inside the terminology service, but nothing can be assumed about its syntax outside that context.
    pub code_string: String,
    /// Optional attribute to carry preferred term corresponding to the code or expression in `_code_string_`. Typical use in integration situations which create mappings, and representing data for which both a (non-preferred) actual term and a preferred term are both required.
    pub preferred_term: Option<String>,
}
