[package]
name = "openehr-flat"
version = "0.1.0"
description = "FLAT / STRUCTURED / Web Template formats (Better semantics, EHRbase quirks)"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
openehr-rm = { path = "../openehr-rm" }
openehr-serde = { path = "../openehr-serde" }
openehr-adl = { path = "../openehr-adl" }

[features]
ehrbase-quirks = []

[lints]
workspace = true
