// @generated by openehr-codegen from BMM (`TYPE_DEF_DATE_TIME`) — DO NOT EDIT.
// SPDX-FileCopyrightText: Ruben Talstra
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR `TYPE_DEF_DATE_TIME` spec class, generated from the vendored BMM
//! meta-model.

use openehr_base::v1_3::foundation_types::time::iso8601_date_time::Iso8601DateTime;

/// Rules meta-type representing the primitive type Date_time.
#[doc(alias = "TYPE_DEF_DATE_TIME")]
#[derive(Debug, Clone, PartialEq)]
pub struct TypeDefDateTime {
    /// The `type_name` attribute of openEHR `TYPE_DEF_DATE_TIME` (the vendored BMM carries no documentation for it).
    pub type_name: String,
    /// The `type_anchor` attribute of openEHR `TYPE_DEF_DATE_TIME` (the vendored BMM carries no documentation for it).
    pub type_anchor: Iso8601DateTime,
}
