// @generated by openehr-codegen from BMM (`EXTRACT_CONTENT_ITEM`) — DO NOT EDIT.

use crate::ehr_extract::generic_extract::generic_content_item::GenericContentItem;
use crate::ehr_extract::openehr_extract::openehr_content_item::OpenehrContentItem;

/// Abstract model of a wrapper for one content item in an Extract, containing various meta-data. Indicates whether it was part of the primary set and what its original path was. Intended to be subtyped for wrappers of specific types of content.
/// Closed subtype set of `EXTRACT_CONTENT_ITEM`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq)]
pub enum ExtractContentItem {
    GenericContentItem(GenericContentItem),
    OpenehrContentItem(OpenehrContentItem),
}
