// @generated by openehr-codegen from BMM (`EXTRACT_ITEM`) — DO NOT EDIT.

use crate::ehr_extract::common::extract_folder::ExtractFolder;
use crate::ehr_extract::generic_extract::generic_content_item::GenericContentItem;
use crate::ehr_extract::openehr_extract::openehr_content_item::OpenehrContentItem;
use serde::Serialize;

/// Abstract parent of Extract Folder and Content types.
/// Closed subtype set of `EXTRACT_ITEM`: a closed subtype set dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ExtractItem {
    ExtractFolder(ExtractFolder),
    GenericContentItem(GenericContentItem),
    OpenehrContentItem(OpenehrContentItem),
}

impl<'de> ::serde::Deserialize<'de> for ExtractItem {
    #[allow(clippy::too_many_lines, clippy::match_same_arms)]
    fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        let __value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        match __value.get("_type").and_then(::serde_json::Value::as_str) {
            ::core::option::Option::Some("EXTRACT_FOLDER") => {
                ::core::result::Result::Ok(Self::ExtractFolder(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("GENERIC_CONTENT_ITEM") => {
                ::core::result::Result::Ok(Self::GenericContentItem(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::Some("OPENEHR_CONTENT_ITEM") => {
                ::core::result::Result::Ok(Self::OpenehrContentItem(
                    ::serde_json::from_value(__value).map_err(::serde::de::Error::custom)?,
                ))
            }
            ::core::option::Option::None => {
                ::core::result::Result::Err(::serde::de::Error::custom(
                    "EXTRACT_ITEM: missing required `_type` on polymorphic slot (expected one of: EXTRACT_FOLDER, GENERIC_CONTENT_ITEM, OPENEHR_CONTENT_ITEM)",
                ))
            }
            ::core::option::Option::Some(__other) => {
                ::core::result::Result::Err(::serde::de::Error::custom(::std::format!(
                    "EXTRACT_ITEM: unexpected `_type` {__other:?} (expected one of: EXTRACT_FOLDER, GENERIC_CONTENT_ITEM, OPENEHR_CONTENT_ITEM)"
                )))
            }
        }
    }
}
