// @generated by openehr-codegen from BMM (`ITEM`) — DO NOT EDIT.

use crate::data_structures::representation::cluster::Cluster;
use crate::data_structures::representation::element::Element;
use serde::{Deserialize, Serialize};

/// The abstract parent of `CLUSTER` and `ELEMENT` representation classes.
/// Closed subtype set of `ITEM` (ADR-004): dispatched on each payload's `_type`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Item {
    Cluster(Cluster),
    Element(Element),
}
