// @generated by openehr-codegen from BMM (`TERMINOLOGY_SERVICE`) — DO NOT EDIT.
// SPDX-FileCopyrightText: FerroEHR contributors
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: MIT AND Apache-2.0

//! The openEHR `TERMINOLOGY_SERVICE` spec class, generated from the vendored BMM
//! meta-model.

/// Defines an object providing proxy access to a terminology service.
#[doc(alias = "TERMINOLOGY_SERVICE")]
#[derive(Debug, Clone, PartialEq)]
pub struct TerminologyService {}
