apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferroehr.fullname" . }}
  labels:
    {{- include "ferroehr.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if and .Values.config.management.enabled .Values.config.management.port }}
    - name: management
      port: {{ .Values.config.management.port }}
      targetPort: management
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ferroehr.selectorLabels" . | nindent 4 }}
